### ISSUE TITLE
How to properly use tink with a non-tink crypto-library?

### ISSUE THREAD

**Issue by Vrakfall** [google/tink#102]
I read a big part of the doc (and a bit of the code) and still struggle to understand if Tink can help me for what I need. I mainly would like to use tink to retrieve key from a `KMS` (mainly `RSA` ones) and then use it with an `SSH` library to connect to a server by `SSH`.

From what I understood from my readings, I assume it's not possible "get" the private key itself as Tink doesn't expose it for security reasons. Am I wrong?

I also read about the possibility to implement primitives but I still don't understand if it can fit my use case. I currently use [SSHJ](https://github.com/hierynomus/sshj) to connect a client application to a server but it could be any other `SSH` lib in the future or for some algorithms that this one doesn't support. On that connection, I need to run commands and get their output in a non-blocking way (SSHJ does it with `InputStream`s).

Is there a proper way to use Tink to get the private key required to connect to a specific `SSH` server from a `KMS` and use it with a non-Tink crypto-library like `SSHJ` and what is it then? `SSHJ` takes the keys as `String` or their location as `String` as input to initiate the connection. It also requires the `known_hosts` as a Java `File`. Could a primitive implementation help me to join both libraries? I feel like it's for a completely different purpose but I prefer to ask in order to be sure if Tink can help in my use case or not.

Thank you really much in advance!

**Comment by thaidn** [comment]
Hi Vrakfall, I'm sorry for the late response. Unfortunately, at the moment Tink cannot really help your use case.

If you only want to decrypt something using Cloud KMS/AWS KMS, you should directly call the KMS client libraries.

**Comment by thaidn** [comment]
Please reopen if you have any further questions.
