### ISSUE TITLE
Rust Implementation?

### ISSUE THREAD

**Issue by ordian** [google/tink#108]
Can be implemented as a wrapper for `openssl` and `soduim` or by porting [ring](https://github.com/briansmith/ring), which is based on boringssl.

**Comment by tomtau** [comment]
Another option is to port [mundane](http://github.com/google/mundane) (also based on boringssl)

**Comment by tomtau** [comment]
BTW, there's a bounty on this issue: https://www.bountysource.com/issues/62883990-rust-implementation

**Comment by denim2x** [comment]
[Here](https://github.com/denim2x/tink/tree/rust/rust) is my preliminary implementation; progress follows the inheritance hierarchy in the Java codebase (from the interfaces towards the final subclasses)

**Comment by tomtau** [comment]
@denim2x you can open a pull request prefixed with "WIP: " if you'd like to receive some early feedback.
The contribution guidelines are quite brief: https://github.com/google/tink/blob/master/docs/CONTRIBUTING.md

I assume one should be able to build the Rust implementation with Bazel (to be consistent with other languages in the repo). This plugin may be helpful: https://github.com/google/cargo-raze

**Comment by meteorsnows** [comment]
Hopefully Mozilla interested enough.

**Comment by empijei** [comment]
Hello, may I ask what is the progress on this one?

**Comment by KoStard** [comment]
Any updates on this?

**Comment by daviddrysdale** [comment]
There's now a Rust port at https://github.com/project-oak/tink-rust ([docs](https://project-oak.github.io/tink-rust)).  It's currently based on the [RustCrypto crates](https://github.com/RustCrypto) and is still under construction, but there's a reasonable fraction of the Tink functionality implemented.

**Comment by tholenst** [comment]
I will close this issue since rust will not be available in this repo. For updates follow the repository which David linked above.
