### ISSUE TITLE
.NET Standard 2.0

### ISSUE THREAD

**Issue by elucidsoft** [google/tink#109]
Any plans to support .NET Standard 2.0? I will take this on and submit a PR for it.

**Comment by thaidn** [comment]
We tried to support .NET, but ran into a bunch of issues with Bazel. We also don't have anyone knowing .NET on the team.

Like PHP, I think it's best to create a separate repo, and we can help you review your design and implementation.

Please let us know if this works for you.

**Comment by elucidsoft** [comment]
This is being implemented at https://github.com/elucidsoftllc/tink.net

**Comment by thaidn** [comment]
Thanks @elucidsoft. Please reopen if you have any questions or need help from us.

**Comment by mtausig** [comment]
That repo is not available anymore. What happened @elucidsoft ?

**Comment by elucidsoft** [comment]
> That repo is not available anymore. What happened @elucidsoft ?

Life happened really. I just don't have the time.

**Comment by mtausig** [comment]
But why did you delete the repo instead of setting it to archived? Maybe somebody else wants to pick it up.
