### ISSUE TITLE
why mac not support streaming?

### ISSUE THREAD

**Issue by suarezu** [google/tink#111]
How to do if a mac of a file desired?

**Comment by thaidn** [comment]
Yes, this is something we plan to add.

@bleichen

**Comment by suarezu** [comment]
Great to hear that, now I am using mac of java for update/doFinal

**Comment by przydatek** [comment]
We're working on it (cf. [interface](https://github.com/google/tink/blob/master/cc/streaming_mac.h)), so stay tuned :-)
