### ISSUE TITLE
Please support exposing API to do public key encryption (and private key decryption)!

### ISSUE THREAD

**Issue by evalsinca** [google/tink#122]
Hybrid encryption beautifully encapsulates the common use case - encrypting text with a symmetric key K, and then encrypting K with the user public key.   For our use case, this does not work.  

In particular,  in our use case, our system generates N strings S1, S2, .., Sn.  We want to encrypt each of these N strings with N public keys B1,..., Bn to produce ciphers C1,.., Cn.   In addition, our plain text T is then encrypted with a password formed from catenating S1, S2, .., Sn.   The resulting cipher text C along with the ciphers C1 through Cn are sent to the user who then  decrypts the N ciphers using their corresponding private keys to generate the S1,.., Sn, which they then catenate to decrypt the cipher text C yielding T.  

So we want to access the public key encryption, and private key decryption APIs directly if possible.

**Comment by thaidn** [comment]
Would you mind sharing a bit more about your protocol and what you want to achieve with it?

We work with many product teams at Google and usually we want to understand why they think they need crypto before telling them which crypto primitives they should use.

**Comment by evalsinca** [comment]
@thaidn  - can i drop you a direct message with details?  

(Short-term, we have a work-around using Hybrid Encryption as-is.  :-))

**Comment by thaidn** [comment]
Yes, please email me at thaidn@gmail.com. Thanks!

**Comment by thaidn** [comment]
Please reopen if you need additional help.
