### ISSUE TITLE
Sources are missing for com.google.crypto.tink.subtle package in Maven source jar

### ISSUE THREAD

**Issue by andrewl102** [google/tink#123]
I assume this isn't intentional, as the sources for the rest of the packages appear to be published properly (except aead) but this package is missing.
Given the source is freely accessible in Github, I assume this is a bug?

**Comment by thaidn** [comment]
Yes, it looks like a bug.

@chuckx Charles, wonder if you want to take a look? Good chance to learn how we're generating the Maven jars.

**Comment by chuckx** [comment]
Yup, I'll dig into this one.

**Comment by chuckx** [comment]
FYI, I'll be performing a release within the next couple days to update the published Maven packages.

**Comment by thaidn** [comment]
This is fixed in https://github.com/google/tink/releases/tag/v1.2.1.

I've verified that https://repo1.maven.org/maven2/com/google/crypto/tink/tink/1.2.1/tink-1.2.1-sources.jar contains com.google.crypto.tink.subtle package.

Please reopen if this still doesn't work. Thanks!
