### ISSUE TITLE
Need more detailed documentation for Android

### ISSUE THREAD

**Issue by Fi5t** [google/tink#125]
This library looks like very interesting to use in Android apps, but android part of its documentation is very poor.

Thank you!

**Comment by thaidn** [comment]
Hi there,

The Android library is almost the same as the Java one. We add AndroidKeysetManager [1] and a couple of supporting classes [2] but that's about it.

Could you please tell us what you want to do and why you can't find useful documentation in the Java HOWTO [3]?

[1] http://google.github.io/tink/javadoc/tink-android/1.1.0/com/google/crypto/tink/integration/android/AndroidKeysetManager.html
[2] http://google.github.io/tink/javadoc/tink-android/1.1.0/com/google/crypto/tink/integration/android/package-summary.html
[3] https://github.com/google/tink/blob/master/docs/JAVA-HOWTO.md

**Comment by Fi5t** [comment]
@thaidn oh, my bad... It seems I didn't understand some nuances of this library for android at the first time. Your links gave me the complete understanding. I thought that I could use remote KMS in android too, but no =)

Thank you for the explanation.

**Comment by thaidn** [comment]
No problem.

> I thought that I could use remote KMS in android too, but no =)

Android doesn't support remote KMS like Cloud KMS or AWS KMS because one needs credentials to access these services, but I don't think it's a good idea to store credentials on mobile apps.
