### ISSUE TITLE
Add support for an encrypting InputStream/ReadableChannel

### ISSUE THREAD

**Issue by jeantil** [google/tink#128]
Currently, encrypting is only supported for "output" and decrypting for "input" channels/streams. The notion of which direction is "input" and which is "output" depends on your point of view. 

In my use case I need to add encryption around the jclouds blobstore api which exposes inputstreams for both reading and writing the content of a blob. This kind of makes sense as it allows the user to provide a source of bytes to be written. The blobs are received unencrypted but we don't want to store them in clear on a third party hosting service. 

Currently using tink I am forced to read the whole InputStream to get the bytes, encrypt them then recreate a new InputStream of the ciphertext to send to the wrapped API. This is very inefficient for larger messages. I seems like is should be possible to have an InputStream which wraps an existing InputStream but encrypts the content of the underlying stream on the fly as the calls to read() are made.

This would behave in the same way as `javax.crypto.CipherInputStream` using except tinks `StreamingAead` implementations instead of a raw cipher allowing it to handle encryption + authentication in a transparent fashion. 

Disclaimer: I am a cryptography novice, I may have missed something which makes this idea impossible to implement.

**Comment by thaidn** [comment]
@bleichen 

I'm not sure I understand the question. Jean, how do you write to an InputStream [1] which doesn't have any write() method?

> Currently using tink I am forced to read the whole InputStream to get the bytes, encrypt them then recreate a new InputStream of the ciphertext to send to the wrapped API. This is very inefficient for larger messages. I seems like is should be possible to have an InputStream which wraps an existing InputStream but encrypts the content of the underlying stream on the fly as the calls to read() are made.

What you want to do is to initialize a StreamingAead with an OutputStream that connects to the destination that you want to write to. Then you loop reading a buffer from the Blobstore InputStream and writing it to the StreamingAead object, until the InputStream is closed.

Why doesn't this work?

[1] https://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html

**Comment by jeantil** [comment]
>I'm not sure I understand the question. Jean, how do you write to an InputStream [1] which doesn't have any write() method?

I want to encrpyt the bytes which are returned by the read method of *another* InputStream, in the exact same fashion as [javax.crypto.CipherInputStream](https://docs.oracle.com/javase/7/docs/api/javax/crypto/CipherInputStream.html) except using StreamingAead. 

the constructor would look something like
```
public StreamingAeadEncryptingInputStream(AesGcmHkdfStreaming streamAead,
                                     InputStream clearTextStream, 
                                     byte[] associatedData){...}
```

The read method would work on the following principle : 
- blockingly read getPlaintextSegmentSize bytes from clearTextStream (or set endOfPlainText)
- encrypt the plainTextSegment 
- handle the read from the caller by setting the destination byte array's bytes from the encryptedSegment

>What you want to do is to initialize a StreamingAead with an OutputStream that connects to the destination that you want to write to. Then you loop reading a buffer from the Blobstore InputStream and writing it to the StreamingAead object, until the InputStream is closed.

This does work, however the documentation for [PipedStreams](https://docs.oracle.com/javase/7/docs/api/java/io/PipedInputStream.html) states that:
>Attempting to use both objects from a single thread is not recommended, as it may deadlock the thread

Since I can't be sure what the consuming thread will be, I have to start a thread for each payload I want to encrypt, or I have to start managing a threadpool which rapidly increases the complexity of the task. 
The proposed `StreamingAeadEncryptingInputStream` would not have this issue and would preserve the InputStreams _"pull"_ model.

**Comment by thaidn** [comment]
Hi Jean,

Could you please explain why PipedStreams is relevant here? Would you mind writing some code (pseudo is fine) that follows my proposal and tells me why it doesn't work for you? Thanks!

**Comment by jeantil** [comment]
Here is what my current implementation looks like
```
    public Payload write(InputStream is) {
        PipedInputStream snk = new PipedInputStream();
        try {
            PipedOutputStream src = new PipedOutputStream(snk);
            OutputStream outputStream = streamingAead.newEncryptingStream(src, PBKDF2StreamingAeadFactory.EMPTY_ASSOCIATED_DATA);
            Thread copyThread = new Thread(() -> {
                try (PipedOutputStream stream = src) {
                    IOUtils.copy(is, stream);
                } catch (IOException e) {
                    throw new RuntimeException("Stream copy failure ", e);
                }
            });
            copyThread.setUncaughtExceptionHandler((Thread t, Throwable e) -> {
                throw new RuntimeException(e);
            });
            copyThread.start();
            return Payloads.newInputStreamPayload(snk);
        } catch (IOException | GeneralSecurityException e) {
            throw new RuntimeException("Unable to build payload for object storage, failed to " +
                "encrypt", e);
        }
    }
```

**Comment by jeantil** [comment]
Hello @thaidn, I was wondering if you would share your current thoughts on this.

**Comment by thaidn** [comment]
@przydatek @bleichen hey folks, could you please take a look?

**Comment by thaidn** [comment]
Jean, I understand your problem now. Basically you want an API that wraps an input stream and gives you another input stream, like FilteredInputStream. When you read from the resulting input stream, data from the original input stream is read and encrypted.

This sounds reasonable to me, but let's see what my teammates would say.

**Comment by jeantil** [comment]
>Basically you want an API that wraps an input stream and gives you another input stream, like FilteredInputStream.When you read from the resulting input stream, data from the original input stream is read and encrypted.
@thaidn thanks : this is indeed exactly what I want :) sorry if my explanation was unclear, english is not my native language :/

**Comment by przydatek** [comment]
Hi Jean, we discussed the options for providing the functionality you need, and came to conclusion that adding new method(s) to StreamingAead-primitive might be not the best thing to do in the long run.
We'd like to keep the main interfaces/primitives rather small, so that they are manageable and easy to understand.  Given that the problem you describe, i.e. inverting the direction of a stream, has a relatively standard solution (using pipes, something like the code you've posted above), it seems that the reasons to extend the primitive are not very strong. Moreover, the inversion of the stream can be implemented in a generic helper, something like here:

``` java
 /**
   * Returns an InputStream that provides ciphertext resulting from encryption
   * of 'plaintextStream' with 'associatedData' via 'streamingAead'.
   *
   * NOTE: this method is for demonstration only, and should be adjusted
   *       to specific needs. In particular, the handling of potential
   *       exceptions via a RuntimeException might be not suitable.
   */
  public static InputStream getCiphertextStream(final StreamingAead streamingAead,
      final InputStream plaintextStream, final byte[] associatedData)
      throws IOException {

    PipedInputStream ciphertextStream = new PipedInputStream();
    final PipedOutputStream outputStream = new PipedOutputStream(ciphertextStream);
    new Thread(new Runnable() {
        @Override
        public void run(){
          try (OutputStream encryptingStream =
              streamingAead.newEncryptingStream(outputStream, associatedData)) {
            byte[] buffer = new byte[1024];
            int length;
            while ((length = plaintextStream.read(buffer)) != -1) {
              encryptingStream.write(buffer, 0, length);
            }
            plaintextStream.close();
          } catch (GeneralSecurityException | IOException e) {
            throw new RuntimeException("Stream encryption failure.", e);
          }
        }
      }
      ).start();
    return ciphertextStream;
  }
```
Would such a helper be sufficient for your use case?  Or maybe there are some stronger reasons that would justify addition of new methods to StreamingAead?

**Comment by jeantil** [comment]
hi @przydatek, 
Last week was very busy,  I didn't find the time to write a proper answer. 

All pipe approaches in Java are a misfit for this use case and should only be used for I/O not for in memory CPU bound operations : 
- The `PipedInputStream/PipedOutputStream` which I demonstrated in my earlier message and you extracted to a generic helper in your latest comment creates one new thread for each stream. As you probably know, threads are horribly expensive on the JVM not to mention context switching. You could possibly limit the impact by using some kind of executor or thread pool but that's still a heavyweight for something that can easily be avoided by providing a `FilterInputStream`-based implementation.
- The NIO channels do offer a pipe facility too, unfortunately it is system dependant (on unix it actually creates a unix pipe, consuming a file descriptor in the process) again this is 

I understand that you don't want to extend the `StreamingAead` primitive because it is currently designed around the assumption that `encrypting` is for `OutputStream` and `decrypting` is for `InputStream`. Thus it is hard to provide a consistent name for the `EncryptingInputStream`. 
I don't really care for the helper method on the API as long as I can find an implementation alongside its promoted siblings. 

May I suggest that without changing the name of the methods on `StreaminAead` you start by renaming the actual implementations ? 
* `StreamingAeadDecryptingStream`-> `StreamingAeadDecryptingInputStream`
* `StreamingAeadEncryptingStream`-> `StreamingAeadEncryptingOutputStream`

Thus you can provide a `StreamingAeadEncryptingInputStream` (and possibly a StreamingAeadDecryptingOutputStream for the sake of completeness though I don't have a use case for this).

It could even be in a contrib library somewhere if you don't want it in the main library as long as it is discoverable enough. The reason I ask is that I tried to implement it myself and failed, getting this to work requires specialized knowledge on how the byte stream is structured and I wasn't able to figure it out or find proper reference documentation. I can't seem to be able to figure out the proper sizes of the various frames :(
I don't know if the encrypting/decrypting can be abstracted from the stream type if so that would be even better.

**Comment by dbcloudbin-dev** [comment]
We have the same scenario described by @jeantil and it is in fact preventing us from using Tink.
We would like this scenario to be reconsidered into the library interface to make it more flexible and versatile.

**Comment by freygriff** [comment]
16c999e8c71134401a78d4d46435517b2271d6ac
mojombo@16c999e8c71134401a78d4d46435517b2271d6ac
mojombo/github-flavored-markdown@16c999e8c71134401a78d4d46435517b2271d6ac

**Comment by siepkes** [comment]
For of all thanks for this great library! 

I've also bumped into this. I think most people who want to use Tink for Crypto for cloud object storage (ie. S3-style storage) run in to the issue that they need to supply and `InputStream` for encrypting. For the simple reason that in order to upload something with Apache HTTP client, OKHttp, etc. you need to supply an `InputStream`.

In case of the object store use-case spinning up and tearing down a thread per upload for the `PipedInputStream` feels kinda dirty for the reasons @jeantil outlines. I guess one could use something like a `ExecutorService` but all in all technically speaking all that extra complexity and overhead isn't needed.

**Comment by siepkes** [comment]
@przydatek Maybe I'm missing something but are you sure the `PipedInputStream` example works properly? The Javadoc for `PipedInputStream`'s says (emphasis mine):

>  Typically, data is read from a PipedInputStream object by one thread and data is written to the corresponding PipedOutputStream by some other thread. **Attempting to use both objects from a single thread is not recommended, as it may deadlock the thread**.

**Comment by jeantil** [comment]
> EDIT: Forget what I said. I was missing something.
hello @siepkes I am still missing it, can you enlighten me (so I can contribute a proper streaming implementation back to the apache james project ... )

**Comment by siepkes** [comment]
@jeantil Unfortunately the "EDIT" remark doesn't apply to the message above it. I don't have a fix for the problem. It's about the message which was in that comment before I removed it by replacing it with "EDIT". You can still view the older message if you press the "edited" button. Apparently I (erroneously) thought there was an error in the example but it turns out there wasn't. Hence the removal of the message.

Sorry to get your hopes up ;-).

**Comment by jeantil** [comment]
@siepkes that's too bad :D I had forgotten about this issue because AES encryption for the blobstore had been dropped from the project during a massive refactoring it is being reintroduced and for now it ended up using non-streaming encryption (reading the whole blob to memory) which is kind of sad. I will try and suggest implementing a FilteredInputStream based implementation as an exercise at the coding dojo... maybe with more brains and a fresh attempt we can make it work !
