### ISSUE TITLE
tink missing in wikipedia crypto library comparison

### ISSUE THREAD

**Issue by froh** [google/tink#133]
if someone knowledgeable of tink could add tink information to the tables on that wikipedia page :-) ?

https://en.wikipedia.org/wiki/Comparison_of_cryptography_libraries

**Comment by thaidn** [comment]
Thanks.

@przydatek Do you think we should write something?

**Comment by alizadehh** [comment]
tanks

**Comment by tholenst** [comment]
According to https://en.wikipedia.org/wiki/Wikipedia:An_article_about_yourself_isn%27t_necessarily_a_good_thing this is probably not the task of the Tink maintainers.

**Comment by froh** [comment]
the kind nudge was about adding _verifiable information_ about a _technology_, by someone who knows enough about tink to add that to said Wikipedia page.

that's different from advertisement and different from self aggrandizing blunder, which is the intent of the linked Wikipedia policy.

anyhow nobody has found the time, so I get that you close the suggestion.  just please close it for the right reason (ain't nobody got time for dat) not for a policy which wouldn't apply.
