### ISSUE TITLE
No instructions for building Java JARs from the source?

### ISSUE THREAD

**Issue by mouse07410** [google/tink#136]
You told how to get from Maven JARs that *you* built.

How do I build those JARs from the source?

**Comment by thaidn** [comment]
Hi there,

There's some instruction here: https://github.com/google/tink/blob/master/docs/JAVA-HACKING.md.

**Comment by thaidn** [comment]
You probably need the latest Bazel.

**Comment by mouse07410** [comment]
I got the latest *stable* Bazel.

**Comment by thaidn** [comment]
Does it work?

**Comment by mouse07410** [comment]
Haven't tried yet. Also, the .md title suggests that it's not a straightforward/clean process? So far I've had enough trouble with what's supposed to be a "normal" (aka "non-hacking") build for C++. I'm not really itching to dive into hacking Java code under Bazel.

**Comment by thaidn** [comment]
@mouse07410 I just tested and confirm that compiling should work with latest Bazel (0.17.2).

The process is pretty straight-forward. Please reopen if you have any further questions or issues.

Cheers :)
