### ISSUE TITLE
Method to extract shareable Public Key?

### ISSUE THREAD

**Issue by xtrycatchx** [google/tink#137]
My question might be a bit stupid or silly, my apologies in advance,  but is there a way to extract the Public Key in java and obj-c? Thanks.

**Comment by xtrycatchx** [comment]
Ah found a utility for it with Java
```java
CleartextKeysetHandle.write(
    publicKeysetHandle, 
    JsonKeysetWriter.withFile(new File("publickey.json"))
);
```

**Comment by xtrycatchx** [comment]
so far only via writing the keys and loading it back, for example in objective-c:

```obj-c
TINKJSONKeysetReader *reader = 
   [[TINKJSONKeysetReader alloc] initWithSerializedKeyset:binaryKeyset  
                                                    error:&readerError];
```

closing this for now.

**Comment by CocoaJiang** [comment]
How is your TINKJSONKeysetReader initialized
Whether it is
NSData *data = [NSData dataWithContentsOfFile:"path"];
TINKJSONKeysetReader *reader = [[TINKJSONKeysetReader alloc]initWithSerializedKeyset:data error:&error]; `
