### ISSUE TITLE
secp256k1 and RFC 6979 support

### ISSUE THREAD

**Issue by reaperhulk** [google/tink#146]
Is there any interest in potentially adding `secp256k1` and RFC 6979 deterministic `k` support in the ECDSA signer? `secp256k1` is widely used in the cryptocurrency space and projects like that could use a library like tink to help them choose sane cryptographic defaults outside of the elliptic curve constraints placed upon them by ethereum, bitcoin, et cetera.

**Comment by thaidn** [comment]
Hi Paul, we don't have any for this curve at the moment, but if you can contribute, we can advise and review your implementation.

**Comment by arnabmitra** [comment]
+1 please support secp256k1

**Comment by tholenst** [comment]
We currently don't have any plans to provide secp256k1.
