### ISSUE TITLE
AWS KMS does not load region

### ISSUE THREAD

**Issue by simplesteph** [google/tink#147]
This is because it's using a deprecated constructor for the KMS client, which ignores the environment variable `AWS_REGION`. This makes every single KMS call default to `us-east-1`

**Comment by thaidn** [comment]
Thanks @simplesteph. We're working on merging your PR to 1.2.1 release.

**Comment by thaidn** [comment]
This is fixed now. Thanks @simplesteph!

**Comment by thaidn** [comment]
https://github.com/google/tink/releases/tag/v1.2.1 is the release with the fix.
