### ISSUE TITLE
KeysDownloader URL validation

### ISSUE THREAD

**Issue by snotecki** [google/tink#150]
Could you change implementation of method:
- com.google.crypto.tink.util.KeysDownloader#validate
and allows also http://[host]:443 URL's?

In the newest version (1.2.0) this URL is validated if HTTPS protol is used. By default https://payments.developers.google.com/paymentmethodtoken/keys.json is used. In our production environment due to our network infrastructure we have to use proxy selector and change this URL from https://payment.developers.google.com/... to http://payment.developers.google.com:443/.... It's working with version 1.0.0 of Tink library (there is no validation). In the newest one unfortunately validation failed and we cannot update Tink library without changing network infastructure.

**Comment by thaidn** [comment]
Thanks @snotecki. We'll fix this shortly.

@chuckx Maybe if it's not too late, we should include the fix in 1.2.1.

**Comment by thaidn** [comment]
Wait, so you want to use http://?

Not sure what we can do here because we don't really want to allow this cleartext protocol.

**Comment by chuckx** [comment]
FYI, it's not too late for inclusion in 1.2.1. Looks like we need to figure out if there's a workable approach though.

**Comment by thaidn** [comment]
@snotecki Could you please share with us more about your network setup? Does your proxy man-in-the-middle all https connection? If so, can you make that server that runs Tink trusts the proxy's CA certificate?

**Comment by thaidn** [comment]
Please reopen if you still have this issue and can give us some more information on your network setup.

Thanks!
