### ISSUE TITLE
Incorrect version of protobuf-java generated in tink.pom.xml

### ISSUE THREAD

**Issue by sjurco** [google/tink#153]
It fails in runtime with error:

`java.lang.NoSuchMethodError: com.google.crypto.tink.proto.Keyset.parseUnknownFieldProto3`

There is a protobuf version 3.3.0 in `tink.pom.xml` generated with Bazel

https://github.com/google/tink/blob/6625fcf2cfc3f56fc8babbb0f0388a5983fab65c/maven/tink.pom.xml#L74

but I think that it should be higher version since the method `com.google.protobuf.GeneratedMessageV3#parseUnknownFieldProto3` was introduced in 3.4.0 and manually excluding 3.3.0 and forcing 3.4.0 fixed runtime.

Is version 3.4.0 the correct one? I cannot find it in source.

**Comment by sjurco** [comment]
@thaidn sure.

Simplest possible example:
```scala
import com.google.crypto.tink.{ BinaryKeysetReader, CleartextKeysetHandle }
import com.google.crypto.tink.config.TinkConfig
import java.io.ByteArrayInputStream

val is = new ByteArrayInputStream("a".getBytes())
val reader = BinaryKeysetReader.withInputStream(is)
val handle = CleartextKeysetHandle.read(reader)
```

online runnable example: https://scastie.scala-lang.org/bU54JwqKTmSEUJ0JEzQA3w

**Comment by thaidn** [comment]
Thanks!

It looks like you're parsing an invalid keyset. Have you tried with a correct one?

**Comment by sjurco** [comment]
Yes, that works.

Is there a way to validate a keyset without catching an Error? I need to support arbitrary user input (keysets)

**Comment by thaidn** [comment]
According to https://github.com/protocolbuffers/protobuf/issues/3499 I suspect the problem is that you have some other version of protobuf on your class path. Can you double check?

> since the method com.google.protobuf.GeneratedMessageV3#parseUnknownFieldProto3 was introduced in 3.4.0 and manually excluding 3.3.0 and forcing 3.4.0 fixed runtime.

I'll upgrade to 3.4.0.

**Comment by thaidn** [comment]
This should be fixed in 1.2.1 release, which is coming this week.

**Comment by sjurco** [comment]
Thanks. But is the 3.4.0 version the correct one? I asked it in the original question because I had no luck finding the correct version, I've just mentioned 3.4.0 because the missing method was introduced in that version. 

Now I grepped whole repo once again and found this:
https://github.com/google/tink/blob/213794f4eba3542f9ebaa29995a63dbe8246f825/WORKSPACE#L78-L90

Is it possible that correct version is 3.6.0? I have no idea how the build tool (bazel?) works.

**Comment by sjurco** [comment]
Thank you.

**Comment by thaidn** [comment]
@sjurco just so you know 1.2.1 was released yesterday. Please try and see if it works for you!
