### ISSUE TITLE
Objective C Implementation 

### ISSUE THREAD

**Issue by CodeTeamLabs** [google/tink#154]
hello to all ... I wanted to ask you if you can show me an example of implementation for objective C. I tried to read the documentation but I had some problems in understanding how to use in objective c ... can you give me an easy practical example? I need Use this for Firebase RealTime Database

**Comment by tl0gic** [comment]
Hi, did you check the Obj-C HowTo ? https://github.com/google/tink/blob/master/docs/OBJC-HOWTO.md

Any specific questions about the Obj-C usage?

**Comment by CodeTeamLabs** [comment]
Yes .. a simile example with implementation for firebase real time databe in objective c

**Comment by CodeTeamLabs** [comment]
When I use
 id<TINKAead> aead = [TINKAeadFactory primitiveWithKeysetHandle:handle error:&error];
my app crash ... why?

**Comment by CodeTeamLabs** [comment]
i implemented Tink in this way...

```
-(void)setupEncryption {
    NSError *error = nil;

    _config = [[TINKAllConfig alloc] initWithError:&error];
    if (![TINKConfig registerConfig:_config error:&error]) NSLog(@"%@", error.description);

    _aeadTemplate = [[TINKAeadKeyTemplate alloc] initWithKeyTemplate:TINKAes128Gcm error:&error];
    _keySetHandle = [[TINKKeysetHandle alloc] initWithKeyTemplate:_aeadTemplate error:&error];
}

-(NSString *)getEncryptedStringFromString:(NSString *)messageText  {
    NSError *error = nil;
    
    id <TINKAead> aead = [TINKAeadFactory primitiveWithKeysetHandle:_keySetHandle error:&error];

    NSData *messageTextData = [NSData dataWithContentsOfFile:messageText];
    _cipherText = [aead encrypt:messageTextData withAdditionalData:nil error:&error];
    
    NSString *encryptedString = [[NSString alloc] initWithData:_cipherText encoding:NSASCIIStringEncoding];
    
    return encryptedString;
}
```

The value is saved in **Firebase RealTime Database**... now I have a problem when I retrieve the encrypted data in `UICollectionView` `cellForItemAtIndexPath`... How to show the message decrypted? The string value is alway NULL... where I wrong?

```
-(UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(nonnull NSIndexPath *)indexPath {
    MessageRoomCell *cell = [collectionView dequeueReusableCellWithReuseIdentifier:NSStringFromClass([MessageRoomCell class]) forIndexPath:indexPath];
    
    MessageReference *messageRef = _messages[indexPath.item];
    cell.messageRef = messageRef;
    
    NSError *error = nil;
    
    id <TINKAead> aead = [TINKAeadFactory primitiveWithKeysetHandle:_keySetHandle error:&error];
    
    NSData *decryptedData = [aead decrypt: [messageRef.text dataUsingEncoding:NSUTF8StringEncoding] withAdditionalData:nil error:&error];
    NSString *decryptedString = [[NSString alloc] initWithData:decryptedData encoding:NSASCIIStringEncoding];
    
    NSLog(@"%@", decryptedData);
    
    cell.textMessage.text = decryptedString;
   
    return cell;
}
```

**Comment by tl0gic** [comment]
After this line:
NSData *decryptedData = [aead decrypt: [messageRef.text dataUsingEncoding:NSUTF8StringEncoding] withAdditionalData:nil error:&error];

Print the contents of error: NSLog(@"error: %@", error);

**Comment by CodeTeamLabs** [comment]
@tl0gic  hi... the log write this when add NSLog(@"error: %@", error);

> error: Error Domain=TinkErrorDomain Code=3 "Tink Error" UserInfo={NSLocalizedDescription=Tink Error, NSLocalizedFailureReason=decryption failed}

Surely it's me that I'm doing something wrong ... I have various problems ...

When I try to encrypt using `NSUTF8StringEncoding` it does not save any data. To save the **encrypted** message I have to use `NSASCIIStringEncoding`. Only in this way I can **encrypt** a message .. 

So besides not being able to **decrypt** my messages I can not even **encrypt**. Could you give me a specific example of how to **encrypt** a message and how to decrypt it using `UICollectionView`?

I followed the documentation you suggested but I can not solve the problem ...

Forgive me if I'm asking stupid questions :D

**Comment by CodeTeamLabs** [comment]
???

**Comment by tl0gic** [comment]
I don't see anything wrong with the way you are using Tink.

I suggest you add NSLog statements before and after each call to encrypt, decrypt, generate keys etc. to figure out exactly at which point your code fails.

You could also leverage Xcode's debugger to step through the code and inspect the return values etc.

**Comment by tl0gic** [comment]
Here is a full example that uses AEAD to encrypt and decrypt a string:
```
- (void)setupTink {
    NSError *error = nil;
    TINKAllConfig *config = [[TINKAllConfig alloc] initWithError:&error];
    if (!config || error) {
        NSLog(@"Failed to init tink config, error: %@", error);
        return;
    }
    
    if (![TINKConfig registerConfig:config error:&error]) {
        NSLog(@"Failed to register tink config, error: %@", error);
        return;
    }
    
    TINKAeadKeyTemplate *tpl = [[TINKAeadKeyTemplate alloc] initWithKeyTemplate:TINKAes128Gcm error:&error];
    if (!tpl || error) {
        NSLog(@"Failed to generate tink AEAD key template, error: %@", error);
        return;
    }
    
    TINKKeysetHandle *handle = [[TINKKeysetHandle alloc] initWithKeyTemplate:tpl error:&error];
    if (!handle || error) {
        NSLog(@"Failed to get keyset handle from key template, error: %@", error);
        return;
    }
    
    id<TINKAead> aead = [TINKAeadFactory primitiveWithKeysetHandle:handle error:&error];
    if (!aead || error) {
        NSLog(@"Failed to get AEAD primitive, error: %@", error);
        return;
    }
    
    NSData *plaintext = [@"hello, world!" dataUsingEncoding:NSUTF8StringEncoding];
    NSData *ciphertext = [aead encrypt:plaintext withAdditionalData:nil error:&error];
    if (!ciphertext || error) {
        NSLog(@"Failed to encrypt plaintext, error: %@", error);
        return;
    }
    NSLog(@"Ciphertext = %@", ciphertext);
    
    NSData *decrypted = [aead decrypt:ciphertext withAdditionalData:nil error:&error];
    if (!decrypted || error) {
        NSLog(@"Failed to decrypt ciphertext, error: %@", error);
        return;
    }
    
    NSLog(@"Decrypted = %@, decrypted as UTF8 string: '%@'", decrypted, [NSString stringWithUTF8String:[decrypted bytes]]);
    NSLog(@"Plaintext = %@", plaintext);
    if ([decrypted isEqualToData:plaintext]) {
        NSLog(@"Success! decrypted is equal to plaintext");
    } else {
        NSLog(@"Failure! decrypted is NOT equal to plaintext");
    }
}
```

Running the example prints the following:
```
2018-11-14 15:44:50.826506-0800 TinkExample[17173:292256] Ciphertext = <01a1efa1 2004a3ae 02a4b4a6 acfb4bd3 5f069e06 186ef29f 81a00ab4 1ec0f6d9 149d8983 7dc3f71d 3472db5f 5fc0>
2018-11-14 15:44:50.826624-0800 TinkExample[17173:292256] Decrypted = <68656c6c 6f2c2077 6f726c64 21>, decrypted as UTF8 string: 'hello, world!'
2018-11-14 15:44:50.826722-0800 TinkExample[17173:292256] Plaintext = <68656c6c 6f2c2077 6f726c64 21>
2018-11-14 15:44:50.826804-0800 TinkExample[17173:292256] Success! decrypted is equal to plaintext
```

**Comment by CodeTeamLabs** [comment]
@tl0gic Hi ... so I followed your implementation advice step by step and with Firebase I found some problems ...

When I encrypt my text it gives me back the encrypted text in NSLog, but this text I need to be saved in my **Firebase Database** and if I use

 `NSString * convertedStr = [[NSString alloc] initWithData: _cipherText encoding: NSUTF8StringEncoding];`

so with encoding NSUTF8StringEncoding firebase does not save my encrypted message and I do not know why. This is the first problem ..

The second problem remained what I told you before ... If I use NSASCIIStringEncoding instead of NSUTF8StringEncoding my message is saved in Firebase but it is not decrypted ..

**Not WORK**
```
 NSData *data = [_inputContainerView.textView.text dataUsingEncoding:NSUTF8StringEncoding];
    _cipherText = [_aead encrypt:data withAdditionalData:nil error:nil];
    
    NSString * convertedStr = [[NSString alloc] initWithData:_cipherText encoding:NSUTF8StringEncoding];
  dictionary[kMessageText] = convertedStr;
```

 **WORK**

```
 NSData *data = [_inputContainerView.textView.text dataUsingEncoding:NSASCIIStringEncoding];
    _cipherText = [_aead encrypt:data withAdditionalData:nil error:nil];
    
    NSString * convertedStr = [[NSString alloc] initWithData:_cipherText encoding:NSASCIIStringEncoding];
  dictionary[kMessageText] = convertedStr;
```

In your example when you want to decrypt the message you always use the same NSData you use when you crypt a message (cipherText).

`NSData ***ciphertext** = [aead encrypt:plaintext withAdditionalData:nil error:&error];
 NSData *decrypted = [aead decrypt:**ciphertext** withAdditionalData:nil error:&error];
`
In my case (I'm using Tink for a simultaneous chat) I need another NSData that contains all the messages I've retrieved through the Firebase query.

`NSData ***ciphertext** = [aead encrypt:plaintext withAdditionalData:nil error:&error];

// Decrypt
 NSData ***dataToDecrypt** = [myDatabase.messageText.text dataUsingEncoding:NSASCIIStringEncoding];
 NSData *decrypted = [aead decrypt:**dataToDecrypt** withAdditionalData:nil error:&error];
`

> 2018-11-15 11:45:15.870706+0100 Ium[3061:1172607] Data decrypted = (null)


In this case when I go to check my decrypted message my NSLog is **NULL**

I hope I managed to explain myself sometimes it is not easy to communicate a technical concept and in another language: D

I apologize also for my bad English

**Comment by tl0gic** [comment]
Oh I see. You can't convert ciphertext to an NSString using: `NSString * convertedStr = [[NSString alloc] initWithData: _cipherText encoding: NSUTF8StringEncoding];`

The reason you can't do this is because the ciphertext contains a bunch of random-looking bytes which aren't valid UTF-8. If you try to convert it to UTF-8 it will fail.

You have to encode to another format, such as Base64:
```
NSString *convertedStr = [NSString stringWithUTF8String:[[_cipherText base64EncodedDataWithOptions:nil] bytes]];
```

You can store the base64 encoded string to firebase. Then when you retrieve it you need to first base64 decode it and then use Tink to decrypt it.

**Comment by CodeTeamLabs** [comment]
Here I am! : D then I can say that I have achieved some results ... Surely all these errors I had are my mistakes .. in a nutshell now I can save on Firebase in this way :

```
-(void)sendMessage {
    NSMutableDictionary *dictionary = NSMutableDictionary.new;
    
    // Message 
    NSData *plaintext = [_inputContainerView.textView.text dataUsingEncoding:NSUTF8StringEncoding];
    NSLog(@"Plaintext = %@", plaintext);

   // Encrypt Message
    NSData *cipherText = [_aead encrypt:plaintext withAdditionalData:nil error:nil];
    NSLog(@"cipherText: %@", cipherText);
    
    // Convert Encrypt Message in base64 String
    NSString *convertedStr = [cipherText base64EncodedString];
    NSLog(@"Encoded: %@", convertedStr);

    // Save Encrypt Base64 String in Firebase
    dictionary[kMessageText] = convertedStr;
    
    [self sendMessageWithProperty:dictionary];
}
```
Now Retrieve the Crypt Message in `UICollectionView`

```
-(UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(nonnull NSIndexPath *)indexPath {
    MessageRoomCell *cell = [collectionView dequeueReusableCellWithReuseIdentifier:NSStringFromClass([MessageRoomCell class]) forIndexPath:indexPath];
    
    MessageReference *messageRef = _messages[indexPath.item];
    cell.messageRef = messageRef;
     
    // Encrypt Base64 String From Firebase
    NSLog(@"Firebase output %@", messageRef.text);

     // Decode Encrypt Base64 String From Firebase
    NSData *dataFromBase64String = [NSData dataFromBase64String:messageRef.text];
    NSLog(@"dataFromBase64String %@", dataFromBase64String);
    
    // Decrypt Message
    NSData *decrypt = [_aead decrypt:dataFromBase64String withAdditionalData:nil error:nil];
    NSLog(@"DECRYPT %@", decrypt);
    
    // NSString Decrypted
    NSString *decodedString = [[NSString alloc] initWithData:decrypt encoding:NSUTF8StringEncoding];
    NSLog(@"DecodStr %@", decodedString);
    
     // Show NSString Decrypted
    cell.textMessage.text = decodedString;

    return cell;
}
```
Now after all this implementation if I send a message everything works ... The message is encrypted, then encoded in Base64 and saved in Firebase.

When I recover the message here everything works, but only if I am in my `View Controller` ... If I had to leave the `ViewController` that contains the `Collection View` and return again all the messages are gone ..

In short, the decryption works only if I do not leave the `ViewController` .. If I go out and go back to my view controller all the previously decrypted data are not displayed ...

I show you my `NSLog` to understand

if I am in the viewController and start sending messages these are the results

**Send Message**
> 2018-11-16 13:44:59.290498+0100 [3730:1419570] Plaintext = <4369616f 20>
> 2018-11-16 13:44:59.291391+0100  [3730:1419570] cipherText: <01018130 1128f2a6 faa5970b 355e3ec3 b22fbfbe bf176907 e234876d d25d2e20 79a24562 13f5>
> 2018-11-16 13:44:59.291541+0100 [3730:1419570] Encoded: AQGBMBEo8qb6pZcLNV4+w7Ivv76/F2kH4jSHbdJdLiB5okViE/U=

**Retrieve Message real Time**
> 2018-11-16 13:45:00.611582+0100 [3730:1419570] Firebase output AQGBMBEo8qb6pZcLNV4+w7Ivv76/F2kH4jSHbdJdLiB5okViE/U=
> 2018-11-16 13:45:00.611755+0100 [3730:1419570] dataFromBase64String <01018130 1128f2a6 faa5970b 355e3ec3 b22fbfbe bf176907 e234876d d25d2e20 79a24562 13f5>
> 2018-11-16 13:45:00.611891+0100 [3730:1419570] DECRYPT <4369616f 20>
> 2018-11-16 13:45:00.611928+0100 [3730:1419570] DecodStr Ciao
_______
Instead if I exit my viewController and return I get this ...

**Retrieve Message**
> 2018-11-16 13:47:32.546022+0100 [3730:1419570] Firebase output AQGBMBEo8qb6pZcLNV4+w7Ivv76/F2kH4jSHbdJdLiB5okViE/U=
> 2018-11-16 13:47:32.546220+0100 [3730:1419570] dataFromBase64String <01018130 1128f2a6 faa5970b 355e3ec3 b22fbfbe bf176907 e234876d d25d2e20 79a24562 13f5>
> 2018-11-16 13:47:32.546285+0100 [3730:1419570] DECRYPT (null)
> 2018-11-16 13:47:32.546327+0100 [3730:1419570] DecodStr

Why "decrypt" in this case is null?

**Comment by tl0gic** [comment]
Hm I'm not sure what's going on. You will have to debug it a bit.

Btw for support requests please use our mailing list https://groups.google.com/forum/#!forum/tink-users instead of the bug tracker.

I'm going mark this issue resolved since it's not a bug in Tink.
