### ISSUE TITLE
Java: Verify signature using external public key

### ISSUE THREAD

**Issue by alex-iov42** [google/tink#155]
Hi,

We would like to start using Tink as our crypto library, but at the moment we have difficulties figuring out how to do some very simple things.

We have the following:

- Some raw data
- User's public key
- Signature of the raw data

So, we want to do something like the following:
```
val publicKeySetHandle = ??? // somehow create a KeysetHandle from the user's public key
val verifier = PublicKeyVerifyFactory.getPrimitive(publicKeysetHandle)
verifier.verify(signature.getBytes, rawData.getBytes)
```

But we cannot figure out a way to create a `KeysetHandle` from a user's public key.

How is this done? Is it even possible?

Thank you,
Alex

**Comment by thaidn** [comment]
Please reopen if you have any other questions.
