### ISSUE TITLE
Missing third_party/BUILD.bazel files in Tink 1.2.1 tar ball

### ISSUE THREAD

**Issue by mapx** [google/tink#161]
The following BUILD.bazel files are missing in https://github.com/google/tink/releases/tag/v1.2.1 source code:
* `third_party/aws_sdk_cpp.BUILD.bazel`
* `third_party/curl.BUILD.bazel`
* `third_party/zlib.BUILD.bazel`

**Comment by przydatek** [comment]
Hi Yuchen,

this omission is intentional, as these files are part of [C++ integration with AWS KMS](https://github.com/google/tink/tree/master/cc/integration/awskms), which is not included in release 1.2.1 (they will probably be included in the upcoming release 1.3.0).
Cheers,

Bartosz.
