### ISSUE TITLE
Front page README tutorial seems wrong

### ISSUE THREAD

**Issue by rjcarr** [google/tink#162]
Seems the README has been changed to this code:

```
// 2. Get the primitive.
Aead aead = keysetHandle.getPrimitive(Aead.class);
```

But I'm pretty sure `getPrimitive()` isn't a method of KeysetHandle, at least not in the published API docs.  Before, the tutorial instructed to use a factory like this:

```
Aead aead = AeadFactory.getPrimitive(keysetHandle);
```

Which seems to work fine.  Maybe this is some future and/or undocumented feature?

**Comment by chuckx** [comment]
The README in the master branch documents the latest implementation. So, the example here:

https://github.com/google/tink/blob/master/README.md

corresponds with the documentation here:

https://google.github.io/tink/javadoc/tink/HEAD-SNAPSHOT/com/google/crypto/tink/KeysetHandle.html#getPrimitive-java.lang.Class-

The documentation for the latest release (v1.2.1) still contains the example you remember. See the following links for comparison with the above:

https://github.com/google/tink/blob/v1.2.1/README.md

http://google.github.io/tink/javadoc/tink/1.2.1/com/google/crypto/tink/KeysetHandle.html

**Comment by chuckx** [comment]
Furthermore, we're working on refreshing how the documentation is presented to make the delineation between versions more clear.

**Comment by decoded4620** [comment]
Yeah, @chuckx that document link doesn't exist anymore. Can we update this with the correct information as I'm running into the same issue trying to use the HOW TO examples.

**Comment by chuckx** [comment]
It looks like there an issue with the javadoc generation. A bunch of expected interfaces/classes are missing. For comparison, compare:

 * https://google.github.io/tink/javadoc/tink/1.3.0-rc1/com/google/crypto/tink/package-summary.html
 * https://google.github.io/tink/javadoc/tink/1.3.0-rc2/com/google/crypto/tink/package-summary.html

I'll take a look into this and open a new issue for it in a bit.

**Comment by chuckx** [comment]
FYI, bc589d5f fixes the Javadoc generation issue, and the HEAD-SNAPSHOT link above is working again.
