### ISSUE TITLE
Missing Key Exchange Primitive

### ISSUE THREAD

**Issue by java-crypto** [google/tink#163]
Hi Team, I'm missing a Key Exchange Primitive like DH or EC on Basis Curve25519. 

As the keys e.g. for encryption or Digital Signatures are capsulated within the KeyHandles we cannot put the data from (external) DH or EC-Key Exchange inside the KeyHandles :-(

Kind regards, Michael

**Comment by bleichen** [comment]
I think there are two problems above.
The first one is the key derivation: I.e. given a shared secret byte string to derive a key for a given
key format. This has use cases beyond just key exchange. There is extensive code in the previous
library "keymaster", so at least some ideas from there can be reused.
The second one is an API for a key exchange. I'd probably start with an API for an authenticated or signed key exchange with key confirmation. I haven't done any literature search so far, so I don't know
what standards are available.

**Comment by java-crypto** [comment]
Happy new year and thanks to both of you. Is there any timeline for completion ?
Kind regards, Michael

**Comment by berendjan** [comment]
Until there is a key exchange primitive, you could use a hybrid primitive to share a key to others.

**Comment by tholenst** [comment]
This is a reasonable request, but it has been open for more than 4 years and it is clear that we will not get to this any time soon.
