### ISSUE TITLE
Support dart and flutter

### ISSUE THREAD

**Issue by rashedmyt** [google/tink#165]
Dart is very weak in native crypto packages. It would be really great if you could support dart and those languages which have very weak crypto libraries instead of those having them already..

**Comment by rashedmyt** [comment]
I think its doable as mentioned by this article https://www.dartlang.org/articles/server/native-extensions. But I would prefer Dart code anytime over these inter-language calls and wrappers. Maybe a collaboration with dart team might give more insight on how to best achieve this requirement.

**Comment by dnfield** [comment]
`dart:ffi` should make it easier to do native interop for this via C++, but it would be really nice if it was also available as a Dart library.

**Comment by Boehrsi** [comment]
+1 for a native Dart implementation. I could imagine as Flutter + Dart is spreading more and more (e.g. to the desktop and also to the web) especially the https://github.com/google/tink/tree/master/apps/webpush part could be really helpful for secure cross platform push efforts.

**Comment by Comevius** [comment]
+1 
A native Dart library would help a lot of developers trying to do cross-platform crypto correctly.

You should contact the Dart team to see if they can lend a hand. Either they or the Flutter people will be probably interested given how much Tink could contribute to their efforts of making mobile, web and desktop development more enjoyable and productive.

**Comment by leisim** [comment]
There is currently no actively developed encryption library for Dart / Flutter and tink support would be amazing. Please don't create an implementation that relies on ffi since it will not work on the web.

**Comment by terrier989** [comment]
You may consider Dart package [cryptography](https://pub.dev/packages/cryptography), which has the same goals, largely the same algorithms, and the same Apache License 2.0.

**Comment by budo76** [comment]
+1 for native flutter/dart implementation ... because Flutter has poor Crypto implementations, and well... "tink" is from google right?... "dart" is from google... "flutter" is from google... but there's no Dart/flutter implementation and no people who knows Dart in the core tink team? ... :-O

**Comment by tholenst** [comment]
We agree that this should exist, but we do not have the headcount to consider working on this at the moment.
