### ISSUE TITLE
[Feature Request] Support for HashiCorp Vault

### ISSUE THREAD

**Issue by willsalz** [google/tink#167]
As titled. If I get some free cycles I'd be interested in taking a stab as a contributor!

**Comment by thaidn** [comment]
That'll be most welcome, thanks Will!

**Comment by perezd** [comment]
I'd love to see this for Java.

**Comment by thaidn** [comment]
We have some support for HashiCorp Vault in Golang: https://github.com/google/tink/tree/master/go/integration/hcvault.

**Comment by thaidn** [comment]
Please send PRs if you want to add support for other languages.

**Comment by rosstimothy** [comment]
I am looking to contribute Java support for HashiCorp Vault. Are either of the [Java clients](https://www.vaultproject.io/api/libraries.html#java) listed by HashiCorp acceptable to be used?
