### ISSUE TITLE
 encrypt in OBJC, Decrypt in java

### ISSUE THREAD

**Issue by fengsong89** [google/tink#168]
Now we use iOS client, and Java server.
If I encrypt a string in objective-c, such as ciphertext = "hello123", associatedData = "qwert", then transfter them to byte array.
After encrypting in objective-c, the result is byte[] = {127,81,102,226,73,189......}.
But in java,  the byte's range is  from -128 to 127, some of the values in result byte array beyond -128-127,
the result byte[] in java will be transfter to  {127,81,102,-30,73,-67......}
after decrypt: java.security.GeneralSecurityException: decryption failed
how can I do ?

**Comment by thaidn** [comment]
@tl0gic

**Comment by fengsong89** [comment]
we use base64 to solve this problem~~~

**Comment by thaidn** [comment]
Thanks for the update!
