### ISSUE TITLE
How to verify the signature on signedStringForIntermediateSigningKeySignature

### ISSUE THREAD

**Issue by youminglei** [google/tink#169]
// When I use Tink to verify signedStringForIntermediateSigningKeySignature, it always fails. 
        // I thought it was my problem, but I used the parameters on the document or failed. 
        // I found the reason why I couldn't find the problem for a long time. 
        // Please help, thank you.

        
        // Below is the code 
        
        // from https://payments.developers.google.com/paymentmethodtoken/test/keys.json
        String keyValue = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEGnJ7Yo1sX9b4kr4Aa5uq58JRQfzD8bIJXw7WXaap/hVE+PnFxvjx4nVxt79SdRuUVeu++HZD0cGAv4IOznc96w==";
        ECPublicKey publicKey = PaymentMethodTokenUtil.x509EcPublicKey(keyValue); 
        
        // from https://developers.google.cn/pay/api/web/guides/resources/payment-data-cryptography#how-to-construct-the-byte-string-for-intermediate-signing-key-signature 
        String signedKeyAsString = "{\"keyExpiration\":\"1542323393147\",\"keyValue\":\"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE/1+3HBVSbdv+j7NaArdgMyoSAM43yRydzqdg1TxodSzA96Dj4Mc1EiKroxxunavVIvdxGnJeFViTzFvzFRxyCw\\u003d\\u003d\"}";
        byte[] signedBytes =
            PaymentMethodTokenUtil.toLengthValue(
                // The order of the parameters matters.
                "Google", "ECv2", signedKeyAsString);
        
        // from https://developers.google.cn/pay/api/web/guides/resources/payment-data-cryptography#how-to-construct-the-byte-string-for-intermediate-signing-key-signature 
        byte[] signature = Base64.decode("MEYCIQCO2EIi48s8VTH+ilMEpoXLFfkxAwHjfPSCVED/QDSHmQIhALLJmrUlNAY8hDQRV/y1iKZGsWpeNmIP+z+tCQHQxP0v");
        EcdsaVerifyJce verifier =
            new EcdsaVerifyJce(
                publicKey, HashType.SHA256, EcdsaEncoding.DER);
        try {
          verifier.verify(signature, signedBytes);
          // No exception means the signature is valid.
          System.out.println("successful");
        } catch (GeneralSecurityException e) {
            e.printStackTrace();
          // ignored, try again
            System.out.println("failed");
        }

**Comment by thaidn** [comment]
@waltercacau

**Comment by Day512** [comment]
Hello, do you find solution, we have same problem with ECv2

**Comment by thaidn** [comment]
@Day512 Have you resolved this?

**Comment by waltercacau** [comment]
@Day512 @youminglei , could you please instead try the instructions in https://developers.google.com/pay/api/web/guides/resources/payment-data-cryptography#using-tink ?

you should not need to use the lower level ECPublicKey and EcdsaVerifyJce. We provide a PaymentMethodTokenRecipient helper which correctly implements the protocol.

**Comment by freygriff** [comment]
{
  "protocolVersion": "ECv2",
  "publicKey": "BOdoXP+9Aq473SnGwg3JU1..."
}

**Comment by thaidn** [comment]
Please reopen if you need more help.

**Comment by ipsi-apant** [comment]
Hi @thaidn and @waltercacau 
We are doing the same steps mentioned in this document but consistently receiving following error. Please advise.

### Error
```java
java.security.GeneralSecurityException: cannot verify signature
	at com.google.crypto.tink.apps.paymentmethodtoken.PaymentMethodTokenRecipient.verify(PaymentMethodTokenRecipient.java:471)
	at com.google.crypto.tink.apps.paymentmethodtoken.PaymentMethodTokenRecipient.verifyECV2(PaymentMethodTokenRecipient.java:409)
	at com.google.crypto.tink.apps.paymentmethodtoken.PaymentMethodTokenRecipient.unsealECV2(PaymentMethodTokenRecipient.java:375)
	at com.google.crypto.tink.apps.paymentmethodtoken.PaymentMethodTokenRecipient.unseal(PaymentMethodTokenRecipient.java:352)
```

### Unit test
```java
@Test
  public void testUnseal() throws Exception {
    
    // created using Google Pay API via GPAY button in JS
    // The value for "tokenizationData.token" is similar to the value in following example
    // https://developers.google.com/pay/api/web/guides/resources/payment-data-cryptography#example
    String encryptedMessage = "..."; 

    PaymentMethodTokenRecipient recipient =
        new PaymentMethodTokenRecipient.Builder()
            .protocolVersion("ECv2")
            .fetchSenderVerifyingKeysWith(GooglePaymentsPublicKeysManager.INSTANCE_TEST)
            .recipientId("test") // encryptedMessage created using this merchant id
            .addRecipientPrivateKey(googlePayPrivateKey)
            .build();

    String decryptedMessage = recipient.unseal(encryptedMessage); // Fails here

    log.info("Decrypted Message: {}", decryptedMessage);
  }
```
