### ISSUE TITLE
Getting a javac warning from the classfile linter but not sure what is going on

### ISSUE THREAD

**Issue by rjcarr** [google/tink#173]
After adding tink to my java build I'm getting linter warnings that look like this (probably 10 total all the same):

    .../tink-1.2.1.jar(com/google/crypto/tink/Aead.class): warning: [classfile] MethodParameters attribute introduced in version 52.0 class files is ignored in version 51.0 class files

I've tried a number of things but I think it has to do with the way the tink class files were compiled?  I think it's been opened, and resolved, as a jdk bug, but I have the latest Java 8 and it still shows up.  See the bug here:

https://bugs.openjdk.java.net/browse/JDK-8190452

Any idea what is going on and how to make it stop (short of turning off the warnings with -Xlint:-classfile)?

Thanks!

**Comment by thaidn** [comment]
Interesting. Tink was compiled for Java 7, so it should work with Java 8. Actually we're using Java 8 at Google, and Tink works just fine. Here's the compiler flag: https://github.com/google/tink/blob/master/tools/build_defs/javac.bzl.

Are you building Tink with Bazel?

**Comment by rjcarr** [comment]
Hi @thaidn, actually, I'm not building Tink at all, but using the available jar library directly.  As I said, when I compile against it (using my Java 8, with source and target as Java 8), I get those classfile warnings.

I think it's a bug in javac, but as I said, I don't 100% understand what is going on.  If you can't repeat my problem then I'll just live with it until I start using Java 11 I guess.

Thanks!

**Comment by thaidn** [comment]
I cannot repeat the problem, so I guess I'll close this. Please reopen if you have additional insights. Thanks!
