### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by gridcellcoder** [google/tink#175]
In `JAVA-HOWTO`:

>  For example, you can encrypt the key material with a Google Cloud KMS key at `gcp-kms:/projects/tink-examples/locations/global/keyRings/foo/cryptoKeys/bar as follows:`

Should be 

> For example, you can encrypt the key material with a Google Cloud KMS key at `gcp-kms://projects/tink-examples/locations/global/keyRings/foo/cryptoKeys/bar` as follows:

with

`gcp-kms://`

**Comment by thaidn** [comment]
Thanks for the report, this should be fixed now!
