### ISSUE TITLE
 Multiple private/public Key pairs in Tink

### ISSUE THREAD

**Issue by Muhammad-Umer** [google/tink#181]
I started exploring **Tink** recently and now stuck at a particular problem, and couldn't find the solution in docs or online.

The case is: I want to have two sets of Public/Private keypairs. One would be active and other would be disabled.

What I did was to generate a KeyHandle like this and stored it in AWS KMS:

**FOR PRIMARY:**

`
KeysetHandle pri = KeysetHandle.generateNew(SignatureKeyTemplates.ECDSA_P256);
`
`KeysetHandle pub = privateKeySetHandle.getPublicKeysetHandle();`

`pri.write(JsonKeysetWriter.withFile(new File("pri_p")),  new AwsKmsClient().withDefaultCredentials().getAead(keyStoreUrl));`

`pub.write(JsonKeysetWriter.withFile(new File("pub_p")), new AwsKmsClient().withDefaultCredentials().getAead("someUrl"));
`

**FOR SECONDARY:**

`KeysetHandle pri = KeysetHandle.generateNew(SignatureKeyTemplates.ECDSA_P256);`
`KeysetHandle pub = privateKeySetHandle.getPublicKeysetHandle();`

`pri.write(JsonKeysetWriter.withFile(new File("pri_s")), new AwsKmsClient().withDefaultCredentials().getAead(keyStoreUrl));`

`pub.write(JsonKeysetWriter.withFile(new File("pub_s")), new AwsKmsClient().withDefaultCredentials().getAead("someUrl"));
`

I did this because I thought that I'd generate two pairs and keep them in different json files as:
1. **pri-p** (primary)
2. **pub-p** (primary)
3. **pri-s** (secondary)
4. **pub-s** (secondary)

After doing this, I wrote an API which returned both public keys (primary & secondary) to the client and the response was:

`({
"primaryKeyId": 12345,
"key": [{
    "keyData": {
        "typeUrl": "type.googleapis.com/google.crypto.tink.EcdsaPrivateKey",
        "keyMaterialType": "ASYMMETRIC_PUBLIC",
        "value": "IDJNVUs,csaIQDP9jhF+MERyoZ6Ede/LteBYS0n4zVbYTcuCZCiFBERhyIhAJettefH3BPjFyyZC3m90Pw+m/K8sjiEPS"
    },
    "outputPrefixType": "TINK",
    "keyId": 12345,
    "status": "ENABLED"
}]
},{
"primaryKeyId": 6789,
"key": [{
    "keyData": {
        "typeUrl": "type.googleapis.com/google.crypto.tink.EcdsaPublicKey",
        "keyMaterialType": "ASYMMETRIC_PUBLIC",
        "value": "EgYI7hfsdhfsdm0eeii3m43434334390439TcuCZCiFBERhyIhAJettefH3BPjFyyZC3m90Pw+m/K8sjiEPSXKSMgmWEgr"
    },
    "outputPrefixType": "TINK",
    "keyId": 6789,
    "status": "ENABLED"
}]
})`
Now I wanted to make the secondary one as inactive so that nobody uses it, meaning status: DISABLED using the code as below:

`KeysetHandle secondaryPublicKey = KeysetManager
            .withKeysetHandle(secondaryPublicKey)
            .disable(keySetHandle.getKeysetInfo().getPrimaryKeyId())
            .getKeysetHandle();
`
but I got the exception as:

> java.security.generalsecurityexception: cannot disable the primary key

At that time, I realized that what I did was wrong, and I had to do it altogether again, so that both Keys are in the same KeysetHandle and this I am unable to do as when a KeysetHandle is created like:

`KeysetHandle pri = KeysetHandle.generateNew(SignatureKeyTemplates.ECDSA_P256);`

It's already marked as a primary key and if I retrieve the public key from this, that would also be primary key. No matter how many keys I generate, all will be marked as primary using this.

But I am not sure how to go about this, or is whether it is the correct way.

Need some help on this, I'd really appreciate.

**Comment by thaidn** [comment]
I answered this question on StackOverflow: https://stackoverflow.com/questions/54426283/multiple-private-public-key-pairs-in-tink/54455225#54455225.

We can continue the discussion there.

Cheers,
Thai.
