### ISSUE TITLE
How do you use the TINK encryption component in javascript?

### ISSUE THREAD

**Issue by leilei807** [google/tink#182]
How do you use the TINK encryption component in javascript?

**Comment by thaidn** [comment]
We had some initial support for Javascript, but it is not open source yet. We plan to open source it in August 2019.

**Comment by ssc-hrep3** [comment]
Are you still planning to release a JavaScript version of tink this month?

**Comment by sambegin** [comment]
> We plan to open source it in August 2019. 

Still on target? :P

**Comment by freygriff** [comment]
Yes

**Comment by thaidn** [comment]
FYI: @taymonbeal has finally helped us publish a package, check out https://www.npmjs.com/package/tink-crypto.
