### ISSUE TITLE
Encrypting using private key in Hybrid Encryption

### ISSUE THREAD

**Issue by izBasit** [google/tink#183]
I am trying to encrypt plain text using a private key, via Hybrid encryption. 
It doesn't allow me to do it, and gives an error  `invalid HybridEncrypt key material`. 
Doesn't tink support encryption using the private key? And i am assuming, I won't be able to decrypt using a public key as well. 🤔 

Any leads on how i can do this?

**Comment by thaidn** [comment]
Hi there,

You want to encrypt with *public key* and decrypt with *private key*.

**Comment by izBasit** [comment]
Hi man,
Yes, you are right. I am doing that as well. And it works flawlessly. 
But, I also want to encrypt using the private key (or rather sign the data with my private key) so the receiver can decrypt using my public key and get confirmation that the data is actually coming from me.

**Comment by thaidn** [comment]
Ah you want a digital signature for that. Check out https://github.com/google/tink/blob/master/docs/JAVA-HOWTO.md#digitial-signatures

**Comment by thaidn** [comment]
Please reopen if you have any further questions.
