### ISSUE TITLE
Questions regarding the AEAD Streaming

### ISSUE THREAD

**Issue by Kinchkun** [google/tink#185]
Hello there,

we would like to develop an iOS (written in Objective C) and Android App (written in Java) with Streaming Encryption of larger files (up to 100MB) using AES256/GCM.

Where can I find a documentation about utilizing tink to encrypt/decrypt NSInputStreams/NSOutputstreams? The ObjC [Readme#Symmetric Key Encyption](https://github.com/google/tink/blob/master/docs/OBJC-HOWTO.md#symmetric-key-encryption) only mentioned working with NSData.

Is the streaming api of both languages (Java, iOS) compatible i.e. can in decrypt in ObjC a Message generated in Java?

If I understand this correctly you support streaming of AEAD Ciphers by splitting the message into segments or chunks. Is there a in deep documentation how this is performed? I would like to know for example how it is ensured that the message is received completely e.g. the last segment is not missing.

Thank you very much :)
Kinch

**Comment by przydatek** [comment]
Hi Kinch,

Streaming AEAD is so far available only in Java, but C++ and ObjC implementations are [in preparation for the next release](https://github.com/google/tink/blob/master/docs/ROADMAP.md#130).  These implementations will be compatible with Java (so yes, you'll be able to decrypt in ObjC a message encrypted in Java). 
For some background info on implementation of Streaming AEAD in Tink please see [this doc](https://github.com/google/tink/blob/master/docs/PRIMITIVES.md#streaming-authenticated-encryption-with-associated-data), and the key interface responsible for encrypting segments is [StreamSegmentEncrypter](https://github.com/google/tink/blob/master/java/src/main/java/com/google/crypto/tink/subtle/StreamSegmentEncrypter.java), which is responsible for encrypting segments and treats plaintext segment differently, depending whether it is a last segment or not  (the details depend in the particular scheme, see e.g. [AesCtrHmacStreaming](https://github.com/google/tink/blob/master/java/src/main/java/com/google/crypto/tink/subtle/AesCtrHmacStreaming.java#L255)or [AesGcmHkdfStreaming](https://github.com/google/tink/blob/master/java/src/main/java/com/google/crypto/tink/subtle/AesGcmHkdfStreaming.java#L200)). 
(Unfortunately, we don't have yet a doc which would describe the implementations in more detail).

Hope that helps, please let us know if you have further questions.
Cheers,

Bartosz.

**Comment by Kinchkun** [comment]
Hi Bartosz,

thank you very much for the response :) So far this answered my questions and I will close the issue.

Cheers,
Kinch
