### ISSUE TITLE
additionalData Clarification

### ISSUE THREAD

**Issue by sstubbs** [google/tink#188]
Hi,

What does additionaldata in the encrypt function mean? In the hello world example https://github.com/google/tink/blob/master/examples/helloworld/java/src/main/java/com/helloworld/Commands.java it is set to a new byte[0]

Is this just additional plaintext information that will added if needed or should it this be secure random iv for each message encrypted?

**Comment by hf** [comment]
Additional data is a construct of [authenticated encryption](https://en.wikipedia.org/wiki/Authenticated_encryption). It is data that will modify the cipher state but will not be encrypted.

**Comment by chuckx** [comment]
For background, please refer to the paper [Authenticated-Encryption with Associated-Data by Phillip Rogaway](http://web.cs.ucdavis.edu/~rogaway/papers/ad.pdf).

From the abstract:

"When a message is transformed into a ciphertext in a way designed to protect both its
privacy and authenticity, there may be additional information, such as a packet header, that
travels alongside the ciphertext (at least conceptually) and must get authenticated with it. We
formalize and investigate this authenticated-encryption with associated-data (AEAD) problem."
