### ISSUE TITLE
Build Javascript library with rules_closure

### ISSUE THREAD

**Issue by thaidn** [google/tink#189]
Thread: https://groups.google.com/forum/#!topic/tink-users/fYwI0xeB6VA.

Tink for Javascript is a Closure library, we need to build it with https://github.com/bazelbuild/rules_closure. Last time we tried it didn't work, got the following errors:

```
So we narrowed it down to some of the Bazel/Maven imports in WORKSPACE having different versions from the ones in rules_closure. If we comment out args4j, com_google_auto_value and com_google_guava, we got a different error:

bazel build javascript/...
WARNING: /usr/local/google/home/thaidn/.cache/bazel/_bazel_thaidn/17efd31e20159bed504469bd5cc9767b/external/com_google_protobuf_java/WORKSPACE:1: Workspace name in /usr/local/google/home/thaidn/.cache/bazel/_bazel_thaidn/17efd31e20159bed504469bd5cc9767b/external/com_google_protobuf_java/WORKSPACE (@com_google_protobuf) does not match the name given in the repository's definition (@com_google_protobuf_java); this will cause a build error in future versions
INFO: Analysed 4 targets (59 packages loaded).
INFO: Found 4 targets...
ERROR: /usr/local/google/home/thaidn/.cache/bazel/_bazel_thaidn/17efd31e20159bed504469bd5cc9767b/external/io_bazel_rules_closure/java/com/google/javascript/jscomp/BUILD:17:1: Building external/io_bazel_rules_closure/java/com/google/javascript/jscomp/libjscomp.jar (14 source files) and running annotation processors (ComponentProcessor) failed (Exit 1)
error: cannot access Immutable
  class file for com.google.errorprone.annotations.Immutable not found
```

**Comment by thaidn** [comment]
The Javascript code is here: https://github.com/google/tink/tree/master/javascript. Veronika Slívová wrote most of the code.

Michael, I'm going to provide an initial BUILD.bazel file for you to work with.

**Comment by thaidn** [comment]
In https://github.com/google/tink/commit/e938df554d2efe4ceb11adfd15efeb81f7f25f05 I made it build correctly with closure_js_library in rules_closure! Now I'm going to see if I can run tests with closure_js_test.

We also need to figure out distribution, i.e., how to provide a NPM package or something.

**Comment by thaidn** [comment]
I ran into an issue.

I added these rules to javascript/BUILD.bazel

```
closure_js_library(
    name = "test_utils",
    testonly = 1,
    srcs = [
        "test_utils.js",
    ],
    deps = [
        "//proto:tink_closure_proto",
        "@io_bazel_rules_closure//closure/library",
    ],
)

closure_js_test(
    name = "test_lib",
    testonly = 1,
    srcs = glob([
        "*_test.js",
    ]),
    deps = [
        ":catalogue",
        ":cleartext_keyset_handle",
        ":test_utils",
        "//proto:aes_ctr_closure_proto",
        "//proto:aes_ctr_hmac_aead_closure_proto",
        "//proto:common_closure_proto",
        "//proto:config_closure_proto",
        "//proto:ecdsa_closure_proto",
        "//proto:ecies_aead_hkdf_closure_proto",
        "//proto:hmac_closure_proto",
        "//proto:tink_closure_proto",
        "@io_bazel_rules_closure//closure/library",
        "@io_bazel_rules_closure//closure/library/testing:asserts",
        "@io_bazel_rules_closure//closure/library/testing:jsunit",
        "@io_bazel_rules_closure//closure/library/testing:testsuite",
        "@io_bazel_rules_closure//closure/library/useragent",
        "@io_bazel_rules_closure//closure/protobuf:jspb",
    ],
)
```

and got this error

```shell
bazel build javascript/...
INFO: Analysed 78 targets (139 packages loaded, 2544 targets configured).
INFO: Found 78 targets...
ERROR: /usr/local/google/home/thaidn/.cache/bazel/_bazel_thaidn/7d6699ec815ad012ed8794fe6c3641cb/external/io_bazel_rules_closure/java/io/bazel/rules/closure/BUILD:37:1: Building external/io_bazel_rules_closure/java/io/bazel/rules/closure/libtarjan.jar (1 source file) failed (Exit 1)
external/io_bazel_rules_closure/java/io/bazel/rules/closure/Tarjan.java:119: error: cannot find symbol
      return new AutoValue_Tarjan_Result<>(result.build(), sorted.build());
                 ^
  symbol:   class AutoValue_Tarjan_Result
  location: class Finder<V>
  where V is a type-variable:
    V extends Object declared in class Finder
```

**Comment by michaelfig** [comment]
I will be working on this during the week.  I hope to have some results by next week.

**Comment by dslomov** [comment]
Looks like the com.google.auto.* defined in your WORKSPACE do not match what rules_closure want? https://github.com/bazelbuild/rules_closure/blob/master/closure/repositories.bzl#L225

**Comment by thaidn** [comment]
Yes, that's the issue we encountered when we tried last year.

Have you tried upgrade the version in WORKSPACE?

**Comment by dslomov** [comment]
> Have you tried upgrade the version in WORKSPACE?

You mean in rules_closure? I do not think I will have time to do this, but I'll merge patches.

**Comment by gkdn** [comment]
Your workspace is incorrectly setup. You are shadowing com_google_auto_value but you don't have java plugins setup for it hence the Java APTs are not running.
If you move closure_repositories to top of the file and remove your own definition of com_google_auto_value from your workspace, it should fix the problem.

**Comment by michaelfig** [comment]
With @gkdn's [#issuecomment-472158247](comment), my changes in #190 are getting closer to building and testing.

@thaidn, I wanted to ask if there are particular Closure flags/suppressions that need to be in place for the compile? 

I'm finding that while the build works to my satisfaction (modulo needing a patched version of `rules_closure` to support `entry_points` as a dict, and the Internal Compiler Error I came across), there are many compile errors, notably of the form:

```
javascript/subtle/elliptic_curves.js:505: ERROR - could not determine the type of this expression
  const privateKey = await window.crypto.subtle.importKey(
                     ^
  ProTip: "JSC_UNKNOWN_EXPR_TYPE" or "missingSourcesWarnings" or "reportUnknownTypes" can be added to the `suppress` attribute of:
  //javascript/subtle:subtle
  Alternatively /** @suppress {reportUnknownTypes} */ can be added to the source file.
```

there are others, but I lose them amongst the voluminous output.  I'll deal with these more obvious errors first.

Thanks,
Michael.

**Comment by thaidn** [comment]
>@thaidn, I wanted to ask if there are particular Closure flags/suppressions that need to be in place for the compile?

We didn't use any special flags or suppresions. It looks like the problem can be fixed by adding a type annotation. Let me try that first.

**Comment by michaelfig** [comment]
In #190, I turned on `lenient = True` and all the warnings went away.  Not sure if that's best, but I'm still hung up on the ICEs.

**Comment by michaelfig** [comment]
@thaidn, in #190 I have all the tests compiling and running (though several of them fail).  The ICE's were because I was misusing Bazel (`bazel test :*` instead of `bazel test :test_lib`).

- [x] Get library to compile
- [x] Get tests to compile and run
- [ ] Fix failing tests
- [ ] Add top level build rule to create compiled tink library
- [ ] Package with NPM
- [ ] Write example and docs

Am I missing anything?

**Comment by thaidn** [comment]
FYI: @taymonbeal has helped us publish a package, check out https://www.npmjs.com/package/tink-crypto.

**Comment by taymonbeal** [comment]
For the record, we're not using `rules_closure` (except as an intermediate build step to handle protos); we're using `rules_nodejs`, as the library has been ported to TypeScript.
