### ISSUE TITLE
C++ ONLY !?

### ISSUE THREAD

**Issue by pip010** [google/tink#193]
Is it possible to build C++ only lib using CMake under Windows ?
Failed to find any such instructions in the docs!

**Comment by mjrogozinski** [comment]
I have tried the same and could not find a CMake target for libtink.so. As far as I understand the CMake support is still in development and is good enough to develop tink, but not for building the final product.

What's more, tink uses absl, meaning using CMake alone could be tricky as a package-manager-like functionality is needed to install absl (or other deps) and build the tink itself. CMake does not do that by itself.

I might be wrong though.

**Comment by pip010** [comment]
CMake in combination with CPack adn CTest can do everything. It is super frustrating how many C++ projects still rely on self-baked build systems :( last one I adopted was botan, same issue :( CMake was only ment for developers :(

Thanks for the update!
