### ISSUE TITLE
Feature Request: Strongbox support on Android

### ISSUE THREAD

**Issue by TTransmit** [google/tink#195]
The AndroidKetsetManager is a very nice implementation that makes it easy to integrate good cryptography across multiple Android versions without handling the various API versions yourself. 

It would be nice if it could include the latest Android security options, specifically StrongBox Keymaster from Android 9. The ideal would be an implementation that updating tink  would give access to the strongest security protections an Android device can provide without needing to change the code calling tink. 

It could be really nice if this could also use the strongest cipher available on the device too.

**Comment by juergw** [comment]
There are currently no plans to add this. 

But what you can do instead is to use AndroidX's security MasterKey, which has the option to use strongbox:
https://developer.android.com/reference/androidx/security/crypto/MasterKey.Builder#setRequestStrongBoxBacked(boolean)

Creating a MasterKey will store it in android keystore, and you should be able to use it with AndroidKeysetManager,
using

withMasterKeyUri("android-keystore://" + masterKeyAlias);

where masterKeyAlias is the alias you used to create the MasterKey object.
