### ISSUE TITLE
Using TINKKeysetHandle.init(cleartextKeysetHandleWith:) in Swift

### ISSUE THREAD

**Issue by einarnot** [google/tink#200]
**Problem**
Im trying to call the `initCleartextKeysetHandleWithKeysetReader` function from my swift code. But in runtime, it crashes and logs: `initCleartextKeysetHandleWithKeysetReader:error:]: unrecognized selector sent to instance`

**Temporary fix:**
To fix this I modified the tink objective c code. My modification was to move the function from the interface in TINKKeysetHandle+Cleartext.h to TINKKeysetHandle.h. And the implementation from TINKKeysetHandle+Cleartext.mm to TINKKeysetHandle.mm. After doing this it workes perfectly.

**My questions**
- Do I need to configure Bazel or anything to make this function work as intented? (Without moving it from the Category and into the class implementation as described above)

- Is it because Im calling objective C code from Swift, that this problem occurs? Is there anything I can configure/do in my Project to make it work?

- Is this a bug in the Tink code, that should be fixed?

**My Swift code:**
```
private func decryptUsingAES(cipherText: Data, aesKey: Data) throws -> String? {
	do {
		let tinkAllConfig = try TINKAllConfig.init()
		try TINKConfig.register(tinkAllConfig)

		let reader = try TINKBinaryKeysetReader.init(serializedKeyset: aesKey)
		let handle = try TINKKeysetHandle.init(cleartextKeysetHandleWith: reader)
		let aead = try TINKAeadFactory.primitive(with: handle)

		let decryptedData = try aead.decrypt(cipherText, withAdditionalData: nil)

		return String.init(data: decryptedData, encoding: .utf8)
	} catch {
		throw DecryptPushMessageError.failedDecryptingMessage(message: error.localizedDescription)
	}
}
```

**Comment by tholenst** [comment]
Is this still an issue?

**Comment by tholenst** [comment]
I think this shouldn't be an issue anymore.
