### ISSUE TITLE
Provide C compatible interface to tink

### ISSUE THREAD

**Issue by afk11** [google/tink#202]
Tink is written in c++ which means it's not possible to use it in many languages without writing your own C compatible interface. I think the best place for such a wrapper is in the main tink code base. 

At the moment, I don't believe it'd be possible to call tink from a C or rust codebase, or languages like PHP which are written in C.

**Comment by stamster** [comment]
C compatible interface would be nice indeed - so even legacy Cobol could use it.

**Comment by tholenst** [comment]
This is a very good point, and I totally agree it would be great to provide a C compatible interface. Unfortunately, I don't see anyone on the team having the time to work on this at the moment. I think I would leave this open as a reminder, maybe at some point we can work on it.

I must say, my interest in legacy Cobol is rather limited though...

**Comment by tholenst** [comment]
I will close this. It would be good, but it's so far out of reach for the moment that there doesn't seem to be any use in keeping this open.
