### ISSUE TITLE
Inconsistent SHA256 macs

### ISSUE THREAD

**Issue by gridcellcoder** [google/tink#203]
I create a simple HMAC_SHA256_128BITTAG

```java 
KeysetHandle keysetHandle1 = KeysetHandle.generateNew(
                MacKeyTemplates.HMAC_SHA256_128BITTAG);
        // and write it to a file...
//        // encrypted with the this key in GCP KMS
       keysetHandle1.write(JsonKeysetWriter.withFile(new File("/tmp/file")),
                aead);
```

and I can extract the private key

```java
ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        CleartextKeysetHandle.write(keysetHandle, JsonKeysetWriter.withOutputStream(outputStream));
        String s = new String(outputStream.toByteArray());
        ObjectMapper mapper = new ObjectMapper();
        JsonNode jsonNode =
                mapper.readTree(s);
        JsonNode jsonNode1 = jsonNode.get("key").get(0).get("keyData").get("value");
        System.err.println(jsonNode1);
```
and `jsonNode1` is say `KEY FROM KEYSET HANDLE`

I use the standard Java SHA256

```
 String secret = "KEY FROM KEYSET HANDLE";
        String message = "message";

        javax.crypto.Mac sha256_HMAC = javax.crypto.Mac.getInstance("HMACSHA256");
        SecretKeySpec secret_key = new SecretKeySpec(secret.getBytes(), "HmacSHA256");
        sha256_HMAC.init(secret_key);
        byte[] bytes = sha256_HMAC.doFinal(message.getBytes());
        String hash = Base64.encodeBase64String(sha256_HMAC.doFinal(message.getBytes()));
        System.out.println(hash);
```
I read the Tink keyset back
```java
KeysetHandle keysetHandle = KeysetHandle.read(JsonKeysetReader.withFile
                (new File("/tmp/file")), aead);
Mac mac2 = MacFactory.getPrimitive(keysetHandle);
        byte[] MAC = mac2.computeMac("message".getBytes());        System.err.println(Base64.encodeBase64String(Base64.encodeBase64String(MAC).getBytes()));
        mac2.verifyMac(MAC,"message".getBytes());
```
but the hash from `hash` does not equal the hash from `MAC` i.e. tinks HMAC256 hash does not match the one from basic `HMACSHA256` is there something I'm missing here or does tink use a different algorithm/implementation for HMACSHA26?

**Comment by gridcellcoder** [comment]
Using 
```
<dependency>
            <groupId>com.google.crypto.tink</groupId>
            <artifactId>tink</artifactId>
            <version>1.2.2</version>
        </dependency>
```

**Comment by thaidn** [comment]
Hi there,

Tink outputs key_id + mac_tag. key_id is a hint that allows Tink to know which key it should use for verification.

**Comment by gridcellcoder** [comment]
Hi @thaidn thanks for the input.

I'm trying to recreate the Tink output with the Java one and don't seem to be working. I don't know to to replicate ` key_id + mac_tag` is this string or byte array concatenation?

Maybe its not necessary, basically I want to use Tink to verify the MAC sent by a javascript client. E.g. the web client has a `nonce`, `secret` and `message` I want to compute mac in javascript (at present using something like
```
 var hash = CryptoJS.HmacSHA256("message+nonce", "secret");
  var hashInBase64 = CryptoJS.enc.Base64.stringify(hash);
  document.write(hashInBase64);
```
and then verify that on the server side using Tink. But as tink hash is key_id+mac_tag so the 2 do not match.

However I am also aware that tink is available in JS but not yet as a GA? In the example above how do I 1) get Tink to verify the hash from cyrptoJS
2) replace cryptoJS with tink JS (any examples of this?)

With thanks

**Comment by gridcellcoder** [comment]
Hi can anyone please help with an example (or let us know if it's possible )of using Tink Java to verify a HmacSHA256 produced by JS (either CryptoJS or TinkJS)? otherwise can close this issue?

**Comment by thaidn** [comment]
(Cleaning up old tickets)

Please circle back if this is still an issue.
