### ISSUE TITLE
Key construction in Tink for KeysetHandle

### ISSUE THREAD

**Issue by UrsaEli** [google/tink#212]
The following lines show how to generate a key in Tink:

> keysetHandle=KeysetHandle.generateNew(AeadKeyTemplates.AES128_GCM)
> privateKeysetHandle = KeysetHandle.generateNew(SignatureKeyTemplates.ECDSA_P256)

Could you show on how to construct a key given the parameters such as key bytes and related parameters?

It is also possible to create a key by loading the parameters from JSON:

>   String keysetFilename = "my_keyset.json";
>   KeysetHandle keysetHandle = CleartextKeysetHandle.read(
>           JsonKeysetReader.withFile(new File(keysetFilename)));

How is the key format in JSON defined?
Thanks.

**Comment by prfcttone2** [comment]
Okay

**Comment by UrsaEli** [comment]
e.g. 

aes gcm 128:  (18 bytes) in json file, is AAD: just 2 bytes? (usually it is 0 and 2^64 bits)
aes gcm 256: # (34 bytes) in json file, is AAD: just 2 bytes? (usually it is 0 and 2^64 bits)
AES256_CTR_HMAC_SHA256: # (82 bytes) in json file

• 82 - 32 (aes ctr key length) = 48 bytes
• HMACSHA256 can be any key length, usually it is 64 bytes, and usually it is not the same key for the ciphering, but 48 bytes were left from the previous

How about RSA and ECC?

**Comment by thaidn** [comment]
@UrsaEli I believe you have existing keys and you want to use them with Tink. Is that correct?

Internally Tink stores keys and keysets in protocol buffers [1]. To load your keys with Tink, you want to add a KeysetReader [2]. For example, [3] shows how we convert keys in PEM format to Tink.

[1] https://github.com/google/tink/blob/master/proto/tink.proto
[2] https://github.com/google/tink/blob/master/java/src/main/java/com/google/crypto/tink/KeysetReader.java
[3] https://github.com/google/tink/blob/master/java/src/main/java/com/google/crypto/tink/signature/SignaturePemKeysetReader.java

**Comment by UrsaEli** [comment]
@thaidn yes, could we have simple usage sample codes to demonstrate how to load keys for aes gcm, rsa, dsa, and hmac?

**Comment by UrsaEli** [comment]
One of the comments on an open issue ‘Key construction in Tink for KeysetHandle #212’ provided links to specific files on how to convert keys in PEM format to tink. Turns out the version is different from the one we are using. We currently are using tink 1.2 and it doesn’t have com.google.crypto.tink.signature.SignaturePemKeysetReader. Is there an alternative?

**Comment by thaidn** [comment]
Hi UrsaEli, com.google.crypto.tink.signature.SignaturePemKeysetReader is included in release 1.3.0-RC1.
