### ISSUE TITLE
Analysis of target '//cc:libtink.so' failed

### ISSUE THREAD

**Issue by coder579** [google/tink#213]
This seems to be a quite common error as I can see this in several previous issues as well like #134, although I am using Linux Ubuntu machine. Can someone tell the exact steps that I need to follow in order to get this setup running as I am not able to figure it out otherwise.

**Comment by przydatek** [comment]
Hi Shubham,

could you please provide more info on  the issue, like which command failed and what was the log output?  (the issue #134 was resolved by #151)
Thanks!

**Comment by thaidn** [comment]
@coder579 please reopen if you can provide more info as @przydatek suggested. Thanks!
