### ISSUE TITLE
[Golang] Replace `log.Fata` with `log.Fatal`

### ISSUE THREAD

**Issue by DazWilkin** [google/tink#217]
5 occurrences of `log.Fata` should be `log.Fatal`
https://github.com/google/tink/blob/master/docs/GOLANG-HOWTO.md

Was heartened to see relevant and straightforward samples but these contain other code errors.

Will file issues for those as I fix them.

**Comment by przydatek** [comment]
Done in https://github.com/google/tink/commit/61213e175268462931b142043129e5d134ab5cc8, thanks!
