### ISSUE TITLE
[Golang] Envelope encryption sample has errors

### ISSUE THREAD

**Issue by DazWilkin** [google/tink#218]
https://github.com/google/tink/blob/master/docs/GOLANG-HOWTO.md#envelope-encryption

Replace:
```golang
gcpclient := gcpkms.NewGCPClient(keyURI)
```
With:
```golang
gcpclient, err := gcpkms.NewGCPClient(keyURI)
if err != nil {
	log.Fatal(err)
}
```
And then, because `err` exists:
```golang
_, err = gcpclient.LoadCredentials(credentialsPath)
```
I think it would be helpful to point the developer to the documentation that explains the URIs for the [Key Management Systems](https://github.com/google/tink/blob/master/docs/KEY-MANAGEMENT.md#key-management-systems) (and, while we're at it, the [Credentials](https://github.com/google/tink/blob/master/docs/KEY-MANAGEMENT.md#key-management-systems) too).

Since the sample uses Cloud KMS, perhaps:
```golang
keyURI := fmt.Sprintf(
    "gcp-kms://projects/%s/locations/%s/keyRings/%s/cryptoKeys/%s",
    project, location, keyring, key)
```

IIUC the service account (credentials) will need at least `roles/cloudkms.cryptoKeyEncrypterDecrypter` ([list](https://cloud.google.com/kms/docs/reference/permissions-and-roles)) for the sample to run. It would be helpful to provide this context.

See also https://github.com/google/tink/issues/217

**Comment by przydatek** [comment]
Done in https://github.com/google/tink/commit/61213e175268462931b142043129e5d134ab5cc8, thanks!
