### ISSUE TITLE
How to encrypt in a client side (Android) and decrypt in a server side (PHP) with "tink"

### ISSUE THREAD

**Issue by PankajSavaliya** [google/tink#225]
I have used this [demo](https://github.com/google/tink/tree/master/examples/helloworld/android) for the android side. 

In my case, I want to set this encrypt and decrypt process in the REST API. if someone has API  through the reverse process(decompile) of apk and call this API anyhow so I want to secure this process through this Tink.

**Comment by thaidn** [comment]
I'm sorry, but Tink doesn't support Tink at the moment. There was a community effort to port Tink to PHP, but it seems that it's stalled.
