### ISSUE TITLE
[android] Support for encryption of symmetric master key  on Android L and earlier?

### ISSUE THREAD

**Issue by alapshin** [google/tink#226]
This question is followup to a second point from issue https://issuetracker.google.com/issues/132325342#comment3 regarding new android-security library which uses tink under the hood for key management/encryption.

According to documentation in [AndroidKeysetManager](https://github.com/google/tink/blob/master/java/src/main/java/com/google/crypto/tink/integration/android/AndroidKeysetManager.java) on devices with Android L and earlier master key is stored in shared preferences unencrypted. Which if I understand correctly makes overall security only as strong as ordinary shared preferences. If someone has access to internal storage then one can extract key from shared preferences file and decrypt data.

There is a workaround for storing symmetric key in encrypted form on Android L and earlier. It comes down to generating symmetric key using different provider (BouncyCastle)  and then wrapping it with private part of asymmetric key. Asymmetric key in turn is stored in Android Keystore (asymmetric keys are supported from API 19). Encrypted symmetric key is then written to file on internal storage.

This is example of such workaround using Kotlin https://gist.github.com/alapshin/c82a87d30c4a0cc3015381c454e0ebf2

Would you consider adding something similar to tink's implementation of `AndroidKeysetManager` or such change is it out of scope?

**Comment by z0mbie42** [comment]
Hi,

I would also love to see this implemented.

According to https://developer.android.com/about/dashboards there is ~22% of devices don't have access to secure encryption keys storage because of this deficiency.

So to recapitulate:

* Add support for Keyset encryption on Android > 18 and < 23 By using RSA (https://developer.android.com/training/articles/keystore#SupportedCiphers) which Key will be stored in Android Keystore and is used to encrypt an AES key which will encrypt the Keyset.

* Handle migration when a device is updated.

I know it's far from optimal, but it's better than plaintext keys in shared preferences.

**Comment by thaidn** [comment]
Thanks. Yeah we chatted about this internally and agreed that we should use RSA in Android Keystore when it is available.

**Comment by piotr-pawlowski** [comment]
> I'll see what I can do.

Hi,
is there any progress?

**Comment by thaidn** [comment]
I'm working on this, will have something by the end of this month.

**Comment by AfzalivE** [comment]
Any updates on this?

Thanks

**Comment by thaidn** [comment]
I hit an unexpected wall. The maintainer of Android Keystore said that the key generation APIs on Android L or earlier were broken and deprecated. They recommend not using them.

I ran out of ideas. Any suggestions are welcome and appreciated.

**Comment by AfzalivE** [comment]
> I hit an unexpected wall. The maintainer of Android Keystore said that the key generation APIs on Android L or earlier were broken and deprecated. They recommend not using them.
> 
> I ran out of ideas. Any suggestions are welcome and appreciated.

I mean yes, they're deprecated but only for newer platforms.

The maintainer is very correct though. In my own testing that I did on 9 versions of Android (4 through 9), version 4.x had issues where if the user changed the Security method (PIN to Pattern or something), the keystore clears itself. So definitely cannot support KitKat.

On Android 5.x (on Xiaomi Redmi no less), everything seemed fine with RSA.

I believe for API 21 and 22, you can use this method. Below that, definitely not.

Don't know if this helps but this was my test matrix.

From -> To | Swipe | Pattern | PIN | Password
-- | -- | -- | -- | --
Swipe | X | OK |   |  
Pattern | OK | X | OK |  
PIN |   | OK | X | OK
Password | OK |   | OK | X

**Comment by thaidn** [comment]
Thanks @AfzalivE. It seems that even on API 21 and 22, the master keys might easily be corrupted.

I think we'll have to accept the fact that there is no good option in Android below 23.

I'm so sorry.

Please reopen if you have suggestions.

**Comment by AfzalivE** [comment]
Thanks for trying @thaidn 

Would be useful if there's a way for us to provide custom compatibility if we want to on these versions, through extending something.
