### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by tjstone14** [google/tink#228]
Apple is fully embracing Swift Package Manager in Xcode 11.  The feature will be integrated into the IDE and allow for managing external packages and dependencies.  It is also now supported on all platforms (iOS, etc.).

Is there any plan to add this feature?

**Comment by thaidn** [comment]
@tl0gic what do you think?

**Comment by thaidn** [comment]
Closing this up, as we don't have any plan for it atm.
