### ISSUE TITLE
go get

### ISSUE THREAD

**Issue by tsingson** [google/tink#234]
go version 1.12.7
OS macOS  10.14

error: can't load  github.com/google/tink/go/keyset
```
build github.com/tsingson/vk/test-example/tinktest: cannot load github.com/google/tink/go/keyset: cannot find module providing package github.com/google/tink/go/keyset
```

**Comment by thaidn** [comment]
@tl0gic could you please take a look? This is similar to https://github.com/google/tink/issues/215#issuecomment-514360901.

**Comment by tl0gic** [comment]
Can you give me an example repository and the commands you typed so I can reproduce it?

When I try locally to fetch all the go modules I can't get the error you mentioned above.

**Comment by tl0gic** [comment]
Also which version of tink are you using? master or one of the releases?

**Comment by ericbock** [comment]
When you `go build` in a project using modules, it's writing `github.com/google/tink v1.2.2` into go.mod. That fails with the error above. If you modify go.mod to reference `github.com/google/tink v1.3.0-rc1` it'll build.

**Comment by tsingson** [comment]
@ericbock  cool, it's work.  great job.
