### ISSUE TITLE
How to store AesGcmJce

### ISSUE THREAD

**Issue by maxglu** [google/tink#237]
Hi! Please, provide more documentation about storing custom AEAD.
I use AesGcmJce, because I need create key from user entered pin-code, but I really do not understand how I can store my key in Android KeyStore, and use it to decrypt data in future.

Or maybe I should generate same key by pin-code? At this time I do not understand how I can do it. Under hood AesGcmJce generate new IV every time, and keys do not match.

**Comment by przydatek** [comment]
Hi, not sure I understand what you're trying to achieve, can you elaborate?
To access/use Android Keystore with Tink, take a look at code in https://github.com/google/tink/tree/master/java/src/main/java/com/google/crypto/tink/integration/android like https://github.com/google/tink/blob/master/java/src/main/java/com/google/crypto/tink/integration/android/AndroidKeystoreAesGcm.java or https://github.com/google/tink/blob/master/java/src/main/java/com/google/crypto/tink/integration/android/AndroidKeysetManager.java

**Comment by przydatek** [comment]
(please reopen if you have further questions)
