### ISSUE TITLE
Publish Encrypt and Sign public key

### ISSUE THREAD

**Issue by AdrianChallinorOsiris** [google/tink#239]
I would like to be able to extract the public key for a signature and encryption operation so that I can exchange it with other parties. Unfortunately the tink classes are not serialisable. The initail idea would be to extract just the public key as a json object so that it can be sent over a REST call to another party. 

I could write it to a file, but that seems an unnecessary step and overly complex.

**Comment by przydatek** [comment]
For exporting public keys one can use KeysetHandle.writeNoSecret(writer), where writer could be a JsonKeysetWriter, that writes an output stream (that can be in-memory).  The receiving party would then use KeysetHandle.readNoSecret(reader) with a JsonKeysetReader.  This flow does serialize the keysets though, and currently we don't offer API that provides json objects.
For persisting secret keys one can use a CleartextKeysetHandle.
Please reopen if this doesn't solve the problem.
