### ISSUE TITLE
missing com.google.crypto.tink.integration.awskms.AwsKmsClient in version 1.3.0-rc1

### ISSUE THREAD

**Issue by papug145** [google/tink#240]
Hi guys, i try to use following snippet from your documentation page but there is no AwsKmsClient, nor integration package at all in most recent version: 

KeysetHandle keysetHandle = KeysetHandle.read(
        JsonKeysetReader.withFile(new File(keysetFilename)),
        new AwsKmsClient().getAead(masterKeyUri));

What is the substitute? Could you please provide equivalent?

**Comment by przydatek** [comment]
Since 1.3.0.-rc1 the support for AWS/GCP KMS is in separate packages, see https://repo1.maven.org/maven2/com/google/crypto/tink/, so e.g. to use AWS KMS one should add also add dependency on tink-awskms.  Please re-open if it doesn't work for you.
