### ISSUE TITLE
GcpKmsClient does not provide a public method of creating the client with provided Credentials

### ISSUE THREAD

**Issue by tahasabih** [google/tink#241]
Currently the GcpKmsClient can only be creating by using default credentials or providing a path of the credentials json. There is no way of using existing an GoogleCredentials object to instantiate the client. We have the credentials json as a string in the environment variable, and it is possible to create a GoogleCredentials object from that but we can't instantiate a GcpKmsClient with that.

**Comment by przydatek** [comment]
This has been resolved in #244.
