### ISSUE TITLE
Insecure Mode of Operation

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/tink#246]
https://github.com/google/tink/blob/040358275e99d47cace38d2dbd3e2885bedd62cf/java/src/main/java/com/google/crypto/tink/subtle/AesEaxJce.java#L69
https://github.com/google/tink/blob/040358275e99d47cace38d2dbd3e2885bedd62cf/java/src/main/java/com/google/crypto/tink/subtle/AesEaxJce.java#L172
https://github.com/google/tink/blob/040358275e99d47cace38d2dbd3e2885bedd62cf/java/src/main/java/com/google/crypto/tink/subtle/AesEaxJce.java#L199
ECB mode is inherently weak, as it results in the same ciphertext for identical blocks of plain text. CBC mode is the superior choice as it does not have this weakness.

**Comment by przydatek** [comment]
Hello,

you're right about weaknesses of ECB for general encryption, but in this context (AES-EAX) ECB is just a block cipher needed to compute CBC-MAC, which is used for computation of OMAC (see https://web.cs.ucdavis.edu/~rogaway/papers/eax.pdf), so there is no weakness here.

Cheers,

- Bartosz.
