### ISSUE TITLE
Does this javascript version provide to decrypt google pay payment token?

### ISSUE THREAD

**Issue by st931630** [google/tink#247]

**Comment by thaidn** [comment]
No, it doesn't.

Do you want to use it with NodeJS?

**Comment by st931630** [comment]
Yes, I want to use it with Node.js.
Thank you for your reply.

**Comment by hrc95** [comment]
I see August 2019 in the roadmap for Javascript support -- is there an updated expected date for that release? I saw in other comments that Python may be supported by November but didn't see anything regarding Javascript. Any updated info you have would be helpful!

**Comment by thxmike** [comment]
Is there an npm package that can be used? If not, is there a process to download and build the library for consumption in a nodejs application?

**Comment by thaidn** [comment]
Unfortunately we have no plan to support Google PMT in Javascript.
