### ISSUE TITLE
Google pay payment token decrypt with Jave "cannot verify signature"

### ISSUE THREAD

**Issue by st931630** [google/tink#249]
I use three method to add sender verifying key from Google root signing keys test link, however it still error for "cannot verify signature".  And I used TEST environment to try google pay.  Which part don't I notice it? Thanks.

> java.security.GeneralSecurityException: cannot verify signature

`  String decryptedMessage =
                new PaymentMethodTokenRecipient.Builder()
                        .fetchSenderVerifyingKeysWith(GooglePaymentsPublicKeysManager.INSTANCE_TEST)
//                        .addSenderVerifyingKey(senderVerifyingKey)    // verify signature public key string
//                        .senderVerifyingKeys(senderVerifyingKeyJson)    // verify signature public key json
                        .recipientId("merchant:01234567890123456789")   // 12345678901234567890
                        // This guide applies only to protocolVersion = ECv2
                        .protocolVersion("ECv2")
                        // Multiple private keys can be added to support graceful
                        // key rotations.
                        .addRecipientPrivateKey(recipientPrivateKey)
                        .addRecipientPrivateKey(recipientPrivateKey)
                        .build()
                        .unseal(ciphertext);

        System.out.println(decryptedMessage);
    }`

**Comment by freygriff** [comment]
Freya Griffin

**Comment by st931630** [comment]
I find my problem for wrong test sender verify key.
Additionally, the merchant id is 01234567890123456789 for test environment.

**Comment by qualwebs** [comment]
> 01234567890123456789

Hey @st931630 I'm facing the same issue, I'm using google's test ECv2 keys as sender Key
https://payments.developers.google.com/paymentmethodtoken/test/keys.json

And the merchant I tried both, 01234567890123456789 and generated my merchant.

Can you please help?

**Comment by st931630** [comment]
> > 01234567890123456789
> 
> Hey @st931630 I'm facing the same issue, I'm using google's test ECv2 keys as sender Key
> https://payments.developers.google.com/paymentmethodtoken/test/keys.json
> 
> And the merchant I tried both, 01234567890123456789 and generated my merchant.
> 
> Can you please help?

I used this method to get google verify signature.
`Verify signature
The tokens produced in ENVIRONMENT_TEST are encrypted with your test public key that was previously sent to Google.

The tokens are signed with Google's test keys. If you use Tink, ensure that .fetchSenderVerifyingKeysWith(GooglePaymentsPublicKeysManager.INSTANCE_TEST) is set when you build a PaymentMethodTokenRecipient object.`
reference:
https://developers.google.com/pay/api/android/guides/resources/sample-tokens#verify-signature

And merchant id for test environment is '12345678901234567890'.

*Notice: If you complete a DIRECT tokenizationSpecification type integration, you must annually rotate your public encryption key and provide PCI Attestation to Google via the Business Console. 
So I used GATEWAY type integration, and I don't use Tink to decrypt payment data by myself.

**Comment by dshivrin** [comment]
I had similiar exeption.
 I'm using [C# wrapper ](https://github.com/google-pay/payment-data-cryptography-dotnet) for tink and this is how my code looks like. 



              private const string _paymentSampleToken = "{\"signature\":your_payment_sample_token...}";
              var keyProvider = new GooglePay.PaymentDataCryptography.GoogleKeyProvider(true);//true = test env
              var parser = new GooglePay.PaymentDataCryptography.PaymentMethodTokenRecipient("gateway:your_gateway_name", keyProvider);

              //loading pem key 
              AsymmetricCipherKeyPair keyPair;
              var path = $"path to your key.pem file"
              using (var reader = File.OpenText(path)) // file containing RSA PKCS1 private key
                  keyPair = (AsymmetricCipherKeyPair)new PemReader(reader).ReadObject();

              parser.AddPrivateKey((ECPrivateKeyParameters)keyPair.Private);
              string decryptedMessage = parser.Unseal(_paymentSampleToken);
              Console.WriteLine(decryptedMessage);

**Comment by shailyshahtrx** [comment]
> I had similiar exeption. I'm using [C# wrapper ](https://github.com/google-pay/payment-data-cryptography-dotnet) for tink and this is how my code looks like.
> 
> ```
>           private const string _paymentSampleToken = "{\"signature\":your_payment_sample_token...}";
>           var keyProvider = new GooglePay.PaymentDataCryptography.GoogleKeyProvider(true);//true = test env
>           var parser = new GooglePay.PaymentDataCryptography.PaymentMethodTokenRecipient("gateway:your_gateway_name", keyProvider);
> 
>           //loading pem key 
>           AsymmetricCipherKeyPair keyPair;
>           var path = $"path to your key.pem file"
>           using (var reader = File.OpenText(path)) // file containing RSA PKCS1 private key
>               keyPair = (AsymmetricCipherKeyPair)new PemReader(reader).ReadObject();
> 
>           parser.AddPrivateKey((ECPrivateKeyParameters)keyPair.Private);
>           string decryptedMessage = parser.Unseal(_paymentSampleToken);
>           Console.WriteLine(decryptedMessage);
> ```

Hi - I have the same error,  Are there any updates on how you have resolved the issue?
