### ISSUE TITLE
Google pay payment data decrypt with Java "cannot decrypt"

### ISSUE THREAD

**Issue by st931630** [google/tink#254]
I use DIRECT method integration and TEST environment for google pay in the app.
I use OpenSSL to generate a pair of public key and private key.
The public key puts in DIRECT method to encrypt payment data and the private key decrypts payment data with Tink library(java version).
As stated before, I can get a payment data from my app; however, I can’t use the private key to decrypt the payment data.
How can I solve this problem ? Thanks.

This's error code:
> java.security.GeneralSecurityException: cannot decrypt

`      String recipientPrivateKey = my_private_key;
        String ciphertext = my_payment_data;

        GooglePaymentsPublicKeysManager.INSTANCE_TEST.refreshInBackground();

        String decryptedMessage =
                new PaymentMethodTokenRecipient.Builder()
        .fetchSenderVerifyingKeysWith(GooglePaymentsPublicKeysManager.INSTANCE_TEST)
                        .recipientId("merchant:12345678901234567890")
                        // This guide applies only to protocolVersion = ECv2
                        .protocolVersion("ECv2")
                        // Multiple private keys can be added to support graceful
                        // key rotations.
                        .addRecipientPrivateKey(recipientPrivateKey)
                        .addRecipientPrivateKey(recipientPrivateKey)
                        .build()
                        .unseal(ciphertext);`

**Comment by st931630** [comment]
> I use DIRECT method integration and TEST environment for google pay in the app.
> I use OpenSSL to generate a pair of public key and private key.
> The public key puts in DIRECT method to encrypt payment data and the private key decrypts payment data with Tink library(java version).
> As stated before, I can get a payment data from my app; however, I can’t use the private key to decrypt the payment data.
> How can I solve this problem ? Thanks.
> 
> This's error code:
> 
> > java.security.GeneralSecurityException: cannot decrypt
> 
> ` String recipientPrivateKey = my_private_key;
> String ciphertext = my_payment_data;
> 
> ```
>     GooglePaymentsPublicKeysManager.INSTANCE_TEST.refreshInBackground();
> 
>     String decryptedMessage =
>             new PaymentMethodTokenRecipient.Builder()
>     .fetchSenderVerifyingKeysWith(GooglePaymentsPublicKeysManager.INSTANCE_TEST)
>                     .recipientId("merchant:12345678901234567890")
>                     // This guide applies only to protocolVersion = ECv2
>                     .protocolVersion("ECv2")
>                     // Multiple private keys can be added to support graceful
>                     // key rotations.
>                     .addRecipientPrivateKey(recipientPrivateKey)
>                     .addRecipientPrivateKey(recipientPrivateKey)
>                     .build()
>                     .unseal(ciphertext);`
> ```


I can decrypt payment data with protocolVersion is ECv1 but I can't use ECv2 to decrypt.
Does anyone know why? Thanks.

**Comment by thaidn** [comment]
(cleaning up old tickets)

Please circle back if this is still an issue.

**Comment by sarahrobinson96** [comment]
I'm having the same issue as the above poster. Any ideas?

   public static void main(String[] args) throws Exception {
        GooglePaymentsPublicKeysManager.INSTANCE_TEST.refreshInBackground();
        String sEncryptText = new String(Files.readAllBytes(Paths.get("/path/to/file")), "ISO-8859-1");
        try {
            String decryptedMessage = 
            new PaymentMethodTokenRecipient.Builder()
            .fetchSenderVerifyingKeysWith(GooglePaymentsPublicKeysManager.INSTANCE_TEST)
            .recipientId("gateway:tabapay")
            // This guide applies only to protocolVersion = ECv2
            .protocolVersion("ECv2")
            // Multiple private keys can be added to support graceful
            // key rotations.
            .addRecipientPrivateKey(sPrivateKeyString)
            .build()
            .unseal(new String(sEncryptText));
            System.out.println(decryptedMessage);
        } catch(GeneralSecurityException e) {
            System.out.println(e.getLocalizedMessage());
            return;
        }
    }

**Comment by vamshi-finix** [comment]
I have a similar issue as well. My payload is 
`tokenizationSpecification: {
                type: 'DIRECT',
                  parameters: {
                      protocolVersion: 'ECv2',
                      publicKey: 'public-key-from-openssl-command',
                  },
              },
            },
          ],
          merchantInfo: {
            merchantId: '012345678901234567890',
            merchantName: 'Merchant_name-On-Dashboard',
          }`

My Java code is 
` new Builder()
        .fetchSenderVerifyingKeysWith(GooglePaymentsPublicKeysManager.INSTANCE_TEST)
        .recipientId("merchant:01234567890123456789")
        .protocolVersion("ECv2")
        .addRecipientPrivateKey("private-key-generated-with-openssl")
        .build()
        .unseal("payment-token-received-from-google-pay");`

Why am I unable to verify the signature? The stacktrace is 
`Exception in thread "main" java.security.GeneralSecurityException: cannot verify signature
	at com.google.crypto.tink.apps.paymentmethodtoken.PaymentMethodTokenRecipient.verify(PaymentMethodTokenRecipient.java:461)
	at com.google.crypto.tink.apps.paymentmethodtoken.PaymentMethodTokenRecipient.verifyECV2(PaymentMethodTokenRecipient.java:399)
	at com.google.crypto.tink.apps.paymentmethodtoken.PaymentMethodTokenRecipient.unsealECV2(PaymentMethodTokenRecipient.java:365)
	at com.google.crypto.tink.apps.paymentmethodtoken.PaymentMethodTokenRecipient.unseal(PaymentMethodTokenRecipient.java:342)`

**Comment by sarahrobinson96** [comment]
What editor/IDE are you using? I couldn’t get this to work using VSCode (or Visual Studio). Once I switched to Eclipse, it worked—didn’t change one thing about the code. Very strange.

**Comment by vamshi-finix** [comment]
It's funny, I figured the mistake right after I posted. I was using incorrect test merchantID. The correct value is `.recipientId("merchant:12345678901234567890")` in Java code. I am using IntelliJ for Java and webstorm for the react app, btw.

**Comment by sarahrobinson96** [comment]
Yeah, I went through every single character (literally!) and nothing proved to be wrong. It was so strange. I literally copied and pasted my code from one editor to another and it worked!

**Comment by ashwinigiri** [comment]
Hi @st931630, if possible could you post your exact code that fixed this issue. I am facing the same issue and I tried everything but still not able to solve it.
