### ISSUE TITLE
WebPushHybridDecrypt doesn't support padding

### ISSUE THREAD

**Issue by Boehrsi** [google/tink#256]
First of all thanks for this library, it reduces the efforts required to get the actual encryption / decryption stuff running a lot!

While using com.google.crypto.tink:apps-webpush / https://github.com/google/tink/tree/master/apps/webpush we discovered a problem with the decryption. WebPushHybridDecrypt (https://github.com/google/tink/blob/master/apps/webpush/src/main/java/com/google/crypto/tink/apps/webpush/WebPushHybridDecrypt.java#L261) prohibits any kind of padding, which in our understanding is allowed by the RFC (https://tools.ietf.org/html/rfc8291#section-4). Is this intentionally or is this a bug? The check for 0x2 is valid but padding (0x0) appended to the plain text should be also fine, or are we wrong?

**Example:**
Works:
`abcd1234<0x2>`
Doesn't work:
`abcd1234<0x2><0x0><0x0><0x0><0x0>`

**Comment by thaidn** [comment]
This looks like a bug to me.

Can you send us a PR to fix this?

**Comment by Boehrsi** [comment]
I'm actually not really experienced in encryption / decryption stuff, but I will have a look and will try to provide a simple, but valid fix.

**Comment by Boehrsi** [comment]
Closing this issue, as it was fixed by https://github.com/google/tink/pull/397
