### ISSUE TITLE
[Question] How to build tink-android module as an independent aar/jar

### ISSUE THREAD

**Issue by tuancoltech** [google/tink#257]
So I've been searching for the guidelines on how to build `tink-android` module as an independent aar/jar so that I can include it as local library in another of my project.
However I could not find a specific guide. I'm new to `bazel` too.

Can you please shed me some light?
Thanks a lot

**Comment by thaidn** [comment]
You can find the jars of the latest version on Maven Central: https://search.maven.org/search?q=g:com.google.crypto.tink%20AND%20a:tink-android&core=gav.

You can also compile with Gradle, see https://github.com/google/tink/blob/master/docs/JAVA-HOWTO.md#gradle.

Please reopen if you need additional help.

**Comment by tuancoltech** [comment]
@thaidn Thanks for your response.
I think I'm not able to re-open this issue, so please do it for me if you can.

My purpose is to **rebuild** the `tink-android.jar` against `protobuf-java` to use in my project. So I guess the prebuilt jars do not help, since they were built against `protobuf-lite`  (?)
What I currently do is as below:

<img width="1377" alt="Screen Shot 2019-10-03 at 11 36 35 PM" src="https://user-images.githubusercontent.com/4281969/66146613-524eda80-e637-11e9-9973-c3dbf1827601.png">

Then I just do a `bazel build tink-android`.

However, it seems there are still missing classes from protobuf (For instance: `GeneratedMessageV3`) when I import the output `tink-android.jar`, which I just build myself, into another project.

Hence, what I'm looking for help is how I can rebuild `tink-android.jar` against `protobuf-java` in a correct way.

Thanks in advance.

**Comment by thaidn** [comment]
Do you want to run Tink on Android or server side apps?

If Android, you want to use tink-android, and it only works with protobuf-lite. Otherwise you want to use tink.

Now if you want to build Tink with Bazel, take a look at these examples: https://github.com/thaidn/tink-examples. I haven't updated them in a while, let me know if you encounter any issue. You should also check out how we define the protobuf dependencies in our [WORKSPACE](https://github.com/google/tink/blob/master/WORKSPACE).

**Comment by tuancoltech** [comment]
> Do you want to run Tink on Android or server side apps?
> 
> If Android, you want to use tink-android, and it only works with protobuf-lite. Otherwise you want to use tink.
> 
> Now if you want to build Tink with Bazel, take a look at these examples: https://github.com/thaidn/tink-examples. I haven't updated them in a while, let me know if you encounter any issue. You should also check out how we define the protobuf dependencies in our [WORKSPACE](https://github.com/google/tink/blob/master/WORKSPACE).

I want to run Tink on Android.

The reason for rebuilding Tink against `protobuf-java` (and run in Android) is that, the original `tink-android.jar` is having a class conflict with another lib, which was built against `protobuf-java`, in our project.

The detailed error is as below
`Program type already present: com.google.protobuf.ByteString$ByteIterator`

This is the dependency tree of the 2 above-mentioned libs in our project

<img width="505" alt="Screen Shot 2019-10-06 at 11 46 17 AM" src="https://user-images.githubusercontent.com/4281969/66264411-09fa0d00-e82f-11e9-8d33-63cf709fe7d5.png">
<img width="425" alt="Screen Shot 2019-10-06 at 11 46 28 AM" src="https://user-images.githubusercontent.com/4281969/66264412-0a92a380-e82f-11e9-8c3a-6e8973fdb1f2.png">

As you can see, one is using` protobuf-java`, another one is using `protobuf-lite`, which I believe is the cause of such conflict.

Therefore, I want to know if I'm able to rebuild **Tink** with `protobuf-java`, if yes then what I should do.
I'm expecting that the conflict will be resolved if this build is possible.

**Comment by tholenst** [comment]
We don't really support this at the moment (and I'd prefer somewhat if we don't). The reason is that things are already complicated as is, and AFAIU the general idea is that one should use protobuf-lite on Android.

That being said, you can in principle patch the BUILD.bazel files. For example, you can replace all java_lite_proto_library targets in proto/BUILD.bazel with java_library_targets.

**Comment by tuancoltech** [comment]
> We don't really support this at the moment (and I'd prefer somewhat if we don't). The reason is that things are already complicated as is, and AFAIU the general idea is that one should use protobuf-lite on Android.
> 
> That being said, you can in principle patch the BUILD.bazel files. For example, you can replace all java_lite_proto_library targets in proto/BUILD.bazel with java_library_targets.

I see. Yeah the build process seems to be very complicated to me if I need to customize it to use protobuf-java, that's why I came here.

I'll see if there's other possible solution around and get back if there's further inquiry.

Thanks a lot.

**Comment by thaidn** [comment]
Tuan,

Someone reported a potential solution here: https://github.com/google/tink/issues/282.

**Comment by tuancoltech** [comment]
> Tuan,
> 
> Someone reported a potential solution here: #282.

Awesome. Thanks a lot.
