### ISSUE TITLE
Are there plans to support streaming AEAD in golang?

### ISSUE THREAD

**Issue by challarao** [google/tink#258]
Background: I'm looking to find something that can encrypt large files(or streams) without having to put everything in memory.

Interoperability is a big factor in choosing the right library for cryptographic work loads. I found Tink very positive.

I've not found a way to do streaming AEAD with go tink library.

Is it possible to do this with the existing AEAD interface by chunking the data myself? Is there any other way in tink that I can achieve my file encryption goal?

Thanks

**Comment by thaidn** [comment]
There was a 20% project, but the contributor has been too busy to work on it. We're looking for someone else.

If you have cycles to help, we can show you how to do it and review your PRs.

**Comment by challarao** [comment]
That sounds great @thaidn. I would be more than happy to see what I can do to help finish it.

**Comment by thaidn** [comment]
Good news! We would have this soon. Probably it can't make 1.3.0 cut, but it'll be in HEAD-SNAPSHOT in a few days.

**Comment by thaidn** [comment]
Golang support for Streaming AEAD has been available for a while: https://github.com/google/tink/tree/master/go/streamingaead.

Some documentation can be found at https://godoc.org/github.com/google/tink/go/streamingaead.

**Comment by thaidn** [comment]
Please try it out to see if it works for you. We'll include this in 1.4.0.

**Comment by thaidn** [comment]
Please comment if you have any questions.

**Comment by maoxs2** [comment]
It seems that the steaming aead cannot apply to the conn. When I wrap the conn with streamaead, the remote conn wont receive any message.

```
type CryptoConn struct {
	net.Conn

	w io.WriteCloser
	r io.Reader
}

func (c *CryptoConn) Write(b []byte) (n int, err error) {
	return c.w.Write(b)
}

func (c *CryptoConn) Read(b []byte) (n int, err error) {
	return c.r.Read(b)
}

func NewCryptoConn(conn net.Conn, password []byte) *CryptoConn {
	c := &CryptoConn{
		Conn: conn,
	}

	k := streamingaead.AES256GCMHKDF4KBKeyTemplate()

	kh, err := keyset.NewHandle(k)
	if err != nil {
		log.Fatal(err)
	}

	a, err := streamingaead.New(kh)
	if err != nil {
		log.Fatal(err)
	}

	c.w, err = a.NewEncryptingWriter(conn, password)
	if err != nil {
		log.Fatal(err)
	}

	c.r, err = a.NewDecryptingReader(conn, password)
	if err != nil {
		log.Fatal(err)
	}

	return c
}
```

**Comment by thaidn** [comment]
```
k := streamingaead.AES256GCMHKDF4KBKeyTemplate()
```

This line generates a brand new keyset each time this code is run. If the sender and the receiver aren't using the same keyset, they can't decrypt data from the other side.

See https://github.com/google/tink/blob/master/docs/GOLANG-HOWTO.md#key-management for how to store and load keysets.

It seems that you want to build an interactive data transfer protocol. Would you mind sharing what you want to achieve? I want to make sure you're safe against replay or reflection attacks.

**Comment by maoxs2** [comment]
Thanks.

But I dont wanna use gcpkms to manage my key due to it cannt be reached in China. So is it possible that inputing a 32 or 16-length bytes as AES key like https://godoc.org/crypto/aes#NewCipher does?

**Comment by yilunzhang** [comment]
@maoxs2 It seems that you have very similar use case as me. Have you checked this one? https://github.com/nknorg/encrypted-stream

**Comment by maoxs2** [comment]
@yilunzhang Thanks, I have implemented [my own one](https://github.com/maoxs2/go-aead-iostream) by studying shadowsocks' [shadowaead](https://godoc.org/github.com/shadowsocks/go-shadowsocks2/shadowaead) and this [aead stream](https://godoc.org/ekyu.moe/eae/lib/aeadstream).

But I think it would be better that using a more general and cross-language lib like tink. @thaidn

**Comment by thaidn** [comment]
@maoxs2 in order to make a connection, the sender and the receiver have to use the same keyset. In your snippet, both sides are generating their own keyset, that's why the decryption fails.

More importantly, you're building an interactive protocol. While Tink provides building blocks to build such a protocol, it doesn't address problems like replay attacks. I think you'd be better off using a TLS/Noise library or something like that.

**Comment by thaidn** [comment]
I'm going to close this, as the original question about Streaming AEAD in Golang is answered in https://github.com/google/tink/issues/258#issuecomment-626089649.

**Comment by AndreKR** [comment]
Is this compatible with the STREAM mechanism from [Online Authenticated-Encryption and its Nonce-Reuse Misuse-Resistance](https://eprint.iacr.org/2015/189.pdf) or is it something else?
