### ISSUE TITLE
Bug in Hello World C++ example

### ISSUE THREAD

**Issue by NielsH12** [google/tink#259]
Following your C++ Hello World example produces the following error when compiling:
(I'm compiling in terminal using g++: `g++ -std=c++11 -I/usr/local/include/ -L/usr/local/lib/ hello_world.cc -ltink -o hello_world` as per the tutorial)

```
hello_world.cc:145:42: error: ‘class crypto::tink::KeysetHandle’ has no member named ‘GetPrimitive’
   auto primitive_result = keyset_handle->GetPrimitive<crypto::tink::Aead>();
                                          ^~~~~~~~~~~~
hello_world.cc:145:73: error: expected primary-expression before ‘>’ token
   auto primitive_result = keyset_handle->GetPrimitive<crypto::tink::Aead>();
                                                                         ^
hello_world.cc:145:75: error: expected primary-expression before ‘)’ token
   auto primitive_result = keyset_handle->GetPrimitive<crypto::tink::Aead>();
```

I can see that line 145 in hello_world.cc was changed in commit `29477af476da93b6f18ecc9561a592da81a6cd9c` but I don't have time to investigate the issue further, if you can't reproduce the error, please let me know.

**Comment by tholenst** [comment]
Thanks for the report.

The example you use if for the version at head; but you are compiling with the latest released version. Please use the examples at https://github.com/google/tink/blob/1.2/docs/CPP-HOWTO.md or here https://github.com/google/tink/blob/1.2/examples/helloworld/cc/hello_world.cc

**Comment by NielsH12** [comment]
You're absolutely right, thanks for pointing it out, cheers.
