### ISSUE TITLE
Hybrid golang example is not useful

### ISSUE THREAD

**Issue by DukeyToo** [google/tink#260]
https://github.com/google/tink/blob/master/docs/GOLANG-HOWTO.md#hybrid-encryption-and-decryption

The example shows how to get a public key *from a private key* for use in hybrid encryption. 

If I understand the use case correctly, the purpose of hybrid is to use the public key of the *recipient*, not a random public key. It is not at all clear to me how keysets can be used to do that.

Supporting info, from the primitive docs:

> Hybrid Encryption combines the efficiency of symmetric encryption with the convenience of public-key encryption: to encrypt a message a fresh symmetric key is generated and used to encrypt the actual plaintext data, while the recipient’s public key is used to encrypt the symmetric key only, and the final ciphertext consists of the symmetric ciphertext and the encrypted symmetric key.

**Comment by thaidn** [comment]
>If I understand the use case correctly, the purpose of hybrid is to use the public key of the recipient, not a random public key. It is not at all clear to me how keysets can be used to do that.

Your understanding is correct. The recipient generates a key pair, persists the private key and export the public key using https://github.com/google/tink/blob/master/go/insecurecleartextkeyset/insecurecleartextkeyset.go.

```
// export the private keyset
kh, err := keyset.NewHandle(hybrid.ECIESHKDFAES128CTRHMACSHA256KeyTemplate())
if err != nil {
  return nil, err
}
exported := &keyset.MemReaderWriter{}
if err := insecurecleartextkeyset.Write(kh, exported); err != nil {
  return nil, err
}
serializedPrivateKeyset, err := proto.Marshal(exported.Keyset)
if err != nil {
  return nil, err
}

// store serializedPrivateKeyset somewhere

// export the public keyset
khPub, err := kh.Public()
exported = &keyset.MemReaderWriter{}
if err := insecurecleartextkeyset.Write(khPub, exported); err != nil {
  return nil, err
}
serializedPublicKeyset, err := proto.Marshal(exported.Keyset)
if err != nil {
  return nil, err
}

// share serializedPublicKeyset with the sender
```

Does it make sense?

**Comment by thaidn** [comment]
You're right that the example needs more work. I'll update it. Thanks for the suggestion!

**Comment by DukeyToo** [comment]
Thanks for making it clearer.
