### ISSUE TITLE
SHA3-512

### ISSUE THREAD

**Issue by mestebansosa** [google/tink#263]
Are you supporting SHA3-512 for java?
Thanks in advance.

**Comment by mestebansosa** [comment]
This is just a question as I do not see SAH3-512 support in the documentation.
In other case I will use another library, but I would like to use google tink as I am going to use it for AES_256_GCM_SIV.
Thanks.

**Comment by thaidn** [comment]
Unfortunately, Tink isn't supporting SHA3. We have no plan to address this issue, but we'd be happy to accept PRs. Please tell us your implementation ideas before sending PRs though.
