### ISSUE TITLE
On-disk format specification

### ISSUE THREAD

**Issue by binwiederhier** [google/tink#267]
I was wondering if there is an on disk format spec somewhere that describes the ciphertext and crypto params. I'd expect something like (version, primitive ID, IV, ciphertext length, ciphertext bytes). 

Can you point me to a spec or a proto file?

**Comment by thaidn** [comment]
Here you go: https://github.com/google/tink/blob/master/docs/WIRE-FORMAT.md.

Please send PRs if you found mistakes and comment if there's anything you want us to clarify.
