### ISSUE TITLE
Extremely high rate of heap churn when verifying Ed25519 signed data

### ISSUE THREAD

**Issue by eeSeeGee** [google/tink#269]
Using Java Flight Recorder profiling I discovered that our Java app was routinely GCing massive amounts of long[] data. With some digging these were found to all be coming from Tink. I wrote a small test program which calls Ed25519::verify once per second. After five minutes this produces 177MiB of long[]'s, with a 156MiB GC:
![image](https://user-images.githubusercontent.com/4116883/66426276-761b7300-e9df-11e9-9cf1-b69823d8a539.png)

Note that this isn't a traditional memory leak, it's just a very high rate of churn on heap allocation. At load in production this appears to be the cause of 2-3GiB GCs every few minutes.

I took a stab at a fix in https://github.com/google/tink/pull/265, which in my test app keeps the heap to a stable 750KiB.

**Comment by juergw** [comment]
Closing this because https://github.com/google/tink/pull/265 has also been closed.
