### ISSUE TITLE
AWS KMS client decrypt using KMS Key Alias Fails

### ISSUE THREAD

**Issue by jaxley** [google/tink#271]
I see that code was added as a result of issue https://github.com/google/tink/issues/71 that checks the key ID and that this was known to break with key aliases.

However, using key aliases is quite useful, especially for consistency across environments (to abstract configuration from infrastructure as code details).  

Can the code skip this check if a key alias is used so it won't break?  It seems to me that the REST API would return a non-200 status code if the decrypt failed with the given key and that would seem to be sufficient to determine if decryption succeeded?

**Comment by thaidn** [comment]
Hi there,

I'm not super familiar with AWS KMS. How do we tell if a key alias is used?

**Comment by jaxley** [comment]
Fully qualified kms key ID example:
arn:aws:kms:us-west-2:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab

Fully qualified Key alias example:
arn:aws:kms:us-west-2:111122223333:alias/ExampleAlias

**Comment by thaidn** [comment]
Sorry that I missed this. Will fix this soon.

@tholenst @kste maybe this is relevant for C++ and Python too.

**Comment by thaidn** [comment]
@chuckx we also want to fix this in Golang

**Comment by thaidn** [comment]
Just an update: we have a fix for this in Java, but it doesn't make the 1.4.0 release cut.
