### ISSUE TITLE
JavaScript aead encrypt not working

### ISSUE THREAD

**Issue by codejamninja** [google/tink#273]
`await new Aead().encrypt()` returns `undefined`. I'm not sure why. I dug around in the code and it look like it wasn't implemented.

https://github.com/google/tink/blob/master/javascript/aead.js#L43

**Comment by thaidn** [comment]
Hi there, could you please me a full snippet?

How did you build the Javascript library?

**Comment by codejamninja** [comment]
I didn't build it. I just moved it into the google-closure-library npm module and modified the `closure/goog/bootstrap/nodejs.js` file to bootstrap it.

Is there a better way to use this with npm?

**Comment by rekapallym** [comment]
Can you please help me how did you move to  google-closure-library?

**Comment by codejamninja** [comment]
I moved over the google-closure-library `crypt` module to npm. It has a lot of similar algorithms. I probably could move this library over using a similar technique. You can see the codebase at the link below.

https://github.com/codejamninja/google-closure-library

**Comment by rekapallym** [comment]
Hey thank you, can you help me out how to move google's tink into google-closure-library as you did for google's crypt?

**Comment by codejamninja** [comment]
I think it first needs to be packaged with the google-closure-library.

**Comment by codejamninja** [comment]
I tried doing to before. I'll see if I can get around to it soon.

**Comment by rekapallym** [comment]
Lmk if you get that done,Thank you!!!

**Comment by thaidn** [comment]
(cleaning up old tickets)

Please see https://github.com/google/tink/issues/276 for the latest status update w.r.t Javascript.

**Comment by thaidn** [comment]
FYI: @taymonbeal has helped us publish a package! https://www.npmjs.com/package/tink-crypto. We'll provide a how to shortly.
