### ISSUE TITLE
Getting Started with Javascript

### ISSUE THREAD

**Issue by thxmike** [google/tink#276]
I would like to know how to get started with the Javascript version of this library. I see the javascript folder in the source code but there are no clear instructions on how to get import or include this library in an application or project. Since there is no npm package, index.js file,  bootstrap file, or readme file, I am at a loss on how to include this in my project.

I also attempted to get the Bazel build to work for the javascript folder. However, all it does is makes a copy of the code to the output folder specified in the build file. 
The instructions that are available for this repository are for other languages which do not help.

Upon reading the previous issues and documentation, It indicates that a version would be available in August, in which it appears that the javascript files were provided but no sample or example on how to get started and how to consume this library. Any assistance in this matter would be appreciated.

**Comment by milky2028** [comment]
I don't think they've reached an initial release yet for JS. The roadmap says August was the target, but that seems to have been missed. Maybe we'll hear more at Chrome Dev Summit

**Comment by mike-rivera** [comment]
Can we at least get unofficial guidance on how to use and get started with a simple NodeJS application?

**Comment by thaidn** [comment]
Just an update: we're still making progress on Javascript, but it's going slow because we only have one 20% contributor working on it part time.

**Comment by thaidn** [comment]
I'm going to close this up because it looks like we aren't going to release Javascript/Typescript anytime soon.

**Comment by thaidn** [comment]
I was wrong. @taymonbeal has helped us publish a package! https://www.npmjs.com/package/tink-crypto. Documentation will be available soon!

**Comment by Mavenic** [comment]
> I was wrong. @taymonbeal has helped us publish a package! https://www.npmjs.com/package/tink-crypto. Documentation will be available soon!

Any update on documentation release for javascript?

**Comment by sounddroid** [comment]
I’m also in need for JavaScript documentation!

**Comment by tavoohoh** [comment]
Any luck implementing this without the documentation?

**Comment by umerali523** [comment]
Hi there...
Has anyone worked on JS/Ts/NodeJs version of this lib yet? Please provide any working sample thanks

**Comment by kevkevinpal** [comment]
I'm trying to import `tink-crypto` but I am running into this error

```
node_modules/tink-crypto/bundles/tink-crypto.umd.js:70
    goog.global = undefined || self;
                               ^

ReferenceError: self is not defined
```

**Comment by dmdabbs** [comment]
Where did this land? Does Tink support JS/Ts?

**Comment by chiderlin** [comment]
need javascript +1
