### ISSUE TITLE
CMake: Use FetchContent instead of HttpArchive

### ISSUE THREAD

**Issue by ronhe** [google/tink#277]
Hi,
Why not using the builtin CMake's `FetchContent` module instead of the custom made `HttpArchive` (which uses  CMake's `ExternalProject` module)?
`FetchContent` provides the same functionality and more.
For example, it would enable building Tink in an offline environment, by making use of  the `FETCHCONTENT_FULLY_DISCONNECTED` variable.

**Comment by tholenst** [comment]
The latest version of CMake we currently aim to support is 3.5. It seems FetchContent was added in 3.11.4, which was released on June 14, 2018.

I think we should support a bit of an older version than that. However, it might be possible and a good idea to have check the CMake version and use FetchContent if it is available. I would be willing to review such PRs.

**Comment by ronhe** [comment]
I have an alternative suggestion which allows both using `FetchContent` and supporting older CMake versions, while adding minimum extra code:
We can just use `FetchContent.cmake`, either by adding the file to Tink's repo, or by downloading it from CMake's repo in the configure step.
What do you think?

**Comment by tholenst** [comment]
Not sure that would be easier: we would preferably still want to have a conditional to use the built in when CMake is new enough (already so we don't forget to remove our code when we upgrade). Next, we would have to ensure that the licenses allow these things. It's unclear when I will get around to do that check.

Of course I didn't try either variant, so I can't really tell. What's important is that we have something where we will easily spot that we can remove the code once we support only CMake 3.11.4 and above, and that I will be able to verify that the license is fine.

**Comment by thaidn** [comment]
Please comment if this is still an issue.
