### ISSUE TITLE
RewardedAdsVerifier: Bad input triggers runtime exceptions

### ISSUE THREAD

**Issue by adam-p** [google/tink#278]
There are some places in [RewardedAdsVerifier.verify](https://github.com/google/tink/blob/09fc71c45dc7c4ecc7fb0df3414b0fb3a9ca52c3/apps/rewardedads/src/main/java/com/google/crypto/tink/apps/rewardedads/RewardedAdsVerifier.java#L119) that will throw runtime exceptions if given bad (or malicious input). This could crash a webhook server.

If `SIGNATURE_PARAM_NAME` is at the start of the query string, `i` will be 0, the second parameter to [the substring call](https://github.com/google/tink/blob/09fc71c45dc7c4ecc7fb0df3414b0fb3a9ca52c3/apps/rewardedads/src/main/java/com/google/crypto/tink/apps/rewardedads/RewardedAdsVerifier.java#L127-L134) will be -1, and `IndexOutOfBoundsException` [will be thrown](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#substring(int,%20int)).

```
    int i = queryString.indexOf(SIGNATURE_PARAM_NAME);
    if (i == -1) {
      throw new GeneralSecurityException("needs a signature query parameter");
    }
    byte[] tbsData =
        queryString
            .substring(0, i - 1 /* i - 1 instead of i because of & */)
            .getBytes(Charset.forName("UTF-8"));
```

Relatedly, but not identical, if the query string is `signature=key_id=` the -1 [here](https://github.com/google/tink/blob/09fc71c45dc7c4ecc7fb0df3414b0fb3a9ca52c3/apps/rewardedads/src/main/java/com/google/crypto/tink/apps/rewardedads/RewardedAdsVerifier.java#L136-L143) will not give the desired effect (although not as bad as the other problems here):
```
    String sigAndKeyId = queryString.substring(i);
    i = sigAndKeyId.indexOf(KEY_ID_PARAM_NAME);
    if (i == -1) {
      throw new GeneralSecurityException("needs a key_id query parameter");
    }
    String sig =
        sigAndKeyId.substring(
            SIGNATURE_PARAM_NAME.length(), i - 1 /* i - 1 instead of i because of & */);
```

Finally, if the `key_id` can't be parsed to a long, then [this line](https://github.com/google/tink/blob/09fc71c45dc7c4ecc7fb0df3414b0fb3a9ca52c3/apps/rewardedads/src/main/java/com/google/crypto/tink/apps/rewardedads/RewardedAdsVerifier.java#L144) will [throw a NumberFormatException](https://docs.oracle.com/javase/7/docs/api/java/lang/Long.html#parseLong(java.lang.String)) runtime exception.
```
long keyId = Long.parseLong(sigAndKeyId.substring(i + KEY_ID_PARAM_NAME.length()));
```

**Comment by thaidn** [comment]
Thanks @adam-p. This will be fixed shortly.
