### ISSUE TITLE
RewardedAdsVerifier: Cannot resolve symbol 'RewardedAdsVerifier'

### ISSUE THREAD

**Issue by idrisyagci** [google/tink#280]
Hello. I wanted to do server-side validation for rewarded video ads in Android apps. So when I try to use this class i got that error: Cannot resolve symbol 'RewardedAdsVerifier'. I implemented the tink library into my android app like "implementation 'com.google.crypto.tink:tink-android:1.3.0-rc1'". Then when i call the RewardedAdsVerifier class in my MainActivity that i show the rewarded video ads, i got that error. How can i solve this problem?

**Comment by thaidn** [comment]
Hi there,

You need `com.google.crypto.tink:apps-rewardedads:1.3.0-rc1`, see https://github.com/google/tink/tree/master/apps/rewardedads.

Note that currently RewardedAdsVerifier doesn't support Android. It should work, but please use it at your own risk, as it is meant to run on servers only.
