### ISSUE TITLE
Go - Exporting Ed25519 Public Key with RAW outputPrefixType seems to return too long key value

### ISSUE THREAD

**Issue by mlga** [google/tink#283]
Hi! Using Tink with Go, I'm trying to:

1. Generate Ed25519 private / public key pair.
1. Perform signing of a file.
1. Save signature to a file.
1. Save public key to a file.

There is a catch however. Verification is to be done by a party not using Tink, because of this, I want to export signature and public key without any Tink-specific information. 

I've managed to successfully export "_raw_" signature but I have problems exporting "_raw_" public key. I've ended up with a key value 34 bytes long [despite description given here](https://github.com/google/tink/blob/09fc71c45dc7c4ecc7fb0df3414b0fb3a9ca52c3/proto/ed25519_go_proto/ed25519.pb.go#L43).

Here is the code demonstrating the problem:
```go
package main

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"os"

	"github.com/google/tink/go/insecurecleartextkeyset"
	"github.com/google/tink/go/keyset"
	"github.com/google/tink/go/signature"
	tinkpb "github.com/google/tink/proto/tink_go_proto"
)

func check(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

func main() {
	args := os.Args[1:]
	if len(args) < 1 {
		log.Fatal("No file to sign given.")
	}

	// Read file that is being signed.
	data, err := ioutil.ReadFile(args[0])
	check(err)

	// Generate signing keys.
	kTemplate := signature.ED25519KeyTemplate()              // create template using safe defaults
	kTemplate.OutputPrefixType = tinkpb.OutputPrefixType_RAW // change prefix type to raw
	khPriv, err := keyset.NewHandle(kTemplate)
	check(err)

	// Initialize signer.
	signer, err := signature.NewSigner(khPriv)
	check(err)

	// Sign file.
	a, err := signer.Sign(data)
	check(err)

	// Encode signature as base64 string and save to a file.
	b64sign := make([]byte, base64.StdEncoding.EncodedLen(len(a)))
	base64.StdEncoding.Encode(b64sign, a)
	err = ioutil.WriteFile("signature.txt", b64sign, 0644)
	check(err)

	// Get public key handle.
	khPub, err := khPriv.Public()
	check(err)

	// Export public key in plain form.
	exported := &keyset.MemReaderWriter{}
	err = insecurecleartextkeyset.Write(khPub, exported)
	check(err)
        // Following yields 34-bytes value too::
        // log.Printf("pubkey: %s\n", b64.StdEncoding.EncodeToString(exported.Keyset.Key[0].KeyData.Value))

	// Format public key in plain, JSON format.
	buf := new(bytes.Buffer)
	jwriter := keyset.NewJSONWriter(buf)
	jwriter.Write(exported.Keyset)

	// Indent public key, save to file.
	jsonBuf := new(bytes.Buffer)
	err = json.Indent(jsonBuf, buf.Bytes(), "", "    ")
	check(err)
	err = ioutil.WriteFile("pubkey.txt", jsonBuf.Bytes(), 0644)
	check(err)

	fmt.Println("File signed, signature saved to signature.txt, public key exported to pubkey.txt.")
}
```

Here is produced signature:
```
lIchB2Q+GYD3lxit/Qv0ysFT7MP+htXNalp9V1+f+LKpWMtauz2XtFjMUdTdzw0dqrVribsZWYCDkyXUrHvtBw==
```

And here, exported public key:

```json
{
    "primaryKeyId": 791596364,
    "key": [
        {
            "keyData": {
                "typeUrl": "type.googleapis.com/google.crypto.tink.Ed25519PublicKey",
                "value": "EiDCxqZK6nHUnf03reAM2RMRcBGBRVz0nCwuqmqQHFceww==",
                "keyMaterialType": "ASYMMETRIC_PUBLIC"
            },
            "status": "ENABLED",
            "keyId": 791596364,
            "outputPrefixType": "RAW"
        }
    ]
}
```

As you can see, signature has a correct length but exported key has 34 bytes instead of 32. Is this by design? Can I export raw key somehow?

Environment:
- `go version go1.13.3 darwin/amd64`
- Tink `v1.3.0-rc1`

**Comment by thaidn** [comment]
@mlga the key `EiDCxqZK6nHUnf03reAM2RMRcBGBRVz0nCwuqmqQHFceww==` that you observe is a serialized protobuf.

Tink has two APIs: the main API that uses protobufs, and the subtle API that uses raw strings. The former deals with keysets and key management, the latter doesn't.

In your case, it seems that you should use the subtle layer.

```
package main

import (
    "crypto/rand"
    "golang.org/x/crypto/ed25519"
    "fmt"

    "github.com/google/tink/go/subtle/signature"
)

pub, priv, err := ed25519.GenerateKey(rand.Reader)
if err != nil {
    fmt.Errorf("key generation error: %s", err)
}

signer, err := signature.NewED25519SignerFromPrivateKey(priv)
if err != nil {
    fmt.Errorf("cannot obtain signer: %s", err)
}

// sign data
```

**Comment by mlga** [comment]
@thaidn Thank you for clarification. That's a real shame however. I would like to use Tink mainly because of its built in key management and KMS integrations 😢 
Last question, do you see any problem with manually stripping off any prefixes from protobuf representation, using for example proto definitions provided with Tink:

```golang
package main

import (
	"encoding/base64"
	"log"

	"github.com/golang/protobuf/proto"
	ed25519pb "github.com/google/tink/proto/ed25519_go_proto"
)

func main() {
        //...
	pbPubkey := &ed25519pb.Ed25519PublicKey{}
        proto.Unmarshal(exported.Keyset.Key[0].KeyData.Value, pbPubkey)
        //...
	log.Printf("pubkey: %s\n", base64.StdEncoding.EncodeToString(pbPubkey.KeyValue))
}
```

I know this is kinda hacky but still, I just want to dump public key.

**Comment by thaidn** [comment]
One way is to convince the recipients to switch to Tink ;-).

The hack should work, but I wouldn't recommend it because we don't actually want users to depend on our protobuf definitions, which are kind of internal implementation details.

I'm going to close this, please reopen if you want to discuss more.
