### ISSUE TITLE
Unable to use openssl and boringssl  at the same time in cpp application

### ISSUE THREAD

**Issue by preetigaur** [google/tink#284]
Hi

I am trying to use tink/cc library in a cpp application on macOS. The cpp application uses openssl library for some cryptographic algorithms. When I try to use  tink/cc library which internally depends on boringssl, I can't use openssl. At a time one of the two libraries can be installed in /usr/local/ with the same name i.e openssl. Some of the algorithms are not supported by boringssl which is required in the application. 
Could you please provide a solution.

Thanks in Advance.

**Comment by thaidn** [comment]
@tholenst @przydatek

**Comment by pval** [comment]
"At a time one of the two libraries can be installed in /usr/local/ with the same name i.e openssl" - you should not be installing BoringSSL with the same name as OpenSSL... the necessary parts of BoringSSL are bundled with in libtink.so. Are you compiling from source, or using the pre-built package (C++ instructions in https://github.com/google/tink/releases) ?

We just tested it on Linux and we can have a program that uses both tink and OpenSSL code, and compile/link with both -ltink and -lcrypto successfully. If you can provide a test case that exhibits your problem, and some more detail, that will help us figure this out.

**Comment by preetigaur** [comment]
I tried both the ways, used pre-built package as well as compiled tink from source. I have openssl lib in /usr/local/lib. 

<img width="993" alt="Screenshot 2019-11-19 at 3 21 53 PM" src="https://user-images.githubusercontent.com/7146976/69136209-7596f180-0ae0-11ea-96d3-851d5b203c55.png">

**Comment by thaidn** [comment]
We had long discussion about this issue internally. Unfortunately, we can't find any short-term solution. I'm afraid that we have to declare that Tink can't co-live with OpenSSL in a single address space. Otherwise it could lead to undefined behaviors and serious vulnerabilities.

Long-term, the only viable solution is to shade a copy of BoringSSL directly in Tink. I believe this is the approach that gRPC took. It looks like a dirty hack, but we've run out of ideas, and we are all ears for better solutions.

**Comment by thaidn** [comment]
This is something we want to look into for 1.5.0.

**Comment by morambro** [comment]
Since v1.7.0 one can build Tink C++ using OpenSSL 1.1.1 instead of BoringSSL (https://github.com/google/tink/releases/tag/v1.7.0). This should partially solve this issue.

**Comment by tholenst** [comment]
Due to the above comment, I will close this. Please reopen or file another issue if this is still a problem.
