### ISSUE TITLE
java: How do I use EcdsaSignatureEncoding.IEEE_P1363?

### ISSUE THREAD

**Issue by Capstan** [google/tink#297]
I am trying to verify a JWT. I can explicitly specify this signature format in the constructor to `EcdsaVerifyJce` and then verification works:

```java
EcdsaVerifyJce verifyJce =
    new EcdsaVerifyJce(publicKey, HashType.SHA256, EllipticCurves.EcdsaEncoding.IEEE_P1363);
verifyJce.verify(jws.getSignatureBytes(), jws.getSignedContentBytes());
```

but `EcdsaVerifyJce` is in `subtle` and so [direct use is warned against](https://github.com/google/tink/blob/master/docs/JAVA-HOWTO.md#important-warnings). If I use `SignaturePemKeysetReader` to read the keys, then the underlying Keyset has `DER` uniformly set by `convertEcPublicKey`, and so the following fails:

```java
KeysetReader reader =
    SignaturePemKeysetReader.newBuilder()
        .addPem(examplePublicKey, PemKeyType.ECDSA_P256_SHA256)
        .build();
KeysetHandle keysetHandle = KeysetHandle.readNoSecret(reader);
PublicKeyVerify verifier = keysetHandle.getPrimitive(PublicKeyVerify.class);
verifier.verify(jws.getSignatureBytes(), jws.getSignedContentBytes());
```

I haven't yet found a way to either customize it or amend the `EcdsaEncoding` from outside the `subtle` packages. Is there a way to do this?

**Comment by Capstan** [comment]
I can _almost_ do it if I write an amending `KeysetReader` that modifies the `EcdsaSignatureEncoding` on the keyset provided by the delegate reader:

```java
// This is necessary because SignaturePemKeysetReader uniformly applies DER rather than
// IEEE_P1363.  https://github.com/google/tink/issues/297
private static class JWTKeysetReader implements KeysetReader {
  private final KeysetReader delegate;

  public JWTKeysetReader(KeysetReader delegate) {
    this.delegate = delegate;
  }

  @Override
  public Keyset read() throws IOException {
    Keyset keyset = delegate.read();
    if (!"type.googleapis.com/google.crypto.tink.EcdsaPublicKey"
        .equals(keyset.getKey(0).getKeyData().getTypeUrl())) {
      throw new AssertionError(
          String.format("Unexpected type %s", keyset.getKey(0).getKeyData().getTypeUrl()));
    }
    EcdsaPublicKey ecdsaPublicKey =
        EcdsaPublicKey.parseFrom(
            keyset.getKey(0).getKeyData().getValue(), ExtensionRegistry.getEmptyRegistry());
    EcdsaPublicKey.Builder keyBuilder = ecdsaPublicKey.toBuilder();
    keyBuilder.getParamsBuilder().setEncoding(EcdsaSignatureEncoding.IEEE_P1363);
    Keyset.Builder keysetBuilder = keyset.toBuilder();
    keysetBuilder
        .getKeyBuilder(0)
        .getKeyDataBuilder()
        .setValue(keyBuilder.build().toByteString());
    return keysetBuilder.build();
  }

  @Override
  public EncryptedKeyset readEncrypted() throws IOException {
    throw new AssertionError("unimplemented");
  }
}
```

This seems pretty heavyweight to me, but is that what is expected?

Even then, `SignaturePemKeysetReader`'s only obvious builder uses `PemKeyType` which is also in `subtle`. But is that OK because it's not an API, but just an enum?

**Comment by juergw** [comment]
Yes, SignaturePemKeysetReader only supports DER, and there is no easy way to get this working.

But we now have JWT primitives that let you directly verify JWTs, see
https://github.com/google/tink/blob/master/docs/JWT-HOWTO.md

An example on how to use it to verify JWTs in Java from a public JWK-set is here:
https://github.com/google/tink/blob/master/examples/java_src/jwt/JwtVerify.java

Note that importing PEM-formatted keys for these primitives is currently not supported. So you will need to ask the signer of the JWTs to provide the public key(s) in JWK-set format.
