### ISSUE TITLE
Streaming AEAD Always returning an output file of 1 KB

### ISSUE THREAD

**Issue by jaigurudevswamiji** [google/tink#303]
I am trying to encrypt files of format (txt, pdf, doc) using Google Tink - streaming AEAD encryption API, below is the Java code which I am trying to execute. But all I get is 1 KB output encrypted file and no errors. Input files are 2 MB or more than 10 MB, output encrypted file will be always of 1 KB. I am unable to figure out what could be going wrong, is the problem in the code or the algorithm of Streaming Aead. Please assist.

```java
TinkConfig.register();

final int chunkSize = 256;

KeysetHandle keysetHandle = KeysetHandle.generateNew(               
      StreamingAeadKeyTemplates.AES128_CTR_HMAC_SHA256_4KB);

// 2. Get the primitive.
StreamingAead streamingAead = keysetHandle.getPrimitive(StreamingAead.class);

// 3. Use the primitive to encrypt some data and write the ciphertext to a file,

FileChannel ciphertextDestination =
            new FileOutputStream("encyptedOutput.txt").getChannel();

String associatedData = "Tinks34";

WritableByteChannel encryptingChannel =
            streamingAead.newEncryptingChannel(ciphertextDestination, associatedData.getBytes());

ByteBuffer buffer = ByteBuffer.allocate(chunkSize);
InputStream in = new FileInputStream("FileToEncrypt.txt");

while (in.available() > 0) {
        in.read(buffer.array());
        encryptingChannel.write(buffer);
}
encryptingChannel.close();
in.close();
System.out.println("completed");
```

**Comment by thaidn** [comment]
@bleichen Daniel, could you please assist? I can't see any obvious issue.

**Comment by chuckx** [comment]
You're not using ByteBuffer properly.

You need to call the clear()
<https://docs.oracle.com/javase/7/docs/api/java/nio/Buffer.html#clear()>
method
<https://docs.oracle.com/javase/7/docs/api/java/nio/Buffer.html#clear()> to
reset the buffer for each iteration. Also, you should cleanly handle the
case where the amount you read into buffer is less than chunkSize.

Here's a start:

        while (in.available() > 0) {
            // Sets buffer position to zero and sets the limit to the
capacity.
            buffer.clear();
            // Capture the number of bytes read.
            int bytesRead = in.read(buffer.array());
            // Since you're interacting directly with the backing array,
manually set the buffer position.
            buffer.position(bytesRead);
            // Sets the buffer limit to the position (which was set above)
and resets the position to zero.
            // This allows the following write to only output the actual
number of bytes read in.
            buffer.flip();
            int bytesWritten = encryptingChannel.write(buffer);
            // A little bit of debugging output so you can see what's
happening during each iteration.
            System.out.printf("wrote %d bytes... ", bytesWritten);
        }

**Comment by chuckx** [comment]
You're not using ByteBuffer properly.

You need to call the [clear() method](https://docs.oracle.com/javase/7/docs/api/java/nio/Buffer.html#clear()) to reset the buffer for each iteration. Also, you should cleanly handle the case where the amount you read into buffer is less than chunkSize.

Here's a start:

```
while (in.available() > 0) {
  // Sets buffer position to zero and sets the limit to the capacity.
  buffer.clear();

  // Capture the number of bytes read.
  int bytesRead = in.read(buffer.array());

  // Since you're interacting directly with the backing array, manually set the buffer position.
  buffer.position(bytesRead);

  // Sets the buffer limit to the position (which was set above) and resets the position to zero.
  // This allows the following write to only output the actual number of bytes read in.
  buffer.flip();

  int bytesWritten = encryptingChannel.write(buffer);
  // A little bit of debugging output so you can see what's happening during each iteration.
  System.out.printf("wrote %d bytes... ", bytesWritten);
}
```

**Comment by bleichen** [comment]
Also wrong is to use 
    while(in.available()) {

available() is defined as follows: 
Returns an estimate of the number of bytes that can be read (or skipped over) from this input stream without blocking by the next invocation of a method for this input stream. 
...
Hence it can return 0 even if the file has not been read fully.

Possibly, easier would be to use channels for the input too. I.e., 
FileChannel in = new FileInputStream("FileToEncrypt.txt").getChannel();
FileChannel seems more suitable to me for a number of reasons:
  * it supports reading and writing to ByteBuffers. I consider using both
    ByteBuffers and backing array to be error prone.
 * FileChannel has a method .size(). I'd use this to double check that the full
   file has been read and encrypted. It is too easy to oversee some blocking
   behaviour and interpret it as an end of file.
* There is a method .transferTo(.), which looks useful to me. (But I haven't tested this).

**Comment by chuckx** [comment]
Here's an updated code snippet taking into account the suggestions from @bleichen above. Using `transferTo()` removes the need to instantiate a `ByteBuffer` in the first place:

```
FileChannel in = new FileInputStream("FileToEncrypt.txt").getChannel();

long size = in.size();
long position = 0;
long previousPosition = 0;
while (position < size) {
    position += in.transferTo(position, chunkSize, encryptingChannel);
    System.out.printf("Wrote %d bytes... ", (position - previousPosition));
    previousPosition = position;
}
```

**Comment by jaigurudevswamiji** [comment]
@thaidn @chuckx @bleichen 

Awesome Guys, thanks very much for your help. It encrypts in matter of seconds.

**Comment by thaidn** [comment]
@chuckx if we haven't, can we put your code in an example somewhere?

**Comment by bleichen** [comment]
On Fri, Feb 7, 2020 at 6:13 PM Thai Duong <notifications@github.com> wrote:

> @chuckx <https://github.com/chuckx> if we haven't, can we put your code
> in an example somewhere?
>

We could, but maybe we shouldn't. See, one  @chuckx and I discussed
previously is that transferTo actually
implements some chunking internally. This means on the one hand that the
user does not have to implement
a loop, just one call is enough. But it means on the other hand that
transferTo, transferFrom etc are not
atomic operations and using them in a threaded application can lead to very
unexpected results.
(Again I haven't tested this, but I could not find any locks in the code).
In the code about that is not an issue of course.

But before making any general recommendations, it would make sense to have
a closer look at
the existing methods and maybe ask if they are enough or if some additional
interfaces would avoid some
pitfalls.

**Comment by thaidn** [comment]
Slightly off topic, but I want to apology for not taking a closer look before asking for help. I should have read the documentation.

**Comment by jaigurudevswamiji** [comment]
@chuckx @bleichen @thaidn 
Just one questions guys, When I try to encrypt and decrypt txt files, it works fine. But any other file format like .docx, .pdf, .zip or any other file format it gets corrupted. Am I missing something, I have followed every detail in HOW-to Java guide. Please give instructutions.
