### ISSUE TITLE
Simple way to convert/import java.security.[Public/PrivateKey]Key to a KeysetHandle

### ISSUE THREAD

**Issue by cmoine** [google/tink#308]
I am loading an X.509 DER file this way (sorry it is Kotlin):
```kotlin
val cf = CertificateFactory.getInstance("X.509")
val cert = cf.generateCertificate(TestED25519Function::class.java.getResourceAsStream("client-ed25519.der")) as X509Certificate
val publicKey = cert.publicKey;
```
In the `publicKey` value (of type java.security.PublicKey), there is an private/protected value to get the key itself, but no mean to export it, appart from the `encoded` value.

Unless I am missing a very big point here, I think we would need one of these two:
1) A way to go from java.security.[Public/PrivateKey]Key 'world' to Tink 'world' and vice et versa, but I guess it is not so easy, since approach are different (only PublicKey.getEncoded() is exposed for instance)
2) a toolbox to load existing certificate of different kinds (maybe it exist but didn't find it sorry, but yet I really investigated a lot already)

Thank you in advance.

PS: This library looks really powerful and promising, but it is not always so easy to use. There's a lack of documentation and example for the moment imho

**Comment by thaidn** [comment]
Yeah we're working on improving documentation and providing more examples.

For this particular problem we'll add a a tool that allows to convert back and forth from Tink to other key formats.

The design is already there, take a look at the `KeysetReader` interface if you want to implement this yourself.

Anyway just want to say that this is on our radar for 1.5.0.

Please circle back if you have more thoughts to share.

**Comment by bhargman** [comment]
Hello,

Is there any update on adding this support? I see that `1.5.0` is released, but don't see any APIs for converting back and forth between `Tink` and `java.security.[Public/PrivateKey]Key`.

**Comment by MidnightFiend** [comment]
Hello, is there any plan optimize for it ?

**Comment by tholenst** [comment]
Yes, thank you, we are still working on this.

**Comment by juergw** [comment]
This is now possible for Ecdsa and RSA SSA PKCS1 keys. I've added some tests that show how to convert Java keys into Tink keys:

https://github.com/tink-crypto/tink-java/blob/main/src/test/java/com/google/crypto/tink/signature/EcdsaPrivateKeyTest.java#L132

and

https://github.com/tink-crypto/tink-java/blob/main/src/test/java/com/google/crypto/tink/signature/RsaSsaPkcs1PrivateKeyTest.java#L405

These keys can then be imported into a KeysetHandle use the KeysetHandle.Builder and importKey, see test here:

https://github.com/tink-crypto/tink-java/blob/main/src/test/java/com/google/crypto/tink/KeysetHandleTest.java#L1411

**Comment by snorp** [comment]
Following the examples linked above with an `EcdsaPublicKey`, I get the following when trying to import it into a `KeysetHandle`. Is that expected?

```
java.security.GeneralSecurityException: No Key serializer for EcdsaPublicKey with serialization type: ProtoKeySerialization available
        at com.google.crypto.tink.internal.SerializationRegistry.serializeKey(SerializationRegistry.java:291)
        at com.google.crypto.tink.internal.MutableSerializationRegistry.serializeKey(MutableSerializationRegistry.java:177)
        at com.google.crypto.tink.KeysetHandle$Builder.createKeysetKeyFromBuilderEntry(KeysetHandle.java:354)
        at com.google.crypto.tink.KeysetHandle$Builder.build(KeysetHandle.java:403)
```

**Comment by snorp** [comment]
Ah, it seems `TinkConfig.register()` gets past the serialization issue.
