### ISSUE TITLE
Android and iOS failed to encrypt and decrypt each other

### ISSUE THREAD

**Issue by alphater** [google/tink#310]
Hi tink team:
I ’m very glad to use your encryption scheme. Now we have a problem. We are using aead encryption and decryption scheme, but we want to encrypt and decrypt each other from Android and iOS platforms. The result is that Android and iOS can encrypt and decrypt themselves, but Android generates files After encrypting the plaintext string after the key, the key file and the encrypted content are sent to iOS, and iOS decryption fails. Similarly, iOS sent the encrypted content of the key file to Android, and the decryption failed.
Here is the relevant code snippet:

**iOS init：**
![image](https://user-images.githubusercontent.com/4635693/74514627-f0d53b80-4f47-11ea-963d-474808f99aae.png)

**iOS decrypt：**
![image](https://user-images.githubusercontent.com/4635693/74514680-0cd8dd00-4f48-11ea-8165-66234a28f383.png)

**Android init：**
![image](https://user-images.githubusercontent.com/4635693/74514772-35f96d80-4f48-11ea-99bb-49e3f9eaca59.png)
![image](https://user-images.githubusercontent.com/4635693/74514792-44e02000-4f48-11ea-8e91-a3cb1fdcb139.png)

**Android decrypt：**
![image](https://user-images.githubusercontent.com/4635693/74514847-60e3c180-4f48-11ea-90e8-d4482bebcf56.png)

**Secret key：**
![image](https://user-images.githubusercontent.com/4635693/74515325-5249da00-4f49-11ea-8843-258383ca6e6d.png)

**Comment by alphater** [comment]
Supplementary key file
**sr_keyset.json**

`{
    "primaryKeyId": 449869332,
    "key": [
        {
            "keyData": {
                "typeUrl": "type.googleapis.com\/google.crypto.tink.AesGcmKey",
                "value": "GiBnMY+VDsOxphEfwvYSSL6FEJVgxvsT0M0QVcYzMIEuLA==",
                "keyMaterialType": "SYMMETRIC"
            },
            "status": "ENABLED",
            "keyId": 449869332,
            "outputPrefixType": "TINK"
        }
    ]
}
`

**Comment by thaidn** [comment]
Which error did you get?

**Comment by alphater** [comment]
> Which error did you get?

Regardless of encryption on either side, decryption on the other side fails.

**Comment by thaidn** [comment]
I need to see the error messages returned by Tink.

BTW, it seems that on iOS you didn't base64 encode, but on Android you did.

**Comment by alphater** [comment]
> 我需要查看Tink返回的错误消息。
> 
> 顺便说一句，似乎在iOS上您没有base64编码，但是在Android上却做了。

Thank you very much, I will look at the problem of base64 encoding later;
Now that I have switched to other programs, I can't get the relevant logs for the time being, and I will give timely feedback when I test later.

**Comment by thaidn** [comment]
Thanks. Please reopen when you come back to this.
