### ISSUE TITLE
[Android] Android Keystore master key URI requirements are unclear

### ISSUE THREAD

**Issue by kinex** [google/tink#313]
I have read the documentation available here https://google.github.io/tink/javadoc/tink-android/1.2.2/com/google/crypto/tink/integration/android/AndroidKeysetManager.html

The documentation says the master key URI must start with `android-keystore://`. It is unclear if the URI must be unique (in device scope) or can two apps use the same URI without tampering each other's data?

**Comment by thaidn** [comment]
Hi there,

Android Keystore ensures that keys generated by an app can only be accessed by that app. The answer to your question is two apps can use the same URI without tampering each other's data.

Please reopen if you have any other questions.

**Comment by kinex** [comment]
Thank you for this information. In my thinking URI based name refers to a global identifier so I wanted to confirm this to avoid any security issues.
