### ISSUE TITLE
Tink pre-built binary crashes ld with binary layout optimiaztions

### ISSUE THREAD

**Issue by jerrymarino** [google/tink#315]
Good afternoon! I'm getting a few errors when trying to link Tink when using a binary layout optimization profile.

Currently, attempting to use this release https://dl.google.com/dl/cpdc/3a198ab317d35620/Tink-1.2.2.tar.gz with Xcode's ld for an iOS ARM64 build

```
$ xcodebuild -version
Xcode 11.2.1
Build version 11B500
```

```
  | 0  0x101568198  __assert_rtn + 127
  | 1  0x101571f04  ld::passes::order::Layout::buildFollowOnTables() (.cold.5) + 0
  | 2  0x10153ede7  ld::passes::order::Layout::buildFollowOnTables() + 2209
  | 3  0x10153f7c5  ld::passes::order::Layout::doPass() + 23
  | 4  0x10153f8cd  ld::passes::order::doPass(Options const&, ld::Internal&) + 151
  | 5  0x10144b113  main + 1001
```

Do you have any suggestions on working around the LD crash? Longer term, I'm planning to build Tink from source and generate a PGO profile with a source build but that will be non trivial.

**Comment by tholenst** [comment]
Thanks for the report. Unfortunately, it will be difficult for us to help you in the near future. Can you produce step by step instructions how you build Tink?

**Comment by thaidn** [comment]
Please comment if you want us to continue working on this issue.
