### ISSUE TITLE
File-based KeysetWriter and KeysetReader do not close their respective Input/OutputStreams

### ISSUE THREAD

**Issue by marco-boeck** [google/tink#316]
Neither com.google.crypto.tink.JsonKeysetWriter/Reader nor com.google.crypto.tink.BinaryKeysetWriter/Reader close their respective Output/InputStreams after operation.
They also do not provide a method to manually close the streams. This causes file handle leaks and you cannot delete a key file after you have created it unless you shutdown the entire JVM.

**Comment by thaidn** [comment]
Thanks. I'm on it.

**Comment by thaidn** [comment]
Just want to confirm that I understand than this correctly: this is only a problem when you call `BinaryKeysetReader.withFile()`, right? Tink will create an InputStream, but it doesn't close it. If you pass an InputStream directly to  `BinaryKeysetReader.withInputStream()`, you can close it yourself.

**Comment by marco-boeck** [comment]
Yes, indeed. I noticed it for the `withPath()` method, but as that one delegates to `withFile()`, this covers it.

**Comment by thaidn** [comment]
This is being fixed and the fix should be included in 1.4.0 final release.

**Comment by thaidn** [comment]
This is fixed in HEAD-SNAPSHOT and will be included in 1.4.0.
