### ISSUE TITLE
Unable to compile Tink for CPP with Bazel

### ISSUE THREAD

**Issue by AndreasRo** [google/tink#317]
Trying to build Tink fpr CPP using Bazel : https://github.com/google/tink/blob/master/docs/CPP-HOWTO.md

Cloned the master branch, installed Bazel. Getting error message when running "bazel build -c opt cc:libtink.so":
ERROR: Failed to load Starlark extension '@tink_py_deps//:requirements.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @tink_py_deps
This could either mean you have to add the '@tink_py_deps' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
ERROR: cycles detected during target parsing
INFO: Elapsed time: 0.126s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

Running on Windows 10 1909 x64.

**Comment by kste** [comment]
We recently moved to individual WORKSPACEs for each language, but unfortunately that part of the documentation was not updated yet. You should be able to run "bazel build -c opt :libtink.so" inside the /cc directory, in order for the correct WORKSPACE to be used.

**Comment by AndreasRo** [comment]
Thank you for yout quick reply :)

Unfortunately I got a new error now:
ERROR: C:/users/ar/source/repos/tink/cc/BUILD.bazel:678:1: Configurable attribute "linkopts" doesn't match this configuration (would a default condition help?).
Conditions checked:
 //:linux_x86_64
 //:mac_x86_64

Apparently Windows 10 is not supported?

Full error trace:
[trace.txt](https://github.com/google/tink/files/4287304/trace.txt)

**Comment by tholenst** [comment]
Yes sorry -- Windows 10 is not supported. Also, libtink.so will not be supported anymore -- I already modified this internally. Sorry about that.

**Comment by AndreasRo** [comment]
:'(

Thanks for quick replies guys. The documentation was a bit ambiguous at that point; I was hoping that the 'linux and mac only' was only related to what was offered as percompiled files.
