### ISSUE TITLE
Unable to build Tinkey

### ISSUE THREAD

**Issue by antjori** [google/tink#319]
While trying to build Tinkey, using the [Tinkey build instructions](https://github.com/google/tink/blob/master/docs/TINKEY.md), I'm getting the following error:
> \> bazel build tools/tinkey
> ERROR: Failed to load Starlark extension '@tink_py_deps//:requirements.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
> \- @tink_py_deps

> This could either mean you have to add the '@tink_py_deps' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
ERROR: cycles detected during target parsing

I've installed Bazel v0.29.1, through the Bazel installer, using the instructions mentioned in the [Installing Bazel on macOS](https://docs.bazel.build/versions/master/install-os-x.html) guide.

**Comment by kste** [comment]
It should work if you are inside the "tools" folder and run "bazel build tinkey".

**Comment by antjori** [comment]
@kste thank you for the feedback. It solved it!
