### ISSUE TITLE
GeneralSecurityException: decryption failed

### ISSUE THREAD

**Issue by zsweigart** [google/tink#321]
```
GeneralSecurityException: decryption failed
  File "AeadWrapper.java", line 82, in decrypt
  File "TinkHelper.kt", line 33, in decrypt
```

This error occurs with version 1.3.0-rc1 on an Android device running 9.0 but is fixed in versino 1.3.0-rc4.  We can't upgrade to 1.3.0-rc4 because of https://github.com/google/tink/issues/301.

Will the 1.3.0 release contain the fix for the decryption error but not the issue with firebase?

**Comment by thaidn** [comment]
Could you please provide more information?  For example, why do you think this is fixed in 1.3.0-rc4?

>Will the 1.3.0 release contain the fix for the decryption error but not the issue with firebase?

Yes. 1.3.0 cannot be used with Firebase, I'm so sorry about this, but there's little we can do at the moment.

I hope that we can make 1.4.0 work with Firebase.

**Comment by amytang0** [comment]
Hi, is there an updated timeline on 1.4.0? The roadmap says Feb 2019 (https://github.com/google/tink/blob/master/docs/ROADMAP.md). We are possibly going to roll our own branch with Firebase-compatible protobufs since this is blocking us

**Comment by thaidn** [comment]
We're working very hard on 1.4.0. The main blocker is Tink for Python, but it's getting ready. We think it should be ready by end of April.

Note that it's very unlikely that we will be able to resolve the protobuf issue with 1.4.0.

**Comment by amytang0** [comment]
Thanks for the update!

**Comment by simtse** [comment]
> Yes. 1.3.0 cannot be used with Firebase, I'm so sorry about this, but there's little we can do at the moment.

We've been using 1.3.0 and we have `firebase-core` and `firebase-messaging` and generally, users are able to encrypt and decrypt. But we have a significant amount of users that also get `GeneralSecurityException`. @thaidn can you elaborate more on how 1.3.0 tink doesn't work with firbase?

@amytang0 what modifications did you have to have Tink become Firebase-compatible?

**Comment by thaidn** [comment]
@simtse #301 is being fixed. Could you kindly upgrade to HEAD-SNAPSHOT to try it out?

**Comment by simtse** [comment]
Thanks @thaidn Would you be able to elaborate on the commits and causes for the fixes? I'm puzzled specifically about this and the Protobuf errors. Seemed like a series of fixes if addressing both the Protobuf and decryption problems, but I don't know for sure why.

**Comment by simtse** [comment]
So I'm still getting this `GeneralSecurityException: decryption failed` that I originally thought was my own code. But now, it seems that AndroidX's `EncryptedSharedPrefences` also runs into this problem when I'm just saving (encrypting) and fetching (decrypting) Strings.

```
Caused by: java.lang.SecurityException: Could not decrypt value. decryption failed
	at androidx.security.crypto.EncryptedSharedPreferences.getDecryptedObject(EncryptedSharedPreferences.java:33)
	at androidx.security.crypto.EncryptedSharedPreferences.getString(EncryptedSharedPreferences.java:1)
	... 20 more
Caused by: java.security.GeneralSecurityException: decryption failed
	at com.google.crypto.tink.aead.AeadWrapper$WrappedAead.decrypt(AeadWrapper.java:15)
	at androidx.security.crypto.EncryptedSharedPreferences.getDecryptedObject(EncryptedSharedPreferences.java:5)
	... 21 more
```

**Comment by thaidn** [comment]
Have you observed any logging statements from AndroidKeysetManager on these devices?

**Comment by simtse** [comment]
😞 No we haven't observed or seen the logging statements because we can't reproduce locally that represents what's happening to our users in production. We also won't see the info logs from our production users in our reports because the `AndroidKeysetManager` is using the base `Log.i()` method isn't captured in our log files that we send when we capture feedback

**Comment by simtse** [comment]
> That's strange. I still don't understand what happened.

A theory is that the `AndroidKeysetManager` failed to read the keyset and decrypt it with Android keystore, then because of then, it would either create a new encrypted keyset or use the current keyset (that couldn't be decrypted) as a clear text keyset. 

Then since that keyset is not matched to the encrypted cipher text, it fails to decrypt. I've had some tests that had 
1) Encrypted a known hard-coded string and saved them several months ago
2) Check if I can decrypt them on a regular basis.
3) When the another cipher text started to fail to decrypt, these hard coded strings that were encrypted and stored would also fail to decrypt.

**Comment by eygraber** [comment]
I've been having the same problem with androidx security RC 2 (see [here](https://issuetracker.google.com/issues/157501475) and [here](https://issuetracker.google.com/issues/158234058)). I'm at 10k crashes in the past 30 days.

**Comment by thaidn** [comment]
Thank you all for your reports and comments.

Here's what we're doing to do:

1/ Tink will disable Android Keystore by default. Users can enable it by setting a master key URI, but Tink will run a self-test and disable it if it detects any issues. We recommend keeping Android Keystore disabled unless you have a very strong reason to depend on it.

2/ Tink will only generate a new keyset or a new master key if there's no existing key material. Currently Tink attempts to generate a new keyset or a new master key whenever it can't read the existing key material. This behavior is useful in certain cases, but it hides the actual problems in Android Keystore from Tink users.

**Comment by eygraber** [comment]
Will clients already affected by the AndroidKeystore issue be able to recover when this new idea is implemented?

**Comment by thaidn** [comment]
@eygraber Unfortunately I'm not sure. If you had some data encrypted with a keyset that is in turn wrapped by a master key in Android Keystore, you won't be able to recover the data if the master key is lost :-(. I'm really sorry that Android Keystore is so unreliable. I regret the decision to use it in Tink in the first place.

The new change will only tell you exactly what happened, as Tink shouldn't hide the error anymore. The best way to move forward on devices that are having problems is to disable Android Keystore, by not setting a master key URI. Again, existing data will be lost but new data should be safe.

**Comment by simtse** [comment]
Thanks @thaidn I'll bring this back to my team and I'll need to internalize what this means for us and our users. But sounds like if we set a master key, then Tink will try to continue to use the Android keystore. But if not, then it will use Tink with the keyset saved in SharedPreferences as clear text.

> 2/ Tink will only generate a new keyset or a new master key if there's no existing key material. Currently Tink attempts to generate a new keyset or a new master key whenever it can't read the existing key material. This behavior is useful in certain cases, but it hides the actual problems in Android Keystore from Tink users.

I think this was happening to me because it coudln't read the key material, but there wasn't any extra feedback or callback to notify my code that this regeneration happened. Are you suggesting that there will be an API change to notify the callers that this regeneration or what happened underneath so the calling code can make adjustments?

**Comment by thaidn** [comment]
https://github.com/google/tink/releases/tag/v1.4.0 was released a few minutes ago. It includes several, backward-compatible changes to the Android Keystore integration. Please consult the release notes.

>I think this was happening to me because it coudln't read the key material, but there wasn't any extra feedback or callback to notify my code that this regeneration happened. Are you suggesting that there will be an API change to notify the callers that this regeneration or what happened underneath so the calling code can make adjustments?

As explained in the [Javadoc](https://google.github.io/tink/javadoc/tink-android/1.4.0/com/google/crypto/tink/integration/android/AndroidKeysetManager.html):

- If the key material doesn't exist, and you tell Tink to generate a new one (by specifying a key template), Tink will generate one. If the key material does exist, but is corrupt, Tink will throw `InvalidKeyException`.

- If the master key in Android Keystore doesn't exist, and you tell Tink to generate a new one (by specifying a master key URI), Tink will generate a new one. If the master key does exist, but is unusable, Tink will throw `KeyStoreException`.

Please comment if you have any other questions.
