### ISSUE TITLE
Hybrid Go private key manager wrong key validation checks

### ISSUE THREAD

**Issue by Baha-sk** [google/tink#324]
https://github.com/google/tink/blob/master/go/hybrid/ecies_aead_hkdf_private_key_manager.go#L174

at the line stated above, the two following conditions are not comparing to the right string value:
```
	if strings.Compare(params.KemParams.HkdfHashType.String(), "HashType_UNKNOWN_HASH") == 0 {
		return errors.New("hash unsupported for HMAC")
	}

	if strings.Compare(params.EcPointFormat.String(), "EcPointFormat_UNKNOWN_FORMAT") == 0 {
		return errors.New("unknown EC point format")
	}
```

The string representation for the Unknown HashType value is mentioned here: https://github.com/google/tink/blob/master/go/proto/common_go_proto/common.pb.go#L114:
`"UNKNOWN_HASH"`

and the same for Unknown EC Point format value is found here:
https://github.com/google/tink/blob/master/go/proto/common_go_proto/common.pb.go#L82:
`"UNKNOWN_FORMAT"`

I think it makes more sense to replace these two conditions with:
```
	if params.KemParams.HkdfHashType.String() == commonpb.HashType_UNKNOWN_HASH.String() {
		return errors.New("hash unsupported for HMAC")
	}

	if params.EcPointFormat.String() == commonpb.EcPointFormat_UNKNOWN_FORMAT.String() {
		return errors.New("unknown EC point format")
	}
```

**Comment by thaidn** [comment]
Good catch! I'm fixing this.

**Comment by thaidn** [comment]
Unfortunately, the fix is easy but it needs a lot of tests. I don't have cycles atm.

@chuckx another Go task for you to take.

**Comment by juergw** [comment]
I think I fixed this in https://github.com/google/tink/commit/57746da75a4d1a80be1ad2a94a256660b92a9de2, without realizing that there is an open issue for this.
