### ISSUE TITLE
Go: bad signature verification from keyset.Handle created from raw []byte public key

### ISSUE THREAD

**Issue by Baha-sk** [google/tink#325]
When signing a message with a normally created keyset.Handle from Tink, a prefix is appended to the signature.

If the public key is exchanged with a receiver in raw []bytes (ie marshalled elliptic curve bytes) and the receiver tries to create keyset.Handle from these raw bytes (by pre-building the associated protobuf for the given curve used in the signature) then verifies the signature, it fails since raw type does not have a prefix.

Particularly, this code snippet for raw keys fails (from Verify() in `go/signature/verifier_factory.go`):
```
	// try raw keys
	entries, err = v.ps.RawEntries()
	if err == nil {
		for i := 0; i < len(entries); i++ {
			var verifier = (entries[i].Primitive).(tink.Verifier)
			if err = verifier.Verify(signature, data); err == nil {
				return nil
			}
		}
	}
```

It fails because signing was done with valid Tink created keyset.Handle which has Key.OutputPrefixType = `tinkpb.OutputPrefixType_TINK`

But for verification, as the recipient has only the []bytes representing the raw marshalled EC key value, tinkpb.Keyset_key is built with OutPrefixType = `tinkpb.OutputPrefixType_RAW` and KeyId = 1 (the recipient does not know of KeyId, we just default it to 1 for the purpose of key verification).

A possible fix I can think of this is to run Verify() with the prefix trimmed (for raw keys only) and return nil if successful (I have tried it locally and it does return a successful verification). Here is the updated code snippet for raw keys for this fix:
```
	// try raw keys
	entries, err = v.ps.RawEntries()
	if err == nil {
		for i := 0; i < len(entries); i++ {
			var verifier = (entries[i].Primitive).(tink.Verifier)
			if err = verifier.Verify(signature, data); err == nil {
				return nil
			}

			if len(signature) > cryptofmt.NonRawPrefixSize {
				// try signature by stripping NonRaw Prefix
				strippedSig := signature[cryptofmt.NonRawPrefixSize:]
				if err = verifier.Verify(strippedSig, data); err == nil {
					return nil
				}
			}
		}
	}
```

**Comment by Baha-sk** [comment]
Any feedback is welcome, I will be happy to submit a PR for this.

I need this fix urgently, if Tink folks can provide me with an answer soon, it would be much appreciated.

**Comment by thaidn** [comment]
Hi there,

Your proposal introduces a potential malleability issue. That is, someone can forge a new signature by prepending 5 arbitrary bytes to an existing raw signature.

The cleanest solution is to use `tinkpb.OutputPrefixType_RAW` when signing. This can be achieved by adding key templates with tinkpb.OutputPrefixType_RAW, similar to how we did in Java. Can you send a PR to do that? You'd have to re-generate your private keys.

[1] https://github.com/google/tink/blob/master/java/src/main/java/com/google/crypto/tink/signature/SignatureKeyTemplates.java#L211

**Comment by Baha-sk** [comment]
I see, so instead we should support a new key template type for OutputPrefixType_RAW instead of the default OutputPrefixType_TINK one in Go?

Sure, I'll update the key templates and create a new one like this one:
https://github.com/google/tink/blob/master/java/src/main/java/com/google/crypto/tink/signature/SignatureKeyTemplates.java#L155

any specific reason why only one key template is created without prefix in Java? `ECDSA_P256_IEEE_P1363_WITHOUT_PREFIX` 
ie, why isn't there `ECDSA_P512_IEEE_P1363_WITHOUT_PREFIX` or even `ECDSA_P256_IEEE_DER_WITHOUT_PREFIX` ?

I'm just wondering if we should support only P256 curve in Go as well.

Also, from what I see in Go signature package, it only supports DER key format, not IEEE_P1363. I hope this is not an issue.

Thanks for the prompt response @thaidn. I'm fine with regenerating the private keys for now.

**Comment by Baha-sk** [comment]
I will submit a PR with the addition of `...WithoutPrefixTemplate()` for all the ECDSA keys under Go's signature package.

**Comment by Baha-sk** [comment]
Please review the PR I pushed a minute ago.
