### ISSUE TITLE
Unable to compile Tink for CPP with Bazel on RHEL 7.7

### ISSUE THREAD

**Issue by skb2005** [google/tink#327]
I am unable to compile tink on RHEL 7.7. I have managed to install bazel 2.1.1.

```
git clone https://github.com/google/tink
cd tink/cc
bazel build -c opt :libtink.so
```
I am getting the following error message

ERROR: Skipping ':libtink.so': no such target '//:libtink.so': target 'libtink.so' not declared in package '' defined by /home/username/tink/cc/BUILD.bazel
WARNING: Target pattern parsing failed.
ERROR: no such target '//:libtink.so': target 'libtink.so' not declared in package '' defined by /home/username/tink/cc/BUILD.bazel
INFO: Elapsed time: 0.110s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by tholenst** [comment]
Thanks for the report; I removed linktink.so recently because there was some potential for UB in case it was linked in with different versions of Abseil. Is it possible for you to avoid using it? Otherwise, can you explain how you are using it, so we can work on finding a replacement?

**Comment by thaidn** [comment]
Please comment if you still need help on this. I'll reopen the bug if necessary.
