### ISSUE TITLE
StreamingAead#newDecryptingStream() not support null as associatedData

### ISSUE THREAD

**Issue by marco-boeck** [google/tink#328]
The opposite StreamingAead#newEncryptingStream(out, null) is fine with passing null as associated data (it is simply not used then), but the decrypting stream explodes with a NullPointerException when trying that. This makes the APIs not consistent and forces the user to either use a dummy associatedData, or try a mitigation strategy of an empty byte[] array instead.

streamingAead.newDecryptingStream(in, null) ->

java.lang.NullPointerException
	at com.google.crypto.tink.streamingaead.InputStreamDecrypter.<init>(InputStreamDecrypter.java:75)
	at com.google.crypto.tink.streamingaead.StreamingAeadHelper.newDecryptingStream(StreamingAeadHelper.java:76)

version 1.3.0-rc4

**Comment by thaidn** [comment]
@bleichen Daniel, do you think we should accept null associated data and make it equivalent to an empty array?

This is the behavior of other APIs such as AEAD.

**Comment by bleichen** [comment]
I still don't understand why the AEAD interface has been changed to accept
null for the AD and still think that there are some reasons not to do so:
(1) promoting the AD: Additional data can be used to prevent that
ciphertexts encrypted with the same key are switched, by binding the
ciphertext to some context.
(2) errors: It is unfortunately still quite common to return null in cases
where throwing an exception would be more appropriate. Not accepting null
would therefore be a bit more robust.
(3) ambiguities: null and "" have often not the same meaning. There are
ciphers that distinguish between no AD and an AD with value "". AES-SIV
(RFC 5297) is one such cipher. Hence, treating null and "" as the same adds
a small incompatibility.

**Comment by marco-boeck** [comment]
I would be fine with not accepting null, I just expected the APIs to behave consistently between the different primitives which share signatures.

At the very least I would expect an IllegalArgumentException when calling with null if that's not supported, instead of a random NPE somewhere down the line.

**Comment by thaidn** [comment]
Yeah it looks like a mistake treating null equal to empty. I can't recall the reason, but it seems that most people don't know what additional data to use and end up wanting to use an empty value, so the change was made to make their life easier. In Tink 2.x we may be able to revert this, but in the meantime I guess we have to live with it.

@marco-boeck IllegalArgumentException is also an unchecked exception. I'm not sure why it is better than NPE. The exception would be thrown earlier, but it still needs to be handled anyway. I think GeneralSecurityException or InvalidAlgorithmParameterException might be more appropriate, but honestly I'm not sure.

@tholenst wdyt?

**Comment by tholenst** [comment]
Not sure about this.

If we don't want to accept null, I think the best way would be to call Guava's checkNotNull [1]. Since Guava is the standard for this kind of thing for Google libraries, this will be most consistent. This still throws a NPE, but we would do so immediately at the beginning of the function.

We would probably implement it ourselves though, in order to avoid the dependency in prod code.

https://guava.dev/releases/snapshot/api/docs/com/google/common/base/Preconditions.html#checkNotNull-T-

**Comment by tholenst** [comment]
I will close due to inactivity. If this is still an issue, please open a new issue in tink-crypto/tink-java.
