### ISSUE TITLE
KDF support

### ISSUE THREAD

**Issue by rbroggi** [google/tink#333]
Hi, 

Are there any plans to support KDFs in the library? Is there anywhere where we can check the goals of the lib along with it's priorities?

**Comment by thaidn** [comment]
Hi there, what do you want to do with KDFs?

If you have a master key and want to derive sub keys from it, we have some support for this, but it's not open source yet.

@tholenst is it possible to open source the key derivation primitive?

**Comment by rbroggi** [comment]
Dear @thaidn,

In the context of some payment methods (e.g.: Apple Pay / Google Pay) key derivation functions are used to derive symmetric keys for cipher decryption. This is just one of the things that comes to my mind. Recently I've developed a whole cpp application component (with openSSL) that handles apple pay detokenization, this operation foresees many cryptographic operations, as can be described [here](https://developer.apple.com/library/archive/documentation/PassKit/Reference/PaymentTokenJSON/PaymentTokenJSON.html). I was wondering if tink had plans to support cryptographic operations as key derivation, PKCS7 signature/verification and so on. 

Thank you,

Rodrigo

**Comment by thaidn** [comment]
Supporting crypto standards like Apple Pay fits within our vision for Tink. Unfortunately, we're stretching very thin and won't be able to work on it in the foreseeable future.
