### ISSUE TITLE
Can files encrypted using Tink be decrypted by other programs or libraries?

### ISSUE THREAD

**Issue by vahidpaz** [google/tink#335]
I'd like to invest in using Tink to encrypt binary files. If at some point in the future I decide that I don't want to use Tink anymore, can I easily switch over to a new encryption program without having to modify my Tink-encrypted files? In other words, are encrypted Tink files "compatible" with any other tool such as [gpg](https://gnupg.org/), [jasypt](http://www.jasypt.org/), [libsodium](https://libsodium.gitbook.io/doc/), openssl, or whatever else?

If I want to move away from Tink, there's always the option of decrypting all my files using Tink, and then re-encrypting them using my new tool of choice... but that is laborious given the amount of data that I have.

thx!

**Comment by thaidn** [comment]
Unfortunately, no.

We might produce a mode that is compatible with libsodium, but at the moment it's not of high priority.

**Comment by vahidpaz** [comment]
Okay thanks for the info. I can see that AesGcmJce saves encrypted data in a clean format that I can manipulate later. For those who don't know, look at AesGcmJce.encrypt():

IV + encrypted_data + GCM_TAG

**Comment by mobitar** [comment]
> Unfortunately, no.

@thaidn is this still the case? I noticed in `KeyTemplate rawXChaCha20Poly1305Template` the comment:

```
@return a {@link KeyTemplate} that generates new instances of XChaCha20Poly1305 keys. Keys
   *     generated from this template create ciphertexts compatible with libsodium and other
   *     libraries.
```

which mentions compatibility with libsodium.
