### ISSUE TITLE
Go - avoid panics when using wrong keyset.Handle on a primitive

### ISSUE THREAD

**Issue by Baha-sk** [google/tink#336]
This is especially true for signerSet, verifierSet (signing primitives) and primitiveSet for MAC primitive.

The issue is when creating a new Signer or Verifier primitive for instance with a bad `*keyset.Handle` type (say AES128GCM), the primitive function panics as it tries to convert (or cast in Java terms) the primitive instance to the corresponding primitive type.

Examples of unchecked primitive type are:
https://github.com/google/tink/blob/master/go/signature/signer_factory.go#L60
https://github.com/google/tink/blob/master/go/signature/verifier_factory.go#L79
https://github.com/google/tink/blob/master/go/signature/verifier_factory.go#L89
https://github.com/google/tink/blob/master/go/mac/mac_factory.go#L58
https://github.com/google/tink/blob/master/go/mac/mac_factory.go#L85
https://github.com/google/tink/blob/master/go/mac/mac_factory.go#L95

Other primitives might also have the same issue.

A possible solution to this is to add the optional second `ok` bool to confirm the type check right at these lines. An example would be (first example above):
```
	signer, ok := (primary.Primitive).(tink.Signer)
	if !ok {
		return nil, fmt.Errorf("invalid signer keyset primitive")
	}
```

Another solution is to verify the primary primitiveset of the `*keyset.Handle` argument passed to New...() and return an error before the primitive function is called. This means, for the same signer example above, we would rather change `newSignerSet` to be:
```
func newSignerSet(ps *primitiveset.PrimitiveSet) (*signerSet, error) {
	ret := new(signerSet)
	if _, ok := (ps.Primary.Primitive).(tink.Signer); !ok {
		return nil, fmt.Errorf("invalid signer keyset primitive")
	}

	ret.ps = ps
	return ret, nil
}
```
and remove `, nil` in the return of `NewSignerWithKeyManager()`

This way, calling Sign() will be forcibly using a valid primitive type.

Need this fixed to avoid the library to panic when users pass in invalid `*keyset.Handle` types to the primitive.

I can submit a PR, but need to know what approach to use, change New....(), change Sign() or even both? Thoughts?

**Comment by Baha-sk** [comment]
I submitted a PR.

In the PR, I decided to add the `ok` in the new Primitiveset function as well as in the primitive function. It is best to always check for the type to avoid panics at all costs to prevent user applications from panicking when if they set wrong `*keyset.Hanle`s.

**Comment by tholenst** [comment]
This is merged internally and will be here next time we push. Thanks for the contribution.
