### ISSUE TITLE
Android (tink : 1.3.0-rc3) KeyStoreException + UnrecoverableKeyException 

### ISSUE THREAD

**Issue by ArjunAchatz** [google/tink#339]
Hello, 

I'd like to report the follow exceptions happening with Android; we are using 1.3.0-rc3. I am not able to reproduce these issues; however they have been seen in the wild. 

OS Issue observed : Android 6,7,8,9
Devices : Samsung Galaxy S6, S7 edge. LG g4, g5, g6

**KeyStoreException (Invalid Key Blob)** with stack trace : 

android.security.KeyStore.getKeyStoreException (KeyStore.java:708)
android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreSecretKeyFromKeystore (AndroidKeyStoreProvider.java:283)
android.security.keystore.AndroidKeyStoreSpi.engineGetKey (AndroidKeyStoreSpi.java:98)
java.security.KeyStore.getKey (KeyStore.java:1062)
com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.<init> (AndroidKeystoreAesGcm.java:48)
com.google.crypto.tink.integration.android.AndroidKeystoreKmsClient.getAead (AndroidKeystoreKmsClient.java:111)
com.google.crypto.tink.integration.android.AndroidKeystoreKmsClient.getOrGenerateNewAeadKey (AndroidKeystoreKmsClient.java:130)
com.google.crypto.tink.integration.android.AndroidKeysetManager.<init> (AndroidKeysetManager.java:118)
com.google.crypto.tink.integration.android.AndroidKeysetManager.<init> (AndroidKeysetManager.java:88)
com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build (AndroidKeysetManager.java:185)
com.loblaw.pcoptimum.android.app.utils.Crypto$AEAD.getAndroidKeysetManager (Crypto.java:204)

**KeyStoreException (Unknown error)** with stack trace : 

android.security.KeyStore.getKeyStoreException (KeyStore.java:1107)
android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreSecretKeyFromKeystore (AndroidKeyStoreProvider.java:283)
android.security.keystore.AndroidKeyStoreSpi.engineGetKey (AndroidKeyStoreSpi.java:98)
java.security.KeyStore.getKey (KeyStore.java:825)
com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.<init> (AndroidKeystoreAesGcm.java:48)
com.google.crypto.tink.integration.android.AndroidKeystoreKmsClient.getAead (AndroidKeystoreKmsClient.java:111)
com.google.crypto.tink.integration.android.AndroidKeystoreKmsClient.getOrGenerateNewAeadKey (AndroidKeystoreKmsClient.java:130)
com.google.crypto.tink.integration.android.AndroidKeysetManager.<init> (AndroidKeysetManager.java:118)
com.google.crypto.tink.integration.android.AndroidKeysetManager.<init> (AndroidKeysetManager.java:88)
com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build (AndroidKeysetManager.java:185)

**UnrecoverableKeyException (-49)** with stack trace : 

android.security.KeyStore.getKeyStoreException (KeyStore.java:839)
android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics (AndroidKeyStoreProvider.java:236)
android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyFromKeystore (AndroidKeyStoreProvider.java:356)
android.security.keystore.AndroidKeyStoreSpi.engineGetKey (AndroidKeyStoreSpi.java:101)
java.security.KeyStore.getKey (KeyStore.java:1062)
com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.<init> (AndroidKeystoreAesGcm.java:48)
com.google.crypto.tink.integration.android.AndroidKeystoreKmsClient.getAead (AndroidKeystoreKmsClient.java:111)
com.google.crypto.tink.integration.android.AndroidKeystoreKmsClient.getOrGenerateNewAeadKey (AndroidKeystoreKmsClient.java:130)
com.google.crypto.tink.integration.android.AndroidKeysetManager.<init> (AndroidKeysetManager.java:118)
com.google.crypto.tink.integration.android.AndroidKeysetManager.<init> (AndroidKeysetManager.java:88)
com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build (AndroidKeysetManager.java:185)

**Comment by thaidn** [comment]
Yeah this is a known issue with Android Keystore. A small number of Android devices were shipped with broken Keystore implementations.

Do you know the Android versions and device models where this happened?

**Comment by ArjunAchatz** [comment]
Yes I can give you a more detailed list : 

Note: LG phones account for 40%, Samsung 36% of the errors we've logged

Samsung Galaxy S6 - Android 7
Samsung Galaxy Note 4 - Android 6.0.1
Samsung Tab S2 - Android 7
LG G4 - Android 6
LG G5 - Android 7
LG G6 - Android 9
OnePlus3T - Andriod 9
ZenFone 3 Max (ZC520TL) - Android 8.1.0

**Comment by thaidn** [comment]
Thanks.

We plan to add a self-test to detect if Android Keystore is broken. If it is, we bail and just store the keys in private shared preferences. It is less secure, but it's better than nothing.

**Comment by thaidn** [comment]
>Also when you implementing this, will there be a way to know that Keystore failed, and that SharedPreferences was used ?

Good question. I'm not sure. How's about a log statement?

**Comment by simtse** [comment]
We are asking the same question now that we are finding similar reports as @ArjunAchatz that there will be devices that just won't be able to have a stable keystore. Any progress on this other than a log statement? Is there something in the `KeysetHandle` that can return what type of storage is used for the keys?

**Comment by simtse** [comment]
@thaidn Other than using the private shared preferences, is there a way to reset the key that the `AndroidKeystoreAesGcm` uses? For example, if the result of not being able to read the keyset means cleaning user data in the app, the underlying key created by Tink for the app in the Android keystore would probably still be broken.

But if Tink had a mechanism to clear/reset/remove the key from the Android keystore, then the user wouldn't need to fully reinstall the app in order to start with a fresh key in the key store.

**Comment by thaidn** [comment]
@simtse does https://developer.android.com/reference/java/security/KeyStore#deleteEntry(java.lang.String) work for you? This will delete the master key.

**Comment by simtse** [comment]
Yes I probably could do that. Seems like an implementation detail to know to remove the prefix `"android-keystore://` inside of `AndroidKeystoreKmsClient`. So I think I've heard of some consumers of Tink remove directly like this, but it seems like a more extreme case that should be done in conjunction with Tink so the keyset could be reset along with a new Android keystore key. 

I don't mind removing as you suggested, but I'm also curious what you think about putting some mechanism in the future for this kind of reset of the master key. 

Slightly similar, but separate question. If Tink fails to decrypt the keyset with the Android keystore,  [does it just create a brand new Keyset](https://github.com/google/tink/blob/master/java_src/src/main/java/com/google/crypto/tink/integration/android/AndroidKeysetManager.java#L361-L366) and stores it into the shared preferences?

**Comment by thaidn** [comment]
@simtse our release candidates are pretty stable. At Google everybody uses Tink at HEAD, and public release candidates are built from HEAD.

>Also when you implementing this, will there be a way to know that Keystore failed, and that SharedPreferences was used ?

We're adding a isUsingKeystore() method to AndroidKeysetManager.

>I don't mind removing as you suggested, but I'm also curious what you think about putting some mechanism in the future for this kind of reset of the master key.

How's about a `delete(String keyUri)` method in AndroidKeystoreKmsClient?

>Slightly similar, but separate question. If Tink fails to decrypt the keyset with the Android keystore, does it just create a brand new Keyset and stores it into the shared preferences?

No, if it can decrypt it assumes that the keyset is in cleartext.

**Comment by msfjarvis** [comment]
OP mentioned OnePlus 3T on Android 9 as a broken device and while the self-test from the `master` branch passes on it (verified independently with a sample app), the device still appears to not have a usable KeyStore implementation (https://github.com/android-password-store/Android-Password-Store/issues/1144). Is there anything we can do here?

**Comment by msfjarvis** [comment]
Hey @thaidn do you have anything else we can try?

**Comment by RomanMinenok** [comment]
@thaidn `androidx.security:security-crypto:1.0.0-rc04` which uses Tink 1.5 still has this issue. So did you add a fallback to use regular shared preferences in case something like this happens or decided not to do it?
