### ISSUE TITLE
JOSE/JWE support

### ISSUE THREAD

**Issue by Baha-sk** [google/tink#342]
I noticed there's an empty [jose](https://github.com/google/tink/tree/master/apps/jose) folder in Tink.

I'm wondering how one would use Tink primitives to create serialized JWEs with say ECDH-ES key wrapping.

What's the best approach? 

Tink's AEAD primitives use symmetric keys for Encrypt/Decrypt by hiding the nonce.
Tink's Hybrid primitives are rightfully using asymmetric key and generating an ephemeral key then computing an HKDF derived key then returning a serialized []byte. Although it could be similar to ECHD-ES key wrapping, but it's different in nature and JWE needs to support multiple recipients as opposed to only one.

Would someone explain the approach to build a secure JWE message in Tink? 

Is creating new Tink primitives for JWE a better option or do these steps manually:
1. Use Tink's AEAD with a generated symmetric CEK (content encryption key) to call Encrypt() on plaintext and aad.
2. Extract the nonce and tag manually from the resulting ciphertext of Encrypt() call in 1 above (not safe and, I believe, not recommended by Tink authors).
3. Do key wrapping outside of Tink for each recipient. (I don't see an option in Tink to do key wrapping although I've seen kwp was recently added in Go, but it's minimal at this point and believe it's only used by hybrid primitive?)

I would like to know what's the best approach and if there are hints/pointers I can use from the Tink experts.

I'm working in Go. I believe folks would love to see the same for other languages as well, but my main focus is on how to implement this in Go.

**Comment by thaidn** [comment]
Hi there,

We don't actually plan to support JWE, but only JWS.

Why do you need JWE?

**Comment by Baha-sk** [comment]
We've built a communication protocol for Hyperledger Aries agents in Go called DIDComm (project is [here](https://github.com/hyperledger/aries-framework-go)). We will also be using JWE for protecting DID documents persistence in other related projects.

JWE is used for protocol encryption, JWS is used to msg signing/verification namely to authenticate a document owner and issuer.

I've built a new Tink key template and primitive similar to `Hybrid` to create the crypto related artifacts for JWE envelopes (ie ciphertext, iv, tag, recipients protected crypto material) using ECDH-ES key wrapping, but it's still wip. It's in the project mentioned above. Once it's ready for use, I'll probably post a link here.

**Comment by Baha-sk** [comment]
The key template is now available @thaidn in our repo.

I've called it `composite` because, similarly to `hybrid` it wraps keys but also allows for extensions with new algorithms/key wrapping methods:
https://github.com/hyperledger/aries-framework-go/tree/master/pkg/crypto/tinkcrypto/primitive/composite

The Encrypt output is a marshalled JSON containing the necessary info to build a JWE message. 

Package `ecdhes` contains key templates for key wrapping using a256kw alg +AES256GCM content alg which is the only key wrapping algorithm supported for now. I've used go-jose's key wrapping [here](https://github.com/hyperledger/aries-framework-go/blob/master/pkg/crypto/tinkcrypto/primitive/composite/ecdhes/subtle/ecdhes_concatkdf_sender_kw.go#L48) but I believe I can use Tink's KWP probably. I'll have to compare the two and see.

I'm looking to add chacha content encryption + X25519 key wrapping in the near future. I believe this is not in the JWE specs (yet).

Eventually I'm intending to implement a new key wrapping algorithm called the 1 pass unified model or ECDH-1PU for short (draft [here](https://tools.ietf.org/html/draft-madden-jose-ecdh-1pu-03)). This would allow to securely authenticate the sender.

So `ecdh1pu` will be sitting next to ecdhes implementation above, hence the name `composite` for the key template.

To use the new key templates, I have incorporated them into our jwe package, see [here](https://github.com/hyperledger/aries-framework-go/blob/master/pkg/doc/jose/encrypter_decrypter_test.go#L30) for JWE unit tests.

You can also find interop tests with go-jose using the new key templates and ECDH-ES with `a256kw` [here (encrypt in go-jose and decrypt in Tink](https://github.com/hyperledger/aries-framework-go/blob/81d7c3a237e519f034d5db11592b08b75417b982/pkg/doc/jose/encrypter_decrypter_test.go#L165) and [here (encrypt in Tink and decrypt in go-jose)](https://github.com/hyperledger/aries-framework-go/blob/81d7c3a237e519f034d5db11592b08b75417b982/pkg/doc/jose/encrypter_decrypter_test.go#L201)

If this is peeks the interest of the community, I can submit a PR.

**Comment by thaidn** [comment]
Thanks for the offer @Baha-sk. It's unlikely that we're going to support JWE. We don't like JWT, but there's a subset of it that can be made secure and, fortunately, that's all most people need. We plan to support only that part.
