### ISSUE TITLE
Unable to to use asw kms keys with tink

### ISSUE THREAD

**Issue by fulcimus** [google/tink#344]
Hello:

I'm trying to use tink with a Spring boot project but I'm getting stuck.  I keep getting an "invalid encrypted keyset" error.  This error occurs when I try to read the json keyset file.  My json file looks like this: {"accessKey":"ABCDEFG","secretKey":"123456789"}.  Can anyone point out what I'm doing wrong?  Thanks.

**Comment by thaidn** [comment]
Can you provide a snippet or something?

**Comment by fulcimus** [comment]
Hi Thai:
 Here's my code.  It's just like the example code.  It errors at JsonKeysetReader reading my_keyset.json.  The my_keyset.json looks like this: {"accessKey":"ABCDEFG","secretKey":"123456789"}.

        AeadConfig.register();

        String masterKeyUri = "aws-kms://" + kmsKeyId;
        String keysetFilename = "/resources/my_keyset.json";

        KeysetHandle keysetHandle = KeysetHandle.read(JsonKeysetReader.withFile(new File(keysetFilename)), new AwsKmsClient().getAead(masterKeyUri));

        Aead aead = keysetHandle.getPrimitive(Aead.class);
        String aad = "test";

        byte[] encryptedTextBytes = null;
        encryptedTextBytes = aead.encrypt(inputdata, aad.getBytes());

**Comment by thaidn** [comment]
Your keyset looks wrong. It looks like an AWS credential, not a Tink keyset. 

To read this credentials, use https://github.com/google/tink/blob/master/java/src/main/java/com/google/crypto/tink/integration/awskms/AwsKmsClient.java#L80.

Please reopen if this still doesn't work.
