### ISSUE TITLE
TInky build issue on Fedora

### ISSUE THREAD

**Issue by bfloch** [google/tink#345]
Following the instructions on how to build tinkey I eventually got:
> failed to create directory /home/username/.ccache/tmp: Read-only file system

Fixed by:
```sh
mkdir -p ~/.ccache
bazel build tinkey --sandbox_writable_path ~/.ccache
```
If applicable, maybe worth mentioning it in the docs at:

https://github.com/google/tink/blob/master/docs/TINKEY.md

Thanks.

**Comment by thaidn** [comment]
Thanks. Can you send us a PR?

**Comment by thaidn** [comment]
Now you don't have to build Tinkey yourself, but you can install with Homebrew.

On your Linux box, run

```
brew tap google/tink https://github.com/google/tink
brew install tinkey
```
