### ISSUE TITLE
Using tinkey tool with custom KMS

### ISSUE THREAD

**Issue by shkdmhhb** [google/tink#346]
If one develops custom inhouse KMS for tink, how does one register it with tinkey tool to use it to encrypt the key set generated?

**Comment by thaidn** [comment]
Tinkey can automatically search and load instances of the KmsClient interface in the current classpath. See:
https://github.com/google/tink/blob/master/java/src/main/java/com/google/crypto/tink/KmsClient.java
https://github.com/google/tink/blob/master/java/src/main/java/com/google/crypto/tink/KmsClients.java#L76

Note that we don't do this at Google. Our in-house KMS can actually generate/rotate Tink keysets on its own. This is safer than generating keys outside the KMS. We then develop a KeysetHandle class to directly load keysets from the KMS.

Hope this helps. Please reopen if you have any other questions.
