### ISSUE TITLE
Go hybrid encrypt factory contains debug log

### ISSUE THREAD

**Issue by weitzj** [google/tink#349]
The line https://github.com/google/tink/blob/master/go/hybrid/hybrid_encrypt_factory.go#L47 prints a string similar to:

```
type is: &{0xc000389cc0 [] SHA256 UNCOMPRESSED 0xc00058d770}
```

This messes up any usage of google/tink where you want to have pipes in a shell script, wrapping google/tink and using `stdout, stdin` 

Could you delete any `fmt` logs, which mess up the console output.

Using tink as a library, which has a side-effect on `fmt` is not practical.

**Comment by tholenst** [comment]
Thanks for the report; fix is in work.
