### ISSUE TITLE
Java source build error in Windows 10 

### ISSUE THREAD

**Issue by jimi-pz** [google/tink#351]
I'm getting an error about **javalite_toolchain** while trying to build java sources via bazel. 
my proto-buffer is 3.11.4v;
bazel is 3.0.0v;
java version "1.8.0_251";
Java(TM) SE Runtime Environment (build 1.8.0_251-b08).

I'd appreciate any help!

**ERROR**: C:/users/jimi/_bazel_jimi/n4ofdyla/external/tink_base/proto/BUILD.bazel:195:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf//:javalite_toolchain', but this target could not be found because of: no such target '@com_google_protobuf//:javalite_toolchain': target 'javalite_toolchain' not declared in package '' (did you mean 'java_toolchain'?) defined by C:/users/jimi/_bazel_jimi/n4ofdyla/external/com_google_protobuf/BUILD

**ERROR**: C:/git/tink/java_src/proto/BUILD.bazel:113:1: every rule of type java_lite_proto_library implicitly depends upon the target '@com_google_protobuf//:javalite_toolchain', but this target could not be found because of: no such target '@com_google_protobuf//:javalite_toolchain': target 'javalite_toolchain' not declared in package '' (did you mean 'java_toolchain'?) defined by C:/users/jimi/_bazel_jimi/n4ofdyla/external/com_google_protobuf/BUILD

**ERROR**: Analysis of target '//proto:aes_ctr_java_proto_lite' failed; build aborted: Loading failed

**Comment by tholenst** [comment]
This is probably due to https://github.com/bazelbuild/bazel/issues/10335, meaning that we will need to update something within Tink for bazel 3.

Until then, plase use with bazel 2.

**Comment by jimi-pz** [comment]
Thanks, it builds with bazel 2.
