### ISSUE TITLE
Using Tink with an existing raw key

### ISSUE THREAD

**Issue by overheadhunter** [google/tink#353]
Sorry for opening an issue for this, I have the gut feeling that this should already be answered, but I don't find it.

Is there any chance to use Tink primitives with an already existing key that is available in my program as a raw byte array?

It seems like KeyHandles can only be created _within_ Tink and then only be serialized to Tink-specific formats. I didn't find any way to import raw key material that I received from 3rd parties. This would be a shame, since I definitely want to avoid reinventing the wheel when it comes to implementation of cryptographic primitives.

**Comment by thaidn** [comment]
Hi there, you can use the *subtle* APIs which accept raw key material.

We don't allow this in the main APIs because we don't want our users to store keys in code. We want to encourage people to store keys in key management systems.

Hope this helps. Please reopen if you have any other questions.

**Comment by overheadhunter** [comment]
I should have added, that I want to use Tink's ObjC-Bindings in a Swift project. Maybe I'm just blind, but I don't think subtle is even publicly accessible (other than in Java).

While I understand that using subtle bears the risk of unsafe use, it is still a shame that by hiding these APIs Google effectively makes developers to use other (potentially incorrect or untested) implementations.

No possible way to get around a KeysetHandle and just use the primitives. If I'm mistaken, I'd be grateful for any hint on how to use the API.

(also, I only repo owners can reopen issues)

**Comment by thaidn** [comment]
Can you call C++? The subtle APIs can be found at https://github.com/google/tink/tree/master/cc/subtle.

Alternative you can also implement a KeysetReader that converts a raw key into a Keyset and call the main APIs with that.

**Comment by overheadhunter** [comment]
I'm not an expert on this field, but it seems like calling c++ functions [requires a wrapper](https://stackoverflow.com/a/35230973/4014509).

Implementing a custom KeysetReader isn't as easy either, as again the API seems to be internal (in Swift it is just an empty interface with no methods defined).

I guess this issue has to be rephrased: How to use subtle in Objc/Swift.

**Comment by tholenst** [comment]
I'm sorry but this is currently not supported. I understand this answer is not optimal, but we currently don't even have time to properly support what we have in ObjC, so adding the whole subtle library into Objective C is not possible right now.

**Comment by overheadhunter** [comment]
@tholenst Thanks for the clarification. While not what I hoped for, at least this shows the scope and constraints of Tink. I was hoping to replace a variety of platform-specific high-level crypto wrappers by one single library, but at least today, this isn't what Tink can do for me.
I will watch the project and eventually give it a retry. Keep up the great work!
