### ISSUE TITLE
Error calling Tink.register() Android, when proguard is enabled

### ISSUE THREAD

**Issue by jcaiqueoliveira** [google/tink#357]
I got the following error:
```
 RuntimeException: 
Field configName_ for f.b.b.a.h0.g3 not found. Known fields are [private static final f.b.b.a.h0.g3 f.b.b.a.h0.g3.i, private static volatile f.b.d.a1 f.b.b.a.h0.g3.j]
        at f.b.d.v0.a(MessageSchema.java:608)
        at f.b.d.v0.a(MessageSchema.java:502)
        at f.b.d.v0.a(MessageSchema.java:221)
        at f.b.d.k0.a(ManifestSchemaFactory.java:85)
        at f.b.d.k0.a(ManifestSchemaFactory.java:71)
        at f.b.d.d1.a(Protobuf.java:93)
        at f.b.d.d1.a(Protobuf.java:107)
        at f.b.d.z$a.a(GeneratedMessageLite.java:419)
        at f.b.d.z$a.b(GeneratedMessageLite.java:414)
        at f.b.b.a.b0.a.<clinit>(TinkConfig.java:44)
        	... 63 more
```
when I was trying to call:
```
 TinkConfig.register()
```

To fix this error I added some rules to proguard and everthing works well

```
-keep class com.google.crypto.tink.proto.** { *;}
-dontwarn com.google.crypto.tink.proto.**
```

Is this the correct way to fix the error?

**Comment by tholenst** [comment]
Thanks for the report. There shouldn't be any special configuration needed for proguard; in fact needed. In fact, within Google we have tests which check that it works out of the box.

I suspect you might be running into troubles with different versions of proto which would imply the conflicts. This typically comes if you use another library in your binary which also uses proto.

That being said, I can imagine that your fix does do a proper fix, but I don't know enough about how proguard works to know for sure. (The weird thing is that the error message references the field "configName_", which seems to have not been mangled by proguard for whatever reason).

**Comment by jcaiqueoliveira** [comment]
Hey @tholenst thanks =)

Just trying to give more information about my case:

I was using tink 1.2.2 that uses **com.google.protobuf:protobuf-lite:3.0.1** and no proguard rules was needed. Now I'm using 1.4.0-rc1, the same case appears when using 1.3.0

Looking to my dependencies there is an another version of protobuf but used only for tests

```
 org.robolectric:shadows-framework:4.3.1
     |    +--- org.robolectric:annotations:4.3.1
     |    +--- org.robolectric:resources:4.3.1 (*)
     |    +--- org.robolectric:pluginapi:4.3.1 (*)
     |    +--- org.robolectric:shadowapi:4.3.1 (*)
     |    +--- org.robolectric:utils:4.3.1 (*)
     |    +--- org.robolectric:utils-reflector:4.3.1 (*)
     |    +--- androidx.test:monitor:1.2.0 (*)
     |    +--- com.almworks.sqlite4java:sqlite4java:0.282
     |    +--- com.ibm.icu:icu4j:53.1
     |    +--- com.google.android.apps.common.testing.accessibility.framework:accessibility-test-framework:2.1
     |    |    +--- org.hamcrest:hamcrest-core:1.3
     |    |    +--- org.hamcrest:hamcrest-library:1.3
     |    |    |    \--- org.hamcrest:hamcrest-core:1.3
     |    |    \--- com.google.protobuf:protobuf-java:2.6.1
```

**Comment by thaidn** [comment]
This is a known issue. We're working on a fix. It should be available in HEAD-SNAPSHOT next week and included in 1.4.0-RC2.

**Comment by thaidn** [comment]
This is fixed in HEAD-SNAPSHOT. Could you kindly try it out to see if it helps?

```
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}

dependencies {
    implementation 'com.google.crypto.tink:tink-android:HEAD-SNAPSHOT'
}
```

**Comment by thaidn** [comment]
This is a dup of #301. Let's move this discussion over there.
