### ISSUE TITLE
PyPI package for tink/python

### ISSUE THREAD

**Issue by masteusz** [google/tink#358]
Hi,
Would it be possible to push tink package to PyPI python repository?
Being able to do just `pip install tink` would solve a lot of my problems.

**Comment by thaidn** [comment]
Yeah we're working on this.

@kste

**Comment by willypicard** [comment]
Can you provide some timeline or a date for the PyPI package? Using Tink with Dataflow without a PyPI package is more than challenging...

**Comment by willypicard** [comment]
@thaidn, any update about a date for the PyPI package?

**Comment by kste** [comment]
We plan to release a package on the PyPi test repository in the next 2 weeks. 

Are there any specific binary wheels you would need for your target platform (e.g. Python 3.6 Linux)?

**Comment by masteusz** [comment]
In my use case I would like to run it on Google Dataflow with Python 3. I guess that 3.6 will be okay.

**Comment by willypicard** [comment]
Same case here.

**Comment by thaidn** [comment]
Willy and Mateusz, does the timeline work for you?

BTW would you mind sharing your use cases? We're very interested in how people are using Tink.

If you don't want to share here, please email me at thaidn@google.com. Thanks!

**Comment by masteusz** [comment]
Hey Thai,
No problem. We have a Dataflow pipeline that eventually will process sensitive data. Other parts of the workflow are written in Go and Scala and we had no issues with integrating with Tink, but I spent a week trying to make it working on Dataflow and failed.

I tried using the approach described here: https://github.com/apache/beam/blob/master/sdks/python/apache_beam/examples/complete/juliaset/setup.py
or 
https://gist.github.com/inchoate/bd0ff7f609f57c85d9de8ff9d5586e30

My code is basically the same, but I changed custom commands to:

```
CUSTOM_COMMANDS = [
    ['echo', '$PATH'],
    ['apt-get', 'update'],
    ['apt-get', '--assume-yes', 'install', 'git', 'gnupg', 'g++', 'unzip', 'zlib1g-dev'],
    ['wget', 'https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel-3.1.0-linux-x86_64'],
    ['chmod', 'a+x', 'bazel-3.1.0-linux-x86_64'],
    ['mv', 'bazel-3.1.0-linux-x86_64', '/bin/bazel'],
    ['pip', 'install', '--trusted-host', 'pypi.python.org', '--no-use-pep517',
     '--extra-index-url=<our custom repo>', 'tink']
]
```

- Overall Dataflow and Tink works with DirectRunner. All the problems I had were with the cloud run.
- I wasn't able to add package repo to sources.list in the worker. I guess it's a security measure. The only way to get `bazel` working was to download bin file and copy it to `/bin`. I don't know if that's a security issue or not :)
- Funnily enough `cd` command didn't work either, so I couldn't change my working directory and couldn't build the `tink` package itself. `bazel` wanted to be ran from the work dir.
- I tried using pip with git (`pip install git+https://...`), but because python package is in the common repo I wasn't able to point to only this one path.
- The last line in `CUSTOM_COMMANDS` is the biggest hack I guess. I built the custom package and uploaded it to our private PyPI repo. While trying to install it I got another error, here's the abridged version:
```
Complete output (7 lines):

Traceback (most recent call last):
File \"<string>\", line 1, in <module>
File \"/tmp/pip-install-ki9v9nuk/tink/setup.py\", line 216, in <module>
version=_get_tink_version(),
File \"/tmp/pip-install-ki9v9nuk/tink/setup.py\", line 34, in _get_tink_version
with open(os.path.join(here, \\'VERSION\\')) as f:
FileNotFoundError: [Errno 2] No such file or directory: \\'/tmp/pip-install-ki9v9nuk/tink/VERSION\\'\
 ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by masteusz** [comment]
Two weeks would definitely work for me, because I have a deadline a month from now :smile:

**Comment by willypicard** [comment]
My use case is an ML pipeline for textual file processing. Parts of the pipeline are related with basic text operations such as stopword removal or counting word frequencies. These parts are performed using Dataflow reading from files written on in gcs buckets.
As we are moving from synthetic data to production data, we need to secure the production data to avoid data leakage. So we encrypted to files when writing them to gcs in Go. Now we need to read the files back with the Dataflow modules of our ML pipeline.

We have a very aggressive schedule, with a delivery in 3 weeks. We are also considering wrapping the Go or Java implementation in Python but we would really like to avoid this and stick with a clean Python solution.

**Comment by tholenst** [comment]
Just to make sure we are on the same page: python should already work, you just need to currently download the source and call "pip install" on the directory.

The test script at https://github.com/google/tink/blob/master/kokoro/gcp_ubuntu_per_language/python/pip/run_tests.sh is run on a clean ubuntu 1604 instance with bazel installed, and it seems to work fine. So if you need a starting point which works, this can be used.

What doesn't work yet is to install Tink with "pip install tink".

**Comment by masteusz** [comment]
Hi @tholenst,
It did work for me locally, but not in cloud run in Dataflow.

**Comment by kste** [comment]
I made a release based on 1.4.0-rc2 on test pypi. You can install it with:
```
pip3 install -i https://test.pypi.org/simple/ tink
```
It has binary wheels for Linux using Python 3.7 and 3.8. For other platforms it will fallback to compiling from source, which requires Bazel and protoc to be installed on the system. Note that Python 3.6 will not work, as some of the type hints we use require features from 3.7+.

**Comment by masteusz** [comment]
Hey @kste, it works! Thanks! :1st_place_medal:

**Comment by willypicard** [comment]
This is great news. It unlocks the situation. Thank you a million times for the package! 

Any plan for a release on the main pypi repo?

**Comment by kste** [comment]
We will definitely release it on the main pypi repo and should be rather soon (~2-3 weeks).

**Comment by hpnhxxwn** [comment]
Hi! I am working on a project that requires Tink library. We only support PyPi to import Tink. Just wonder if the production PyPi package is ready? Thank you!

**Comment by kste** [comment]
It will definitely come with the 1.4.0 release, which should happen very soon :-). 

In the mean time you can either use the release of 1.4.0rc2 on [test PyPI](https://test.pypi.org/project/tink/) or [build your own binary release](https://github.com/google/tink/tree/master/python/tools/distribution) from the latest version. This you can also install simply with pip then, given some local path.

**Comment by thnee** [comment]
I would also be very happy to see a package on pypi.

> BTW would you mind sharing your use cases? We're very interested in how people are using Tink.

@thaidn Looking to encrypt data before sending it to bigquery, so that it can be decrypted in there using `AEAD.DECRYPT_STRING()`, for the purpose of crypto-shredding to comply with GDPR.

**Comment by hpnhxxwn** [comment]
> It will definitely come with the 1.4.0 release, which should happen very soon :-).
> 
> In the mean time you can either use the release of 1.4.0rc2 on [test PyPI](https://test.pypi.org/project/tink/) or [build your own binary release](https://github.com/google/tink/tree/master/python/tools/distribution) from the latest version. This you can also install simply with pip then, given some local path.

I am wondering if the production PyPi version still depends on Bazel? The reason I asked is that, we used a Mac without Bazel and tried pip install the test PyPi version of Tink, it popped up an error asking to install Bazel first. However, our development does not support Bazel..

Thank you!

**Comment by avoll** [comment]
also really looking forward to the official PyPi release! 

Hopefully it does not require bazel, as building a prod environment docker image with an additional build tool is not the best security practice.

> It will definitely come with the 1.4.0 release, which should happen very soon :-).
> 
> In the mean time you can either use the release of 1.4.0rc2 on [test PyPI](https://test.pypi.org/project/tink/) or [build your own binary release](https://github.com/google/tink/tree/master/python/tools/distribution) from the latest version. This you can also install simply with pip then, given some local path.

**Comment by marrrcin** [comment]
Bazel dependency for prod environment is no-go for us too. Please provide official PyPI without install time dependencies.

**Comment by kste** [comment]
Yes, the PyPI package will include binary packages and not require Bazel. Initially, this will be for x86 Linux only, but if there is demand we can look into adding more builds like MacOS.

**Comment by avoll** [comment]
great!! Looking forward to the release :)

**Comment by zxhuang** [comment]
Looking forward to the release!~ :)

**Comment by thaidn** [comment]
As part of the 1.4.0 release, binary packages for Linux and macOS are now available on production PyPi: https://pypi.org/project/tink/.

You can install with

```
pip3 install tink
```

Tink supports Python 3.7 and 3.8.
