### ISSUE TITLE
Howto: examples don't build and lacking

### ISSUE THREAD

**Issue by pmullaney** [google/tink#359]
A few of the examples in the howto fail to compile and run. It's a shame because it's going to deter adoption. Perhaps the examples from the howto should be maintained in the source. 

https://github.com/google/tink/blob/master/docs/GOLANG-HOWTO.md#hybrid-encryption-and-decryption
 
./main.go:47:38: undefined: exported
./main.go:49:17: too many arguments to return
	have (nil, error)
	want ()
./main.go:64:17: too many arguments to return
	have (nil, error)
	want ()
./main.go:67:37: undefined: exported
./main.go:69:17: too many arguments to return
	have (nil, error)
	want ()

**Comment by thaidn** [comment]
Thanks for the report. We're addressing this issue.

**Comment by thaidn** [comment]
We've cleaned up the examples. They're now part of the source code, so should always compile and work, see 
https://godoc.org/github.com/google/tink. We're also working on adding more examples.

I'm going to close this up, please comment if you have additional feedback.

Thanks again for your report.
