### ISSUE TITLE
DeepCode found  several possible problems

### ISSUE THREAD

**Issue by patlecat** [google/tink#366]
Running deepcode it found 5 possible leaks/problems and 13 recommendations ([DeepCode](https://www.deepcode.ai/)):

Link to report: https://www.deepcode.ai/app/gh/google/tink/185056691b2464e6799a1c04ccf55ae90534a013/_/dashboard

**Comment by thaidn** [comment]
I can't access the report (without granting DeepCode access to my account). Could you please attach it here if you happen to have a copy?

**Comment by patlecat** [comment]
![image](https://user-images.githubusercontent.com/422020/84248053-2f02f600-ab09-11ea-8f96-3889165ba02d.png)

**Comment by thaidn** [comment]
Thanks, this is useful.

I took a closer look at the 6 warnings, and here are my thoughts:

1/ byte->int: Do you have a link to the line of code that causes it?

2/ Will replace isNaN() with Number.isNaN()

3/ We use SHA1 to build HMAC-SHA1, which is safe despite the brokenness of SHA1

4/ ReturnPtrStatusOr, this looks fine to me as it returns a reference to a *static* variable

5/ open: do you have a link to the line of code that causes it?

6/ exports: this is just how we write Javascript/Typescript at Google.

**Comment by patlecat** [comment]
@thaidn You can do the same as me, and just run the analysis over the repo yourself and have all the information. There are also maybe some false positives or warnings that you consider not a problem, that's fine of course.
