### ISSUE TITLE
Signing/verification time decreases with message size 

### ISSUE THREAD

**Issue by harnen** [google/tink#374]
I'm trying to benchmark signature algorithms using Java Tink implementation 1.4.0-rc2 for Android and following [those examples](https://github.com/google/tink/blob/master/docs/JAVA-HOWTO.md#digital-signatures). 

I've noticed that with increasing message size, the signature creation/verification time decreases which seems weird. 

I run the following code on Galaxy A50 with Android 10:
```
TinkConfig.register();
for(int i = 0; i < 20; i++) {
   KeysetHandle privateKeysetHandle = KeysetHandle.generateNew(
                                                       SignatureKeyTemplates.ED25519);
   PublicKeySign signer = privateKeysetHandle.getPrimitive(PublicKeySign.class);
   KeysetHandle publicKeysetHandle = privateKeysetHandle.getPublicKeysetHandle();
   PublicKeyVerify verifier = publicKeysetHandle.getPrimitive(PublicKeyVerify.class);
   
   int size = 32 + (i * 66);
   byte[] data = new byte[size];
   new Random().nextBytes(data);

   long startTime = System.nanoTime();
   byte[] signature = signer.sign(data);
   long endTime = System.nanoTime();
   long signElapsed = endTime - startTime;

   startTime = System.nanoTime();
   verifier.verify(signature, data);
   endTime = System.nanoTime();
   long verifyElapsed = endTime - startTime;

   Log.d(TAG, "Size:" + size + " signing: " + signElapsed + " verify: " + verifyElapsed);
}
```

When plotted, the computation time clearly decreases:
![image](https://user-images.githubusercontent.com/7314908/85039216-cad6d680-b187-11ea-82b0-27a1913423d2.png)

Is there something I'm missing here? Behavior for ECDSA_P256 seems to be similar.

**Comment by tholenst** [comment]
The size doesn't matter much for ECDSA_P256. 

Probably the virtual machine will do some JIT compilation after some runs, so that it's not the size which has the impact, but instead the order. Try to count i down.

**Comment by harnen** [comment]
Indeed, the graph changes when counting down, so seems to be JIT. 

![image](https://user-images.githubusercontent.com/7314908/85043233-6a966380-b18c-11ea-8344-87f33f0da5db.png)

I guess, I'll do separate runs for benchmarking. Thank you.
