### ISSUE TITLE
How to fetch private/public key?

### ISSUE THREAD

**Issue by hpnhxxwn** [google/tink#376]
Hi,

I looked into key handler class and seems there is no API for fetch private/public key out? We are going to use Tink to generate daily rotated private/public key pair using Hybrid Engine, so will have a storage to store keys. Could you advise how to achieve this? 

Thank you!

**Comment by hpnhxxwn** [comment]
After reading source code, I found I could use this?
```
private_keyset_handle._keyset.key[0].key_data.value
```

This will give the private key. For example:
```
b'\x12\x8a\x01\x12D\n\x04\x08\x02\x10\x03\x12:\x128\n0type.googleapis.com/google.crypto.tink.AesGcmKey\x12\x02\x10\x10\x18\x01\x18\x01\x1a \xe1\x8fd\xf1\x80\xc5\x14\x14\xd3\xac\xf1\xda\xaf\x14\x80\xa0\xf0Uhq!\xb8l\xc7i\xe58\xe6\x7f+\x14\xfd" x\xf6x\x7fc\xc9$#m\xfa\x8d&\xdc!\xb8g0q\x8f\x86U\xf60\xffSD\x14<\xf6_\xab`\x1a \x05\x895\xf9\x19\x0b}N\xc5q\x1e\xa9\xf9e\xcft\x1fS\x06\x1bt/\xb9\xe71\xf4t\x1d\xb3\xb9D3'
```

**Comment by thaidn** [comment]
The key management aspects in Tink are documented in https://github.com/google/tink/blob/master/docs/KEY-MANAGEMENT.md. The language how-to guides also contain sections on storing, loading and generating keys.

In short, Tink stores keys as protobuf. A key consists not only the raw key material, but also all parameters necessary to instantiate a primitive. We strongly recommend not to extract the raw key material out of a key protobuf and use it as in other context. Doing so will certainly lead to cross-protocol attacks (e.g., a single key material is used in two different protocols).

Please comment if you have any additional question.
