### ISSUE TITLE
Streaming support for python - release date

### ISSUE THREAD

**Issue by marrrcin** [google/tink#377]
When the support for streaming ciphers in Python will be released? Is there any publicly available roadmap of upcoming features?

**Comment by thaidn** [comment]
This should be part of 1.5.0. Should be easy, as the only missing pieces are the key managers.

@kste please keep me honest

**Comment by marrrcin** [comment]
When is 1.5.0 planned to be released?

**Comment by thaidn** [comment]
@juergw has been working on this, but it looks like this is more complicated than we thought and likely won't make the cut for 1.5.0. After we finish the implementation, we also want to run it in production for awhile to squeeze out potential bugs, so at this point we can't tell for sure when it'll be ready for external users. My apologies!

**Comment by kste** [comment]
I have no update on the release date, but there is now an [example](https://github.com/google/tink/tree/master/examples/python/streaming_aead) for using the streaming AEAD in Python if you can use the head version.

**Comment by thaidn** [comment]
1.5.0 will be released early next week.

**Comment by thaidn** [comment]
Tink Python 1.5.0 is out!

```
pip install tink==1.5.0
```
