### ISSUE TITLE
Proposal: Use kmsiface.KMSAPI interface in aws integration instead of kms.KMS struct

### ISSUE THREAD

**Issue by leighmcculloch** [google/tink#378]
It's currently difficult to write tests that use the AWS integration in the same way that is common in other projects I've worked on because the `kms.KMS` type is used as the input parameter in the `awskms.NewClientWithKMS` function. KMS SDKs provides an interface `kmsiface.KMSAPI` that if it was used instead would allow for use of a mock KMS in tests while exercising the rest of the standard Tink code.

Could the `kms.KMS` type in the function be replaced with the kmsiface.KMSAPI interface? The kms.KMS type satisfies the interface so that should be a non-breaking change for anyone passing in the type. Or could another New function be added that takes the KMSAPI instead?

**Comment by thaidn** [comment]
I'm fixing this. The change will be included in 1.5.0.

**Comment by leighmcculloch** [comment]
Thanks @thaidn!!! 🎉

**Comment by JordanVliegCoinbase** [comment]
Excellent! This is amazing to see. Is there a timeline for 1.5? (or a RC for it?)

**Comment by thaidn** [comment]
I'm aiming for next Tuesday, if Earth wasn't swallowed by a black hole by then.
