### ISSUE TITLE
Primitive lookup for decryption in *_factory.go files

### ISSUE THREAD

**Issue by howardtw** [google/tink#381]
I found that in `func (a *wrappedAead) Decrypt(ct, ad []byte) ([]byte, error)`, we start [searching](https://github.com/google/tink/blob/f10b8b638203f18e18ab7a86af5011f1e0064fdf/go/aead/aead_factory.go#L98) for the right entry from the front the slice while new entries are [appended](https://github.com/google/tink/blob/f10b8b638203f18e18ab7a86af5011f1e0064fdf/go/core/primitiveset/primitiveset.go#L105-L106) to the back. Same thing happens to [hybrid decrypt](https://github.com/google/tink/blob/f10b8b638203f18e18ab7a86af5011f1e0064fdf/go/hybrid/hybrid_decrypt_factory.go#L79) as well. I didn't check for all the primitive factories, but this issue appears to be fairly common in tink/go.

It seems to be an easy optimization if we start searching for the right entry from the back as it is more intuitive to start searching from the newer keys.

Feel free to close this issue if this is done on purpose because it's also valid to argue that most data in a particular system should have been encrypted by the old key when a key rotation happens. And this can remain true if the system doesn't rewrite the data with the new key.

**Comment by thaidn** [comment]
Good catch! This should be easy to fix, will do soon.

**Comment by thaidn** [comment]
@chuckx Charles, can you take care of this? This seems useful and is well aligned with your goal of making Golang better.

**Comment by thaidn** [comment]
On a closer thought, this is not necessary and might not result in a performance gain, because old and new keys usually have the same probability of being correct.

I'll revert the change in https://github.com/google/tink/commit/c38283bbd314c4803856579f99634f8b72b8170f.
