### ISSUE TITLE
Using tink 1.2.2 with java 7 fails with java.security.NoSuchAlgorithmException: Cannot find any provider supporting AES/GCM/NoPadding

### ISSUE THREAD

**Issue by brianmituka** [google/tink#383]
We are using tink 1.2.2 with java 7 and it fails with `java.security.NoSuchAlgorithmException: Cannot find any provider supporting AES/GCM/NoPadding`. Do you have a suggestion on how we can bypass this issue. Our current setup does not allow us to easily migrate to a newer version of java that has support for the algorithm. We have tried adding the Bouncy castle provider but the error still occurs.

We are using the Hybrid Encryption primitive.

`KeysetHandle privateKeysetHandle = KeysetHandle
                .generateNew(HybridKeyTemplates.ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM)`

**Comment by thaidn** [comment]
Bouncy Castle should support that algorithm. Which version of BC did you use?

You can also try https://conscrypt.org.
