### ISSUE TITLE
Proposal: Add utility function for splitting MAC prefix from raw MAC

### ISSUE THREAD

**Issue by leighmcculloch** [google/tink#387]
The MAC primitives are easy to use and it is really useful that a keyset can have its key rotated and verification is still efficient because the key hint is included as the prefix. In a case I'm using the Go implementation in I'm needing to get the hint and the raw MAC out separately so they can be stored separately. I need the MAC by itself, but I still want the prefix to store separately because I need to regenerate the MAC at a later point and need to make sure for this specific case that I regenerate it with the same key.

I'm reasonably confident that I can split the string on the `cryptofmt.NonRawPrefixSize` but it feels like I'm setting myself up for a bug or for some sort of failure. As I'm aware Tink's vision is to help people from making silly mistakes, and I get the feeling what I'm doing is brittle and like I'm creating a situation where this could become a mistake through changes down the line.

I realize the `tink.MAC` interface is locked in and it wouldn't be possible to change it, but maybe there is room for a function that given a Tink MAC will give back the prefix and/or the raw MAC, or a function that given a MAC and a keyset will return the key and the raw MAC.

It's also possible I'm using the MAC primitive for something it's not intended, generating deterministic values and not for verification, and so it's possible my use case does not fit into this utility.

**Comment by thaidn** [comment]
If you don't want the prefix, the best option is to use the `RAW` output prefix type when generating the keyset. This option is supported in all languages and can be specified as part of the key template.

**Comment by leighmcculloch** [comment]
Thanks for pointing that out. I completely missed I could generate keys that didn't use the prefix.
