### ISSUE TITLE
ECB mode used in AesCmac.java

### ISSUE THREAD

**Issue by walvekar** [google/tink#388]
Source: https://github.com/google/tink/blob/6bc2b34d2817300ae9b2b989f99dbbe48a69368b/java_src/src/main/java/com/google/crypto/tink/subtle/AesCmac.java#L39

AesCmac.java is using ECB more computing the CMAC. Would using ECB mode be secure in this case ?

The AesCmac RFC - https://tools.ietf.org/html/rfc4493#section-2.4 step6 recommends using CBC.

**Comment by thaidn** [comment]
It's secure. We use the ECB mode as a building block to implement CBC and CMAC.
