### ISSUE TITLE
Proposal: Tinkey output JSON in a compact format without indenting and new lines

### ISSUE THREAD

**Issue by leighmcculloch** [google/tink#390]
When using the tinkey commands that output the keyset in JSON, the output is indented and pretty formatted. This is great for the human eye but it isn't a human eye reading these files most of the time and it is somewhat annoying for some use cases. For example if the keyset is set as an environment variable, or stored into a store that has limited size, space is wasted or it is more difficult to set the value.

In cases where pretty formatting is beneficial in consoles where a human is present it is easy for a developer to use a tool such as `jq` to format the JSON.

Could we default to compact JSON output and let the user format it if needed?

Or if backwards compatibility is important could we add an output format option such as `json-compact`? This would be backwards compatible so that the default option is still pretty printed.

**Comment by thaidn** [comment]
Have you tried the `--out-format binary` option?

```
tinkey create-keyset --key-template AES128_GCM --out-format binary --out keyset.cfg
```

This option is the most compact and intended for machines. The JSON option is intended for human users, that's why we want to keep it pretty.

**Comment by leighmcculloch** [comment]
I have. My use case is where the keyset is being injected into an environment using environment variables. In that environment the JSON output is perfect because it doesn't need to be base64 encoded, but the fact it has so much whitespace is a little problematic.

**Comment by thaidn** [comment]
Thanks for the context.

I'd recommend base64 the output as follows:

```
tinkey create-keyset --key-template AES128_GCM --out-format binary | openssl base64
```

You have to decode in your application, but most languages support Base64 out of the box.

In principle, we don't want to add specific workaround for a specific use case when there's already a reasonable solution. One might even say such a workaround is technical debt.

**Comment by leighmcculloch** [comment]
Agreed. I've also since realized I can just use `jq -c` to compact the JSON as well.
