### ISSUE TITLE
Failed to create secure subchannel for secure name 'cloudkms.googleapis.com' on Python

### ISSUE THREAD

**Issue by ozeranskiy** [google/tink#399]
I'm trying to make Envelope encryption, but when calling the method in function `encrypt`
```python
encrypted_dek = self.remote_aead.encrypt(dek.value, b'')
```
errors occur
```
E0720 18:07:39.264596000 4732890560 ssl_utils.cc:453]                  load_file: {"created":"@1595257659.264573000","description":"Failed to load file","file":"external/com_github_grpc_grpc/src/core/lib/iomgr/load_file.cc","file_line":71,"filename":"/usr/share/grpc/roots.pem","referenced_errors":[{"created":"@1595257659.264572000","description":"No such file or directory","errno":2,"file":"external/com_github_grpc_grpc/src/core/lib/iomgr/load_file.cc","file_line":45,"os_error":"No such file or directory","syscall":"fopen"}]}
E0720 18:07:39.264608000 4732890560 ssl_security_connector.cc:423]     Could not get default pem root certs.
E0720 18:07:39.264613000 4732890560 secure_channel_create.cc:132]      Failed to create secure subchannel for secure name 'cloudkms.googleapis.com'
E0720 18:07:39.264619000 4732890560 secure_channel_create.cc:50]       Failed to create channel args during subchannel creation.
E0720 18:07:39.264642000 4732890560 ssl_security_connector.cc:423]     Could not get default pem root certs.
E0720 18:07:39.264647000 4732890560 secure_channel_create.cc:132]      Failed to create secure subchannel for secure name 'cloudkms.googleapis.com'
E0720 18:07:39.264653000 4732890560 secure_channel_create.cc:50]       Failed to create channel args during subchannel creation.
```
```python
tink.cc.pybind.tink_bindings.StatusNotOk: INVALID_ARGUMENT: GCP KMS encryption failed: Empty update
```
Can you tell me how to fix it, please?

Python: 3.7.8
System Version: macOS 10.15.5

**Comment by kste** [comment]
It looks like you have to install the certificates for GRPC to work. Can you try if https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/bigtable/examples/README.md#configure-grpc-root-certificates resolve the issue for you?

**Comment by ozeranskiy** [comment]
@kste Yes, it worked, thank you. I think we should add that to the documentation.

**Comment by thaidn** [comment]
@kste can you add the instruction to the how to?

**Comment by kste** [comment]
I've added a description of this in https://github.com/google/tink/commit/c8f34c45a7877cc2434c33c1612cc3ba8302459a.

**Comment by ranpipl** [comment]
@kste https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/bigtable/examples/README.md#configure-grpc-root-certificates r
I think that this reference is outdated. Can you please suggest other solution?

**Comment by ranpipl** [comment]
As a work around I did the following:
Download [https://pki.google.com/roots.pem](https://pki.google.com/roots.pem) to my local machine.
And then set the following environment variable `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH=PATH/TO/roots.pem`
