### ISSUE TITLE
Installation instructions don't mention tink package on pypi

### ISSUE THREAD

**Issue by martin-sucha** [google/tink#400]
The instructions in [PYTHON-HOWTO](https://github.com/google/tink/blob/7e6d51d3ac1bdb29944f2df2b8b5e5925bc36e65/docs/PYTHON-HOWTO.md) (nor I have seen it elsewhere in the project) don't mention whether the `tink` package distributed on pypi (https://pypi.org/project/tink/) is related to this project or not.

Please mention whether it's safe to use `pip install tink` or whether all users need to build python package from source in the project's documentation.

**Comment by kste** [comment]
Thanks for pointing this out. The Python package on pypi is generated from the release here and therefore save to use.

**Comment by thaidn** [comment]
The how to has been updated: https://github.com/google/tink/blob/master/docs/PYTHON-HOWTO.md.
