### ISSUE TITLE
Python package fails when building Docker image based on Alpine Linux

### ISSUE THREAD

**Issue by jdkizer9** [google/tink#406]
I'm running into an issue including Tink in Docker images based on Python / Apline Linux. I get the following error when building the image:

```
Step 1/2 : FROM python:3.7-alpine3.11
 ---> b478b156c249
Step 2/2 : RUN pip install tink
 ---> Running in d7c3c4f809fa
Collecting tink
  Downloading tink-1.4.0.tar.gz (120 kB)
    ERROR: Command errored out with exit status 255:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-58y_vri6/tink/setup.py'"'"'; __file__='"'"'/tmp/pip-install-58y_vri6/tink/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-o48j7siw
         cwd: /tmp/pip-install-58y_vri6/tink/
    Complete output (1 lines):
    Could not find bazel executable. Please install bazel tocompile the Tink Python package.
```

To reproduce, try to build the following Dockerfile:

```
# Fails on Alpine 3.11
FROM python:3.7-alpine3.11

RUN pip install tink
```

The default Python image works fine.

```
# Succeeds on base python image
FROM python:3.7

RUN pip install tink
```

**Comment by kste** [comment]
Unfortunately there are no binary wheels available for Alpine Linux and you will have to build the [package from source](https://github.com/google/tink/blob/master/docs/PYTHON-HOWTO.md#build-a-python-package-using-pip).

The reason for that is that Alpine Linux is incompatible with the (current) manylinux standard as it uses musl libc, therefore it's not possible to distribute binary wheels for Alpine at the current stage.
