### ISSUE TITLE
A Little Help?

### ISSUE THREAD

**Issue by SoftCircuits** [google/tink#409]
There are a dizzying number of things going on with this project. I'm supposed to use Bazel in the form of Baselisk (no idea what either one is). There are folders for Python, GO, Java, etc.

I'm using Microsoft C++ with MFC and would like include a compiled library for Windows to add encryption. Any place I can go to get the steps to do just this?

**Comment by tholenst** [comment]
See the https://github.com/google/tink/blob/master/docs/CPP-HOWTO.md 

With bazel you can go to the example directory at https://github.com/google/tink/tree/master/examples/cc and build it with "bazel build ...". We try this only with the version of bazel which is marked in the .bazelversion file in this directory. Bazelisk is a small wrapper for bazel which downloads this version and uses it. You can also use CMake as in the description there.

Note that we currently do not officially support Windows. Tink might not work for windows. Note also https://github.com/google/tink/issues/284: it might be difficult to use openSSL and Tink in your binary.
