### ISSUE TITLE
CMAKE_C_COMPILER passthrough is not working, with CMake 3.18.2: The current configuration mixes Clang and MSVC or some other CL compatible   compiler tool

### ISSUE THREAD

**Issue by advancedwebdeveloper** [google/tink#410]
I have such bugs, while running CMake in "x64 Native Tools Command Prompt for VS2019":

build>cmake -DCMAKE_GENERATOR=Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
-- The CXX compiler identification is Clang 11.0.0 with GNU-like command-line
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/LLVM/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Fetching com_google_googletest
-- The C compiler identification is MSVC 19.27.29111.0
-- The CXX compiler identification is Clang 11.0.0 with GNU-like command-line
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/Platform/Windows-Clang.cmake:105 (message):
  The current configuration mixes Clang and MSVC or some other CL compatible
  compiler tool.  This is not supported.  Use either clang or MSVC as both C
  and C++ compilers.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/Platform/Windows-Clang-CXX.cmake:1 (include)
  C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeCXXInformation.cmake:48 (include)
  CMakeLists.txt:17 (project)

-- Configuring incomplete, errors occurred!
See also "C:/Users/local_vqocmez/clang/tink-master/build/__third_party/com_google_googletest/CMakeFiles/CMakeOutput.log".
CMake Error at cmake/HttpArchive.cmake:67 (message):
  While configuring com_google_googletest: 1
Call Stack (most recent call first):
  cmake/TinkWorkspace.cmake:39 (http_archive)
  CMakeLists.txt:15 (include)

-- Configuring incomplete, errors occurred!
See also "C:/Users/local_vqocmez/clang/tink-master/build/CMakeFiles/CMakeOutput.log".

build>cmake ..
-- Building for: Visual Studio 16 2019
-- The CXX compiler identification is MSVC 19.27.29111.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Fetching com_google_googletest
-- The C compiler identification is MSVC 19.27.29111.0
-- The CXX compiler identification is MSVC 19.27.29111.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/local_vqocmez/clang/tink-master/build/__third_party/com_google_googletest
Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Creating directories for 'com_google_googletest'
  Performing download step (download, verify and extract) for 'com_google_googletest'
  -- Downloading...

build>cmake -G Ninja ..
-- The CXX compiler identification is MSVC 19.27.29111.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Fetching com_google_googletest
-- The C compiler identification is MSVC 19.27.29111.0
-- The CXX compiler identification is MSVC 19.27.29111.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/local_vqocmez/clang/tink-master/build/__third_party/com_google_googletest
[1/9] Creating directories for 'com_google_googletest'

build>cmake -DCMAKE_C_COMPILER=clang ..
-- Building for: Visual Studio 16 2019
-- The CXX compiler identification is MSVC 19.27.29111.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Fetching com_google_googletest

build>cmake -G Ninja  ..
-- The CXX compiler identification is MSVC 19.27.29111.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Fetching com_google_googletest
-- The C compiler identification is MSVC 19.27.29111.0
-- The CXX compiler identification is MSVC 19.27.29111.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/local_vqocmez/clang/tink-master/build/__third_party/com_google_googletest

build>cmake -DCMAKE_GENERATOR=Ninja -G Ninja ..
-- The CXX compiler identification is MSVC 19.27.29111.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Fetching com_google_googletest
-- The C compiler identification is MSVC 19.27.29111.0
-- The CXX compiler identification is MSVC 19.27.29111.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/local_vqocmez/clang/tink-master/build/__third_party/com_google_googletest

\build>cmake -G Ninja -DCMAKE_C_COMPILER=clang ..
-- The CXX compiler identification is MSVC 19.27.29111.0
-- Detecting CXX compiler ABI info
^C
C:\Users\local_vqocmez\clang\tink-master\build>cmake -G Ninja -DCMAKE_CXX_COMPILER=clang++ ..
-- The CXX compiler identification is Clang 11.0.0 with GNU-like command-line
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/LLVM/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Fetching com_google_googletest
-- The C compiler identification is MSVC 19.27.29111.0
-- The CXX compiler identification is Clang 11.0.0 with GNU-like command-line
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/Platform/Windows-Clang.cmake:105 (message):
  The current configuration mixes Clang and MSVC or some other CL compatible
  compiler tool.  This is not supported.  Use either clang or MSVC as both C
  and C++ compilers.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/Platform/Windows-Clang-CXX.cmake:1 (include)
  C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeCXXInformation.cmake:48 (include)
  CMakeLists.txt:17 (project)

build>cmake -DCMAKE_GENERATOR=Ninja -DCMAKE_CXX_COMPILER=clang++ ..
-- The CXX compiler identification is Clang 11.0.0 with GNU-like command-line
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/LLVM/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Fetching com_google_googletest
-- The C compiler identification is MSVC 19.27.29111.0
-- The CXX compiler identification is Clang 11.0.0 with GNU-like command-line
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/Platform/Windows-Clang.cmake:105 (message):
  The current configuration mixes Clang and MSVC or some other CL compatible
  compiler tool.  This is not supported.  Use either clang or MSVC as both C
  and C++ compilers.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/Platform/Windows-Clang-CXX.cmake:1 (include)
  C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeCXXInformation.cmake:48 (include)
  CMakeLists.txt:17 (project)

Looks like -DCMAKE_C_COMPILER=... is not an option that is checked: I have success in ordinary Windows 10 command prompt (without pre-configured. dev. env., for MSVC):

build>cmake -G Ninja ..
-- The CXX compiler identification is Clang 11.0.0 with GNU-like command-line
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/LLVM/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Fetching com_google_googletest
-- The C compiler identification is Clang 11.0.0 with GNU-like command-line
-- The CXX compiler identification is Clang 11.0.0 with GNU-like command-line
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/LLVM/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/LLVM/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/local_vqocmez/clang/tink-master/build/__third_party/com_google_googletest

Ivan

**Comment by thaidn** [comment]
Hi Ivan,

Tink doesn't support Windows. There's been some discussions about this internally, but it's very unlikely we'll get to it until 2021 or 2022. There's simply not enough demand.

I'm sorry that we can't help you. If you think you can make this work and want to contribute, please ping back. We can chat more about how this should be done.

**Comment by advancedwebdeveloper** [comment]
> Hi Ivan,
> 
> Tink doesn't support Windows. There's been some discussions about this internally, but it's very unlikely we'll get to it until 2021 or 2022. There's simply not enough demand.
> 
> I'm sorry that we can't help you. If you think you can make this work and want to contribute, please ping back. We can chat more about how this should be done.

Thaidn,
I could be of help by testing various scenarios. Currently I am able to help with the build automation bugs.
Let me know which scenarios do you expected to be supported, in the future - and guide me, so I would be able to report bugs in a detailed/consistent manner.

**Comment by advancedwebdeveloper** [comment]
This seems to be purely CMake bug - it is not even/yet related to the implementation files/compilation phase.

The cause of my interest is in diversifying crypto lib, useful for integrating with https://github.com/apache/nifi-minifi-cpp. They have (mainly) C++ project - so using a SSL/TLS library, implemented in C++, would make some sense.

СС @phrocker @achristianson @adebreceni @arpadboda @lordgamez @szaszm @hunyadi-dev @fgerlits @achristianson @james94 

Ivan

**Comment by advancedwebdeveloper** [comment]
CC @alopresto

**Comment by szaszm** [comment]
Please stop CC-ing every contributor of the project. thaidn clearly stated that Tink doesn't support Windows and 
1. minifi c++ supports windows
2. I doubt the community would support switching crypto libs "just because"

**Comment by arpadboda** [comment]
@advancedwebdeveloper : did you realise that there is a PR open to add libsodium to MiNiFi cpp - so you get your encryption lib?
