### ISSUE TITLE
Bazel build of tink for Python fails

### ISSUE THREAD

**Issue by JordanStopford** [google/tink#411]
I'm attempting to use FPM to repackage the tink code into an RPM and the build is failing due to a C++ compile error:

`ERROR: /root/.cache/bazel/_bazel_root/dcfda3730e42b07a275abf4fe2eeeda4/external/aws_c_common/BUILD.bazel:5:11: C++ compilation of rule '@aws_c_common//:aws_c_common' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 23 argument(s) skipped) {:level=>:info}
 {:level=>:info}
Use --sandbox_debug to see verbose messages from the sandbox {:level=>:info}
external/aws_c_common/source/allocator.c: In function 'aws_mem_acquire_many': {:level=>:info}
external/aws_c_common/source/allocator.c:134:5: error: 'for' loop initial declarations are only allowed in C99 mode {:level=>:info}
     for (size_t i = 0; i < count; ++i) { {:level=>:info}
     ^ {:level=>:info}
external/aws_c_common/source/allocator.c:134:5: note: use option -std=c99 or -std=gnu99 to compile your code {:level=>:info}
external/aws_c_common/source/allocator.c:156:9: error: 'for' loop initial declarations are only allowed in C99 mode {:level=>:info}
         for (size_t i = 0; i < count; ++i) { {:level=>:info}
         ^ {:level=>:info}
Target //tink/cc/pybind:tink_bindings failed to build {:level=>:info}`

This is using the 1.4.0 release code.

**Comment by JordanStopford** [comment]
Hi,

Is there any update on the above? 

Regards,

Jordan

**Comment by JordanStopford** [comment]
Hi kste,

Thanks for the reply!

That file isn't present on my system - all I've done is download the available sources via pip. I'll try with the latest sources from here instead as I suppose it's possible the sources on pypi aren't complete.

For reference my system is CentOS 7.8.2003, using GCC 4.8.5 and Python 3.8.5

**Comment by JordanStopford** [comment]
OK so adding `copts=["-std=c99"]` to the `aws_c_common.BUILD.bazel` file seems to get it a bit further sometimes, other times it thinks it's still not there. I don't really know how `bazel` works, but it seems to be fetching sources remotely so perhaps it's pulling that build file down from somewhere else instead of using my copy.

I also get inconsistent results using `python3 setup.py install` so I've tried to just use `bazel` for the time being.

Regardless, when it does get further, it then produces this error:

`[root@JSLinuxDev python]# bazel build ...
DEBUG: Rule 'tink_base' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "fe1c5a5bea14f92c64409f36431ae98d5002e23af38ed7c1b2d3fbebdadcfd55"
DEBUG: Repository tink_base instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/78833ac665c89dbc358f9103c001d7b9/external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: in <toplevel>
DEBUG: Rule 'tink_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "fe1c5a5bea14f92c64409f36431ae98d5002e23af38ed7c1b2d3fbebdadcfd55"
DEBUG: Repository tink_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/78833ac665c89dbc358f9103c001d7b9/external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: in <toplevel>
INFO: Analyzed 202 targets (106 packages loaded, 5125 targets configured).
INFO: Found 202 targets...
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/struct_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/type_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/wrappers_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/timestamp_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/compiler/plugin_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From Action external/googleapis/google/cloud/kms/v1/resources.grpc.pb.h:
bazel-out/k8-fastbuild/bin/external/googleapis/external/googleapis: warning: directory does not exist.
google/cloud/kms/v1/resources.proto:23:1: warning: Import google/api/annotations.proto is unused.
INFO: From Generating C++ proto_library @googleapis//google/cloud/kms/v1:kms_proto:
google/cloud/kms/v1/resources.proto:23:1: warning: Import google/api/annotations.proto is unused.
INFO: From Compiling external/com_google_absl/absl/status/status.cc:
In file included from external/com_google_absl/absl/strings/cord.h:84:0,
                 from external/com_google_absl/absl/status/status.h:21,
                 from external/com_google_absl/absl/status/status.cc:14:
external/com_google_absl/absl/types/optional.h:119:7: warning: unused parameter 'src' [-Wunused-parameter]
 class optional : private optional_internal::optional_data<T>,
       ^
external/com_google_absl/absl/status/status.cc: In lambda function:
external/com_google_absl/absl/status/status.cc:303:25: note: synthesized method 'absl::optional<T>& absl::optional<T>::operator=(absl::optional<T>&&) [with T = std::basic_string<char>]' first required here
     if (printer) result = printer(type_url, payload);
                         ^
INFO: From Compiling external/tink_cc/config/tink_fips.cc:
external/tink_cc/config/tink_fips.cc: In function 'crypto::tink::util::Status crypto::tink::ChecksFipsCompatibility(crypto::tink::FipsCompatibility)':
external/tink_cc/config/tink_fips.cc:50:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
INFO: From Compiling external/tink_cc/subtle/aes_gcm_hkdf_stream_segment_decrypter.cc:
external/tink_cc/subtle/aes_gcm_hkdf_stream_segment_decrypter.cc: In function 'crypto::tink::util::Status crypto::tink::subtle::{anonymous}::Validate(const crypto::tink::subtle::AesGcmHkdfStreamSegmentDecrypter::Params&)':
external/tink_cc/subtle/aes_gcm_hkdf_stream_segment_decrypter.cc:67:60: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (params.ikm.size() < 16 || params.ikm.size() < params.derived_key_size) {
                                                            ^
external/tink_cc/subtle/aes_gcm_hkdf_stream_segment_decrypter.cc: In member function 'virtual crypto::tink::util::Status crypto::tink::subtle::AesGcmHkdfStreamSegmentDecrypter::Init(const std::vector<unsigned char>&)':
external/tink_cc/subtle/aes_gcm_hkdf_stream_segment_decrypter.cc:113:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (header.size() != header_size_) {
                        ^
external/tink_cc/subtle/aes_gcm_hkdf_stream_segment_decrypter.cc: In member function 'virtual crypto::tink::util::Status crypto::tink::subtle::AesGcmHkdfStreamSegmentDecrypter::DecryptSegment(const std::vector<unsigned char>&, int64_t, bool, std::vector<unsigned char>*)':
external/tink_cc/subtle/aes_gcm_hkdf_stream_segment_decrypter.cc:172:55: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (ciphertext.size() > get_ciphertext_segment_size()) {
                                                       ^
ERROR: /root/.cache/bazel/_bazel_root/78833ac665c89dbc358f9103c001d7b9/external/tink_cc/subtle/BUILD.bazel:349:1: C++ compilation of rule '@tink_cc//subtle:aes_gcm_hkdf_stream_segment_encrypter' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 40 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/tink_cc/subtle/aes_gcm_hkdf_stream_segment_encrypter.cc: In member function 'virtual crypto::tink::util::Status crypto::tink::subtle::AesGcmHkdfStreamSegmentEncrypter::EncryptSegment(const std::vector<unsigned char>&, bool, std::vector<unsigned char>*)':
external/tink_cc/subtle/aes_gcm_hkdf_stream_segment_encrypter.cc:137:53: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (plaintext.size() > get_plaintext_segment_size()) {
                                                     ^
In file included from bazel-out/k8-fastbuild/bin/external/tink_cc/subtle/_virtual_includes/aes_gcm_hkdf_stream_segment_encrypter/tink/subtle/aes_gcm_hkdf_stream_segment_encrypter.h:27:0,
                 from external/tink_cc/subtle/aes_gcm_hkdf_stream_segment_encrypter.cc:17:
bazel-out/k8-fastbuild/bin/external/tink_cc/util/_virtual_includes/statusor/tink/util/statusor.h: In instantiation of 'crypto::tink::util::StatusOr<T>::StatusOr(const T&) [with T = std::unique_ptr<evp_aead_ctx_st, bssl::internal::Deleter<evp_aead_ctx_st> >]':
external/tink_cc/subtle/aes_gcm_hkdf_stream_segment_encrypter.cc:92:10:   required from here
bazel-out/k8-fastbuild/bin/external/tink_cc/util/_virtual_includes/statusor/tink/util/statusor.h:137:60: error: use of deleted function 'std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = evp_aead_ctx_st; _Dp = bssl::internal::Deleter<evp_aead_ctx_st>]'
 inline StatusOr<T>::StatusOr(const T& value) : value_(value) {
                                                            ^
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/memory:81:0,
                 from bazel-out/k8-fastbuild/bin/external/tink_cc/subtle/_virtual_includes/aes_gcm_hkdf_stream_segment_encrypter/tink/subtle/aes_gcm_hkdf_stream_segment_encrypter.h:20,
                 from external/tink_cc/subtle/aes_gcm_hkdf_stream_segment_encrypter.cc:17:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/unique_ptr.h:273:7: error: declared here
       unique_ptr(const unique_ptr&) = delete;
       ^
INFO: Elapsed time: 54.907s, Critical Path: 14.91s
INFO: 202 processes: 202 processwrapper-sandbox.
FAILED: Build did NOT complete successfully`

**Comment by kste** [comment]
I see! That's interesting, because I would except on that system that pip should use the available binary releases. Could you try installing the binary wheel directly: https://pypi.org/project/tink/#files ([tink-1.4.0-cp38-cp38-manylinux2014_x86_64.whl](https://files.pythonhosted.org/packages/42/16/fb2243f801f2958595ca52111fa46fa45f4451507b8c9718c75de734ed1e/tink-1.4.0-cp38-cp38-manylinux2014_x86_64.whl))?

**Comment by kste** [comment]
This issue for numpy https://github.com/numpy/numpy/issues/14182 seems to have a very similar problem with the same gcc version and CentOS. Maybe this works for you as well :-)

**Comment by JordanStopford** [comment]
> I see! That's interesting, because I would except on that system that pip should use the available binary releases. Could you try installing the binary wheel directly: https://pypi.org/project/tink/#files ([tink-1.4.0-cp38-cp38-manylinux2014_x86_64.whl](https://files.pythonhosted.org/packages/42/16/fb2243f801f2958595ca52111fa46fa45f4451507b8c9718c75de734ed1e/tink-1.4.0-cp38-cp38-manylinux2014_x86_64.whl))?

Well I would've assumed that as well! I can install it directly from the wheel, but because I'm trying to package it up with `fpm` I need to go down this route unfortunately. I'll continue to investigate whether I can just extract the wheel and use that directly with fpm.

I've tried the CFLAGS="-std=c99" approach and that causes more problems due to some `constexpr` statements in other C++ code.

I've followed all the steps in the guide to try and build tink but there must either be something missing or something odd with my machine (entirely possible) - is there an ansible script or something to create a build machine that is known to work? I really just want to rule out me doing anything stupid...!

**Comment by JordanStopford** [comment]
@kste OK so I've managed to get FPM to work with the wheel files, that's the first hurdle done. The issue I now have is the systems I have to deploy onto only have Python 3.6 on there, so even though I've managed to get the RPM built and installed...whenever I try to use tink it falls over because the bindings are for Python 3.8. Could you possibly build a wheel for Python 3.6 and upload it to pypi or provide some more detail on how I'd go about building this myself?

**Comment by kste** [comment]
Unfortunately Tink is not fully compatible with Python 3.6, as it relies on some type hint features which are only available in 3.7+.

**Comment by thaidn** [comment]
Closing, as it looks like the original issue was resolved.

@JordanStopford it's very unlikely that we can support 3.6, I'm sorry.
