### ISSUE TITLE
Bazel build of Tink for IOS Framework

### ISSUE THREAD

**Issue by sonhd86** [google/tink#412]
I have a trouble build tink Framework with Bazel. That my follow:
```
sondh@MacBook-Pro ~ % cd tink
sondh@MacBook-Pro tink % export XCODE_VERSION=9.2
sondh@MacBook-Pro tink % export IOS_SDK=10.0
sondh@MacBook-Pro tink % bazel build -c opt --ios_multi_cpus=x86_64,armv7,arm64 --xcode_version="${XCODE_VERSION}" --ios_sdk_version="${IOS_SDK}"
Starting local Bazel server and connecting to it...
WARNING: Usage: bazel build <options> <targets>.
Invoke `bazel help build` for full description of usage and options.
Your request is correct, but requested an empty set of targets. Nothing will be built.
INFO: Analyzed 0 targets (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Deleting stale sandbox base /private/var/tmp/_bazel_ sondh/3c98bf8edf409f58dd17b25b6773dfb8/sandbox
INFO: Elapsed time: 5.383s, Critical Path: 0.05s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

```
I can find Tink_framework.zip file when build completed. Please show me how to build or fix it

**Comment by tholenst** [comment]
Unfortunately, currently the open source BUILD objC breaks. We only support the cocoa pods described in https://github.com/google/tink/blob/master/docs/OBJC-HOWTO.md

That being said, you'd have to change to the directory tink/objc anyhow.

**Comment by sonhd86** [comment]
I changed the directory **tink/objc** and try bazel build with command above. It's same.
I don't use cocoapods because I'm want to add Tink Framework file to my project framework and this project have to import many project application. Someone have solutions to build Tink framework file. Thank so much.

**Comment by tholenst** [comment]
I will ping the internal bug -- there is no solution except for us to fix it. I'll see if I can get someone to work on it.

**Comment by chuckx** [comment]
FYI, a quick status update...

We've made incremental progress towards getting the Obj-C implementation in this repository into a buildable state again. However, we have a few kinks to work out in terms of how we handle the dependencies on the C++ implementation, which is now in a separate Bazel workspace.

Sorry for the continued wait, but we'll keep this issue updated as we work towards an eventual solution.

**Comment by annathomasQB** [comment]
I have the same issue.. though for me I was not able to find the zip file after building.
Also, It was required to downgrade the bazel version to 3.7.2 for it to work till here.

For me also I required it as a framework,since I'm building a cocoapod with dependency on Tink, but the posdpec fails since the Tink.framework is present in the Pods folder.
