### ISSUE TITLE
Can't implement OpenSSH's ChaCha20-Poly1305 cipher using Tink's Java library

### ISSUE THREAD

**Issue by kruton** [google/tink#416]
Although use of "subtle" APIs is discouraged, I'd like to implement OpenSSH's [`chacha20poly1305@openssh.com`](https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.chacha20poly1305) protocol using Tink in Java. The protocol specifies that two 256-bit keys will be derived. The first key (K_1) will be used with the ChaCha20 cipher to [encrypt the packet length](https://github.com/openssh/openssh-portable/blob/f2950baf0bafe6aa20dfe2e8d1ca4b23528df617/PROTOCOL.chacha20poly1305#L67). However, Tink's [ChaCha20](https://github.com/google/tink/blob/master/java_src/src/main/java/com/google/crypto/tink/subtle/ChaCha20.java#L26) class is package scoped. Additionally the length encryption needs to have the nonce set to the packet sequence number, but Tink [automatically fills the nonce with random data](https://github.com/google/tink/blob/9cc3a01ac0165b033ed51dc9d0812a98b4b6e305/java_src/src/main/java/com/google/crypto/tink/subtle/ChaCha20Base.java#L80).

The rest of the OpenSSH protocol beyond the length encryption uses something compatible with the ChaCha20Poly1305 implementation in Tink as indicated by OpenSSH's [reference to the TLS RFC](https://github.com/openssh/openssh-portable/blob/f2950baf0bafe6aa20dfe2e8d1ca4b23528df617/PROTOCOL.chacha20poly1305#L103).

**Comment by tholenst** [comment]
This is a reasonable request, but unfortunately it is extremely unlikely we will be able to help you any time soon.

**Comment by thaidn** [comment]
I'm sorry, but we can't support this because we can't allow users to set the nonce.
