### ISSUE TITLE
Python library not scaling up for large files

### ISSUE THREAD

**Issue by satyayandra** [google/tink#417]
Hi

We have files with 50 GB to 200 GB, we would like to encrypt certain columns from file but it is not working since we have limited memory. Do you have spark library so that we can run on Hadoop cluster?

Tx,
Satya

**Comment by thaidn** [comment]
Streaming encryption is coming with 1.5.0 which will be released early next week. In the mean time, take a look at this example: https://github.com/google/tink/tree/master/examples/python/streaming_aead.

**Comment by thaidn** [comment]
Tink 1.5.0 is out!

pip install tink==1.5.0
