### ISSUE TITLE
How do I make use of RsaKemHybridEncrypt?

### ISSUE THREAD

**Issue by sparkedarkle** [google/tink#422]
I'd like to make use of `RsaKemHybridEncrypt` but I'm not entirely sure I understand how to implement it Java-wise. `HybridKeyTemplates.java `lists a bunch of templates, but RSA based ones are not present. 

I tried providing a RSA public key with `CleartextKeysetHandle.read()` and then instantiate a `HybridEncrypt` object with `getPrimitive(HybridEncrypt.class)` but then I get:

```
Primtive type com.google.crypto.tink.HybridEncrypt not supported by key manager of type class com.google.crypto.tink.signature.RsaSsaPkcs1VerifykeyManager
```
Any pointers on how to implement RsaKemHybridEncrypt and decrypt in Java? I see the functionality was introduced quite recently.

**Comment by KaANO-8** [comment]
@sparkedarkle Why have you closed this issue? Did you find any implementation of RSA in HybridEncrypt/HybridDecrypt primitive?

I'm working on a requirement where I need to use RSA + AES for hybrid decryption. Any pointers would be useful.
