### ISSUE TITLE
Print public key from a keyset in Tinkey

### ISSUE THREAD

**Issue by onetwopunch** [google/tink#424]
If you want to use asymmetric primitives, there's doesn't seem to be an easy way to get the public key from a keyset. For example, if I want to distribute the public portion of a an asymmetric key, for use in another Tink-compatible program, I would have to write a custom program to do so, it would seem....unless there's some option I'm missing.

I have something that does the trick, but it seems like something like this could be build into `tinkey`.

```python
import os
import sys
import tink
from tink import hybrid
from tink import cleartext_keyset_handle
hybrid.register()

if len(sys.argv) < 2:
	print("Usage: get-pubkey keyset.json")
	os.exit(1)

tink_keyset = sys.argv[1]
with open(tink_keyset, 'r') as f:
	json_keyset = f.read()

# Get a key handle for the private key
reader = tink.JsonKeysetReader(json_keyset)
kh = cleartext_keyset_handle.read(reader)

# Get a public key handle from the private key
pub_kh = kh.public_keyset_handle()

# Write public key to stdout
writer = tink.JsonKeysetWriter(sys.stdout)
cleartext_keyset_handle.write(writer, pub_kh)
```

**Comment by kste** [comment]
There is the [create-public-keyset](https://github.com/google/tink/blob/master/docs/TINKEY.md#usage) option in Tinkey, which allows you to create a public keyset from a private one.

**Comment by onetwopunch** [comment]
Wow I feel like an idiot for missing that. Thank you :)
