### ISSUE TITLE
Request for Hashing support

### ISSUE THREAD

**Issue by sminogue** [google/tink#425]
It would be nice if Tink provided support for hashing passwords.

**Comment by sparkingdark** [comment]
@sminogue like can you give some example other packages exist with this feature ?

**Comment by sminogue** [comment]
Jasypt and bouncy castle (off the top of my head) both provide one way encryption (hashing) which can be used for storage of things like passwords.

**Comment by sparkingdark** [comment]
So we can take them as reference.

**Comment by lukaspieper** [comment]
Hi,

I think there is a duplicate of this at #446. But I really agree on the last sentence there:
>Including hashing could also more often make tink the single required explicit dependency for all of an application's crypto needs.

Would be amazing if Tink provides Argon2.

**Comment by juergw** [comment]
I'm sorry, but we currently do not have plans to design or implement password hashing.

**Comment by BigPanda97** [comment]
> I'm sorry, but we currently do not have plans to design or implement password hashing.

But why? It is a feature which has been requested many times now.

**Comment by juergw** [comment]
Because we have a lot of other things planned and we only have limited resources.
But it is a reasonable feature request, so I guess we can also keep it open for now.

**Comment by tholenst** [comment]
Unfortunately, there is no way we can do this at the moment -- simply due to the limits in our bandwidth at the moment. I will close this.
