### ISSUE TITLE
Example for tink/go/hybrid/subtle package

### ISSUE THREAD

**Issue by devfacet** [google/tink#427]
Is there any example or reference code which shows how to use "github.com/google/tink/go/hybrid/subtle" package properly?

P.S.: I know "github.com/google/tink/go/hybrid" package but I want to avoid protocol buffers.

**Comment by thaidn** [comment]
1/ The unit tests are good examples: https://github.com/google/tink/blob/master/go/hybrid/ecies_aead_hkdf_hybrid_encrypt_test.go.

2/ The `github.com/google/tink/go/hybrid` delegates crypto operations to the `github.com/google/tink/go/hybrid/subtle` package. It provides a good example of how to use the latter package properly.

Hope this helps. Ping back if you have any question.
