### ISSUE TITLE
How to use tink/go for ECIES with existing keys

### ISSUE THREAD

**Issue by udhos** [google/tink#428]
Hi,

I am toying with basic interoperability testing among ECIES implementations in Go, for curves secp256k1 and secp256r1.

How can I load existing keys into tink/go in order to do ECIES encryption?
I am currently using the draft below.
Unfortunately I could not figure out how to import existing keys into tink/go.
Please advise.

Full code: https://github.com/udhos/ecies-go-test/blob/master/main_test.go#L386
```
func encryptTinkHybrid(pubKey *ecdsa.PublicKey, data []byte) ([]byte, error) {
	pub, errPub := priv.Public() // FIXME use pubKey *ecdsa.PublicKey
	if errPub != nil {
		return nil, errPub
	}
	he, errNewEnc := tink_hybrid.NewHybridEncrypt(pub)
	if errNewEnc != nil {
		return nil, errNewEnc
	}
	cipher, errEnc := he.Encrypt(data, salt)
	if errEnc != nil {
		return nil, errEnc
	}
	return cipher, nil
}

func decryptTinkHybrid(privKey *ecdsa.PrivateKey, data []byte) ([]byte, error) {
	hd, errNewDec := hybrid.NewHybridDecrypt(priv) // FIXME use privKey *ecdsa.PrivateKey
	if errNewDec != nil {
		return nil, errNewDec
	}
	plain, errDec := hd.Decrypt(data, salt)
	if errDec != nil {
		return nil, errDec
	}
	return plain, nil
}
```

Thanks,
Everton

**Comment by thaidn** [comment]
IIUC you have keys in PEM format and you want to use them with Tink, right?

If so, this would take some work at the moment. You'd have to implement a keyset.Reader that converts your PEM keys to Tink keys (which are in protobuf format). There's an example in https://github.com/google/tink/blob/master/go/keyset/json_io.go for JSON.

We're working on a new Keyset API that would make this conversion easier.

**Comment by thaidn** [comment]
Ping back if you have any question.
