### ISSUE TITLE
Update Go proto buffs

### ISSUE THREAD

**Issue by thaidn** [google/tink#439]
Copied from the [mailing list](https://groups.google.com/d/msgid/tink-users/CAJEcZ_zb-yzZewfpwAEoZfeUY6LyuXra30whF4U2cyuXV%2BPnnw%40mail.gmail.com?utm_medium=email&utm_source=footer):

```
since protobuf api has been updates, the go protos hasen't been rebuilt.

eg: the following proto Message new function is missing from all Go protos: ProtoReflect()

Can someone rebuild the Go protos with the latest protobuf api?
```

**Comment by thaidn** [comment]
Hi there,

>the following proto Message new function is missing from all Go protos: ProtoReflect()

Why do you need this function?

**Comment by Baha-sk** [comment]
technically I don't,

but when trying to update my project with Tink 1.5, it updated to the latest import path of protobuf.

Go's protos must be rebuilt to reflect the latest import path, even though it doesn't directly impact anyone, what I noticed is it adds a new function to the Message api.

It's good practice to keep the protos in sync with the latest import path of protobuf.

**Comment by Baha-sk** [comment]
Basically, following the latest Tink release update, our Golang-ci linter complains about Tink proto imports with the following error:
```
 SA1019: package github.com/golang/protobuf/proto is deprecated: Use the "google.golang.org/protobuf/proto" package instead.  (staticcheck)
        "github.com/golang/protobuf/proto"
        ^
```

but if you try to change the import path as suggested in the error above, I get compilations errors like the missing `ProtoReflect()` function mentioned in the issue.

You can try to update the import path suggested above in any go file in Tink's Go sub module and will start getting the same errors.

**Comment by juergw** [comment]
In https://github.com/google/tink/commit/4ae3906125b2136621600321bad935a29b77c82f, I changed the import to "google.golang.org/protobuf/proto". So I guess this should be resolved now.
