### ISSUE TITLE
Google Apps Script Support

### ISSUE THREAD

**Issue by zdravko61** [google/tink#441]
Hey,

I'm building small addon for Gmail with apps script. 
I have to  implement AES-GCM encryption and RSA key pair generation, but so far I cant find anything that can bring this functionalities to GAS. 

Will tink have support for GAS ?

**Comment by taymonbeal** [comment]
Unfortunately, we rely on the underlying runtime to provide cryptographic primitives (as they generally can't be implemented safely in JS), and Apps Script doesn't offer encryption primitives. If and when they offer Web Crypto, we can support using it from Tink.
