### ISSUE TITLE
Hashicorp Vault Integration

### ISSUE THREAD

**Issue by gdbelvin** [google/tink#442]
I would love to use tink, but the lack of support for hashicorp vault is a show stopper.

**Comment by thaidn** [comment]
Hi Gary!

We do support HashiCorp Vault in Go: https://github.com/google/tink/tree/master/go/integration/hcvault.

Do you need another language? If you can contribute we'll be happy to review it.

**Comment by gdbelvin** [comment]
That's awesome. Thanks!
