### ISSUE TITLE
Does this this lib is ready for production ?

### ISSUE THREAD

**Issue by muhammadwafa** [google/tink#444]
I have decided to use the `google tink` library for **cryptography**. But still I have some concerns about its **Security** and **stabilities**.

What I need ?

1. Should Supports: **Android + IOS + Web**
2. Support Concept of: **Hybrid Encryptions (AES + RSA)**
3. Should have the **Best Security**
4. Should have the **best performance**  as I am using it in `react-native`

***Can someone please kindly suggest me, to use or not use of this library for production ?***

**Comment by thaidn** [comment]
Yes, Tink for Android and iOS are running in production for years at Google. Tink for Javascript though is still in alpha.

Tink doesn't support hybrid encryption with AES and RSA. It does support ECIES with AES-GCM and ECDH.
