### ISSUE TITLE
How to use Java envelope encryption for latest version?

### ISSUE THREAD

**Issue by zaneli** [google/tink#445]
I have used envelope encryption.
https://github.com/google/tink/blob/master/docs/JAVA-HOWTO.md#envelope-encryption

But now `KeysetHandle.generateNew(com.google.crypto.tink.proto.KeyTemplate keyTemplate)` and `AeadKeyTemplates` are deprecated.

How to migrate this code?
I guess `com.google.crypto.tink.aead.KmsEnvelopeAeadKeyManager` has alternative static method,
but I cannot find it.

**Comment by SvenMarquardt5772** [comment]
I also can't find the method to initialise an `KmsEnvelopeAeadKeyManager`. it seems there is a method missing in the class. For example in `AesGcmKeyManager` we have this method.
```java
public static final KeyTemplate aes128GcmTemplate() {
    return createKeyTemplate(16, KeyTemplate.OutputPrefixType.TINK);
  }
```
There should be an equivalent method in `KmsEnvelopeAeadKeyManager. `

**Comment by SvenMarquardt5772** [comment]
In the meantime one can use 
```java 
Registry.getKeyManager("type.googleapis.com/google.crypto.tink.KmsEnvelopeAeadKey",KmsEnvelopeAeadKey.class);
```
to get the keymanager.

**Comment by SvenMarquardt5772** [comment]
This should be the correct method.
```java
public static final KeyTemplate kmsEnvelopeAeadKeyTemplate(final String keyUri){
    final var keyFormat = KmsEnvelopeAeadKeyFormat.newBuilder()
            .setDekTemplate(AesGcmKeyManager.aes256GcmTemplate())
            .setKekUri(keyUri)
            .build().toByteString();
    return KeyTemplate.newBuilder()
            .setValue(keyFormat)
            .setTypeUrl(new KmsEnvelopeAeadKeyManager().getKeyType())
            .setOutputPrefixType(OutputPrefixType.TINK)
            .build();
  }
```

**Comment by thaidn** [comment]
Thanks @MaSven. We're going to merge your PR and include it in 1.6.0.

**Comment by GregoireW** [comment]
Hello,

On the version 1.5 I never was able to make envelope encryption work (well, it worked as long as my app was up, If I restarted it, previously encrypted data were not decrypted correctly)

I was using:

```java
            AeadConfig.register();

            KeysetHandle keysetHandle = KeysetHandle.generateNew(
                    AeadKeyTemplates.createKmsEnvelopeAeadKeyTemplate(uri, AeadKeyTemplates.AES256_GCM));

            KmsClients.add(new GcpKmsClient().withDefaultCredentials());
           
            Aead aead = keysetHandle.getPrimitive(Aead.class);
```

I switch to the HEAD-SNAPSHOT version and  now it is ok (can decrypt thing encrypted from a previous session).


I modify the code to use:

```
            AeadConfig.register();

            GcpKmsClient.register(Optional.of(uri), Optional.empty());

            var keysetHandle =
                    KeysetHandle.generateNew(
                            KmsEnvelopeAeadKeyManager.createKeyTemplate(uri, KeyTemplates.get("AES256_GCM")));
            Aead aead = keysetHandle.getPrimitive(Aead.class);
```


One additional question on the subject : 
If I want encrypt data from multiple customer, what is the correct way ? 
- create a single "Aead aead=xxxx"  and  use it multiple time ? ( DEK management is done automatically)
- have to create a new keysetHandle, then a new Aead for every customer ( DEK management is manual) 


Thank you

**Comment by juergw** [comment]
Yes, the problem you mentioned in Tink 1.5 was fixed in https://github.com/google/tink/commit/7ac97cb8d3e9955d3c87db0c6dd6aeeb5e6aa858.

I don't know what you mean by "multiple customers". But the two options you mentioned will do exactly the same thing. Because every time you call aead.encrypt, a new DEK is automatically generated, sent to the KMS for encryption, and then used to encrypt the message. The ciphertext returned by encrypt includes both the DEK-encrypted data and the KMS-encrypted DEK. aead.decrypt will extract the encrypted DEK from the ciphertext, then send it to the KMS to decrypt, get the DEK back and use it to decrypt the DEK-encrypted data from the ciphertext.

The DEK is always handled for you, there is no manual DEK management.
