### ISSUE TITLE
Build python3 wheel for macOS Big Sur

### ISSUE THREAD

**Issue by ozeranskiy** [google/tink#447]
Hi! Please build python3 wheel for macOS Big Sur.

**Comment by thaidn** [comment]
Acknowledged. Given current COVID situations, we might not be able to obtain a Big Sur machine.

@chuckx

**Comment by thaidn** [comment]
@chuckx have we obtained a Big Sur?

**Comment by busunkim96** [comment]
If GitHub Actions is an option for you folks they have both Big Sur and Catalina: https://github.com/actions/virtual-environments#available-environments
