### ISSUE TITLE
Javascript / Typescript docs are missing

### ISSUE THREAD

**Issue by chmac** [google/tink#449]
The root `README.md` links to `docs/JAVASCRIPT-HOWTO.md` which does not exist. I can't find the file anywhere else in the repo, so it doesn't look like the link has the wrong path.

Maybe this file exists somewhere else and hasn't been copied to this repo? Otherwise I guess it would make sense to either remove the link, or put a note that it's "coming soon", etc.

**Comment by mpaw** [comment]
This AMP page also states that Tink has examples and docs for JS, but both the links point to pages without JS docs/examples.
https://amp.dev/documentation/guides-and-tutorials/develop/monetization/content_encryption/

```
Tink has extensive documentation and examples in C++, Java, Go, and Javascript to help you get started on your server-side implementation.
```

**Comment by taymonbeal** [comment]
Sorry, this documentation doesn't exist yet. I've started writing it but am time-constrained at the moment so it will probably land in March.

The AMP website is wrong on multiple counts (Tink for JavaScript is still very alpha-quality, and also currently only supports browser environments, not servers). I'll send them a PR to fix it.

**Comment by nbransby** [comment]
Can't see much development on the JS support looking through the recent commits, will 1.6.0 feature any progress on the JS front? Also any plans on node support?

**Comment by sparachi** [comment]
Is there a plan to support Node based apps?

**Comment by officialpiyush** [comment]
> Is there a plan to support Node based apps?

maybe not, the developers firmly stated that they weren't looking to support NodeJS anytime soon

**Comment by juergw** [comment]
We intent to Remove Tink for JavaScript/TypeScript, see https://github.com/google/tink/issues/689.

So I will close this.
