### ISSUE TITLE
Consider switching away from 'org.json:json' in Java binding due to license issue

### ISSUE THREAD

**Issue by kien-truong** [google/tink#450]
`org.json:json` uses a non-free JSON license, which has already been banned by 

* [Apache Software Foundation][apache-cat-x]. 
* [Debian][debian-jsonevil] 

As a result, I think the dependency on `org.json:json` will prevent the usage of Google Tink in many OSS projects. You should consider migrating to some other JSON libraries, like [openjson][openjson] or even Google own `gson`

[apache-cat-x]: https://www.apache.org/legal/resolved.html#category-x
[debian-jsonevil]: https://wiki.debian.org/qa.debian.org/jsonevil
[openjson]: https://github.com/openjson/openjson

**Comment by thaidn** [comment]
Oh, good point.

@chuckx FYI, maybe this is something we should add to the 1.6.0 shopping list, if it isn't too complicated.

**Comment by thaidn** [comment]
I took a quick look and this looks like a fairly straight-forward change. However, I think it'll take at least half a day of work to finish.

Charles, what do you say?

**Comment by wyrickre** [comment]
Was there a decision here?

**Comment by thaidn** [comment]
org.json:json has been replaced with GSON. If there's no last minute surprise this should be shipped in 1.6.
