### ISSUE TITLE
error when use tink with Ktor Server

### ISSUE THREAD

**Issue by Abdktefane** [google/tink#451]
```kotlin
val keysetHandle = KeysetHandle.generateNew(
            AesGcmKeyManager.aes128GcmTemplate()
        )
val file = File(aesKeyFile)
val jsonKeysetWriter : KeysetWriter = JsonKeysetWriter.withFile(file)
CleartextKeysetHandle.write(keysetHandle, jsonKeysetWriter )
```
the server crash  with `Caused by: java.lang.NoClassDefFoundError: org/json/JSONException` `java.lang.ClassNotFoundException: org.json.JSONException`

**Comment by Abdktefane** [comment]
add this to build.gradle solve the problem
`implementation "org.json:json:20141113"`

**Comment by thaidn** [comment]
Yup, Tink depends on org.json.
