### ISSUE TITLE
More than one file was found with OS independent path 'build-data.properties'.

### ISSUE THREAD

**Issue by JcMinarro** [google/tink#452]
Adding this dependency to my android project break my build.
The gradle error is the following one:

```
Picked up _JAVA_OPTIONS: -Xms256m -Xmx6144m -XX:MaxPermSize=350m
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=350m; support was removed in 8.0
> Task :app:mergeDebugJavaResource FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'build-data.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
22 actionable tasks: 2 executed, 20 up-to-date
```

The file `build-data.properties` is present inside of your .jar file artifact (`com.google.crypto.tink:tink-android:1.5.0`) and it is present in the Google Maps SDK artifact as well (Beta version 3.1.0 `com.google.android.libraries.maps:maps:3.1.0-beta`)

`com.google.crypto.tink:tink-android:1.5.0` dependency is used inside of `androidx.security:security-crypto:1.1.0-alpha03` dependency, so anyone that wants to add this library and Google Maps SDK on the same project will have the same problem.

I can see that other Google projects like [Firebase](https://github.com/firebase/firebase-android-sdk) generate a properties file with the name of the artifact, instead of `build-data.properties` that avoid conflict on buildtime

**Comment by thaidn** [comment]
Interesting issue! StackOverflow suggests the following workarounds

```
packagingOptions {
    exclude  'build-data.properties'
 }
```

or

```
packagingOptions {
    pickFirst  'META-INF/*'
}
```

Does any work for you?

>I can see that other Google projects like Firebase generate a properties file with the name of the artifact, instead of build-data.properties that avoid conflict on buildtime

Thanks. I'll be working on a fix.

**Comment by JcMinarro** [comment]
Yes, it works, but it will take the first one that is found at compile-time and the content of both files are different.
I don't know if it could give some issues on runtime

**Comment by JcMinarro** [comment]
@thaidn @chuckx Any idea when it will be released?

**Comment by joejensen8** [comment]
@thaidn @chuckx I would appreciate if this library sends out a release so this fix can be included in my app 😄
