### ISSUE TITLE
java.security.GeneralSecurityException: cannot decrypt

### ISSUE THREAD

**Issue by alia071** [google/tink#467]
I'm unable to decrypt the response from GooglePay API using Tink library. When the decryptMessage function is called, the java.security.GeneralSecurityException: cannot decrypt exception is thrown.

   fun decryptMessage(encryptedMessage: String): String {
     return  PaymentMethodTokenRecipient.Builder()
               .fetchSenderVerifyingKeysWith(keyManagerType)
               .recipientId("merchant:$merchantId")
               .protocolVersion("ECv2")
               .addRecipientPrivateKey(fetchSignedKey)
               .build()
             .unseal(encryptedMessage)
   }

I'm using ECv2 protocol for decryption, I have noticed that unseal function calls unsealECv2 function which uses decrypt function which internally uses ECV1 protocol for decryption. Here is the decrypt function in PaymentMethodRecipient class.

  private String unsealECV2(String sealedMessage) throws JSONException, GeneralSecurityException {
    JSONObject jsonMsg = new JSONObject(sealedMessage);
    validateECV2(jsonMsg);
    String signedMessage = verifyECV2(jsonMsg);
    String decryptedMessage = decrypt(signedMessage);
    validateMessage(decryptedMessage);
    return decryptedMessage;
  }

  private String decrypt(String ciphertext) throws GeneralSecurityException {
    for (HybridDecrypt hybridDecrypter : hybridDecrypters) {
      try {
        byte[] cleartext =
            hybridDecrypter.decrypt(
                ciphertext.getBytes(StandardCharsets.UTF_8),
                PaymentMethodTokenConstants.GOOGLE_CONTEXT_INFO_ECV1);
        return new String(cleartext, StandardCharsets.UTF_8);
      } catch (GeneralSecurityException e) {
        // ignored, try again
      }
    }
    throw new GeneralSecurityException("cannot decrypt");
  } 

Can someone tell me why this exception is thrown? 
Can it be because the decrypt function is using PaymentMethodTokenConstants.GOOGLE_CONTEXT_INFO_ECV1 even when its ECV2 protocol?

Using  'com.google.crypto.tink:apps-paymentmethodtoken:1.5.0' for Android mobile app in Kotlin

**Comment by florinfm** [comment]
@alia071 can you please confirm that the payload you have generated is for Direct integration.
https://developers.google.com/pay/api/android/reference/request-objects#direct

If not please make sure to update  ``.recipientId("merchant:$merchantId")``  accordingly
https://developers.google.com/pay/api/android/guides/resources/payment-data-cryptography#using-tink

**Comment by juergw** [comment]
I'm closing this because it wasn't updated in 2 years.
