### ISSUE TITLE
Decryption Failed - Unable to get primitive

### ISSUE THREAD

**Issue by matthewsamari** [google/tink#468]
**Help us help you**

Please tell us more about
[your Tink deployment](https://docs.google.com/forms/d/1mhHvyNJQgTXFDnqOermB7-BD8GQSyvtFPUAhILRbYcA/edit).

This is on a MacOS. 

When I use the decrypt method, Tink continuously fails to get the primitive. 
I am writing the keyfile to disk (temporarily) while I attempt to decrypt, write to a file, and encrypt.

**Describe the bug**

Tink never gets the correct primitive. The value is always null. Even when using the correct key file.

**To Reproduce**

Include buildable code snippets or gists which triggered the bug.
<img width="1034" alt="Screen Shot 2021-02-02 at 2 36 49 PM" src="https://user-images.githubusercontent.com/51834683/106665882-18138700-6564-11eb-99a8-c14f19c46725.png">

**Expected behavior**

The file decrypts, writes and encrypts.

**Error messages, stack traces, etc.**

If applicable, please include error messages, stack traces or any debugging
information.

**Version information**

 - Language: Java
 - Version: 15.0.1
 - Environment: gradle built.

**Comment by thaidn** [comment]
Can you provide a stack trace or error message?

**Comment by thaidn** [comment]
I think this is probably a problem with the string encoding. Please encode your ciphertext as Base64 and reopen if it still doesn't work.
