### ISSUE TITLE
Java: Add automatic module name to jar

### ISSUE THREAD

**Issue by Dunemaster** [google/tink#473]
Please, add add automatic module name in jar (META-INF\MANIFEST.MF)
For better compatibility with JPMS and to prevent warnings like

"Required filename-based automodules detected: [tink-1.3.0.jar]. Please don't publish this project to a public artifact repository!"

module-info would be even better

**Comment by thaidn** [comment]
Thanks. I'm taking care of this now.

**Comment by thaidn** [comment]
According to http://branchandbound.net/blog/java/2017/12/automatic-module-name/, this looks more complicated than I thought. It'll take me more time to decide what's the right thing to do here.

**Comment by Dunemaster** [comment]
> According to http://branchandbound.net/blog/java/2017/12/automatic-module-name/, this looks more complicated than I thought. It'll take me more time to decide what's the right thing to do here.

Thank you for looking into this issue. Can you be more specific what concerns you?

**Comment by thaidn** [comment]
Ah I'm just not familiar with this and I thought I'd need some time to make sense of it.

To speed this up, can you give me an example that would work in your opinion?

**Comment by Dunemaster** [comment]
Well, I think just adding automatic-module-name to manifest will work, as module name derived from jar name currently works ok.

**Comment by thaidn** [comment]
Thanks I'll add this line to tink.jar:

```
Automatic-Module-Name: tink
```

How's about [tink-gcpkms](https://mvnrepository.com/artifact/com.google.crypto.tink/tink-gcpkms)? I'm not sure if I should use `tink` or `tink-gcpkms`.

**Comment by thaidn** [comment]
@tholenst wdyt?

**Comment by thaidn** [comment]
>This will work if you are ok with fixing "tink" as module name, not something else ( e.g. not com.google.tink)

Why can't we use `com.google.tink` or `com.google.crypto.tink`?

**Comment by AyomideYoung** [comment]
> > This will work if you are ok with fixing "tink" as module name, not something else ( e.g. not com.google.tink)
> 
> Why can't we use `com.google.tink` or `com.google.crypto.tink`?

Yeah. I think that makes more sense and it seems to be the preferred community approach

**Comment by Dunemaster** [comment]
`Why can't we use com.google.tink or com.google.crypto.tink?`

sure you can, just mind that it would be a compatibility break

**Comment by thaidn** [comment]
Thanks. This is fixed and will be included in 1.7.0.
