### ISSUE TITLE
NIST Curve P-256 is considered unsafe?

### ISSUE THREAD

**Issue by evalsinca** [google/tink#477]
I love Tink - and commend you for the awesome work you all have done to make crypto easy for us.  

That said, I am reading that NIST curves, in general, and P256 in particular are considered unsafe (see https://safecurves.cr.yp.to/).  

Bernstein et al give their blessing to curve 25519 but that is not available for Java - which is our primary platform and for which only P256 is available.

Are there plans to add other non-NIST curves to Java?   Thanks!

**Comment by thaidn** [comment]
Thanks for the report.

Contrary to belief made popular by DJB, there's no practical attack against P-256. Nobody has even came up with a theoretical weakness uniquely applied to this curve. I agree that the way it was generated is somewhat shady, but so far we don't have real evidence to support any claim of malice.

>Are there plans to add other non-NIST curves to Java? Thanks!

We have a plan to add X25519 for ECIES. Tink Java also supports Ed25519's signature scheme.
