### ISSUE TITLE
No key manager found for key type type.googleapis.com/google.crypto.tink.AesGcmSivKey

### ISSUE THREAD

**Issue by dave-pollock** [google/tink#482]
Hi there. Just trying to get started with AES-GCM-SIV using Java (Scala actually).

**Describe the bug**
When attempting to generate a key set, I get the error `No key manager found for key type type.googleapis.com/google.crypto.tink.AesGcmSivKey`, even though I have called `AeadConfig.register()` (and also tried `TinkConfig.register()`). Other modes are working fine - I've tried AES-GCM and XChaCha20Poly1305 with no issues. I noticed AES-GCM-SIV was only added in the latest version and there is a mention that Conscrypt would be required in Java. Is there something I need to do to configure Conscrypt? I tried including it as a dependency but that didn't seem to help.

**To Reproduce**
```
import com.google.crypto.tink.KeysetHandle
import com.google.crypto.tink.KeyTemplate
import com.google.crypto.tink.Aead
import com.google.crypto.tink.aead.AeadConfig
import com.google.crypto.tink.aead.AesGcmSivKeyManager

AeadConfig.register()
// also tried: TinkConfig.register()

val keysetTemplate: KeyTemplate = AesGcmSivKeyManager.aes128GcmSivTemplate()
val keysetHandle: KeysetHandle = KeysetHandle.generateNew(keysetTemplate)

val aead: Aead = keysetHandle.getPrimitive(classOf[Aead])

println(aead.encrypt("test".getBytes(), null))
```

**Expected behavior**
Expect to be able to generate an AES-GCM-SIV key set and use it to encrypt some plaintext.

**Error messages, stack traces, etc.**
```
java.security.GeneralSecurityException: No key manager found for key type type.googleapis.com/google.crypto.tink.AesGcmSivKey
	at com.google.crypto.tink.Registry.getKeyManagerContainerOrThrow(Registry.java:317)
	at com.google.crypto.tink.Registry.getUntypedKeyManager(Registry.java:656)
	at com.google.crypto.tink.Registry.newKeyData(Registry.java:712)
	at com.google.crypto.tink.KeysetManager.newKey(KeysetManager.java:245)
	at com.google.crypto.tink.KeysetManager.addNewKey(KeysetManager.java:111)
	at com.google.crypto.tink.KeysetManager.rotate(KeysetManager.java:69)
	at com.google.crypto.tink.KeysetHandle.generateNew(KeysetHandle.java:90)
```

**Version information**
 - Language: Scala / Java
 - Version: Tink 1.5.0
 - Environment: openjdk version "11.0.10" 2021-01-19 with Scala 2.13.0.

**Additional context**
In build.sbt I've added these dependencies:
```
libraryDependencies ++= Seq(
  "com.google.crypto.tink" % "tink" % "1.5.0",
  "org.conscrypt" % "conscrypt-openjdk-uber" % "2.4.0"
)

**Comment by thaidn** [comment]
Have you tried to install Conscrypt?

```
import java.security.Security;
import org.conscrypt.Conscrypt;

Conscrypt.checkAvailability();
Security.addProvider(Conscrypt.newProvider());
```

**Comment by dave-pollock** [comment]
Thanks for your response @thaidn. That seems to solve the problem. Cheers!

Would be nice if this was in the docs - it's not at all obvious that there is anything special about AES-GCM-SIV just based on the java guide.

Thanks again.
