### ISSUE TITLE
Installing Python library with pip requires Bazel

### ISSUE THREAD

**Issue by shubha-rajan** [google/tink#483]
**Describe the bug**

Installing Tink with pip leads to an error which requires that Bazel is required in the build environment, however, this is not documented in the README section about installing with pip: https://github.com/google/tink/blob/master/docs/PYTHON-HOWTO.md#setup-instructions

**To Reproduce**

see: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/5554
build logs: https://source.cloud.google.com/results/invocations/4fd9109f-6d12-439b-8cd9-184c6c148bf3/targets/cloud-devrel%2Fpython-docs-samples%2Fpython3.6%2Fpresubmit/log

**Error messages, stack traces, etc.**

```
Collecting tink==1.5.0
  Downloading tink-1.5.0.tar.gz (132 kB)
    ERROR: Command errored out with exit status 255:
     command: /workspace/cloud-sql/mysql/client-side-encryption/.nox/py-3-6/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4d32fzby/tink_abe5aa1dcbfb43c1be75080f6727880b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4d32fzby/tink_abe5aa1dcbfb43c1be75080f6727880b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-9vsrzphv
         cwd: /tmp/pip-install-4d32fzby/tink_abe5aa1dcbfb43c1be75080f6727880b/
    Complete output (1 lines):
    Could not find bazel executable. Please install bazel tocompile the Tink Python package.
```

**Version information**

 - Language: Python
 - Version: 1.5.0
 - Environment: Python3, Ubuntu 20.04(in docker container)

**Comment by kste** [comment]
It looks like you are using Python 3.6, which is not supported, as Tink relies on some features which available only starting in Python 3.7. There are binary releases available for Python 3.7 and 3.8 available, which will not require to install Bazel.

**Comment by wilford** [comment]
We are seeing this issue in Cloud Shell (https://shell.cloud.google.com), even when using python 3.7.

You can repro this by navigating to https://shell.cloud.google.com and then running `sudo pip3 uninstall -y tink && pip3 install tink`. 

Note that bazel will be run, and a build error will result.

**Comment by kste** [comment]
Would it be possible to upgrade the pip version on Cloud shell? Upgrading pip (`pip3 install --upgrade pip`), fixed the error for me and allows to install the binary wheels.

**Comment by wilford** [comment]
Unfortunately, we've looked at upgrading the version of pip3, and that causes other issues.

This appears to be an issue with the OS we are using. We are currently running debian:buster (current stable debian release) and install pip3 using the standard debian repos. There are numerous warnings about the older supported version of pip3 in debian around the web [1][2][3], and that manually upgrading pip is a bad idea and may cause issues.  Instead, the recommended workaround to upgrade pip3 is to use virtualenv.

The version of pip3 should be updated with the stable release of debian:bullseye, but that may be a few months off.

[1] https://cryptography.io/en/latest/installation/#rust
[2] https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py
[3] https://pythonspeed.com/articles/upgrade-pip/

**Comment by aftab-sigmoid** [comment]
This issues has not been resolved as of now

**Comment by seandinhsquare** [comment]
Getting the same error - MBP M1 Python 3.8.13 = pip-22.3.1

**Comment by juergw** [comment]
Note that Tink 1.7.0 for Python has now been released, see https://pypi.org/project/tink/.

Is this still an issue?

I have tried to install tink on https://shell.cloud.google.com/ and it works.

**Comment by juergw** [comment]
I'll close this now. Please re-open if there is still an issue.

**Comment by davidkhala** [comment]
@juergw I still see this issue even in 1.7.0. Would you mind reopen this while we are collecting info?
