### ISSUE TITLE
Expose AWSClientConfiguration options through tink (like proxyHost and endPointOverride)

### ISSUE THREAD

**Issue by lfendy** [google/tink#485]
**Help us help you**

We have master keys wrapped AWS KMS. We are primarily using python tink SDK.

**Is your feature request related to a problem?**

Yes,

We would like to access AWS KMS tink from an environment without direct access to the internet, thus we need to use a proxy.
This is an issue for us because it seems that AWSClientConfiguration is hardcoded to parse from ARNs:
See:
https://github.com/google/tink/blob/77afecf5b5181efe971ab18a5bd6f25536eb1300/cc/integration/awskms/aws_kms_client.cc#L61-L74

**Describe the solution you'd like**

We would like the ability to supply configuration items for AWSClientConfiguration when we instantiate AWSKMSClient:
See: https://sdk.amazonaws.com/cpp/api/LATEST/struct_aws_1_1_client_1_1_client_configuration.html

This would allow us to supply either `proxyHost` or `endpointOverride` that can allow us to access AWS endpoints.

```
# using the python sdk
import tink

from tink.integration import awskms

key_uri = 'aws-kms://arn:aws:kms:<region>:<account_number>:key/<key_id>'
aws_client = awskms.AwsKmsClient(key_uri, '')
```

**Describe alternatives you've considered**

N/A

**Additional context**

We noticed that `boto3` python library respects the `HTTPS_PROXY` environment variable out of the box.

**Comment by duanasq** [comment]
I've started writing a PR for a basic fix for this that will get the aws kms c++ client to read from `HTTPS_PROXY` env variable.

**Comment by chuckx** [comment]
The Python AWS KMS extension has been migrated to pure Python using the `boto3` library (see 6c2a240a3c746966d060b5e9f22ed19057b0ec87).

Given your observation that `boto3` respects the `HTTP_PROXY` environment variable, the current implementation should now handle your use case.

I'm going to go ahead and close this, but please feel free to reopen if there are any additional aspects that need to be accounted for.
