### ISSUE TITLE
Linking problems for >C++14.

### ISSUE THREAD

**Issue by aarlt** [google/tink#486]
I would like to use Tink in an application that uses at least C++17.

It is not possible to link the resulting application correctly, due to linking problems related to `abseil-cpp`. I didn't checked the built-system yet, but maybe the problem is related that `abseil-cpp` is getting compiled with another version of the c++ standard.

**How to reproduce?**

I used Tink v1.5.0.

Change `CMakeLists.txt` of the `helloworld` example located in `tink/examples/cc/helloworld` and set `CMAKE_CXX_STANDARD` to `17`. 

_Note: There are no linking problems with c++14._

```cmake
# 3.5 is the minimum version supported by Tink and its dependencies.
cmake_minimum_required(VERSION 3.5)
project(TinkHelloWorld CXX)
set(CMAKE_CXX_STANDARD 17)

set(CMAKE_BUILD_TYPE Release)

# Import Tink as an in-tree dependency.
add_subdirectory(../../.. tink)

add_executable(hello_world hello_world.cc)
target_link_libraries(hello_world tink::static)
```

I also didn't find any documentation about what c++ standards are actually supported by Tink - but maybe I missed that. 

If `CMAKE_CXX_STANDARD` is set to `17`, the linking fails due to undefined symbols related to `absl` (abseil-cpp):
```
Consolidate compiler generated dependencies of target hello_world
[ 93%] Linking CXX executable hello_world
Undefined symbols for architecture x86_64:
  "absl::cord_internal::NewExternalWithUninitializedReleaser(absl::string_view, unsigned long (*)(void*, absl::string_view), unsigned long)", referenced from:
      crypto::tink::CordAesGcmBoringSsl::Encrypt(absl::Cord, absl::Cord) const in libtink_internal_aead__internal_cord_aes_gcm_boringssl.a(cord_aes_gcm_boringssl.cc.o)
      crypto::tink::CordAesGcmBoringSsl::Decrypt(absl::Cord, absl::Cord) const in libtink_internal_aead__internal_cord_aes_gcm_boringssl.a(cord_aes_gcm_boringssl.cc.o)
  "absl::Base64Unescape(absl::string_view, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)", referenced from:
      crypto::tink::JsonKeysetReader::Read() in libtink_internal_core_json_keyset_reader.a(json_keyset_reader.cc.o)
      crypto::tink::JsonKeysetReader::ReadEncrypted() in libtink_internal_core_json_keyset_reader.a(json_keyset_reader.cc.o)
  "absl::strings_internal::CatPieces(std::initializer_list<absl::string_view>)", referenced from:
      crypto::tink::util::Status crypto::tink::RegistryImpl::RegisterAsymmetricKeyManagers<google::crypto::tink::EciesAeadHkdfPrivateKey, google::crypto::tink::EciesAeadHkdfKeyFormat, google::crypto::tink::EciesAeadHkdfPublicKey, crypto::tink::List<crypto::tink::HybridDecrypt>, crypto::tink::List<crypto::tink::HybridEncrypt> >(crypto::tink::PrivateKeyTypeManager<google::crypto::tink::EciesAeadHkdfPrivateKey, google::crypto::tink::EciesAeadHkdfKeyFormat, google::crypto::tink::EciesAeadHkdfPublicKey, crypto::tink::List<crypto::tink::HybridDecrypt> >*, crypto::tink::KeyTypeManager<google::crypto::tink::EciesAeadHkdfPublicKey, void, crypto::tink::List<crypto::tink::HybridEncrypt> >*, bool) in libtink_internal_hybrid_hybrid_config.a(hybrid_config.cc.o)
      crypto::tink::util::Status crypto::tink::RegistryImpl::RegisterAsymmetricKeyManagers<google::crypto::tink::EcdsaPrivateKey, google::crypto::tink::EcdsaKeyFormat, google::crypto::tink::EcdsaPublicKey, crypto::tink::List<crypto::tink::PublicKeySign>, crypto::tink::List<crypto::tink::PublicKeyVerify> >(crypto::tink::PrivateKeyTypeManager<google::crypto::tink::EcdsaPrivateKey, google::crypto::tink::EcdsaKeyFormat, google::crypto::tink::EcdsaPublicKey, crypto::tink::List<crypto::tink::PublicKeySign> >*, crypto::tink::KeyTypeManager<google::crypto::tink::EcdsaPublicKey, void, crypto::tink::List<crypto::tink::PublicKeyVerify> >*, bool) in libtink_internal_signature_signature_config.a(signature_config.cc.o)
      crypto::tink::util::Status crypto::tink::RegistryImpl::RegisterAsymmetricKeyManagers<google::crypto::tink::RsaSsaPssPrivateKey, google::crypto::tink::RsaSsaPssKeyFormat, google::crypto::tink::RsaSsaPssPublicKey, crypto::tink::List<crypto::tink::PublicKeySign>, crypto::tink::List<crypto::tink::PublicKeyVerify> >(crypto::tink::PrivateKeyTypeManager<google::crypto::tink::RsaSsaPssPrivateKey, google::crypto::tink::RsaSsaPssKeyFormat, google::crypto::tink::RsaSsaPssPublicKey, crypto::tink::List<crypto::tink::PublicKeySign> >*, crypto::tink::KeyTypeManager<google::crypto::tink::RsaSsaPssPublicKey, void, crypto::tink::List<crypto::tink::PublicKeyVerify> >*, bool) in libtink_internal_signature_signature_config.a(signature_config.cc.o)
      crypto::tink::util::Status crypto::tink::RegistryImpl::RegisterAsymmetricKeyManagers<google::crypto::tink::RsaSsaPkcs1PrivateKey, google
...
```

**Comment by thaidn** [comment]
@tholenst

**Comment by carloscbl** [comment]
Probably the same,
im using C++17, g++ 9 and 10

> [100%] Linking CXX executable ../test_prot
/usr/bin/ld: /usr/bin/ld: DWARF error: could not find variable specification at offset 1c1d
/usr/bin/ld: DWARF error: could not find variable specification at offset 1c7a
...
/usr/bin/ld: DWARF error: could not find variable specification at offset 1a0f1
../thirdparty/tink/cc/aead/libtink_internal_aead_aead_wrapper.a(aead_wrapper.cc.o): in function `void absl::str_format_internal::FormatArgImpl::Init<absl::string_view>(absl::string_view const&)':
/home/cbernal/services_prot/prot/build/thirdparty/tink/__third_party/com_google_absl/src/absl/strings/internal/str_format/arg.h:419: undefined reference to `bool absl::str_format_internal::FormatArgImpl::Dispatch<absl::string_view>(absl::str_format_internal::FormatArgImpl::Data, absl::str_format_internal::FormatConversionSpecImpl, void*)'
/usr/bin/ld: /home/cbernal/services_prot/prot/build/thirdparty/tink/__third_party/com_google_absl/src/absl/strings/internal/str_format/arg.h:419: undefined reference to `bool absl::str_format_internal::FormatArgImpl::Dispatch<absl::string_view>(absl::str_format_internal::FormatArgImpl::Data, absl::str_format_internal::FormatConversionSpecImpl, void*)'
/usr/bin/ld: /usr/bin/ld: DWARF error: could not find variable specification at offset 1c1b
/usr/bin/ld: DWARF error: could not find variable specification at offset 1c78
...
/usr/bin/ld: DWARF error: could not find variable specification at offset 2a5ec
../thirdparty/tink/cc/mac/libtink_internal_mac_mac_config.a(mac_config.cc.o): in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > absl::StrCat<absl::string_view>(absl::AlphaNum const&, absl::AlphaNum const&, absl::AlphaNum const&, absl::AlphaNum const&, absl::AlphaNum const&, absl::string_view const&)':
/home/cbernal/services_prot/prot/build/thirdparty/tink/__third_party/com_google_absl/src/absl/strings/str_cat.h:346: undefined reference to `absl::strings_internal::CatPieces[abi:cxx11](std::initializer_list<absl::string_view>)'
/usr/bin/ld: /usr/bin/ld: DWARF error: could not find variable specification at offset 1bf9
/usr/bin/ld: DWARF error: could not find variable specification at offset 1c55
...
/usr/bin/ld: DWARF error: could not find variable specification at offset 1a183
../thirdparty/tink/cc/mac/libtink_internal_mac_mac_wrapper.a(mac_wrapper.cc.o): in function `void absl::str_format_internal::FormatArgImpl::Init<absl::string_view>(absl::string_view const&)':
/home/cbernal/services_prot/prot/build/thirdparty/tink/__third_party/com_google_absl/src/absl/strings/internal/str_format/arg.h:419: undefined reference to `bool absl::str_format_internal::FormatArgImpl::Dispatch<absl::string_view>(absl::str_format_internal::FormatArgImpl::Data, absl::str_format_internal::FormatConversionSpecImpl, void*)'
/usr/bin/ld: /home/cbernal/services_prot/prot/build/thirdparty/tink/__third_party/com_google_absl/src/absl/strings/internal/str_format/arg.h:419: undefined reference to `bool absl::str_format_internal::FormatArgImpl::Dispatch<absl::string_view>(absl::str_format_internal::FormatArgImpl::Data, absl::str_format_internal::FormatConversionSpecImpl, void*)'
/usr/bin/ld: /usr/bin/ld: DWARF error: could not find variable specification at offset 1cd6
/usr/bin/ld: DWARF error: could not find variable specification at offset 1d33
...
/usr/bin/ld: DWARF error: could not find variable specification at offset ee3c
../thirdparty/tink/cc/subtle/libtink_internal_subtle_subtle_util_boringssl.a(subtle_util_boringssl.cc.o): in function `absl::SubstituteAndAppend(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, absl::string_view, absl::substitute_internal::Arg const&, absl::substitute_internal::Arg const&)':
/home/cbernal/services_prot/prot/build/thirdparty/tink/__third_party/com_google_absl/src/absl/strings/substitute.h:255: undefined reference to `absl::substitute_internal::SubstituteAndAppendArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, absl::string_view, absl::string_view const*, unsigned long)'
/usr/bin/ld: /home/cbernal/services_prot/prot/build/thirdparty/tink/__third_party/com_google_absl/src/absl/strings/substitute.h:255: undefined reference to `absl::substitute_internal::SubstituteAndAppendArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, absl::string_view, absl::string_view const*, unsigned long)'
/usr/bin/ld: /usr/bin/ld: DWARF error: could not find variable specification at offset f915
/usr/bin/ld: DWARF error: could not find variable specification at offset f923
...
/usr/bin/ld: DWARF error: could not find variable specification at offset 4ffd
../thirdparty/tink/cc/util/libtink_util_status.a(status.cc.o): in function `crypto::tink::util::Status::operator absl::Status() const':
/home/cbernal/services_prot/prot/thirdparty/tink/cc/util/status.cc:61: undefined reference to `absl::Status::Status(absl::StatusCode, absl::string_view)'

**Comment by carloscbl** [comment]
Tested with Tink 1.4

`./thirdparty/tink/cc/subtle/libtink_internal_subtle_subtle_util_boringssl.a(subtle_util_boringssl.cc.o): in function `absl::SubstituteAndAppend(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, absl::string_view, absl::substitute_internal::Arg const&, absl::substitute_internal::Arg const&)':
/home/cbernal/services_prot/prot/build/thirdparty/tink/__third_party/com_google_absl/src/absl/strings/substitute.h:252: undefined reference to `absl::substitute_internal::SubstituteAndAppendArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, absl::string_view, absl::string_view const*, unsigned long)'
/usr/bin/ld: /home/cbernal/services_prot/prot/build/thirdparty/tink/__third_party/com_google_absl/src/absl/strings/substitute.h:252: undefined reference to `absl::substitute_internal::SubstituteAndAppendArray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, absl::string_view, absl::string_view const*, unsigned long)'
/usr/bin/ld: /usr/bin/ld: DWARF error: could not find variable specification at offset d402
....
/usr/bin/ld: DWARF error: could not find variable specification at offset 4396
../thirdparty/tink/cc/util/libtink_util_status.a(status.cc.o): in function `crypto::tink::util::Status::operator absl::Status() const':
/home/cbernal/services_prot/prot/thirdparty/tink/cc/util/status.cc:61: undefined reference to `absl::Status::Status(absl::StatusCode, absl::string_view)'`

**Comment by carloscbl** [comment]
You almost kill me
set(TINK_CXX_STANDARD 17) in the top cmakelist.txt
