### ISSUE TITLE
CMake Error -> ANDROID STUDIO

### ISSUE THREAD

**Issue by ANURAGX** [google/tink#488]
I have been trying to develop build tink C++ on android studio and CMake throws error.
`Execution failed for task ':app:generateJsonModelDebug'.
> /Users/anurag/Desktop/native-activity/app/src/main/cpp/CMakeLists.txt : C/C++ debug|armeabi-v7a : CMake Error at /Users/anurag/Desktop/native-activity/app/src/main/cpp/third_party/tink/aead/CMakeLists.txt:1 (tink_module):
    Unknown CMake command "tink_module".

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.`

And this is my CMakeList.txt

`cmake_minimum_required(VERSION 3.7)
set(CMAKE_CXX_STANDARD 11)
add_subdirectory(third_party/tink)
add_executable(native-activity main.cpp)
target_link_libraries(native-activity tink::static)`

**Comment by ANURAGX** [comment]
Hi maintainers,
any comments here.

**Comment by tholenst** [comment]
What CMake version are you using? I'm not familiar with the Android Studio platform. Can you comment more on it?

**Comment by tholenst** [comment]
I will close this -- sorry we didn't respond faster. If there is still a problem, please reopen or file a new issue in https://github.com/tink-crypto/tink-cc
