### ISSUE TITLE
Support using the Objective-C library on macOS

### ISSUE THREAD

**Issue by vmsp** [google/tink#491]
I just tried using the ObjectiveC library, through CocoaPods and got

``` bash
$ pod install
Analyzing dependencies
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
[!] The platform of the target `Keylo` (macOS 10.15) is not compatible with `Tink (1.5.0)`, which does not support `macOS`.
```

EDIT: Or provide instructions for using Bazel, like the C++ library. That would also work.

**Comment by thaidn** [comment]
You're right that Tink doesn't support macOS yet. We'll see what we can do.

**Comment by tholenst** [comment]
Unfortunately, we currently do not have capacity to work on Objective C.
