### ISSUE TITLE
Alternative to AesGmcJce in Python

### ISSUE THREAD

**Issue by davidmorabito** [google/tink#492]
Hi,

I have a script to encrypt a given text but not sure there is an alternative in Python. Here's the snippet I'm using:

`AesGcmJce agjEncryption = new AesGcmJce("MY_SECRET".getBytes());`
`byte[] encrypted = agjEncryption.encrypt("TEXT_TO_BE_ENCRYPTED".getBytes(), null);`

How can I achieve this using Tink Python library?

**Comment by kste** [comment]
Hi,

We have an [example](https://github.com/google/tink/tree/master/examples/python/aead) for a simple CLI program which does encryption with GCM with a key generated with Tinkey.

**Comment by thaidn** [comment]
Please reopen if you have any further question.
