### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by NathanNZ** [google/tink#494]
I personally would love to be able to use this library within existing .NET Core applications - if a contribution of acceptable quality that added a .NET Core Library with feature parity to the other implementations was submitted, would this be something the project maintainers would consider for inclusion?

**Comment by thaidn** [comment]
Unfortunately, we don't have anyone in the team that knows C#, so it'd be hard for us to maintain it. We can give you guidance in API design and review your implementation, but it'll have to stay in a separate repo.

**Comment by npgovintarajan** [comment]
Could you please provide guidance on keeping the tink related JARs for the following example: https://github.com/google-pay/tink-jni-examples/blob/master/docs/CS-HOWTO.md

**Comment by thaidn** [comment]
>Could you please provide guidance on keeping the tink related JARs for the following example: https://github.com/google-pay/tink-jni-examples/blob/master/docs/CS-HOWTO.md

I'm sorry but I don't understand the question.

**Comment by sachinkoppikar** [comment]
@thaidn I can volunteer for creating a .Net version of Tink

**Comment by tholenst** [comment]
We will not maintain this. It would be great if the open source community creates such a version, but we cannot currently do work for this.
