### ISSUE TITLE
Java: isAndroid() shouldn't cause Exceptions to be created

### ISSUE THREAD

**Issue by michael-ameri** [google/tink#497]
**Is your feature request related to a problem?**
com.google.crypto.tink.subtle.SubtleUtil#isAndroid causes a lot of Exceptions to be created during runtime when **not** running on android, since it is called for every invocation of AesGcmJce.encrypt.

**Describe the solution you'd like**
The method should check if it is running on android without throwing and catching an Exception. Possible solutions:
- Check a system property
-- https://stackoverflow.com/questions/4519556/how-to-determine-if-my-app-is-running-on-android
-- https://developer.android.com/reference/java/lang/System#getProperties()
- In case that is not reliable enough: Define an optional custom System Property which can be set to avoid the Class lookup.
- Only perform the lookup once on startup

**Comment by thaidn** [comment]
Ah thanks. I'll fix this.
