### ISSUE TITLE
Python 3.6 official support

### ISSUE THREAD

**Issue by tiboun** [google/tink#499]
Hi, we are currently working with tink in java since two years ago in order to cypher data with dataflow before inserting it to bigquery. This job is the only one in java, others are in python and we would like to change this job to python in order to remove one language from our stack.

Our dataflow is launched by composer and currently composer support only python 3.6 so is our python dataflow job. Tink python officially support 3.7 and 3.8 and I would like to know if you plan to add support for 3.6 as well.

Thanks for your support.

**Comment by kste** [comment]
Hi Tiboun,

There is no plan to add support for a Python 3.6 release at the moment, as it's reaching EOL this year. If you need Python 3.6 you could build the package manually, but this will require some modifications to the code base: Tink uses some type hints which are not supported in 3.6 and those would have to be removed first.
