### ISSUE TITLE
working example in java

### ISSUE THREAD

**Issue by listaction** [google/tink#500]
Hi Folks, 
 trying this out - seeing that docs are not update - is there an example of how to use the api?

```
https://github.com/google/tink/blob/master/docs/JAVA-HOWTO.md#symmetric-key-encryption
    // 1. Generate the key material.
    KeysetHandle keysetHandle = KeysetHandle.generateNew(
        KeyTemplates.get("AES128_GCM"));

there is no class called KeyTemplates and the other methods such as `AeadKeyTemplates.AES128_GCM` seem to be deprecated. I am using version 1.5
```

**Comment by atulluykx** [comment]
Yea, KeyTemplates was introduced in 1.6. In 1.5 you can get the right key template via the key managers, for example AesGcmKeyManager.aes128GcmTemplate().

**Comment by listaction** [comment]
thanks @atulluykx  - do you recommend using 1.6 ?

**Comment by atulluykx** [comment]
Yes, I do recommend using 1.6 if you can. Let us know if you have any issues in doing so. We're slowly working on updating the documentation, so there might be some oversights.
