### ISSUE TITLE
java.security.UnrecoverableKeyException with tink 1.4.0

### ISSUE THREAD

**Issue by snehas13** [google/tink#505]
Below exception has been reproduced by one of the user in our production app.

**Caused by java.security.UnrecoverableKeyException**
Failed to obtain information about key

android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreSecretKeyFromKeystore (AndroidKeyStoreProvider.java:286)
java.security.KeyStore.getEntry (KeyStore.java:1621)
com.efe.user.dataSecurity.KeyStoreTinkManager.getSecretKey (KeyStoreTinkManager.java:99)
com.efe.user.dataSecurity.KeyStoreTinkManager.getOrGenerateNewKeysetHandle (KeyStoreTinkManager.java:42)
com.efe.user.dataSecurity.KeyStoreTinkManager.<init> (KeyStoreTinkManager.java:35)

**Device Info**: Galaxy Tab E8.0 android version: 8.1.0

Let us know the root cause of this issue.
And let me know if it is fixed in 1.6.0 latest tink library version

**Comment by thaidn** [comment]
Tink stores keys in [Android Keystore](https://developer.android.com/training/articles/keystore), which is known to be pretty buggy on several phones.

It looks like for whatever reason the Android Keystore on your user's phone couldn't read the key that Tink stores in it. This is unfortunate, but there's very little we can do about this. I'm sorry :-(
