### ISSUE TITLE
Tink Python 3.9 support 

### ISSUE THREAD

**Issue by adongnmh** [google/tink#514]
I tried installing tink on Python 3.9.5 and I am getting the following errors:
![Screen Shot 2021-05-31 at 10 15 32](https://user-images.githubusercontent.com/10677901/120219888-27949b00-c1f9-11eb-923b-7293ec02eb8e.png)

On the `PYTHON-HOWTO` it specifies that `The simplest way is to install a binary release from PyPi:`

Why do I need bazel?

**Comment by kste** [comment]
The 1.5 release on PyPi did not include Python 3.9 support therefore you have to build Tink from source (which requires Bazel). However, the 1.6 release includes Python 3.9 support and will be up on PyPi very soon, then you should have no problem with installing without Bazel.

**Comment by adongnmh** [comment]
@kste Is there a ETA on the 1.6 release?

**Comment by chuckx** [comment]
The 1.6.0 release should be uploaded later today or tomorrow. I'm finishing up validation of the release artifacts now.

**Comment by chuckx** [comment]
1.6.0 Python packages have just been published, which includes a binary wheel for Python 3.9.
