### ISSUE TITLE
How to generate Data format of keyset for Swift/Objective C

### ISSUE THREAD

**Issue by annathomasQB** [google/tink#515]
Hi,

How do we get the data or base 64 encoded string of a keyset? In the following sample code found in the documentation: 
  ```
#import "Tink/TINKBinaryKeysetReader.h"
    #import "Tink/TINKKeysetHandle+Cleartext.h"

    NSError *error = nil;
    NSData *binaryKeyset = ...;
    TINKBinaryKeysetReader *reader = [[TINKBinaryKeysetReader alloc] initWithSerializedKeyset:binaryKeyset
                                                                                        error:&error];
    if (!reader || error) {
      // handle error.
    }

    TINKKeysetHandle *handle = [[TINKKeysetHandle alloc] initCleartextKeysetHandleWithKeysetReader:reader
                                                                                             error:&error];
    if (!handle || error) {
      // handle error.
    }
```
You can see the BinaryKeysetReader initialized using NSData. What I want to know is, how do I generate this data of a keyset? 

I can say it's equivalent to public key base 64 encoded string, or PEM or DER in terms of normal encryption methods. 
How do I get that from Tink for Objective-C/Swift? 

The equivalent Java code has KeysetWriter, as per the following code :

```
        KeysetHandle handle = KeysetHandle.generateNew(AeadKeyTemplates.AES256_GCM);
        ByteArrayOutputStream keyStream = new ByteArrayOutputStream();
        KeysetWriter privateKeyWriter = BinaryKeysetWriter.withOutputStream(keyStream);
        CleartextKeysetHandle.write(handle, privateKeyWriter);
        System.out.println("KEY : "+ Base64.getEncoder().encodeToString(keyStream.toByteArray()));

```

**Comment by annathomasQB** [comment]
Got an update.

On searching the documentation for Tink 1.6.0, saw this (see attached screenshot)

On testing in my code, found that the following gave a valid output: 
```

        let config = try! TINKAeadConfig.init()
        try! TINKConfig.register(config)
        let template = try! TINKAeadKeyTemplate.init(keyTemplate: .TINKAes256Gcm)
        let handle = try! TINKKeysetHandle.init(keyTemplate: template)
        let firstData = handle.serializedKeyset()
        var error: NSError?
        let secondData = handle.serializedKeysetNoSecret(&error)
        let publicKeyHandle = try! TINKKeysetHandle.publicKeysetHandle(with: handle)
        let thirdData = publicKeyHandle.serializedKeyset()
        let fourthData = publicKeyHandle.serializedKeysetNoSecret(&error)
```

In the above code, `firstData` was giving output, `secondData` returned nil, and was getting crash for `publicKeyHandle`. (That's because I'm not using asymmetric encryption).

So I'm guessing handle.serializedKeyset() is what I'm looking for.
 Please can someone confirm? 
@thaidn (sorry that I'm tagging you but saw your name in many threads!) 

P.S : very clean library! Thank you!

**Comment by thaidn** [comment]
@annathomasQB have you looked at my answer in https://groups.google.com/g/tink-users/c/FNwhOAg8q4k?

**Comment by annathomasQB** [comment]
@thaidn  yes, but is the above implementation incorrect? 

From the code, I could understand that we can get the SecKey item from the keychain and convert it to data. 

But if the above implementation is safe, I would have preferred this so that the code doesn't look too complicated :D 
Thanks for your response @thaidn  :)

**Comment by chuckx** [comment]
To close the loop here:

`serializedKeyset()` ([defined in the `Cleartext` category of the `TINKKeysetHandle` class](https://github.com/google/tink/blob/df5fa42e45b4d43aac6c3506ceba2956b79a62b8/objc/TINKKeysetHandle%2BCleartext.h#L31-L48)) facilitates serializing all key material. This is potentially dangerous, which is why the functionality is separated out into a category.

`serializedKeysetNoSecret()` ([defined in the `TINKKeysetHandle` class](https://github.com/google/tink/blob/df5fa42e45b4d43aac6c3506ceba2956b79a62b8/objc/TINKKeysetHandle.h#L108-L117)) facilitates serializing only public key material. This is a safe operation, hence it not being cordoned off into a separate category.
