### ISSUE TITLE
Creating a Shared Key Python

### ISSUE THREAD

**Issue by adongnmh** [google/tink#518]
I am just looking through the Google payment documentation for merchants, more specifically looking at how to decrypt the payment method token.

In the docs it mentions the following:
```
Use your private key and the given ephemeralPublicKey to derive a 512-bit long shared key that uses ECIES-KEM. Use the following parameters:
- Elliptic curve: NIST P-256, also known in OpenSSL as prime256v1.
- CheckMode, OldCofactorMode, SingleHashMode, and CofactorMode are 0.
- Encoding function: Uncompressed point format.
- Key derivation function: HKDFwithSHA256, as described in RFC 5869, with the following parameter:
- Salt must not be provided. Per the RFC, this must be equivalent to a salt of 32 zeroed bytes.
```

I was wondering if this step could be done using the Python Tink Library? I notice that in the java examples have EllipticCurves.java but there is no equivalent for Python?

**Comment by adongnmh** [comment]
More context:
I am also referencing https://developers.google.com/pay/api/android/guides/resources/payment-data-cryptography#using-tink

Which is the tool build in Java to decrypt the Payment Method Token.

My question is how do I replicate these steps in Python using the Tink Library.

Right now I am trying to complete step one (Use your private key and the given ephemeralPublicKey to derive a 512-bit long shared key). The problem is that when I look at the java implementation they are using class EllipticCurves.computeSharedSecret (https://github.com/google/tink/blob/master/java_src/src/main/java/com/google/crypto/tink/subtle/EllipticCurves.java) but there is nothing equivalent in the Python Library.

**Comment by thaidn** [comment]
I'm sorry but due to lack of resources we have no plan to support Google Payment Method Token in Tink Python.

**Comment by adongnmh** [comment]
@thaidn thanks for getting bak to me. Would the C++ Tink support the Google Payment Method Token?

**Comment by thaidn** [comment]
No, it doesn't. Though it shouldn't be too difficult to reimplement it using Tink C++ and BoringSSL.

BTW have you checked out https://github.com/google-pay/tink-jni-examples? It has a Python port, but I'm not sure if it's working.

**Comment by adongnmh** [comment]
Yeah I am checking out the JNI now. Thanks for the help.
