### ISSUE TITLE
Java_src build gives error about @androidsdk

### ISSUE THREAD

**Issue by jimi-pz** [google/tink#526]
Hello there, 

I'm following the JAVA-HACKING page.
I'm on a Mac BigSur; java version "1.8.0_251", Bazel version 3.7.2, android sdk and buildtools are version 26.
Android stuff is installed on "/Users/xxx/Android/".

When I run 'bazel test "..."', I got the following and could not figure out how to make it work.I've played with bzl configuration where I updated the android version to 26 but still get this error.

BUILD.bazel:177:20: every rule of type javadoc_library implicitly depends upon the target '@androidsdk//:platforms/android-23/android.jar', but this target could not be found because of: no such target '@androidsdk//:platforms/android-23/android.jar': target 'platforms/android-23/android.jar' not declared in package '' defined by /private/var/tmp/_bazel_xxx/5d74fe3b06ed0630be8bb0449f60aff6/external/androidsdk/BUILD.bazel

Any help is appreciated.

Thanks.

**Comment by thaidn** [comment]
You'd have to install Android SDK version 23 and export `ANDROID_HOME` pointing to it.

Can you follow [this tutorial](https://www.androidcentral.com/installing-android-sdk-windows-mac-and-linux-tutorial) and report back if you encounter any issue?

**Comment by jimi-pz** [comment]
Hi,

I've downloaded Android studio with the sdk version **23**; got this error when I run ->  bazel test "..." .

Analysis of target '//src/main/java/com/google/crypto/tink/util:keys_downloader-android' failed; build aborted: Android SDK api level 26 was requested but it is not installed in the Android SDK at /Users/xxx/Library/Android/sdk. The api levels found were [23]. Please choose an available api level or install api level **26** from the Android SDK Manager.
INFO: Elapsed time: 0.164s

Then based on the exception detail I've downloaded the sdk version 26 and got this one.

BUILD.bazel:366:20: every rule of type javadoc_library implicitly depends upon the target '@androidsdk//:platforms/android-23/android.jar', but this target could not be found because of: no such target '@androidsdk//:platforms/android-23/android.jar': target 'platforms/android-23/android.jar' not declared in package '' (did you mean 'platforms/android-26/android.jar'?) defined by /private/var/tmp/_bazel_xxx/5d74fe3b06ed0630be8bb0449f60aff6/external/androidsdk/BUILD.bazel ....

I still could not figure out how to build java sources. 
My ANDROID_HOME is set to **'/Users/xxx/Library/Android/sdk/'**

**Comment by jimi-pz** [comment]
Hi, 

I tried to build Java sources on Windows platform; and it required both version (23, 26) of the sdk; using one sdk version has ended with the above errors.

Then tried on Mac Os having installed both versions, and it finally worked; although I got some protobuf errors later in the build, the fix for me was at below.

https://github.com/protocolbuffers/protobuf/issues/5376
