### ISSUE TITLE
Bug: when creating a release version that uses EncryptedSharedPreferences, getting a warning of "Missing classes detected while running R8."

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/tink#536]
This:
https://issuetracker.google.com/issues/195752905

**Comment by juergw** [comment]
I think adding "-dontwarn com.google.errorprone.annotations.Immutable" should be fine. This annotation is only needed to generate compile-time warnings, and it is not needed at run-time.

I don't have a better solution than adding this "dontwarn" line. I'll close this now, please re-open if there is a problem with this.
