### ISSUE TITLE
Java JWT Availability

### ISSUE THREAD

**Issue by emarx** [google/tink#541]
Hello! I see that the JWT module is looking rather complete, but isn't yet published. Is there appetite to release it? I'd be happy lend a hand.

I've been developing a library wrapping Tink with ZIO for Scala and would love to use your JWT implementation! https://github.com/zio/zio-crypto

**Comment by thaidn** [comment]
@juergw

We're still working on this. To give ourselves a chance to fix problems, we'd like to let internal users to play with the APIs for a while prior to public release.

**Comment by SanjayVas** [comment]
Given that the "do not use" marker was removed in e4a327aca7ef1c0a82d9322697bddec0794da7a3, would it be safe to at least cut a pre-release or release candidate that includes this?

**Comment by thaidn** [comment]
@juergw is the best person to answer this question.

As I said earlier, we're still waiting/looking for feedback from internal users.

At the moment I believe the API is almost complete, but it might be changed without prior notice. Of course, if you don't mind changing your code, you can give it a try and tell us what you think.

**Comment by juergw** [comment]
Since release 1.7, JWT is now available in Java, C++, Golang and Python. See https://github.com/google/tink/blob/master/docs/JWT-HOWTO.md.
