### ISSUE TITLE
api is bad

### ISSUE THREAD

**Issue by ZedLiWenCai** [google/tink#548]
**Help us help you**

Please tell us more about
[your Tink deployment](https://docs.google.com/forms/d/1mhHvyNJQgTXFDnqOermB7-BD8GQSyvtFPUAhILRbYcA/edit).

**Describe the bug**

Provide clear and concise description of the bug.

**To Reproduce**

Include buildable code snippets or gists which triggered the bug.

**Expected behavior**

Describe of what you expected to happen.

**Error messages, stack traces, etc.**

If applicable, please include error messages, stack traces or any debugging
information.

**Version information**

 - Language: (e.g., Java, Python, etc.)
 - Version: (e.g., 1.2.0)
 - Environment: (e.g., JDK 8, Python3.7, iPhone 11, Android M, etc.)

**Additional context**

Add any other context about the problem.

**Comment by thaidn** [comment]
Please reopen if you can provide some actionable info.
