### ISSUE TITLE
Question: Fetching from a repository

### ISSUE THREAD

**Issue by omarkj** [google/tink#55]
I'm curious to know if Tink is being released to any Maven repository? I've been unable to find it at the usual suspects. I realize the project is brand new but I was hoping to poke at it a bit for a project I'm working on.

**Comment by thaidn** [comment]
Hi omarkj!

We just added Maven build yesterday. You can checkout the source and build with mvn package.

Our 1.0.0 version is still in active development, thus we haven't uploaded artifacts to Maven Central. You can find our snapshot package, which is updated with every commit, at https://storage.googleapis.com/tink-build-artifacts/tink-1.0.0-SNAPSHOT.jar.

**Comment by omarkj** [comment]
Hi thaidn,

Thanks! That's great for me so I'll go ahead and close this ticket. Excited to follow along as the project matures.

**Comment by thaidn** [comment]
Hi omarkj,

We've updated the location of our snapshot package to https://storage.googleapis.com/tink-build-artifacts/maven/tink-1.0.0-SNAPSHOT.jar. I'm sorry for any inconvenience caused.

**Comment by thaidn** [comment]
You should also join our mailing list if you haven't: https://groups.google.com/forum/#!topic/tink-users

**Comment by omarkj** [comment]
@thaidn Is that a public group? If I follow the link I get redirected to Google Group's main page.

**Comment by ThierryAbalea** [comment]
Like @omarkj I can't access to the Google Group

**Comment by ThierryAbalea** [comment]
@thaidn @omarkj the right URL (found in the README) is  https://groups.google.com/forum/#!forum/tink-users
