### ISSUE TITLE
Can't find API documentation

### ISSUE THREAD

**Issue by richsalz** [google/tink#550]
**Help us help you**

I am not using tink.  I am trying to learn more about it. I am used to things like comprehensive API documentation, ya know, manpages. I realize this is hard for multi-language systems. Do such docs exist?

**Is your feature request related to a problem?**

I am thinking about doing a new language implementation and would like to know what I need to implement.
The wire-formats doc helps. Is it complete? Is it sufficient to make sure anything I do is interoperable?

**Describe the solution you'd like**

Close this issue with a pointer to the docs :)

**Describe alternatives you've considered**

Reading everything I can find out about the Python implementation. This seems to be just "how do I" docs, unfortunately.

**Additional context**

None.

**Comment by thaidn** [comment]
We have some docs here https://developers.google.com/tink. Let me know if that's not what you're looking for.

**Comment by richsalz** [comment]
Thanks, @thaidn I've seen that.  I was expecting more classic manpage style, not "I want to ... " style.  Time for this old dog to get with the program, I guess :)

**Comment by thaidn** [comment]
I'm sorry, but we indeed don't have manpage. Please let us know if you have any feedback w.r.t our current docs.

PS: thank you for your work on OpenSSL!

**Comment by richsalz** [comment]
> PS: thank you for your work on OpenSSL!

you're too kind.  TINK is cool.  I was looking at https://github.com/project-oak/tink-rust and poking around a bit.
