### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by leahecole** [google/tink#553]
Hi! I'm a DPE in Cloud working on Python Samples and have noticed some of our samples that use tink as an underlying dependency fail on Python 3.10. I was wondering if you have a timeline for Python 3.10 support? 

Thanks!

**Comment by thaidn** [comment]
This sounds reasonable. @kste wdyt?

**Comment by kste** [comment]
We should definitely add Python 3.10 support and create the corresponding wheels in our releases. It should be feasible to publish 3.10 wheels for the previous release as well, then you will not have to wait for the next Tink release.

**Comment by chuckx** [comment]
The project currently fails to build with Python 3.10, so some changes will be necessary to gain compatibility. At first glance, it looks like it may be limited to dependency updates, but it will take some investigation to figure out the extent of the required modifications.

We will be able to publish 3.10 wheels with a subsequent release, once the compatibility issues are taken care of.

**Comment by leahecole** [comment]
🥳 🥳 🥳 🥳 🥳 🥳

**Comment by leahecole** [comment]
Hi - I am still seeing issues installing this and am not seeing a new release on PyPI - https://pypi.org/project/tink/ - is there a different installation path preferred for 3.10?
