### ISSUE TITLE
Fuzzing Tink by way of OSS-Fuzz

### ISSUE THREAD

**Issue by DavidKorczynski** [google/tink#556]
**Help us help you**

**Is your feature request related to a problem?**

Not a specific problem, this is automated security analysis.

**Describe the solution you'd like**

Automated fuzzing by way of OSS-Fuzz

**Describe alternatives you've considered**

**Additional context**

Hi!

I was wondering if you would be interested in getting Tink fuzzed by OSS-Fuzz? Fuzzing is a technique for stress-testing applications and OSS-Fuzz is a service run by Google for fuzzing important open source projects, and it would be great to get Tink integrated with OSS-Fuzz. OSS-Fuzz will run the fuzzers continuously and report back with bug reports when bugs are found. These reports will have full (sanitizer) stack traces, input triggers and more. If you are interested, then the only thing needed is an email(s) connected to a Google account that can be used for receiving the bugs reports, which can be put in the configuration file (project.yaml) over at the OSS-Fuzz repository.

@AdamKorcz have set up an initial integration with OSS-Fuzz here: https://github.com/google/oss-fuzz/pull/5725 and this PR on the OSS-Fuzz repository includes a simple initial fuzzer. We can always extend with more fuzzers if you are happy to integrate. I would just need an email and then get this PR merged, following that we should be good to go and down the line we can also migrate fuzzers from OSS-Fuzz to Tink owns repository.

**Comment by thaidn** [comment]
>I was wondering if you would be interested in getting Tink fuzzed by OSS-Fuzz?

Yes. Please send the report to thaidn@google.com, sschmieg@google.com and tholenst@google.com. Thanks!

**Comment by DavidKorczynski** [comment]
The integration is now done (for a while).
