### ISSUE TITLE
How to do key rotation?

### ISSUE THREAD

**Issue by sangmin7648** [google/tink#562]
**Describe the bug**

- The documentation instructs as below to rotate key. But `rotate()` method is marked `@Depricated`
```
 KeysetHandle rotatedKeysetHandle = KeysetManager
      .withKeysetHandle(keysetHandle)
      .rotate(keyTemplate)
      .getKeysetHandle();
```

- Another part of the documentation recommends separating the creation of keyset and the usage of it. I'm assuming this is the reason why `rotate()` is depricated. So I then tried Tinkey

- But Tinkey has problem outputing to the same file 
  - #511 

- Is there a way for me to either 
  A) bybass tinkey's problem 
  or 
  B) programmatically(as in with code) rotate key?

**Version information**

 - Language: Java
 - Version: Tink 1.6.1
 - Environment: Java 17

**Comment by juergw** [comment]
You'll need to use Tink 1.7 for the above example to work.
