### ISSUE TITLE
tinkey: support generation multiple keys in the keySet with one command.

### ISSUE THREAD

**Issue by xmlking** [google/tink#566]
today we have to run **tinkey** CLI multiple times to generate multi-key keySet file. e.g.:
```bash
tinkey create-keyset --key-template AES128_GCM  --out-format json --out aead_keyset.json
tinkey add-key  --in aead_keyset.json --in-format json --out aead_keyset2.json --out-format json  --key-template AES128_GCM
tinkey add-key  --in aead_keyset2.json --in-format json --out aead_keyset3.json --out-format json  --key-template AES128_GCM
```

it would be nice to support option to specify number of keys when generation same key types ( --key-template) in a single keyset file.

**Use case:** we have streaming app that encrypt each incoming  record with one of the enabled key picked randomly from the keyset, and include **KeyId** along with encrypted message. on decryption  side, it use same `KeyId` to decrypt.

**Comment by morambro** [comment]
Thanks for the issue, and sorry for the delay in replying. The intended behavior can be achieved with a relatively short amount of bash, e.g.:

```shell
bazelisk build ...
TINKEY="bazel-bin/tinkey"
"${TINKEY}" create-keyset --key-template AES128_GCM  --out-format json --out aead_keyset.json
for i in {1..10}; do
    mv aead_keyset.json aead_keyset.json.BAK
    "${TINKEY}" add-key --in aead_keyset.json.BAK --in-format json --out aead_keyset.json \
        --out-format json  --key-template AES128_GCM
done
rm -rf aead_keyset.json.BAK
```

The proposed feature would require in comparison some more complex refactoring of Tinkey, and wouldn't add any additional benefits w.r.t. the script above as far as I can tell. 

If you have any further comment/question please feel free to open a new issue in https://github.com/tink-crypto/tink-tinkey/issues.
