### ISSUE TITLE
Java and Golang AWS KMS AEAD are not compatible.

### ISSUE THREAD

**Issue by dstendardi** [google/tink#568]
**Help us help you**

Please tell us more about
[your Tink deployment](https://docs.google.com/forms/d/1mhHvyNJQgTXFDnqOermB7-BD8GQSyvtFPUAhILRbYcA/edit).

**Describe the bug**

```gherkin
Given I encrypt a string "foo" with the encryption context "bar" in Golang
When I decrypt the string with the Java library
Then I should succeed
But the decryption fail
```

**To Reproduce**

Include buildable code snippets or gists which triggered the bug.

Golang encryption

```golang

newSession, err := session.NewSession()
if err != nil {
  log.Fatal(err)
}

k := kms.New(newSession)

withKMS, err := awskms.NewClientWithKMS("aws-kms://arn:aws:kms:us-east-1:000000000000:alias/testing", k)
if err != nil {
   log.Fatal(err)
}
registry.RegisterKMSClient(withKMS)
mk, err := withKMS.GetAEAD(keyUri)
if err != nil {
   log.Fatal(err)
}

cipherTextBytes := mk.Encrypt([]byte("foo"), []byte("bar"))
```

Kotlin decryption

```kotlin
AeadConfig.register()
val handle = KeysetHandle.generateNew(
   KmsAeadKeyManager.createKeyTemplate(kmsKeyUri)
)

AwsKmsClient.register(
  Optional.of("aws-kms://arn:aws:kms:us-east-1:000000000000:alias/testing"),
  Optional.empty()
)

val aead = handle.getPrimitive(Aead::class.java)

val decrypted = aead.decrypt(
  cipherTextBytes,
  "bar".toByteArray()
)
```

**Expected behaviour**

Java client should be able to decrypt the cyphertext produced by the Golang implementation, even when additional data is passed to the decrypt method.

**Error messages, stack traces, etc.**

Stacktrace : 

```
Caused by: java.security.GeneralSecurityException: decryption failed
	at com.google.crypto.tink.aead.AeadWrapper$WrappedAead.decrypt(AeadWrapper.java:83)
````

**Version information**

 - Language: Kotlin, Golang
 - Version: (e.g., Tink Java 1.6.1, Tink Golang 1.6.1)
 - Environment: (e.g., JDK 11, Golang 1.16)

**Additional context**

We found out that decryption was working properly when no additional data is passed. 
Debugging further we noticed an inconsistency in the key used in the encryption context of AWS KMS: 

Golang : https://github.com/google/tink/blob/e231fe638eb1f1ed8f1d45cc665ee98736c781d6/go/integration/awskms/aws_kms_aead.go#L52

Java:
https://github.com/google/tink/blob/e231fe638eb1f1ed8f1d45cc665ee98736c781d6/java_src/src/main/java/com/google/crypto/tink/integration/awskms/AwsKmsAead.java#L73

**Comment by juergw** [comment]
Sorry that we didn't respond yet. And thanks for noticing this! Yes, this is an unfortunate inconsistency in the Golang implementation. But we can't just change it, because there are probably users that depend on this. So we need to find a solution that doesn't break anybody and gives an easy way to migrate.

**Comment by chuckx** [comment]
[d820737](https://github.com/google/tink/commit/d82073700110ab900739cbb3dd72ac4cacd5b769) introduces a new factory function [`NewClientWithOptions()`](https://pkg.go.dev/github.com/google/tink/go@v1.7.1-0.20230602192830-114bfd679a86/integration/awskms#NewClientWithOptions).

This function takes functional options, one of which is [`WithEncryptionContextName(EncryptionContextName)`](https://pkg.go.dev/github.com/google/tink/go@v1.7.1-0.20230602192830-114bfd679a86/integration/awskms#WithEncryptionContextName). It's argument can be one of the two constants, [`AssociatedData` or `LegacyAdditionalData`](https://pkg.go.dev/github.com/google/tink/go@v1.7.1-0.20230602192830-114bfd679a86/integration/awskms#EncryptionContextName).

By default, `NewClientWithOptions()` will use `AsoociatedData` as the `EncyrptionContextName`. This means that AEAD primitives created by the client will produce ciphertexts compatible with the other languages.

If you need to work with existing ciphertexts produced in the previous, incompatible manner, you can instantiate a client like this:

```
c, err := awskms.NewClientWithOptions(keyURI, awskms.WithEncryptionContextName(awskms.LegacyAdditionalData))
```

Also, clients created using any of the deprecated factory functions `NewClient()`, `NewClientWithCredentials()`, and `NewClientWithKMS()`) use the `LegacyAdditionalData` by default. This should prevent breaking any existing usages until a user is ready and explicitly migrates.
