### ISSUE TITLE
Implement radix 2^51 representation for Curve25519 on 64-bit processors

### ISSUE THREAD

**Issue by timmclean** [google/tink#57]
It looks like the [current implementation of Curve25519](https://github.com/google/tink/blob/3a4ba55ccbed745f7fd0d25f1d5393ed3f72424c/java/src/main/java/com/google/crypto/tink/subtle/Curve25519.java) in tink represents the field elements using 10 digits in base 2^25.5. This representation usually works well on 32-bit processors, since each digit can fit in a 32-bit register.

On 64-bit processors, it's possible, and usually faster, to encode field elements as 5 digits in base 2^51 (I've written about this [here](https://www.chosenplaintext.ca/articles/radix-2-51-trick.html)), fitting each digit in a single 64-bit register.

If this approach has already been considered and rejected, I apologize for the noise :)

**Comment by anergiz** [comment]
Hi Tim, thanks for the suggestion.
Please note that we are also doing multiplication, specifically here:
https://github.com/google/tink/blob/3a4ba55ccbed745f7fd0d25f1d5393ed3f72424c/java/src/main/java/com/google/crypto/tink/subtle/Curve25519.java#L291
Multiplying two 2^51 would overflow (note that we are storing < 2^27 as a long).

Please feel free to reopen this if I have missed something.
