### ISSUE TITLE
AEADBadTagException when trying to decrypt

### ISSUE THREAD

**Issue by prasclt** [google/tink#577]
**Describe the bug:**

AEADBadTagException when trying to decrypt a cipherText

**What was the expected behaviour?**

decrypt() method should have returned back with the plainText

**Do you have any debugging information?**

Our server code is written in C# and makes use of [this library](https://github.com/web-push-libs/web-push-csharp) to perform encryption adhering to the WebPush protocol

**Provide your version information:**

-   Language: Kotlin
-   Environment: Android N

**Is there anything else you’d like to add?**

Does Tink webpush expect the server also to use the same library, for the client to be able to decrypt? As our server is already built, has been running for years and successfully delivering push notifications to web clients, changing the encryption logic there is not an option. Can someone look into the encryption happening in [this library](https://github.com/web-push-libs/web-push-csharp) and confirm if tink can decrypt a payload encrypted by it?

**Comment by tholenst** [comment]
I do not know what "Tink webpush" is.

Also, I do not know how you import the keys into Tink. I will close this because I don't have enough information.
