### ISSUE TITLE
Improve Discoverability of Supported KeyTemplates in Java

### ISSUE THREAD

**Issue by asaikali** [google/tink#578]
There does not seem to be a way to discover what key templates are supported by Tink. The code in `KeyTemplates` class for version 1.6.1 does not provide a list of supported key template names. I had to use a debugger to inspect the returned map. It would be nice if the Javadoc explained how to figure out which key templates are supported in a specific Tink release.  If the Javadoc is not the right place to figure out what key template names are used then maybe point at docs or alternative ways to discover what key names are available. 

```java
public final class KeyTemplates {

  /**
   * Returns a key template that was registered with the {@link Registry} as {@code name}.
   *
   * @throws GeneralSecurityException if cannot find key template with name {@code name} in the
   *     Registry
   * @since 1.6.0
   */
  public static KeyTemplate get(String name) throws GeneralSecurityException {
    if (!Registry.keyTemplateMap().containsKey(name)) {
      throw new GeneralSecurityException("cannot find key template: " + name);
    }
    return Registry.keyTemplateMap().get(name);
  }

  private KeyTemplates() {}
}
```

**Comment by thaidn** [comment]
Can you use Registry.keyTemplateMap()?

**Comment by asaikali** [comment]
I can't because `Registry.keyTemplateMap()` is not a public method it is package protected. Also just knowing the names leaves one guessing what security grantees can be expected from the string name. 

```java
  /** Internal API that returns an unmodifiable map of registered key templates and their names. */
  static synchronized Map<String, KeyTemplate> keyTemplateMap() {
    return Collections.unmodifiableMap(keyTemplateMap);
  }
```

`KeyTemplate` is a public final class so there is no subclass hierarchy that I can query from the IDE to quickly discover the various KeyTemplates and what security guarantees they give me via the a subclass Javadoc. 

I searched the Tink docs for something like the [Java Security Standard Algorithm Names](https://docs.oracle.com/en/java/javase/17/docs/specs/security/standard-names.html) but could not find anything. 

What is the expected / correct way that a user of the library discovers what string names are allowed and what those means.

**Comment by tholenst** [comment]
The plan here is that we will add a new class for each key type. These can then be more easily found since IDEs have tab complettion.

For example, for AesCmac the following works at head:

```
    KeysetHandle keysetHandle =
        KeysetHandle.newBuilder()
            .addEntry(
                KeysetHandle.generateEntryFromParameters(
                        AesCmacParameters.create(/*tag_size=*/10))
                    .withRandomId()
                    .makePrimary())
            .build();
```

(I didn't try, so there might be typos, but see KeysetHandleTest.java for code which works).

I will close this since I assume this will be sufficient -- if not, please reopen this issue.
