### ISSUE TITLE
Cant build 1.6.1 python package on windows

### ISSUE THREAD

**Issue by antomy-gc** [google/tink#581]
`bazel build ...` in `python` subdir fails. Tink version is Release 1.6.1. Bazel version 5.0
![image](https://user-images.githubusercontent.com/57852299/152032657-56c0665f-b6d8-473f-a400-7c04c2974e35.png)

The only change i made in sources is updated Google PKI checksum.
Same result with current master branch

Windows 11 21H2

**Comment by morambro** [comment]
Hi @antomy-gc Tink Python doesn't support Windows at the moment. I'm going to close this issue, feel free to reopen it if you have any feedback/questions.
