### ISSUE TITLE
GCP Kms using deprecated GoogleCredential; use GoogleCredentials instead

### ISSUE THREAD

**Issue by dani29** [google/tink#584]
In the following [code snippet](https://github.com/google/tink/blob/master/java_src/src/main/java/com/google/crypto/tink/integration/gcpkms/GcpKmsClient.java#L126), the GCP Kms client is initialized with the GoogleCredential class. However, per the [documentation of this class](https://googleapis.dev/java/google-api-client/latest/com/google/api/client/googleapis/auth/oauth2/GoogleCredential.html), the usage of this is discouraged and the class is deprecated. As a result, Tink users can not provide an implementation of the prefered way, which is the [GoogleCredentials](https://cloud.google.com/java/docs/reference/google-auth-library/latest/com.google.auth.oauth2.GoogleCredentials) class. This is mostly useful for users that need to provide a custom implementation of the credentials, such as custom, self-refreshing credentials, etc.

Adding the support into Tink sounds trivial, and it the easiest would be to expose another constructor that takes a GoogleCredentials parameter, instead of the GoogleCredentials.

I'd be happy to contribute it, if the maintainers think it's a good idea and can confirm that this a nearby release of the Java client is planned.

**Comment by chuckx** [comment]
This was fixed by f28bf15013e352611b069d2c342b5a6530a9650d.
