### ISSUE TITLE
Google Pay decrypt library

### ISSUE THREAD

**Issue by zhumango** [google/tink#587]
**Help us help you**

Tell us more about
[your Tink deployment](https://docs.google.com/forms/d/1mhHvyNJQgTXFDnqOermB7-BD8GQSyvtFPUAhILRbYcA/).

**Is your feature request related to a problem?**

No, it isn't.

**Have you considered any alternative solutions?**

I created mini library to decrypt Google Pay payload base on your library, please mention it in instructions.

**Would you like to add additional context?**

[my repo](https://github.com/zethuman/google-pay-decryptor)

**Comment by juergw** [comment]
We currently don't add links to libraries based on Tink, we generally prefer that users use Tink directly.

We could consider adding a link if your library adds enough additional benefit to the user, and does something that users can't do with Tink directly.

But your mini library is not available anymore, so I think I can close this.
