### ISSUE TITLE
Make JavaScript / TypeScript version production ready

### ISSUE THREAD

**Issue by robin-kunzler** [google/tink#588]
Hi Tink team!

The JavaScript / TypeScript version of Tink is not for production use according to [this](https://github.com/google/tink#current-status). Is this information still up to date or is it actually closer to production readiness than indicated? Is there an ETA for a production-ready version? 

**Is your feature request related to a problem?**

We would like to start using Tink in web applications, but we are hesitant because the [Current Status](https://github.com/google/tink#current-status) says "JavaScript / TypeScript is in alpha state and should only be used for testing". 

**What sort of feature would you like to see?**

It would be great if the JavaScript / TypeScript version of Tink were ready for production use. In particular, we would like to use AEAD encryption features.

**Comment by hidde-jan** [comment]
No response from the team?

The fact that tink isn't considered stable in js made us go with libsodium instead for a high level cross-platform cryptography library.

**Comment by tholenst** [comment]
Unfortunately, we are at the moment unable to continue supporting Javascript.

See https://groups.google.com/g/tink-users/c/awhF4cs_mVE for more information.
