### ISSUE TITLE
Question: Logging

### ISSUE THREAD

**Issue by fabiogermann** [google/tink#59]
Currently JUL is beeing used for logging throughout the project. I assume this is by design? Would you consider Slf4j as an alternative in the future as it is more flexible?

**Comment by thaidn** [comment]
Hi there,

Thanks for the feedback!

We actually just chatted about logging today. The advantage of JUL is that it's available everywhere, thus we don't have to add an extra dependency (which increases code size). Anyway I'll leave it up to @przydatek to determine which library we should use.

**Comment by thaidn** [comment]
Closing this up, as I believe JUL is sufficient for now.
