### ISSUE TITLE
386 Go AEAD GCM build is broken

### ISSUE THREAD

**Issue by Dheu3** [google/tink#590]
**Describe the bug:**

Running Go 1.16.3 with GOARCH=386 results in compile error:

go@1.6.1/aead/subtle/aes_gcm.go:115:7: constant 68719476704 overflows int

**What was the expected behavior?**

Either the compile works or the readme clearly states what platforms are supported.

**How can we reproduce the bug?**

GOARCH=386 go test ./...

**Do you have any debugging information?**

go@1.6.1/aead/subtle/aes_gcm.go:115:7: constant 68719476704 overflows int

**Provide your version information:**

-   Language: go
-   Version: 1.6.3
-   Environment: 386

**Comment by rohansingh** [comment]
This is addressed in #579 but it needs review.

**Comment by chuckx** [comment]
Fixed by ad6cadb9bfb999687046049591852fc2bb96198c.
