### ISSUE TITLE
compile error in gomobile for android/arm.

### ISSUE THREAD

**Issue by chezgi** [google/tink#601]
using tink on golang it cant be compiled for `gomobile` on `android/arm` architecture.

command:
```
gomobile bind -v -x  -o dist/test.aar -androidapi 21 -target=android  testpkg/
```

result:
```
gomobile: go build -v -x -buildmode=c-shared -o=/tmp/gomobile-work-2353711825/android/src/main/jniLibs/armeabi-v7a/libgojni.so ./gobind failed: exit status 2
```

**Comment by juergw** [comment]
Sorry we have not replied back on this issue yet.

Is this still a problem?

Unfortunately, we don't use or test with gomobile, and we don't have the capacity to look into this problem.

**Comment by morambro** [comment]
Closing this issue for now. Please reopen it in https://github.com/tink-crypto/tink-go/issues if this is still an issue
