### ISSUE TITLE
Support for Ruby

### ISSUE THREAD

**Issue by lifeizhou-ap** [google/tink#602]
We are going to start a new service in Ruby and it will depend on Tink API to encrypt and decrypt data.  

Unfortunately Ruby is not supported by Tink at the moment.  Just wondering whether there is any plan for Tink to support Ruby. Thank you.

**Comment by tholenst** [comment]
Unfortunately, we currently are unable to add more supported languages.

In the future, we hope to be able to provide cross language tests which allow testing of implementations of Tink by third parties.

**Comment by fernandolobato** [comment]
If you do want to use Tink for simplicity, you can use Java Native Interface JNI Ruby-Java bridge. Google pay has some examples on how to do it here: https://github.com/google-pay/tink-jni-examples/blob/master/TinkJNIRuby/tink_ruby_decrypt.rb, please note, that example doesn't call Tink but rather some Google Pay specific functionality. That implementation doesn't interact with Tink, but the same method can be used.
