### ISSUE TITLE
Tinkey doesn't support "DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_256_GCM"

### ISSUE THREAD

**Issue by MikhailKaduchka** [google/tink#603]
**Help us help you**

We’d like to know more about
[your Tink deployment](https://docs.google.com/forms/d/1mhHvyNJQgTXFDnqOermB7-BD8GQSyvtFPUAhILRbYcA/).

**Describe the bug:**

Tinkey cannot generate "DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_256_GCM" key.

In the [documentation](https://developers.google.com/tink/hybrid) for hybrid encryption it's the recommended method.
Also in [example](https://github.com/google/tink/tree/master/examples/java_src/hybrid) command is not valid as tinkey doesn't have keyset template for "DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_256_GCM".

**What was the expected behavior?**

I expect documentation to be aligned with implementation. 

**How can we reproduce the bug?**

```tinkey create-keyset \
    --key-template DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_256_GCM \
    --out-format JSON --out hybrid_test_private_keyset.json```

**Do you have any debugging information?**

Message in console:
```Argument wrong!
org.kohsuke.args4j.CmdLineException: cannot find key template: DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_256_GCM```

**Provide your version information:**

-   Language: Java/Tinkey
-   Version: 1.6.1
-   Environment: Mac OS 12.3.1 (installed by brew)

**Is there anything else you’d like to add?**

As workaround I switched to 'ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM'

**Comment by ariccy** [comment]
I have run into the same issue and found that HPKE is indeed supported by the newest codes in this repo, but not supported in version 1.6.1 which was released on 13 Jul 2021.
Both java library and tinkey tool built from the newest source codes works fine for "DHKEM_X25519_HKDF_SHA256_HKDF_SHA256_AES_256_GCM".
It would be great if we could have a new official release though.

**Comment by juergw** [comment]
Yes, correct. HPKE and the example were added after the 1.6.1 release. It will be part of the next release.

And yes, we are working on making a new release, which will be coming soon.
