### ISSUE TITLE
Project that uses google/tink cannot be built with bazel

### ISSUE THREAD

**Issue by brownoxford** [google/tink#604]
I've got a project that uses https://github.com/hyperledger/aries-framework-go, which in turn uses https://github.com/google/tink. I'm trying to build my project with Bazel, but am running into the following error:

```
ERROR: /private/var/tmp/_bazel_cabernet/f52a3d470efd0f5dfdffb7f8715565db/external/com_github_hyperledger_aries_framework_go/pkg/kms/localkms/BUILD.bazel:3:11: no such package '@com_github_google_tink_go//proto/ed25519_go_proto': BUILD file not found in directory 'proto/ed25519_go_proto' of external repository @com_github_google_tink_go. Add a BUILD file to a directory to mark it as a package. and referenced by '@com_github_hyperledger_aries_framework_go//pkg/kms/localkms:localkms'
```

This appears to have been addressed in [`66d9baf`](https://github.com/google/tink/commit/66d9baf0f57014c63b3fc7f8cdba99ca36044d58), but has not yet been released.

By default, tink is included in `go.mod` indirectly as a pseudo version when adding `aries-framework-go`:

```
github.com/google/tink/go v1.6.1-0.20210519071714-58be99b3c4d0 // indirect
```

I tried using a pseudo version that pointed to `66d9baf` but that did not work either.

**Comment by morambro** [comment]
Hi [brownoxford](https://github.com/brownoxford), are you still having issues with the build with Bazel? I am not sure I have enough context, but I noticed you've mentioned pinning [`66d9baf`](https://github.com/google/tink/commit/66d9baf0f57014c63b3fc7f8cdba99ca36044d58) in your `go.mod` file, but not in your Bazel WORKSPACE/deps.bzl. Have you updated the Bazel files? 

For Go we use [`Bazel Gazelle`](https://github.com/bazelbuild/bazel-gazelle) for generating Bazel deps and `BUILD.bazel` files from `go.mod`

**Comment by morambro** [comment]
Closing this issue. If this is still an issue and/or if a feature request or fix is required please open a new issue in https://github.com/tink-crypto/tink-go/issues
