### ISSUE TITLE
out of memory when run sample streaming code with 9G file

### ISSUE THREAD

**Issue by junlicn** [google/tink#605]
**Help us help you**

We’d like to know more about
[your Tink deployment](https://docs.google.com/forms/d/1mhHvyNJQgTXFDnqOermB7-BD8GQSyvtFPUAhILRbYcA/).

**Describe the bug:**

Provide a clear and concise description of the bug.
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0x624981?, 0x103000000?})
        /usr/local/go/src/runtime/panic.go:992 +0x71
runtime.sysMap(0xc105000000, 0xc000045e90?, 0xc000045ef8?)
        /usr/local/go/src/runtime/mem_linux.go:189 +0x11b
runtime.(*mheap).grow(0x7d40a0, 0x81640?)
        /usr/local/go/src/runtime/mheap.go:1404 +0x225
runtime.(*mheap).allocSpan(0x7d40a0, 0x81640, 0x0, 0x1)
        /usr/local/go/src/runtime/mheap.go:1170 +0x171
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:912 +0x65
runtime.systemstack()
        /usr/local/go/src/runtime/asm_amd64.s:469 +0x49

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:436 fp=0xc000496868 sp=0xc000496860 pc=0x45e200
runtime.(*mheap).alloc(0x102c80000?, 0x81640?, 0xd6?)
        /usr/local/go/src/runtime/mheap.go:906 +0x65 fp=0xc0004968b0 sp=0xc000496868 pc=0x4261e5
runtime.(*mcache).allocLarge(0xc0000021a0?, 0x102c7f000, 0x1)
        /usr/local/go/src/runtime/mcache.go:213 +0x85 fp=0xc000496900 sp=0xc0004968b0 pc=0x4166e5
runtime.mallocgc(0x102c7f000, 0x5e1e80, 0x1)
        /usr/local/go/src/runtime/malloc.go:1096 +0x5a5 fp=0xc000496978 sp=0xc000496900 pc=0x40cfc5
runtime.makeslice(0xff0?, 0x1000?, 0xa4d0cb0f604dfb?)
        /usr/local/go/src/runtime/slice.go:103 +0x52 fp=0xc0004969a0 sp=0xc000496978 pc=0x448092
bytes.makeSlice(0x102c7f000)
        /usr/local/go/src/bytes/buffer.go:229 +0x65 fp=0xc0004969f0 sp=0xc0004969a0 pc=0x4dbf65
bytes.(*Buffer).grow(0xc00006c270, 0x1000)
        /usr/local/go/src/bytes/buffer.go:142 +0x11f fp=0xc000496a38 sp=0xc0004969f0 pc=0x4db8bf
bytes.(*Buffer).Write(0xc00006c270, {0xc0003c2001, 0x1000, 0x300000002?})
        /usr/local/go/src/bytes/buffer.go:172 +0x66 fp=0xc000496a68 sp=0xc000496a38 pc=0x4dbb26
io.(*teeReader).Read(0xc000056000, {0xc0003c2001, 0xc000496b20?, 0x1000})
        /usr/local/go/src/io/io.go:574 +0x77 fp=0xc000496ab0 sp=0xc000496a68 pc=0x496737
io.ReadAtLeast({0x6668c0, 0xc000056000}, {0xc0003c2001, 0x1000, 0x1000}, 0x1000)
        /usr/local/go/src/io/io.go:331 +0x9a fp=0xc000496af8 sp=0xc000496ab0 pc=0x49627a
io.ReadFull(...)
        /usr/local/go/src/io/io.go:350
github.com/google/tink/go/streamingaead/subtle/noncebased.(*Reader).Read(0xc000162ab0, {0xc0003ba000?, 0x8000?, 0x0?})
        /root/go/pkg/mod/github.com/google/tink/go@v1.6.1/streamingaead/subtle/noncebased/noncebased.go:280 +0x12e fp=0xc000496b88 sp=0xc000496af8 pc=0x5c054e
github.com/google/tink/go/streamingaead.(*decryptReader).Read(0xc000010020?, {0xc0003ba000?, 0xff0?, 0x8000?})
        /root/go/pkg/mod/github.com/google/tink/go@v1.6.1/streamingaead/decrypt_reader.go:46 +0xdc fp=0xc000496c70 sp=0xc000496b88 pc=0x5c879c
io.copyBuffer({0x666c20, 0xc000010020}, {0x6667a0, 0xc0000620a0}, {0x0, 0x0, 0x0})
        /usr/local/go/src/io/io.go:426 +0x1b2 fp=0xc000496cf0 sp=0xc000496c70 pc=0x496552
io.Copy(...)
        /usr/local/go/src/io/io.go:385
os.genericReadFrom(0x40d0e5?, {0x6667a0, 0xc0000620a0})
        /usr/local/go/src/os/file.go:162 +0x67 fp=0xc000496d48 sp=0xc000496cf0 pc=0x4bb707
os.(*File).ReadFrom(0xc00000e030, {0x6667a0, 0xc0000620a0})
        /usr/local/go/src/os/file.go:156 +0x1b0 fp=0xc000496d98 sp=0xc000496d48 pc=0x4bb650
io.copyBuffer({0x666920, 0xc00000e030}, {0x6667a0, 0xc0000620a0}, {0x0, 0x0, 0x0})
        /usr/local/go/src/io/io.go:412 +0x14b fp=0xc000496e18 sp=0xc000496d98 pc=0x4964eb
io.Copy(...)
        /usr/local/go/src/io/io.go:385
main.main()
        /root/src/filencryption/tink.go:95 +0x69d fp=0xc000496f80 sp=0xc000496e18 pc=0x5c9b1d
runtime.main()
        /usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc000496fe0 sp=0xc000496f80 pc=0x435c72
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000496fe8 sp=0xc000496fe0 pc=0x4602e1

**What was the expected behavior?**
normal
Describe what you expected to happen.

**How can we reproduce the bug?**
run sample golang code with a  9.7G source file

Include buildable code snippets or gists which triggered the bug.
package main

import (
        "fmt"
        "io"
        "io/ioutil"
        "log"
        "os"
        "path/filepath"

        "github.com/google/tink/go/keyset"
        "github.com/google/tink/go/streamingaead"
)

func main() {
        //dir, err := ioutil.TempDir("", "streamingaead")
        dir := "."
        var (
                srcFilename = filepath.Join(dir, "testdir.enc")
                ctFilename  = filepath.Join(dir, "ciphertext.bin")
                dstFilename = filepath.Join(dir, "testdir.dst")
        )
        /*

        if err := ioutil.WriteFile(srcFilename, []byte("this data needs to be encrypted"), 0666); err != nil {
                log.Fatal(err)
        }
        */

        kh, err := keyset.NewHandle(streamingaead.AES256GCMHKDF4KBKeyTemplate())
        if err != nil {
                log.Fatal(err)
        }

        // TODO: save the keyset to a safe location. DO NOT hardcode it in source code.
        // Consider encrypting it with a remote key in Cloud KMS, AWS KMS or HashiCorp Vault.
        // See https://github.com/google/tink/blob/master/docs/GOLANG-HOWTO.md#storing-and-loading-existing-keysets.

        // Encrypt file.

        a, err := streamingaead.New(kh)
        if err != nil {
                log.Fatal(err)
        }

        srcFile, err := os.Open(srcFilename)
        if err != nil {
                log.Fatal(err)
        }

        ctFile, err := os.Create(ctFilename)
        if err != nil {
                log.Fatal(err)
        }

        aad := []byte("this data needs to be authenticated, but not encrypted")
        w, err := a.NewEncryptingWriter(ctFile, aad)
        if err != nil {
                log.Fatal(err)
        }

        if _, err := io.Copy(w, srcFile); err != nil {
                log.Fatal(err)
        }

        if err := w.Close(); err != nil {
                log.Fatal(err)
        }

        if err := ctFile.Close(); err != nil {
                log.Fatal(err)
        }
        if err := srcFile.Close(); err != nil {
                log.Fatal(err)
        }

        // Decrypt file.

        ctFile, err = os.Open(ctFilename)
        if err != nil {
                log.Fatal(err)
        }

        dstFile, err := os.Create(dstFilename)
        if err != nil {
                log.Fatal(err)
        }

        r, err := a.NewDecryptingReader(ctFile, aad)
        if err != nil {
                log.Fatal(err)
        }

        if _, err := io.Copy(dstFile, r); err != nil {
                log.Fatal(err)
        }

        if err := dstFile.Close(); err != nil {
                log.Fatal(err)
        }
        if err := ctFile.Close(); err != nil {
                log.Fatal(err)
        }

        b, err := ioutil.ReadFile(dstFilename)

        if err != nil {
                log.Fatal(err)
        }

        fmt.Println(string(b))
}

**Do you have any debugging information?**

If applicable, include error messages, stack traces, or any other debugging
information.

**Provide your version information:**

-   Language: (such as Java or Python)   go 18.1
-   Version: (for example, 1.2.0)
-   Environment: (such as JDK 8, Python3.7, iPhone 11, or Android M)
ubunut 18.04
**Is there anything else you’d like to add?**
free -m
              total        used        free      shared  buff/cache   available
Mem:           7833        2971        4090          41         771        4518
Swap:             0           0           0
Provide any additional context about the problem.

golang source code come from :
https://developers.google.com/tink/encrypt-large-files-or-data-streams

**Comment by chuckx** [comment]
This behavior was recently fixed in 37d8a65ae4d6f75774d489485f55952f17ed3454. At the moment, you should be able to verify this by specifying that (or a later) commit in your `go.mod` file. This fix will be present in the upcoming release.
