### ISSUE TITLE
Issue with Installing Tink on Windows 10.0

### ISSUE THREAD

**Issue by syedzubeen** [google/tink#607]
I am trying to install tink on Windows 10, but keep getting an error about a dependent library maybe. "Bezel"
Tried downloading the windows installer for Bezel but it doesn't seem to install properly. 
![tink_issue](https://user-images.githubusercontent.com/14253061/172863580-0643277b-2455-401e-a35d-38059465cdaf.PNG)

**Comment by morambro** [comment]
Hi @syedzubeen, Tink Python requires building Tink C++ on Windows which is currently not supported.

I am going to close this issue, please feel free to re-open it should you have any other questions/concerns.
