### ISSUE TITLE
ETA for tink 1.7.0 on PyPI

### ISSUE THREAD

**Issue by rhofland** [google/tink#623]
The Python section of the release notes for Tink 1.7.0 states that "NOTE: Pending publication to PyPI." 

Is there an ETA for when this will be completed?

In addition, if possible, could you provide wheels for both aarch64 and x86_64

**Comment by Lawouach** [comment]
I echo this question. Any chance for an ETA of that release and Python 3.10 wheels as well? It makes distribution much nicer than bringing basel & co.

Thanks.

**Comment by Tomatosoup97** [comment]
Bump, any updates when the version will be available on PyPI?

**Comment by nmohseny-atz** [comment]
Another bump here! Any update on this release and Python 3.10 wheels?

**Comment by dwt** [comment]
Well, I'm also down for aarch64 builds of tink on pypi. Probably #674 could be merged into this bug (sorry, didn't find it before)

**Comment by astorrs** [comment]
bumping again as it's been 8 months since the 1.7.0 release...

**Comment by dwt** [comment]
@all-contributors @juergw @tholenst @morambro @ise-crypto @chuckx

Sorry to ping all of you guys - but I'd really like to use tink in one of my projects and it's majorly more difficult because the python build is not up to date.

What can we contribute to get this moving? Where is this hanging?

**Comment by KumarGanesha1996** [comment]
sir @chuckx any update on isue?

kind regards,
Kumar

**Comment by chuckx** [comment]
Binary wheels and a source distribution have been uploaded to PyPI. See https://pypi.org/project/tink/1.7.0/.
