### ISSUE TITLE
No key manager found for key type type.googleapis.com/google.crypto.tink.legacy.AesCbcPkcs7Key

### ISSUE THREAD

**Issue by MOHAMEDSAMEEM77** [google/tink#625]
**Help us help you**

We’d like to know more about
[your Tink deployment](https://docs.google.com/forms/d/1mhHvyNJQgTXFDnqOermB7-BD8GQSyvtFPUAhILRbYcA/).

**Describe the bug:**

Provide a clear and concise description of the bug.

**What was the expected behavior?**

Describe what you expected to happen.

**How can we reproduce the bug?**

Include buildable code snippets or gists which triggered the bug.

**Do you have any debugging information?**

If applicable, include error messages, stack traces, or any other debugging
information.

**Provide your version information:**

-   Language: (such as Java or Python)
-   Version: (for example, 1.2.0)
-   Environment: (such as JDK 8, Python3.7, iPhone 11, or Android M)

**Is there anything else you’d like to add?**

Provide any additional context about the problem.

**Comment by MOHAMEDSAMEEM77** [comment]
@thaidn  can u please look into this

**Comment by fernandolobato** [comment]
Why are you using: "type.googleapis.com/google.crypto.tink.legacy.AesCbcPkcs7Key " and how did you generate such template?

Could you give some additional information? Provide a code sample, language and how you are using Tink?

**Comment by MOHAMEDSAMEEM77** [comment]
Gnerated the tink keyset using KEYS.ADD_KEY_FROM_RAW_BYTES(keyset, key_type, raw_key_bytes) where  a 128 bit aes key was provided,  can we generate a tink key using a symmetric 128bit key already used in Application layer https://allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx

**Comment by tholenst** [comment]
This is not an official Tink key type, and only used by BigQuery for backwards compatibility with existing keys. It also does not provide the usual security of an AEAD key. As mentioned at https://cloud.google.com/bigquery/docs/reference/standard-sql/aead_encryption_functions#keysadd_key_from_raw_bytes it is not recommended.

**Comment by MOHAMEDSAMEEM77** [comment]
So lets say I am already using a AES  Key like this (nZr4u7x!z%C*F-JaNdRgUkXp2s5v8y/B)  in my application  can i migrate to Tink  by converting the same key to Tink KeySet

**Comment by tholenst** [comment]
AES is a block cipher. It maps 128 bits to 128 bits. So unless you only encrypt texts of exactly 128 bits, you are not encrypting with "AES". Instead, you use it with a "mode", e.g. with AES CBC PKCS#7. So I cannot answer your question.

Assuming you use AES CBC PKCS#7, the answer is no, since this mode does not provide the security which people typically except of "Encryption".

**Comment by MOHAMEDSAMEEM77** [comment]
https://meet.google.com/mrx-uebm-phn

**Comment by MOHAMEDSAMEEM77** [comment]
pretty relative to this ticket https://github.com/google/tink/issues/353

**Comment by MOHAMEDSAMEEM77** [comment]
I can make it pretty clear, Lets say  i have a symmetric raw  AES key ("abcpassword") which i am using for my current Encryption Decryption using standard AES Algorithm. Can i just generate a Tink key using AES key ("abcpassword") Such that i will continue my legacy application wihtout making much changes and use the new tink for other applications so there is data consistency. Generating a New Key brings the overhaul of decrypting my old data and encrypting using the Tink .As my data flows throgh multiple pipelines it becomes tedious. I would like to know If there is a solution .

**Comment by MOHAMEDSAMEEM77** [comment]
@tholenst  any comments on  this ??
