### ISSUE TITLE
tinkey command line help is lacking

### ISSUE THREAD

**Issue by ferozed** [google/tink#626]
**Help us help you**

tinkey does not provide any help about what it does or what each subcommand does. Besides the name of the sub-command, the user does not have anything to go on.

What I would like to see:

```
tinkey --help

create-keyset : Create a new keyset with a key
add-key: Add a new key to an existing keyset....
...
```

**Have you considered any alternative solutions?**

The only other alternative solution is to download `args4j-tools` and have it generate HTML documentation from source code of the `tinkey` project. But then we will have to add a feature to print out the HTML file when `tinkey --help` is run.

**Would you like to add additional context?**

`tinkey` requires some getting used to. Having documentation of the tools, and of each subcommand will make it much easier for the user to use.

Also... i think that this is a limitation of using `args4j`. It does not provide a way to print `usage()` where the usage could be inlined with the code.

**Comment by juergw** [comment]
Thanks for the suggestion. I added this in https://github.com/google/tink/commit/456d15c9a8fe826caed7249665cd9827237d6779.
