### ISSUE TITLE
[Java] Ed25519 long first verification call

### ISSUE THREAD

**Issue by micbayle-stripe** [google/tink#629]
**Describe the bug:**

When verifying a Ed25519 signature, the first verification takes significantly longer (100x) than subsequent verifications.

**What was the expected behavior?**

All verifications take less than 1ms

**How can we reproduce the bug?**

I modified the [Java tutorial](https://github.com/google/tink/blob/master/docs/JAVA-HOWTO.md) and ran 10 verifications

```java
import com.google.crypto.tink.CleartextKeysetHandle;
import com.google.crypto.tink.JsonKeysetReader;
import com.google.crypto.tink.KeysetHandle;
import com.google.crypto.tink.PublicKeyVerify;
import com.google.crypto.tink.signature.SignatureConfig;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.time.Instant;
import java.time.temporal.ChronoUnit;

public class Main {
  public static void main(String[] args) throws GeneralSecurityException, IOException {
    SignatureConfig.register();
    byte[] hello = "hello".getBytes(StandardCharsets.UTF_8);
    byte[] signatureOfHello =
        new byte[] {
          1, 80, -65, 99, -116, -52, 123, -52, 93, 58, 22, 62, 19, -77, 88, -61, -25, -102, -76,
          -109, -5, 100, -96, 17, 107, -81, 22, 80, 107, 34, -51, -46, -82, 96, 2, -93, -82, -8,
          -22, 5, -78, -69, 98, 34, -36, -57, -37, 126, -91, -1, -98, 112, 127, -113, -1, -31, -51,
          63, 36, 9, -85, -14, 17, -30, -71, 28, 40, 82, 14
        };

    // VERIFYING

    // 1. Obtain a handle for the public key material.
    String publicKey =
        "{\"primaryKeyId\":1354720140,\"key\":[{\"keyData\":{\"typeUrl\":\"type.googleapis.com/google.crypto.tink.Ed25519PublicKey\",\"value\":\"EiBBGA30gT9m79ETMRXZRxie4idJftl0UkZR81wAaaE49w==\",\"keyMaterialType\":\"ASYMMETRIC_PUBLIC\"},\"status\":\"ENABLED\",\"keyId\":1354720140,\"outputPrefixType\":\"TINK\"}]}";
    KeysetHandle publicKeysetHandle =
        CleartextKeysetHandle.read(JsonKeysetReader.withString(publicKey));

    // 2. Get the primitive.
    PublicKeyVerify verifier = publicKeysetHandle.getPrimitive(PublicKeyVerify.class);

    // 4. Use the primitive to verify.
    for (int i = 0; i < 10; i++) {
      Instant start = Instant.now();
      verifier.verify(signatureOfHello, hello);
      System.out.printf(
          "[%d] Verify took %dms\n", i, ChronoUnit.MILLIS.between(start, Instant.now()));
    }
  }
}
```

**Do you have any debugging information?**

```
[0] Verify took 164ms
[1] Verify took 1ms
[2] Verify took 1ms
[3] Verify took 2ms
[4] Verify took 1ms
[5] Verify took 1ms
[6] Verify took 1ms
[7] Verify took 1ms
[8] Verify took 1ms
[9] Verify took 2ms
```

**Provide your version information:**

-   Language: Java
-   Version: 1.7.0
-   Environment: JDK 8

**Comment by juergw** [comment]
You are right, it takes much longer for the first call. The reason seems to be that when the first time Ed25519Constants is used, this class is loaded and some constants are precomputed. And that takes some time.

Is this an issue for you? If it is, I guess you could verify something at startup of your binary, so that everything is loaded when you need to verify the first signature.

**Comment by micbayle-stripe** [comment]
> You are right, it takes much longer for the first call. The reason seems to be that when the first time Ed25519Constants is used, this class is loaded and some constants are precomputed. And that takes some time.
> 
> Is this an issue for you? If it is, I guess you could verify something at startup of your binary, so that everything is loaded when you need to verify the first signature.

I am doing a dummy sign and verify in my binary's startup to get around this. So not a huge deal, but maybe worth noting in docs?

**Comment by juergw** [comment]
I think I will just add some code that make sure that Ed25519Constants is initialized when the Ed25519 PublicKeyVerify primitive is created.

**Comment by juergw** [comment]
I have now added this. When I run you code now, the first call is almost as fast as the following calls.

**Comment by juergw** [comment]
See here: https://github.com/tink-crypto/tink-java/commit/d8a064702f09c586fa983c6cc867a1dcc2ae79f5
