### ISSUE TITLE
Does Tink Supports Key Rotation  while the keyset already uses a AES128bit Raw Key using AESGCMJce Encryption ?

### ISSUE THREAD

**Issue by MOHAMEDSAMEEM77** [google/tink#631]
**Help us help you**

Tell us more about
[your Tink deployment](https://docs.google.com/forms/d/1mhHvyNJQgTXFDnqOermB7-BD8GQSyvtFPUAhILRbYcA/).

**Is your feature request related to a problem?**

If so, provide a description of the problem.

**What sort of feature would you like to see?**

Describe your feature request. Or, how can we help solve the problem you noted
above?

**Have you considered any alternative solutions?**

Provide an explanation of any alternate requests or solutions and why your
request is preferable.

**Would you like to add additional context?**

Provide any other context about the feature request.

**Comment by MOHAMEDSAMEEM77** [comment]
{
  "key": [
    {
      "keyData": {
        "keyMaterialType": "SYMMETRIC",
        "typeUrl": "type.googleapis.com/google.crypto.tink.AesGcmKey",
        "value": "xxxxxxxxxxxxxx"
      },
      "keyId": 123id,
      "outputPrefixType": "RAW",
      "status": "ENABLED"
    }
  ],
  "primaryKeyId": 123id
}

**Comment by MOHAMEDSAMEEM77** [comment]
If my current raw key needs to be changed and rotated with a new key, do we require to decrypt the whole data or it works fine by enable a new primary key

**Comment by MOHAMEDSAMEEM77** [comment]
@tholenst

**Comment by fernandolobato** [comment]
Tink is design for key rotation, you can rotate keys and the primary will be used for encryption, and secondaries will be used for decryption based on key ids and cipher-text tagging. If there's no tagging, the whole keyset is tried. please take a look at the documentation: 

- https://developers.google.com/tink/design/keysets
- https://github.com/google/tink/blob/master/docs/JAVA-HOWTO.md#key-rotation
