### ISSUE TITLE
Caused by: java.lang.RuntimeException: Field keySize_ for ia.u not found. Known fields are ...

### ISSUE THREAD

**Issue by SmartManoj** [google/tink#639]
**Describe the bug:**

The app crashed when opened.

**How can we reproduce the bug?**

[App link](https://play.google.com/store/apps/details?id=one.pice)

[Relavant SO link](https://stackoverflow.com/questions/62135766/secured-android-sharedpreferences-error-caused-by-java-lang-runtimeexception
)

**Do you have any debugging information?**

Logcat :  https://nekobin.com/tavavoqoqa

**Provide your version information:**

-   Environment: Android 13

**Comment by juergw** [comment]
I don't know what causes this problem, and how to fix it. It is not clear to me that this is related to Tink.

In the link you provided, someone suggested to use the prodguard rule "-keep class com.google.crypto.** { *; }". Maybe that solves the problem.
