### ISSUE TITLE
Failed to FetchKeys while Decrypting

### ISSUE THREAD

**Issue by yramakanth** [google/tink#64]
Hi There,

I am seeing " GeneralSecurityException: Failed to fetch keys !"  while decryption. I am using tink in my java code for decryption. I used maven think dependency and created war file and deployed Jboss.  Please let me know will the TINK work if its integrated with code which runs in server which don't have any internet connection . Kindly help.  

Thanks
Ramakanth

**Comment by yramakanth** [comment]
Adding more details. Above is obsessed in Test Environment . I used GooglePaymentsPublicKeysManager.INSTANCE_TEST and merchant:12345678901234567890. I am using private key generated using open ssl.

**Comment by thaidn** [comment]
Hi @yramakanth,

Just to confirm: are you using the Payment Method Token app? If the server doesn't have Internet connection, you need to download the test public keys, store it somewhere on the server, then

String downloadedPublicKeysJson = ...; // read the downloaded public keys from file
 PaymentMethodTokenRecipient recipient = new PaymentMethodTokenRecipient.Builder()
    .senderVerifyingKeys(downloadedPublicKeysJson)
    .recipientId(recipientId)
    .addRecipientPrivateKey(recipientPrivateKey1)
    .build();

Let me know if it doesn't work for you.

@waltercacau

**Comment by thaidn** [comment]
@yramakanth please reopen if you still have any issues.
