### ISSUE TITLE
Put pb.go files in repo

### ISSUE THREAD

**Issue by gdbelvin** [google/tink#65]
It would be nice if tink put the `pb.go` files in the repo. This would allow Go projects to use Tink without also requiring them to also become Basil projects.

**Comment by thaidn** [comment]
Cool. Will find a way to do this.

**Comment by gdbelvin** [comment]
See the [trillian](https://github.com/google/trillian/blob/master/gen.go) repo for an example.

**Comment by thaidn** [comment]
Hmm I don't really know how to do this. Gary if you know how, could you please send a PR?

**Comment by thaidn** [comment]
This can be closed now?
