### ISSUE TITLE
INVALID_ARGUMENT: GCP KMS encryption failed: empty address list

### ISSUE THREAD

**Issue by sovongsa** [google/tink#664]
./bazel-bin/envelope_aead/envelope --mode encrypt \
    --gcp_credential_path gcp_account.json \
    --kek_uri gcp-kms://projects/proeject/locations/global/keyRings/sample-ring/cryptoKeys/test/cryptoKeyVersions/1 \
    --input_path testdata.txt --output_path testdata.txt.encrypted

i am seeing this error tink.core._tink_error.TinkError: INVALID_ARGUMENT: GCP KMS encryption failed: empty address list: 

after running above command to encrypt sample text. can you please check empty address list? it is KMS key not found? i dont think it is the issue with the key since i just copy key from resource name. any comment would help thanks!

**Comment by sovongsa** [comment]
i found a solution for this:
i need to do the following steps:
curl -Lo roots.pem https://pki.google.com/roots.pem
export GRPC_DEFAULT_SSL_ROOTS_FILE_PATH="$PWD/roots.pem"

then run the above bazel command.

**Comment by morambro** [comment]
Hi @sovongsa, I am closing this issue. Please feel free to reopen it if you have any questions/feedback.
