### ISSUE TITLE
Python requirements.txt and requirements.in don't match protobuf versions

### ISSUE THREAD

**Issue by alecgorge** [google/tink#667]
**Describe the bug:**

`protobuf==4.21.9` is declared in [`requirements.in`](https://github.com/google/tink/blob/master/python/requirements.in) but the [`requirements.txt`](https://github.com/google/tink/blob/master/python/requirements.txt) file still says `protobuf==3.20.3`

This will make it difficult for me to update tink alongside other dependencies like `grpcio` or `grpcio-tools` that declare `>=4.21.6` whenever Tink 1.7.0 is released.

**What was the expected behavior?**

I can install `grpcio-tools==1.51.1` alongside tink.

**How can we reproduce the bug?**

requirements.txt
```
grpcio==1.51.1
grpcio-tools==1.51.1
tink~=1.6.1
```

`pip install`

**Comment by tholenst** [comment]
Thanks, sorry about this. I made a mess there, and will take a look.

**Comment by tholenst** [comment]
I upgraded this to 4.21.9 everywhere. Note that Tink does not use any of the APIs which changed and I assume there is a way for you to override this.

I am not very familiar with the way these requirements work though, so let me know if this is still difficult to use.

**Comment by tholenst** [comment]
https://github.com/google/tink/commit/2de9ff92f13c882af427299853862afc0ba67045 should fix this.

**Comment by alecgorge** [comment]
forgot to respond before, but thanks for the quick turnaround on the fix :)
