### ISSUE TITLE
android.content.SharedPreferences.edit()' on a null object reference

### ISSUE THREAD

**Issue by denizbas92** [google/tink#671]
In my application I am using EncryptedSharedPreferences. My application works every device that I have tried. However, there is happenning an error in some of devices that as shown in the title. By the way, I am creating EncryptedSharedPreferences after onCreate. My application worked in my Android 10 Xiamio devices.

**What was the expected behavior?**

I am expecting that EncryptedSharedPreferences can save some data to storage.

**Do you have any debugging information?**

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'android.content.SharedPreferences$Editor android.content.SharedPreferences.edit()' on a null object reference
       at tr.com.dteknoloji.vwticari.datamanager.SharedPrefHelper.save(SharedPrefHelper.java:86)
       at tr.com.dteknoloji.vwticari.ui.intro.OnBoardingActivity.onClick(OnBoardingActivity.java:130)

**Provide your version information:**

-   Language: Java
-   Version: java 19
-   Environment: Android 8.1

**Comment by juergw** [comment]
Could you give some more details on where exactly the NullPointerException occurred?

**Comment by LuisAngelPerezMoreno** [comment]
I have the same problem.

**Comment by juergw** [comment]
Please give more details about the problem.

**Comment by denizbas92** [comment]
<img width="682" alt="Screen Shot 2023-02-14 at 16 14 08" src="https://user-images.githubusercontent.com/38309880/218749436-ba75c258-a60c-4abf-af82-ef3555af9bee.png">

**Comment by juergw** [comment]
If this is still an issue and you have a way to reproduce it or how to fix it, please open an issue on https://github.com/tink-crypto/tink-java.
