### ISSUE TITLE
Provide arm64 linux builds of the python packages on pypi

### ISSUE THREAD

**Issue by dwt** [google/tink#674]
**Is your feature request related to a problem?**

I want to use `tink` inside a linux docker container running on apple silicon. This is problematic because there are no prebuilt binaries of tink for that plattform available on pypi. Ordinarily this wouldn't be a problem, because `pip` will just download and build the wheel on demand. However, if `bazel` is not available in that linux plattform (in my case `centos7`) that fails. This makes it fairly hard to use `tink`.

**What sort of feature would you like to see?**

I would like to see prebuilt binaries for tink for arm / apple silicon on pypi to ease and speed up usage of tink in docker, especially on apple silicon.

**Have you considered any alternative solutions?**

- Building bazel myself to then build tink later: Possible, but involved. I may need to go that route though. :/
- Adding a builder sidecar docker container with a more modern linux distribution that already ships an arm version of bazel. Possible, also more involved than I'd like, but maybe necessary?
- Search for someone to provide a repo that provides bazel builds for arm already… Haven't found anything yet, but pointers would be welcome.

If there are other possible workarounds, especially if they involve less work, that would be most welcome.

**Comment by chuckx** [comment]
Wheels which include universal2 binaries have been uploaded to PyPI. See https://pypi.org/project/tink/1.7.0/#files.
