### ISSUE TITLE
Upgrade C++ library to use the latest AWS SDK

### ISSUE THREAD

**Issue by gergelykovacs** [google/tink#677]
**Is your feature request related to a problem?**

The current C++ version of Tink 1.7 uses AWS C++ SDK version 1.7.345, see in [aws kms integration](https://github.com/google/tink/blob/1.7/cc/integration/awskms/third_party/aws_sdk_cpp.BUILD.bazel)

Current version of [AWS C++ SDK](https://github.com/aws/aws-sdk-cpp) is at 1.11.x.

There were several changes in the AWS SDK since the 1.7.x version and upgrade attempts resulted in compilation errors, e.g.,

```
#22 41.99 CMake Error at CMakeLists.txt:15 (add_library):
#22 41.99   Target "..." links to target "AWS::crypto" but the target was not
#22 41.99   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
#22 41.99   an ALIAS target is missing?
```

**What sort of feature would you like to see?**

Could you follow up on the changes made by AWS to have a compatible version of Tink with AWS SDK 1.11.x?

**Have you considered any alternative solutions?**

Partial copies and overwrites were considered however not used due to maintainability problem and unintentional errors.

**Would you like to add additional context?**

N/A

**Comment by morambro** [comment]
Hi @gergelykovacs, this is something we are aware of. Unfortunately, this is not a trivial upgrade for us because we are maintaining the Bazel build rules for the SDK and dependent libraries, and between 1.7.X and 1.11.X the structure of the repo has changed significantly. Thus I don't have an ETA for this at the moment.

**Comment by gergelykovacs** [comment]
Thanks @morambro for the feedback!
