### ISSUE TITLE
Unable to decrypt previously encrypted file

### ISSUE THREAD

**Issue by jedi-tester** [google/tink#69]
When trying to decrypt previously encrypted file getting `Exception in thread "main" java.security.GeneralSecurityException: decryption failed`

This works fine (kotlin code):
```
    Config.register(AeadConfig.TINK_1_0_0)
    val dir = System.getProperty("user.dir") + "/src/test/resources"
    val keySetHandle = KeysetHandle.generateNew(AeadKeyTemplates.AES128_GCM)
    val aead = AeadFactory.getPrimitive(keySetHandle)
    var fis = FileInputStream("$dir/users.txt")
    val plainText: ByteArray = fis.readBytes()
    fis.close()
    val encrypted = aead.encrypt(plainText, "123".toByteArray())
    var fos = FileOutputStream("$dir/encr.txt")
    fos.write(encrypted)
    fos.close()
    fis = FileInputStream("$dir/encr.txt")
    val decrtptedText: ByteArray = fis.readBytes()
    fis.close()
    val decrptd = aead.decrypt(decrtptedText, "123".toByteArray())
    println(decrptd.toString(Charset.defaultCharset()))
```

But if I try to decrypt previously created encr.txt - getting aforementioned exception:
```
    Config.register(AeadConfig.TINK_1_0_0)
    val dir = System.getProperty("user.dir") + "/src/test/resources"
    val keySetHandle = KeysetHandle.generateNew(AeadKeyTemplates.AES128_GCM)
    val aead = AeadFactory.getPrimitive(keySetHandle)
    fis = FileInputStream("$dir/encr.txt")
    val decrtptedText: ByteArray = fis.readBytes()
    fis.close()
    val decrptd = aead.decrypt(decrtptedText, "123".toByteArray())
    println(decrptd.toString(Charset.defaultCharset()))
```

**Comment by jedi-tester** [comment]
Sorry, this is not an issue, I was doing it wrong.

**Comment by timbrueggenthies** [comment]
Could you tell what you were doing wrong back than?

**Comment by jgod** [comment]
@serpro69  Yeah what were you doing wrong? Also, @timbrueggenthies did you figure it out?

**Comment by serpro69** [comment]
Sorry @jgod , I don't remember what the issue was about. I'll try to find if I still have the code to give you a working example.

**Comment by serpro69** [comment]
@jgod , here's a gist with a (probably) working example - https://gist.github.com/serpro69/d98d1c1ddf88ee541d68d097799d54c3
Note that the tink version back then was `1.0.0`, and this code is using that version. Things most likely have changed significantly, so it will likely not work on the latest versions of tink.

**Comment by jgod** [comment]
Thank you @serpro69. I ended up discovering my error had nothing to do with code, but instead, my environment (Dockerfile) was copying an erroneous file in (the unencrypted one). No wonder it errored.
