### ISSUE TITLE
Go version does not build.

### ISSUE THREAD

**Issue by dgryski** [google/tink#70]

**Comment by thaidn** [comment]
Hey I want to make it work with the regular Go tooling too. Can you tell me the errors that you encountered? I'm new to Go...

**Comment by dgryski** [comment]
From the `tink/go` directory,

So, it seems like at least the protobuf descriptions aren't committed to the repository which is common for Go projects so they can be build directly with `go get`.

```
$ go build ./...
aead/aead_key_templates.go:21:2: cannot find package "github.com/google/tink/proto/aes_gcm_proto" in any of:
	/Users/dgryski/work/src/go/src/github.com/google/tink/proto/aes_gcm_proto (from $GOROOT)
	/Users/dgryski/go/src/github.com/google/tink/proto/aes_gcm_proto (from $GOPATH)
tink/proto_util.go:20:2: cannot find package "github.com/google/tink/proto/common_proto" in any of:
	/Users/dgryski/work/src/go/src/github.com/google/tink/proto/common_proto (from $GOROOT)
	/Users/dgryski/go/src/github.com/google/tink/proto/common_proto (from $GOPATH)
tink/cleartext_keyset_handle.go:22:2: cannot find package "github.com/google/tink/proto/tink_proto" in any of:
	/Users/dgryski/work/src/go/src/github.com/google/tink/proto/tink_proto (from $GOROOT)
	/Users/dgryski/go/src/github.com/google/tink/proto/tink_proto (from $GOPATH)
mac/hmac_key_manager.go:22:2: found packages mac (hmac.go) and hmac (hmac_test.go) in /Users/dgryski/go/src/github.com/google/tink/go/subtle/mac
mac/hmac_key_manager.go:25:2: cannot find package "github.com/google/tink/proto/hmac_proto" in any of:
	/Users/dgryski/work/src/go/src/github.com/google/tink/proto/hmac_proto (from $GOROOT)
	/Users/dgryski/go/src/github.com/google/tink/proto/hmac_proto (from $GOPATH)
signature/ecdsa_sign_key_manager.go:27:2: cannot find package "github.com/google/tink/proto/ecdsa_proto" in any of:
	/Users/dgryski/work/src/go/src/github.com/google/tink/proto/ecdsa_proto (from $GOROOT)
	/Users/dgryski/go/src/github.com/google/tink/proto/ecdsa_proto (from $GOPATH)
can't load package: mac/hmac_key_manager.go:22:2: found packages mac (hmac.go) and hmac (hmac_test.go) in /Users/dgryski/go/src/github.com/google/tink/go/subtle/mac
```

The `mac` vs `hmac` naming issue is a small quick fix.

**Comment by thaidn** [comment]
Thanks, I'll generate the proto code.

**Comment by thaidn** [comment]
I'm using
go version
go version go1.8.1 darwin/amd64

Here's what I did and the errors that I got:

$ pwd
/Users/thaidn/tink/cloudcryptosdk/go # cloudcryptosdk was our code name for Tink
$ cd go/
$ go build ./...
aead/aes_gcm_key_manager.go:22:2: cannot find package "github.com/google/tink/go/subtle/aead" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/google/tink/go/subtle/aead (from $GOROOT)
	/Users/thaidn/go/src/github.com/google/tink/go/subtle/aead (from $GOPATH)
aead/aes_gcm_key_manager.go:23:2: cannot find package "github.com/google/tink/go/subtle/random" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/google/tink/go/subtle/random (from $GOROOT)
	/Users/thaidn/go/src/github.com/google/tink/go/subtle/random (from $GOPATH)
aead/aead_config.go:20:2: cannot find package "github.com/google/tink/go/tink" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/google/tink/go/tink (from $GOROOT)
	/Users/thaidn/go/src/github.com/google/tink/go/tink (from $GOPATH)
aead/aead_key_templates.go:21:2: cannot find package "github.com/google/tink/proto/aes_gcm_proto" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/google/tink/proto/aes_gcm_proto (from $GOROOT)
	/Users/thaidn/go/src/github.com/google/tink/proto/aes_gcm_proto (from $GOPATH)
mac/hmac_key_manager.go:22:2: cannot find package "github.com/google/tink/go/subtle/mac" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/google/tink/go/subtle/mac (from $GOROOT)
	/Users/thaidn/go/src/github.com/google/tink/go/subtle/mac (from $GOPATH)
mac/mac_key_templates.go:21:2: cannot find package "github.com/google/tink/proto/common_proto" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/google/tink/proto/common_proto (from $GOROOT)
	/Users/thaidn/go/src/github.com/google/tink/proto/common_proto (from $GOPATH)
mac/hmac_key_manager.go:25:2: cannot find package "github.com/google/tink/proto/hmac_proto" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/google/tink/proto/hmac_proto (from $GOROOT)
	/Users/thaidn/go/src/github.com/google/tink/proto/hmac_proto (from $GOPATH)
signature/ecdsa_sign_key_manager.go:24:2: cannot find package "github.com/google/tink/go/subtle" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/google/tink/go/subtle (from $GOROOT)
	/Users/thaidn/go/src/github.com/google/tink/go/subtle (from $GOPATH)
signature/ecdsa_sign_key_manager.go:25:2: cannot find package "github.com/google/tink/go/subtle/signature" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/google/tink/go/subtle/signature (from $GOROOT)
	/Users/thaidn/go/src/github.com/google/tink/go/subtle/signature (from $GOPATH)
signature/ecdsa_sign_key_manager.go:27:2: cannot find package "github.com/google/tink/proto/ecdsa_proto" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/google/tink/proto/ecdsa_proto (from $GOROOT)
	/Users/thaidn/go/src/github.com/google/tink/proto/ecdsa_proto (from $GOPATH)
testutil/testutil.go:24:2: cannot find package "github.com/google/tink/go/aead" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/google/tink/go/aead (from $GOROOT)
	/Users/thaidn/go/src/github.com/google/tink/go/aead (from $GOPATH)
testutil/testutil.go:25:2: cannot find package "github.com/google/tink/go/mac" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/google/tink/go/mac (from $GOROOT)
	/Users/thaidn/go/src/github.com/google/tink/go/mac (from $GOPATH)
testutil/testutil.go:26:2: cannot find package "github.com/google/tink/go/signature" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/google/tink/go/signature (from $GOROOT)
	/Users/thaidn/go/src/github.com/google/tink/go/signature (from $GOPATH)

It seems that go build cannot figure out that the prefix of my package is github.com/google/tink. What I should do?

**Comment by thaidn** [comment]
My GOPATH points to /Users/thaidn/go.

**Comment by Saqibm128** [comment]
the build.bevel is in tink/go/tink. If you run ```go build *.go``` there, you get the usual proto errors. I think that might be the correct directory to build?

**Comment by dgryski** [comment]
Normally the directory structure is expected to mirror the package name.  For this kind of shared-language repo, it's not uncommon to have `go` in the package path.  For example Vitess's packages are all at `github.com/youtube/vitess/go`: https://godoc.org/github.com/youtube/vitess/go .

If you checkout the repository into `/Users/thaidn/go/src/github.com/google/tink` then packages should be found (after updating the imports to be `github.com/google/tink/go/aead`, etc)

**Comment by thaidn** [comment]
Thanks for the instructions, I appreciate it.

With my pending PR, go get github.com/google/tink/go/aead works now, but go get github.com/google/tink/go doesn't because I don't actually have any Go code in https://github.com/google/tink/tree/master/go. Is there a trick or convention that allows me to ensure all Tink packages are downloaded and installed with a single command?

**Comment by dgryski** [comment]
You can use `go get github.com/google/tink/go/...` where `...` means "all packages under this directory".

**Comment by thaidn** [comment]
Thanks!

With https://github.com/google/tink/commit/b081da6c782f214cc1009b09bef94ad2a2edcb65, I think **go get github.com/google/tink/go/...** should work now. Please help verify.

You're more than welcome to play with the Go code and tell us what you think, but please don't use it in production.

**Comment by dgryski** [comment]
```
$ go get -v -u github.com/google/tink/go/...
github.com/google/tink (download)
github.com/golang/protobuf (download)
github.com/google/tink/go/subtle
github.com/google/tink/go/subtle/random
github.com/golang/protobuf/proto
github.com/google/tink/proto/tink_proto
github.com/google/tink/proto/common_proto
github.com/google/tink/proto/aes_gcm_proto
github.com/google/tink/proto/hmac_proto
github.com/google/tink/proto/ecdsa_proto
github.com/google/tink/go/tink
github.com/google/tink/go/subtle/mac
github.com/google/tink/go/subtle/aead
github.com/google/tink/go/subtle/signature
github.com/google/tink/go/aead
github.com/google/tink/go/mac
github.com/google/tink/go/signature
github.com/google/tink/go/testutil
```

LGTM. Thanks!
