### ISSUE TITLE
AWS-KMS must check KeyID on decrypt

### ISSUE THREAD

**Issue by SalusaSecondus** [google/tink#71]
In `AwsKmsAead.decrypt()` it is important to check the returned KeyId against the one previously configured. If you don't do this, the possibility exists for the ciphertext to be replaced by one under a key you don't control/expect, but do have decrypt permissions on.

(Yes, this can be prevented by proper policies on the caller, but people sometimes get that wrong).

Note: Aliases or short key-ids (rather than ARNs) will break this logic on decrypt.

**Comment by thaidn** [comment]
Thanks. Will fix.

**Comment by thaidn** [comment]
This is fixed now. Please help verify.

Thanks so much for reviewing our code!

**Comment by SalusaSecondus** [comment]
It's a tad hard for me to follow. What happens to the prefix?

**Comment by thaidn** [comment]
Ah I see the confusion. By the time the key id is passed to AwsKmsAead, the prefix is already removed, see https://github.com/google/tink/blob/master/java/src/main/java/com/google/crypto/tink/integration/awskms/AwsKmsClient.java#L128.

I'll remove the prefix in the test KEY_ID to make the tests clearer.

**Comment by thaidn** [comment]
I added a comment to clarify that the key id must not have the prefix in https://github.com/google/tink/commit/158d242244eb8e24096466bf058310c0d61d45e3.

Again, thanks so much for reviewing Tink!

**Comment by sallybelly** [comment]
Wow
