### ISSUE TITLE
Cannot download tinkey - The project to be billed is associated with a closed billing account.

### ISSUE THREAD

**Issue by rhofland** [google/tink#714]
Trying to download tinkey (as per https://developers.google.com/tink/install-tinkey) using the link https://storage.googleapis.com/tinkey/tinkey-1.9.0.tar.gz

Fails with following error message:

```
<Error>
<Code>UserProjectAccountProblem</Code>
<Message>The project to be billed is associated with a closed billing account.</Message>
<Details>The billing account for the owning project is disabled in state closed</Details>
</Error>
```

**Comment by tholenst** [comment]
Thank you for the report. We will take a look.

**Comment by chuckx** [comment]
This issue should be resolved.
