### ISSUE TITLE
Make Random.java more thread-friendly

### ISSUE THREAD

**Issue by SalusaSecondus** [google/tink#72]
Use of SecureRandom in Java can be a major source of lock contention. I strongly recommend replacing your `private static final SecureRandom` with a `private static final ThreadLocal<SecureRandom>`, which will reduce this lock contention.

**Comment by thaidn** [comment]
This sounds reasonable.

Bartosz/Daniel, what do you think?

**Comment by thaidn** [comment]
@bleichen

**Comment by bleichen** [comment]
Looks OK to me.
Using thread-local random number generators appears to be a bit more robust,
since bugs are less likely to result in repeated random numbers.
But, I'm not very familiar with random number generation.

**Comment by thaidn** [comment]
Alright I committed a fix. @SalusaSecondus could you please verify it? Thanks!

**Comment by SalusaSecondus** [comment]
LGTM
