### ISSUE TITLE
Google Pay Implementation for Golang

### ISSUE THREAD

**Issue by Saqibm128** [google/tink#75]
It would be nice if there was a similar module to the Java Google Pay module. However, since Go Tink is still in active development, this is just a feature request.

**Comment by thaidn** [comment]
Wow, thanks for the PR. I'll take a look soon.

Would you mind telling me if you were asked by someone to build this? I just want to know if this is coming from a Google Pay partner.

**Comment by Saqibm128** [comment]
I created this as part of work for Patientco. We are considering adding Google Pay as one of our options, but wanted to primarily decrypt this in golang

**Comment by Saqibm128** [comment]
Is there still any interest in this? Or would it make more sense as a standalone project/repo?

I haven't had a look at the golang implementation of Tink but can tell that there have been a ton of changes recently.

**Comment by thaidn** [comment]
I'm sorry for going radio silence on this.  The Google Pay team wasn't interested in a Golang implementation for their Payment Method Token standard. We don't have resources to pursue this further.

Your PRs were still used as the basis for our Golang implementation. Thanks for your contributions!

I'm going to close this up. Please comment if there's anything else you want to discuss.

Cheers,
Thai.
