### ISSUE TITLE
Can we have `go.mod` for `github.com/google/tink`

### ISSUE THREAD

**Issue by borats** [google/tink#76]
Details outlined at https://research.swtch.com/vgo-intro and https://research.swtch.com/vgo-tour

Samples: https://github.com/rsc/quote

The `go.mod` will make your package vgo'able.

thanks

**Comment by thaidn** [comment]
Thanks borats. I'll take a look when I'm done with 1.1.0 release (which doesn't include Go).

**Comment by przydatek** [comment]
This has been added in https://github.com/google/tink/commit/455d82568b55f316f563c7aceeeaad6f4bf3925c and will be a part of release 1.3.0 (it is already in 1.3.0-rc1).
