### ISSUE TITLE
Latest head snapshot builds for java are missing Ed25519Constants.class

### ISSUE THREAD

**Issue by bobveznat** [google/tink#78]
We have an application that was working properly against tink 1.0. We're trying to migrate to the snapshots of 1.1 (for streaming aead) in anticipation of the 1.1 release and we're running into trouble with our old code.

When I kick off tests they now fail with:

`crypto.SignedPrincipalTests > crossedValidityTimesInvalidatePrincipal FAILED
    java.lang.NoClassDefFoundError: com/google/crypto/tink/subtle/Ed25519Constants
        at com.google.crypto.tink.subtle.Ed25519.select(Ed25519.java:545)
        at com.google.crypto.tink.subtle.Ed25519.scalarMultWithBase(Ed25519.java:601)
        at com.google.crypto.tink.subtle.Ed25519.scalarMultWithBaseToBytes(Ed25519.java:638)
        at com.google.crypto.tink.subtle.Ed25519Sign$KeyPair.newKeyPair(Ed25519Sign.java:88)
        at com.google.crypto.tink.signature.Ed25519PrivateKeyManager.newKey(Ed25519PrivateKeyManager.java:187)
        at com.google.crypto.tink.signature.Ed25519PrivateKeyManager.newKeyData(Ed25519PrivateKeyManager.java:78)
        at com.google.crypto.tink.Registry.newKeyData(Registry.java:243)
        at com.google.crypto.tink.KeysetManager.newKey(KeysetManager.java:215)
        at com.google.crypto.tink.KeysetManager.rotate(KeysetManager.java:66)
        at com.google.crypto.tink.KeysetHandle.generateNew(KeysetHandle.java:73)`

I've truncated the stacktrace where it enters my code. The line of code that triggers this is simply:

`KeysetHandle.generateNew(SignatureKeyTemplates.ED25519);`

While poking around trying to understand this more it appears that the [Ed25519Constants.class](https://github.com/google/tink/blob/master/java/src/main/java/com/google/crypto/tink/subtle/Ed25519Constants.java) is simply missing from the build?

`$ unzip -ll tink-HEAD-SNAPSHOT.jar | grep Ed255 | awk '{print $8}'
com/google/crypto/tink/subtle/Ed25519Verify.class
com/google/crypto/tink/subtle/Ed25519Sign.class
com/google/crypto/tink/subtle/Ed25519Sign$KeyPair.class
com/google/crypto/tink/subtle/Ed25519.class
com/google/crypto/tink/subtle/Ed25519$XYZT.class
com/google/crypto/tink/subtle/Ed25519$XYZ.class
com/google/crypto/tink/subtle/Ed25519$PartialXYZT.class
com/google/crypto/tink/subtle/Ed25519$CachedXYZT.class
com/google/crypto/tink/subtle/Ed25519$CachedXYT.class
com/google/crypto/tink/signature/Ed25519PublicKeyManager.class
com/google/crypto/tink/signature/Ed25519PrivateKeyManager.class
com/google/crypto/tink/proto/Ed25519PublicKeyOrBuilder.class
com/google/crypto/tink/proto/Ed25519PublicKey.class
com/google/crypto/tink/proto/Ed25519PublicKey$Builder.class
com/google/crypto/tink/proto/Ed25519PublicKey$1.class
com/google/crypto/tink/proto/Ed25519PrivateKeyOrBuilder.class
com/google/crypto/tink/proto/Ed25519PrivateKey.class
com/google/crypto/tink/proto/Ed25519PrivateKey$Builder.class
com/google/crypto/tink/proto/Ed25519PrivateKey$1.class
com/google/crypto/tink/proto/Ed25519.class
com/google/crypto/tink/proto/Ed25519$1.class`

This issue is present in the build on March 5th and also the build on Friday, March 9th (the most current as of this moment).

**Comment by thaidn** [comment]
Hmm this is very strange. I'm taking a look.

BTW are you using Ed25519 in production? It's in @Alpha quality, so it might be not great.

**Comment by thaidn** [comment]
OK found the issue. Will fix and push a new SNAPSHOT in a couple of hours.

**Comment by thaidn** [comment]
This should be fixed. Could you please try again?

Once again, Ed25519 support is for testing only, so are all methods and functions annotated with @Alpha.

Please do not use them in production.

**Comment by bobveznat** [comment]
Yay, our tests are passing again. Thank you. And I'll work on the the emotional attachment to ed25519 in favor of something else :-)
