### ISSUE TITLE
v1.0.0 ChaCha20-Poly1305 NaCl variant (alpha) did not authenticate the associated data

### ISSUE THREAD

**Issue by NeilMadden** [google/tink#88]
The NaCl variant of ChaCha20-Poly1305 that was present in v1.0.0 (marked as Alpha and since removed as far as I can tell) only included the ciphertext in the Poly1305 MAC input and not the associated data.

See https://github.com/google/tink/blob/v1.0.0/java/src/main/java/com/google/crypto/tink/subtle/DjbCipherPoly1305.java#L89

I know that code was marked as Alpha and not reachable except by directly calling com.google.crypto.tink.subtle.DjbCipherPoly1305#constructXSalsa20Poly1305Nacl but there is a small chance that somebody might be doing exactly that, so I wanted to flag it up as I couldn't see any existing issue for it.

**Comment by thaidn** [comment]
Hi Neil,

Thank you for looking into this. XSalsa20Poly1305 in NaCl doesn't accept AAD. ChaCha20Poly1305 does, but it's a subclass of https://github.com/google/tink/blob/v1.0.0/java/src/main/java/com/google/crypto/tink/subtle/DjbCipherPoly1305.java#L58 which supports AAD.

I'm going to close this issue, please reopen if you have any further comments or concerns.
