### ISSUE TITLE
Tinkey tool: disable-key and enable-key operations are duplicated

### ISSUE THREAD

**Issue by serranos** [google/tink#89]
Hi.

I was playing around with the `tinkey` tool and it appears `disable-key` and `enable-key` operations call the same code:

https://github.com/google/tink/blob/master/tools/tinkey/src/main/java/com/google/crypto/tink/tinkey/TinkeyUtil.java#L140-L145

Thanks for open sourcing this work! :)

**Comment by thaidn** [comment]
Oh thanks. Fixing it now.
