### ISSUE TITLE
No keytemplate example

### ISSUE THREAD

**Issue by newsoft** [google/tink#91]
The documentation at https://github.com/google/tink/blob/master/doc/TINKEY.md points to https://github.com/google/tink/tree/master/examples/keytemplates which does not exist at the moment.

Did you forget to publish those? Or are they still WIP?

**Comment by thaidn** [comment]
Ah the TINKEY doc is outdated. We deleted the KeyTemplate examples. The list of current supported templates can be obtained with the --list-key-templates option.

Will update the doc.
