### ISSUE TITLE
X25519 - set of rejected public keys differs from both NaCl and libsodium

### ISSUE THREAD

**Issue by NeilMadden** [google/tink#92]
https://cr.yp.to/ecdh.html#validate lists 12 "banned" public keys if you wish to do validation. Tink Java does perform this validation and rejects 7 of these. For the remaining 5 examples (e.g. "2(2^255-19)-1"), Tink does not reject them up front but performs masking (as per RFC 7748) to transform them into harmless values. 

This is different from both NaCl (which does not reject any points) and libsodium (which rejects all 12). It would be nice from a compatibility and fingerprinting point of view if Tink implemented one of the two existing behaviours.

**Comment by thaidn** [comment]
Quan made this change, so I'll let him decide here.

My two cents:

I think we want to be compatible with RFC 7748 because it's the standard that we believe all implementations should follow.

I'm not sure how this would break compatibility though because these keys should never appear in normal computations.

Also what's the benefit for providing a way to fingerprint Tink and other implementations?

**Comment by thaidn** [comment]
For future reference:

The masking is done at https://github.com/google/tink/blob/master/java/src/main/java/com/google/crypto/tink/subtle/Curve25519.java#L347.

It makes the public key malleable. If someone uses this to implement ECIES, but doesn't include the ephemeral public key in the KDF, the ciphertext is malleable.

**Comment by NeilMadden** [comment]
Do you have a reference I could read for ciphertext malleability?

In our intended application we will be including both public keys in the KDF as a general best-practice, but I wasn't aware that failure to do that might render the ciphertext malleable.

**Comment by thaidn** [comment]
Hi Neil,

ECIES ciphertext consists an ephemeral public key. With the masking, someone can flip the last bit of the last byte of the ephemeral public key to obtain another valid ciphertext.

**Comment by NeilMadden** [comment]
OK, that makes sense. In our usage the ephemeral public key is associated data to the AEAD used to encrypt the payload, so I believe that should prevent that.

**Comment by thaidn** [comment]
Quan, should we do anything here?

**Comment by quannguyentm** [comment]
I think it's a benign difference between libraries, so I will close it without making any change.
