### ISSUE TITLE
Hello World Java Build Failing

### ISSUE THREAD

**Issue by misfir3** [google/tink#94]
Came to check this out by reference of OWASP Top 10 proactive controls project. Trying the Java Hello World example  ($mvn clean package) ... 

On Mac OS X, I get

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project helloworld: Compilation failure
> [ERROR] Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: com.google.auto.service.processor.AutoServiceProcessor Unable to get public no-arg constructor
> 

...

> $ java -version
> java version "10.0.1" 2018-04-17
> Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
> Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
> 

Thought it might be the Java version, but also unable to build on Debian with OpenJDK v. 1.8.0_171

> [ERROR] COMPILATION ERROR : 
> [INFO] -------------------------------------------------------------
> [ERROR] Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider com.google.auto.service.processor.AutoServiceProcessor could not be instantiated: java.lang.NoClassDefFoundError: com/google/common/collect/Multimap
>

**Comment by thaidn** [comment]
Thanks for the report. I'll take a look.

**Comment by misfir3** [comment]
Thanks ... had hoped to (still do) as well. Forked/cloned, but OBE otherwise.

**Comment by thaidn** [comment]
I found the bug, going to merge the fix. Also would add a test to make sure this won't happen again.

**Comment by thaidn** [comment]
This should be fixed. Could you please try again and reopen if it still doesn't work?

Thanks so much for reporting it.

**Comment by rlundy** [comment]
Are there plans to create a new release with the above issue fixed?

**Comment by thaidn** [comment]
Good question. Let me see if we can release 1.1.1.

**Comment by thaidn** [comment]
@rlundy hey Ryan, just to make sure this is something blocking you. Does this bug prevent you from using Tink 1.1.0 with Maven?

**Comment by thaidn** [comment]
@chuckx

**Comment by misfir3** [comment]
finally got to pulling and running a:
```mvn clean package```

Thanks!

![image](https://user-images.githubusercontent.com/5103241/40515320-96553482-5f69-11e8-8b7f-fe73f0e5ce5b.png)

**Comment by rlundy** [comment]
@thaidn Yes, at least in my case it does.  I'm trying to keep things simple, and using a release package is simpler than needing to build from source.  (I'm a .NET dev by trade, but life takes strange turns, and now I'm writing code in a Java shop.  I'll grant that I'm probably not the typical case.)

**Comment by thaidn** [comment]
Rylan, thanks for getting back to me. Does the latest snapshot work for you?

**Comment by thaidn** [comment]
I think it should work. We'll release 1.1.1 today.

**Comment by rlundy** [comment]
@thaidn I apologize for the delay.  I was pulled in other directions.

I got back to it today, and I'm happy to report:

`[INFO] BUILD SUCCESS`

Thank you for the new build and new deploy to mvnrepository.
