### ISSUE TITLE
Feature request: Add Schnorr signature for NIST & Ed25519 elliptic curves

### ISSUE THREAD

**Issue by vietlq** [google/tink#99]
Schnorr signature is not malleable and is simpler (no inverse operations) than the widespread ECDSA. Some popular cryptocurries like Monero (and other CryptoNight clones) use Schnorr signature, and Zilliqa. Bitcoin Schnorr signature is being actively researched and a BIP is being worked on. I believe it's a good time to add Schnorr signature implementation for NIST & Ed25519 elliptic curves.

Some references:

* https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust/blob/master/topics-and-advance-readings/Schnorr-Signatures--An-Overview.md
* https://monero.org/monero-technological-superiority/
* https://docs.zilliqa.com/whitepaper.pdf
* https://github.com/sipa/bips/blob/bip-schnorr/bip-schnorr.mediawiki

Thank you!

**Comment by thaidn** [comment]
Thanks. We have Ed25519 signature in Java, and will add Ed25519 to other languages in 1.3.0.

**Comment by przydatek** [comment]
Ed25519 is now supported in Java, C++, Obj-C, and Go (cf.  https://github.com/google/tink/releases/tag/v1.3.0-rc1)
